### ISSUE TITLE
rook-config-override still not injected in 1.1.2

### ISSUE THREAD

**Issue by k0da** [rook/rook#4063] opened 2019-10-09 06:49 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Despite having:
```
kubectl get cm -n rook-ceph  rook-config-override  -o json | jq -r .data.config
[global]
osd max backfills = 16
osd recovery max active = 4
```
osd config-init doesn't put values into a config used by osd:

```
2019-10-09 06:38:02.947368 I | cephosd: Config file /var/lib/rook/osd0/rook-ceph.config:
[global]
fsid                         = ce7e6343-947e-4b0b-86ad-dbc996bd5d99
mon initial members          = d a b
mon host                     = 172.20.175.9:6789,172.20.189.18:6789,172.20.159.5:6789
log file                     = /dev/stderr
mon cluster log file         = /dev/stderr
public addr                  = 172.16.0.8
cluster addr                 = 172.16.0.8
mon keyvaluedb               = rocksdb
mon_allow_pool_delete        = true
mon_max_pg_per_osd           = 1000
debug default                = 0
debug rados                  = 0
debug mon                    = 0
debug osd                    = 0
debug bluestore              = 0
debug filestore              = 0
debug journal                = 0
debug leveldb                = 0
filestore_omap_backend       = rocksdb
osd pg bits                  = 11
osd pgp bits                 = 11
osd pool default size        = 1
osd pool default min size    = 1
osd pool default pg num      = 100
osd pool default pgp num     = 100
osd max object name len      = 256
osd max object namespace len = 64
osd objectstore              = filestore
crush location               = root=default host=ii-k8s-worker02-int-na-intgdc-com
rbd_default_features         = 3
fatal signal handlers        = false

[osd.0]
keyring          = /var/lib/rook/osd0/keyring
osd journal size = 5120
```
Generated deployment for pod have:
```
    "name": "ROOK_CEPH_CONFIG_OVERRIDE",
    "value": "/etc/rook/config/override.conf"
```
but override values are written to /etc/ceph/ceph.conf

/etc/rook/config/override.conf doesn't exist
**Expected behavior:**
values from rook-config-override are injected to osds

**How to reproduce it (minimal and precise):**
This is a pretty standard ceph block cluster with filestore

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.7
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): 1.1.2
* Storage backend version (e.g. for ceph do `ceph -v`): 1.13.6
* Kubernetes version (use `kubectl version`): 1.15.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): private
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment] 2019-10-09 08:15
Once the OSD pod runs it will read `/etc/ceph/ceph.conf` which has your config overrides.
I'm closing this, if you see something different feel free to re-open, thanks.

**Comment by k0da** [comment] 2019-10-09 12:19
osd started with --conf /var/lib/osdN/rook-ceph.config and when recovery starts see only tho PGs being recovered at the same time, If I use ceph config set osd .... recovery speed is increased immediately.

```
WHO    MASK LEVEL    OPTION                    VALUE                                                        RO 
global      basic    log_file                                                                               *  
global      advanced mon_allow_pool_delete     true                                                            
global      advanced mon_cluster_log_file                                                                   *  
global      advanced rbd_default_features      3     
```
^^ doesn't have overrided options

**Comment by leseb** [comment] 2019-10-09 12:21
@k0da what types of OSDs are you running? ceph-volume prepared? filestore? bluestore?

**Comment by k0da** [comment] 2019-10-09 12:26
@leseb filestore

**Comment by mkhpalm** [comment] 2019-10-11 03:45
rook-config-override is not working for us either with rook 1.1.2. We were using it to limit the osd_target_memory in nautilus after this change:

https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L191-L198

Once upgraded from 1.0.4 -> 1.1.2 multiple OSDs targeted the full system memory of the host they shared and started OOMing. As a result we set resources.osd.limit.memory in the crd to stop all the osds from crashing each other.

**Comment by leseb** [comment] 2019-10-14 13:43
> @leseb filestore

Please answer all my questions, was that OSD provisioned with c-v? (I don't think so but I'd like your confirmation). Thanks.

**Comment by leseb** [comment] 2019-10-14 13:43
> rook-config-override is not working for us either with rook 1.1.2. We were using it to limit the osd_target_memory in nautilus after this change:
> 
> https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L191-L198
> 
> Once upgraded from 1.0.4 -> 1.1.2 multiple OSDs targeted the full system memory of the host they shared and started OOMing. As a result we set resources.osd.limits.memory in the crd to stop all the osds from crashing each other.

Same question, please tell me more, what types of OSDs are you running? ceph-volume prepared? filestore? bluestore? Thanks.

**Comment by benceszikora** [comment] 2019-10-14 14:14
@leseb We are having the same issue, using bluestore for the OSDs.

**Comment by k0da** [comment] 2019-10-14 15:40
@leseb OSDs are NOT ceph-volume provioned

**Comment by mkhpalm** [comment] 2019-10-14 19:29
> > rook-config-override is not working for us either with rook 1.1.2. We were using it to limit the osd_target_memory in nautilus after this change:
> > https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L191-L198
> > Once upgraded from 1.0.4 -> 1.1.2 multiple OSDs targeted the full system memory of the host they shared and started OOMing. As a result we set resources.osd.limits.memory in the crd to stop all the osds from crashing each other.
> 
> Same question, please tell me more, what types of OSDs are you running? ceph-volume prepared? filestore? bluestore? Thanks.

I'm using bluestore, osd_memory_target is a setting for bluestore cache.

I was also suggesting it can easily be reproduced and verified by:

* Using nautilus with bluestore
* Don't set resources.osd.limits.memory in the cluster CRD
* Try to set osd_memory_target with with rook-ceph-override (due to the change linked previously)
* look at osd_memory_target value for ceph osd config, it will show you that the override is not being applied. Nautilus is seeing the entire system memory and defining its own value for osd_memory_target at ~80% of the total system memory.

I did see rook-config-override in /etc/ceph/ceph.conf but that is not being applied to anything.

**Comment by kfox1111** [comment] 2019-10-15 23:39
after chatting with @travisn, I think I may be seeing this too. I'm trying to use separate frontend/backend networks and its failing to apply.

**Comment by kfox1111** [comment] 2019-10-16 00:02
I'm not convinced its not applying the config... I am running 1.1.2. When I have:
public addr = ""
cluster addr = ""
in the overrides file, I get a warning about:
2019-10-15 23:57:16.811587 I | parse error setting 'cluster_addr' to ''
2019-10-15 23:57:16.813106 I | parse error setting 'public_addr' to ''
right after ceph-osd is started. If I remove those two lines from the config, it stops complaining.
Its looking like for my case, ceph may no longer accept it being a blank string?

**Comment by kfox1111** [comment] 2019-10-16 00:16
I think the answer is, "it depends". It looks like the init container is uploading some config stuff to the mons? Maybe due to this https://ceph.com/community/new-mimic-centralized-configuration-management/?

The cluster addr/public addr stuff doesn't seem to  be. and now it seems like maybe in newer versions of ceph it doesn't like being an empty string?

**Comment by kfox1111** [comment] 2019-10-16 00:20
Hmm... unless its not liking the '' because it was previously defined to be an ip because the init container build the config file ignoring the overrides file? Still possible that it is the same issue.

**Comment by kfox1111** [comment] 2019-10-17 23:27
It looks like this is not related to the private network issue I was having. It was primarily related to the kubelet node ip not being in the public ip range

**Closed** 2019-10-23 18:27 UTC
Labels: bug
