### ISSUE TITLE
Rook helm chart linting errors

### ISSUE THREAD

**Issue by denis256** [rook/rook#7346] opened 2021-03-03 09:55 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Noticed that lint of rook-helm chart is not passing now because of invalid metadata names

```
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

$ helm lint rook-ceph
==> Linting rook-ceph
[ERROR] templates/clusterrole.yaml: object name does not conform to Kubernetes naming requirements: "psp:rook": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Expected behavior:**
Helm lint to pass

**How to reproduce it (minimal and precise):**
Use helm 3.4+, run:
```
$ helm lint rook-ceph
```

**Comment by Madhu-1** [comment] 2021-03-03 10:27
this is a helm lint bug https://github.com/helm/helm/issues/9197 we are yet to add helm lint to rook CI https://github.com/rook/rook/pull/6868 waiting for the bug to get fixed in helm first.

**Comment by Madhu-1** [comment] 2021-03-03 10:28
duplicate of https://github.com/rook/rook/issues/6851

**Closed** 2021-03-05 07:12 UTC
Labels: bug
