### ISSUE TITLE
500 internal error to access dashboard in v0.9.1

### ISSUE THREAD

**Issue by aisensiy** [rook/rook#2492] opened 2019-01-15 09:52 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The dashboard failed after create a 3 mon 3 osd cluster with the cluster configuration: 

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.2-20181023
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    hostNetwork: false
  rbdMirroring:
    workers: 0
  resources:
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
    nodes:
    - name: xxx.compute.internal
      devices:
      - name: "xvdg"
    - name: xxxx.compute.internal
      devices:
      - name: "xvdg"
    - name: xxxxx.compute.internal
      devices:
      - name: "xvdg"
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

Create a cluster with the docs. And

    kubectl port-forward svc/rook-ceph-mgr-dashboard 8443:8443 -n rook-ceph

Then open https://localhost:8443 got error, I got logs from mgr:

```
[15/Jan/2019:10:13:03] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib64/python2.7/ssl.py", line 934, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:579)
```

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 16.04
* Kernel (e.g. `uname -a`): Linux xxxx 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: aws
* Rook version (use `rook version` inside of a Rook Pod): v0.9.0
* Kubernetes version (use `kubectl version`): v1.13.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_WARN mon c is low on available space

**Comment by aisensiy** [comment] 2019-01-15 09:59
By the way, is there some way to put the dashboard up again? I don't want to reinstall the cluster just because the dashboard failed...

Thanks in advance.

**Comment by laurybueno** [comment] 2019-01-17 15:30
I can confirm this problem in a very similar setup. However, I've configured an ingress with a valid certificate so that the dashboard could be publicly available. (and my Ceph cluster is HEALTH_OK)

When I try to access it, the page loads indefinitely and the manager pod prints the same error message on its log.

**Comment by aisensiy** [comment] 2019-01-18 07:14
I also try to use ingress, and failed...

**Comment by aisensiy** [comment] 2019-01-23 02:50
I am using traefik ingress which seems that it do not support ssl passthrough. And then I upgrade ceph to v13.2.4 and set `ssl: false` for the dashboard but the error message shows below:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib64/python2.7/ssl.py", line 934, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:618)
```

**Comment by chh315** [comment] 2019-01-24 13:52
I got this error too! installed by helm and using traefik ingress.

  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    port: 8080
    # serve the dashboard using SSL
    ssl: false

like port and ssl is not effected.

**Comment by travisn** [comment] 2019-01-24 15:24
I believe this is the same root cause as #2404. The fix is in master and I'd like to have it in a v0.9.2 release by tomorrow.

**Comment by ruzickap** [comment] 2019-01-26 10:36
Hello. 

I tried to install rook v0.9.2 to freshly installed k8s cluster:

```bash
$ helm repo add rook-stable https://charts.rook.io/stable
$ helm install --namespace rook-ceph-system rook-stable/rook-ceph

$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
wobbly-parrot   1               Sat Jan 26 10:46:18 2019        DEPLOYED        rook-ceph-v0.9.2                        rook-ceph-system

$ kubectl create -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml
```

Then I tried the port redirection to `rook-ceph-mgr`:

```bash
$ kubectl -n rook-ceph port-forward $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath='{.items[0].metadata.name}') 8443:8443
```

but I'm still getting errors when trying to access dashboard on `https://localhost:8443`:

```
E0126 11:14:37.732730    7221 portforward.go:331] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 751f952e3c9fd53c574c322fb3bdf55a41c8e56212e15a9e5ae40ec5dfe746b1, uid : exit status 1: 2019/01/26 10:14:37 socat[19752] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
```

Was this issue really fixed in v0.9.2 ? Is it working for anybody who is using v0.9.2 ?

**Comment by travisn** [comment] 2019-01-28 15:08
@aisensiy @ruzickap Is the scenario that you're trying to turn off ssl termination inside ceph and have the ssl termination handled by the ingress controller? Or connecting to the controller in any way is not working for you? By disabling ssl in the cluster crd, i would expect you'd be able to accomplish that. 

@noahdesu If ssl is disabled, is the dashboard going to be listening on a different port such as 7000?

**Comment by ruzickap** [comment] 2019-01-28 15:15
Actually it is not the case... 
I do not want to use ingress at all. I just want to start the dashboard and be able to connect there using "kubectl port forwarding" (like it is here: https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)

If I use port 7000 I got the same issue/errors `... an error occurred forwarding 7000 -> 7000: error forwarding port 7000 to pod ...`

**Comment by noahdesu** [comment] 2019-01-28 18:38
the ssl setting doesn't affect the port that is used, and if no port is explicitly requested, the port selection is based on ceph version (7000 for luminous, 8443 >= mimic).

**Comment by zedtux** [comment] 2019-01-30 14:36
I'm facing this issue too with a fresh Kubernetes cluster (v 1.13) and followed the same procedure than @ruzickap in order to install rook, and I'm using the `Kubectl proxy` command in order to access the dashboard but it wait forever and I have the error in the pod's log.

Is there anyway to access that dashboard without SSL/TLS?

**Comment by travisn** [comment] 2019-01-30 15:34
I suspect the ingress controller will work at least when the rook cluster is configured with `hostNetwork: true`. @galexrt any ideas on this one?

**Comment by MiticoBerna** [comment] 2019-02-16 16:08
I've tried to configure ingress with traefik and, me too, I still get Internal Server Error.
With nodeport works.

As @travisn suggest, I've put `hostNetwork:true` but still doesn't work with ingress.

rook: `v0.9.2`
ceph: `v13.2 (latest)`
EKS 10.11.5

**Comment by noahdesu** [comment] 2019-02-18 17:09
@MiticoBerna i can try to reproduce this today. can you share your yaml configs?

**Comment by ruzickap** [comment] 2019-02-18 17:27
If you want to reproduce this issue please follow the steps mentioned here: https://github.com/rook/rook/issues/2492#issuecomment-457820437
(It's just few commands)

If you need something more - please let me know.

In my case I'm not using ingress, but only `kubectl port-forward`.

**Comment by noahdesu** [comment] 2019-02-18 17:28
thanks @ruzickap

**Comment by MiticoBerna** [comment] 2019-02-18 23:38
@ruzickap in this comment https://github.com/rook/rook/issues/2526#issuecomment-458289145 @galexrt says that port-forward could not working anymore due "to the fact that the dashboard is only listening on the Pod IP and not localhost".

With the ingress could be the same problem? I don't believe...

@noahdesu following my ingress.yml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-rook-ceph-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    ingress.kubernetes.io/protocol: https
spec:
  rules:
  - host: "rook-dashboard.fabulous.hostname"
    http:
      paths:
      - backend:
          serviceName: rook-ceph-mgr-dashboard
          servicePort: 8443
```

**Comment by ruzickap** [comment] 2019-02-19 08:45
Ok... 
Isn't it a bug, that you can not use `kubectl port-forward` to access the dashboard?
I believe it should be possible to access the dashboard with both `ingress` and `kubectl port-forward` like in other projects.

**Comment by sebastian-philipp** [comment] 2019-02-19 09:33
yeah, it should not depend on the forwarding mechanism.

**Comment by sebastian-philipp** [comment] 2019-02-19 09:39
Upstream Ceph issue: http://tracker.ceph.com/issues/38378

**Comment by sebastian-philipp** [comment] 2019-02-19 09:41
Could you please provide some more log context of the MGR log in the vicinity of the `SSLError`?

**Comment by sebastian-philipp** [comment] 2019-02-19 09:50
Just a guess: are you trying to access the HTTPS endpoint with plain HTTP?

**Comment by ruzickap** [comment] 2019-02-19 14:16
Actually no. Here are the steps + errors I'm getting:

```bash
$ helm repo add rook-stable https://charts.rook.io/stable
$ helm install --namespace rook-ceph-system rook-stable/rook-ceph

$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
rook-ceph       1               Tue Feb 19 14:41:30 2019        DEPLOYED        rook-ceph-v0.9.2                        rook-ceph-system

$ kubectl create -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml

$ kubectl -n rook-ceph get pod -l app=rook-ceph-mgr
NAME                               READY     STATUS    RESTARTS   AGE
rook-ceph-mgr-a-669f5b47fc-pfz8g   1/1       Running   0          1m

$ kubectl -n rook-ceph port-forward $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath='{.items[0].metadata.name}') 8443:8443
Forwarding from 127.0.0.1:8443 -> 8443
Forwarding from [::1]:8443 -> 8443


$ curl -v https://127.0.0.1:8443
* Rebuilt URL to: https://127.0.0.1:8443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443

$ curl -v http://127.0.0.1:8443
* Rebuilt URL to: http://127.0.0.1:8443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8443
> User-Agent: curl/7.61.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

Actually in this case it doesn't matter what protocol you are using, because `kubectl port-forward` can not connect to the pod:port - see the errors:

```
Handling connection for 8443
E0219 14:47:37.956365   13415 portforward.go:331] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 391c10a77f97c0faecfd9d038b654ad6121ae87bab4c7ae31111666dc160b749, uid : exit status 1: 2019/02/19 13:47:37 socat[13417] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
Handling connection for 8443
E0219 14:47:43.281354   13415 portforward.go:331] an error occurred forwarding 8443 -> 8443: error forwarding port 8443 to pod 391c10a77f97c0faecfd9d038b654ad6121ae87bab4c7ae31111666dc160b749, uid : exit status 1: 2019/02/19 13:47:43 socat[13442] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
Handling connection for 8443
```

What I described above is probably only related to port forwarding with `kubectl` (and not using ingress - not sure).

**Comment by sebastian-philipp** [comment] 2019-02-19 14:25
@ruzickap could you also add some more log output of the mgr daemon?

**Comment by ruzickap** [comment] 2019-02-19 14:48
Here it is:

```bash
$ ps -elf | grep 'port-forward'
0 S pruzicka 24147 21887  1  80   0 - 272066 -     15:36 pts/7    00:00:00 kubectl -n rook-ceph port-forward rook-ceph-mgr-a-669f5b47fc-pfz8g 8443:8443
0 S pruzicka 24242 19904  0  80   0 -  1501 -      15:37 pts/6    00:00:00 grep --color=auto port-forward

$ curl -v https://127.0.0.1:8443; kubectl logs -n rook-ceph $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath='{.items[0].metadata.name}') --tail=10
* Rebuilt URL to: https://127.0.0.1:8443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443
2019-02-19 14:38:29.109 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:31.109 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:33.109 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:35.109 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:37.113 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:39.113 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:41.113 7fb55f393700  1 mgr send_beacon active
2019-02-19 14:38:43.113 7fb55f393700  1 mgr send_beacon active
10.244.0.13 - - [19/Feb/2019:14:38:43] "GET /metrics HTTP/1.1" 200 45089 "" "Prometheus/2.3.1"
2019-02-19 14:38:45.113 7fb55f393700  1 mgr send_beacon active
```

Looks like the request coming through tunnel is is not reaching the daemon on port 8443.

I also checked what is listening on port 8443 inside the `rook-ceph-mgr` container:

```bash
$ kubectl -it exec -n rook-ceph $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath='{.items[0].metadata.name}') -- /usr/sbin/ss -onatpe | grep 8443
LISTEN     0      5      10.244.2.6:8443                     *:*                   users:(("ceph-mgr",pid=1,fd=141)) ino:53200 sk:16 <->
```

Not sure if `10.244.2.6:8443` is correct - shouldn't it be `*:8443` ?

**Comment by sebastian-philipp** [comment] 2019-02-19 14:52
Hm, that is a bit in contradiction with the initial error (`SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:579)`).

**Comment by noahdesu** [comment] 2019-02-20 00:51
Setting `ceph config set mgr mgr/dashboard/server_addr 0.0.0.0` and then restarting the `ceph-mgr` pod enables the `port-forward` approach and the `NodePort` approach still works too.

Is there any particular reason to bind to the pod IP if all the access is through one of these two methods?

cc #2526

**Comment by ruzickap** [comment] 2019-02-20 11:52
Thank you @noahdesu 
Your way is working fine for `kubectl port-forward`:

```bash
kubectl -n rook-ceph exec -it $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') -- ceph config set mgr mgr/dashboard/server_addr 0.0.0.0

kubectl delete pod -n rook-ceph  $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath="{.items[0].metadata.name}")

kubectl -n rook-ceph port-forward $(kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o jsonpath="{.items[0].metadata.name}") 8443:8443

curl -k https://localhost:8443
...
```

**Comment by noahdesu** [comment] 2019-02-20 23:19
@ruzickap does the solution continue to work after some time? according to this cherrypy report https://github.com/cherrypy/cherrypy/issues/1100 it looks like this solution might not be robust and it also matches a similar report here https://github.com/rook/rook/issues/2335#issuecomment-446032672 with the problem reoccurring.

**Comment by noahdesu** [comment] 2019-02-25 21:12
This patch https://github.com/ceph/ceph/pull/26635/files should provide a transparent fix for this issue. Once it's merged we'll backport.

**Comment by noahdesu** [comment] 2019-03-04 22:49
* luminous https://github.com/ceph/ceph/pull/26751
* mimic https://github.com/ceph/ceph/pull/26750
* (merged) nautilus https://github.com/ceph/ceph/pull/26635

**Comment by jmreicha** [comment] 2019-04-09 22:58
Just ran into this issue running the dashboard behind an ingress, don't know if it is 100% the same thing so let me know if it needs to be a separate issue.  So far I am able to login to the dashboard but getting the 500 internal server error others have mentioned.

Here are the logs from the ceph-mgr pod.

```
[09/Apr/2019:22:49:14] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib64/ceph/mgr/dashboard/controllers/summary.py", line 68, in __call__
    'rbd_mirroring': self._rbd_mirroring(),
  File "/usr/lib64/ceph/mgr/dashboard/controllers/summary.py", line 43, in _rbd_mirroring
    daemons = data.get('daemons', [])
AttributeError: 'NoneType' object has no attribute 'get'

[09/Apr/2019:22:49:14] HTTP
Request Headers:
  REFERER: https://internal.domain/ceph/
  X-FORWARDED-HOST: internal.domain
  Remote-Addr: 172.18.4.152
  X-REAL-IP: x.x.x.x
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
  COOKIE: csrftoken=U2XP5w7EXypGzEoEU2c27RaMZDS4sM0d9UY7gfyaUSLxfZgJWJ4jBzAcjlHolktb; session_id=8d9d350ab455355749c0ec87953c25dcd6219670
  ACCEPT: application/json, text/plain, */*
  X-FORWARDED-PROTO: https
  X-ORIGINAL-URI: /ceph/api/summary
  DNT: 1
  HOST: internal.domain
  X-SCHEME: https
  ACCEPT-LANGUAGE: en-US,en;q=0.9,fr;q=0.8
  X-FORWARDED-FOR: x.x.x.x
  X-FORWARDED-PORT: 443
  X-REQUEST-ID: 0e745f36f820f930f15d8ebb1c44b075
  ACCEPT-ENCODING: gzip, deflate, br
debug 2019-04-09 22:49:14.373 7ff9dfe34700  0 mgr[dashboard] [172.18.4.152:48554] [GET] [500] [5.003s] [admin] [1.1K] /ceph/api/summary
debug 2019-04-09 22:49:14.373 7ff9dfe34700  0 mgr[dashboard] ['{"status": "500 Internal Server Error", "version": "3.2.2", "detail": "The server encountered an unexpected condition
172.18.4.152 - - [09/Apr/2019:22:49:14] "GET /ceph/api/summary HTTP/1.1" 500 1127 "https://internal.domain/ceph/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36
```

Here is what the ceph config looks like (after following the suggestion from above to update the server_addr).

```
[root@worker1 /]# ceph config dump
WHO   MASK LEVEL   OPTION                     VALUE                                                        RO
  mgr      unknown mgr/dashboard/password     XXX *
  mgr      unknown mgr/dashboard/server_addr  172.18.1.43                                                  *
  mgr      unknown mgr/dashboard/server_addr  0.0.0.0                                                      *
  mgr      unknown mgr/dashboard/server_port  8443                                                         *
  mgr      unknown mgr/dashboard/ssl          false                                                        *
  mgr      unknown mgr/dashboard/url_prefix   /ceph                                                        *
  mgr      unknown mgr/dashboard/username     admin                                                        *
  mgr      unknown mgr/prometheus/server_addr 172.18.1.43                                                  *
```

**Comment by noahdesu** [comment] 2019-04-09 23:49
@jmreicha would you mind submitting a separate request? this does look different.

**Closed** 2019-04-30 20:30 UTC
Labels: ceph
