### ISSUE TITLE
clusters.rook.io CRD removal is impossible in a broken cluster

### ISSUE THREAD

**Issue by dimm0** [rook/rook#1510] opened 2018-02-18 23:37 UTC
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
The rook cluster is in a completely broken state now after a couple nodes lost the power. I'm trying to reinstall rook, and now it's stuck on deleting the rook namespace and clusters.rook.io CRD.

kubectl describe crd clusters.rook.io:
```
    Message:               could not confirm zero CustomResources remaining: timed out waiting for the condition
    Reason:                InstanceDeletionCheck
    Status:                True
    Type:                  Terminating
```

What you expected to happen:
Ability to delete the rook cluster when needed

How to reproduce it (minimal and precise):
Break the cluster (maybe unsync the monitors) with PODs mounting the storage. Try to clear everything.

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`):
Linux 4.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Jan 23 20:28:26 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Baremetal
* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.6.0-219.g09dc9b8
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm

**Comment by dimm0** [comment] 2018-02-18 23:48
`ETCDCTL_API=3 etcdctl --endpoints=localhost:2379 del /registry/apiextensions.k8s.io/customresourcedefinitions/clusters.rook.io` helped cleaning so far..

**Comment by jbw976** [comment] 2018-02-19 00:56
This could be a dupe of #1488

**Comment by dimm0** [comment] 2018-02-19 01:01
Yes. Should I close this one?

**Comment by travisn** [comment] 2018-02-23 19:32
@dimm0 please reopen this issue if the documentation around #1488 does not solve it.

**Closed by travisn** 2018-02-23 19:32 UTC
