### ISSUE TITLE
Does rook support Samba to be in front of Ceph ?

### ISSUE THREAD

**Issue by saltFisher** [rook/rook#5537] opened 2020-05-25 10:43 UTC
in the /cluster/examples/kubernetes/ceph/, i saw nfs.yaml, does rook support samba to be in front of Ceph?
if yes, how to use it ?

**Comment by leseb** [comment] 2020-05-25 10:46
Not at the moment.

**Comment by saltFisher** [comment] 2020-05-25 10:53
@leseb Hi Han, Is there has some work arround to realize this feature ? maybe import ceph.conf and copy it to another samba pod to connect ceph or other ways ?
do you have time to tell me why "not at the comment" ? thanks.

**Comment by leseb** [comment] 2020-05-25 12:14
@saltFisher I don't think there is a good reason to that, I suspect that this is in the CephFS team backlog somewhere. However, the priority might be low at the moment.

@jtlayton  @batrick  what's your take on this? What's the state of vfs_ceph CephFS module for Samba?

Thanks!

**Comment by batrick** [comment] 2020-05-25 17:56
We don't really know what the state of the module is right now.

**Comment by leseb** [comment] 2020-05-26 07:17
@batrick thanks. @saltFisher I think your question was answered, closing now. Thanks.

**Closed by leseb** 2020-05-26 07:17 UTC
Labels: feature

**Comment by saltFisher** [comment] 2020-05-26 10:26
@leseb Thanks Han. This issue can be hanbled by this way:
created ceph filesystem, and then create pvc. config a pod by using this pvc, and also install samba in this pod. 
Although this way is not smart, but it can works. 
Thanks again.

**Comment by jtlayton** [comment] 2020-05-26 11:41
> @jtlayton @batrick what's your take on this? What's the state of vfs_ceph CephFS module for Samba?

It basically works, but there the fact that samba uses a forking model, means that each incoming samba connection gets its own ceph client. So it should work reasonably well if none of those clients are competing for access to the same inodes. If they are, then it's likely performance will not be great. I think it probably needs a lot more love before plumbing support for it into rook.

Mounting the share using kcephfs and exporting that via samba like @saltFisher suggests is another approach that will avoid multiple ceph clients.

**Comment by obnoxxx** [comment] 2020-05-26 16:59
In order to bring Samba into the kubernetes landscape, there are a at least two options:

### central Samba on ceph

This would require deploying and managing a central Samba+CTDB clustered installation on top of the Ceph cluster serving out cephfs volumes. This is fragile and complex and will require a lot of work.

### Samba as service on top of kubernetes  PVCs

This would establish a samba-service crd and deployment on top of PVCs (that is not restricted to cephfs pvcs at this point). I think this is pretty much what @saltFisher means.

I wanted to propose adding this kind of SmbService CRD and operator to rook, but in order to get a PoC quickly, I started a standalone one based on the operator-sdk:

https://github.com/obnoxxx/samba-operator

So this is working in principle but very simple still.

Eventually, one could even add a csi provisioner for convenience to wrap that in PVCs that would be accessed with the https://github.com/kubernetes-csi/csi-driver-smb node plugins.

As far as use cases go, this approach would be a good option to start using cephfs (and other) PVCs
* in VMs (--> kubevirt)
* on Windows worker nodes.

**Comment by obnoxxx** [comment] 2020-05-26 17:01
If folks are interested in adding smb service capabilities to rook (to complement the nfs operator), I'd be more happy to elaborate more on that and bring this standalone prototype into a more rook-y fashion. @travisn @leseb @jtlayton ...

**Comment by obnoxxx** [comment] 2020-05-26 17:12
Just to complete the link to the above question: The mentioned samba operator would NOT use the `vfs_cephfs` module from samba. It would not need to know anything about ceph. It would just export the pvc mounted in its pod. So it would be exporting what looks like a local directory.

Since there would be a 1:1 correspondence PVC <--> Samba deployment, the samba does not need to be clustered or otherwise aware of ceph. Super simple approach.

**Comment by obnoxxx** [comment] 2020-05-29 12:11
@saltFisher , @jtlayton , @batrick , @travisn , @leseb  - any comment? Or is it because the issue is closed? We could open a new issue for the discussion. :-)

**Comment by jtlayton** [comment] 2020-05-29 12:19
Agreed. I think it's probably best to steer away from vfs_ceph for now, especially in cases where SMB clients might be competing for access to the same inodes. That does mean we have some dependency on the kernel where samba is running, and it makes it harder to containerize things, but it's probably the best approach for now.

The problem with vfs_ceph is that because samba forks, each process gets its own ceph client. If the SMB clients then are competing for access to the same files, they'll constantly be revoking each others' caps leading to lousy performance. Sharing a kernel mount however should sidestep that issue since the cap handling is all done in the kernel.

**Comment by obnoxxx** [comment] 2020-05-29 12:43
@jtlayton, and just to emphasize, the proposed approach with one dedicated samba container on top of a PVC is completely generic in that it has no special reference on ceph whatsoever:

```
[ceph] <--- [mount on k8s host] ---> [bind-mount into samba container] <--- [smb client]
```

So the only piece that is aware ceph is the csi driver at the backend PVC. So samba just exports a posix(y) filesystem directory. Just as if you would re-export a local cephfs mount.

**Comment by pschichtel** [comment] 2025-03-22 17:25
@obnoxxx would there even be any advantage in merging your operator into rook? Wouldn't simple Deployment + Service + PVC resources do the same given an appropriate CephFS-backed StorageClass? After all isn't the point that this approach doesn't need to be aware of ceph?
