### ISSUE TITLE
OSD Resize Increases Used Capacity Not Available Capacity

### ISSUE THREAD

**Issue by jameshearttech** [rook/rook#14099] opened 2024-04-19 20:02 UTC
** Previous bug report for same issue. Only this time with a different OS, VMware controller, Kubernetes version, Rook version, and Ceph version. Where is the bug?! https://github.com/rook/rook/issues/12511**

**Is this a bug report or feature request?**

* Bug Report

**Deviation from expected behavior:**

After resizing the underlying disk at the hypervisor and OS level **resizing the OSD increases cluster total capacity and used capacity**.

**Expected behavior:**

After resizing the underlying disk at the hypervisor and OS level **resizing the OSD increases cluster total capacity and available capacity**.

**How to reproduce it (minimal and precise):**

Build a Kubernetes cluster from virtual machines where Rook consumes virtual disks as OSDs. Resize a virtual disk used as an OSD at the hypervisor level. Resize the disk at the OS level. Resize the disk at the Ceph level (e.g., restart the OSD pod).

**File(s) to submit**:

![image](https://github.com/rook/rook/assets/67252279/fd1a1444-56ad-4859-9b27-db0b62ccd168)
![image](https://github.com/rook/rook/assets/67252279/2c834977-c6b3-459a-abb3-cf9af7c8a6af)

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary: [rook-ceph.yaml.txt](https://github.com/rook/rook/files/15045142/rook-ceph.yaml.txt)

**Logs to submit**:

* Operator's logs, if necessary: [Explore-logs-2024-04-19 09_53_04.txt](https://github.com/rook/rook/files/15045122/Explore-logs-2024-04-19.09_53_04.txt)
* Crashing pod(s) logs, if necessary: N/A

**Cluster Status to submit**:

```text
  cluster:
    id:     e1ebb901-75ad-4b7c-90d9-69edf914c04e
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,d (age 2d)
    mgr: b(active, since 90m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 8 osds: 8 up (since 91m), 8 in (since 2h)
    rgw: 2 daemons active (2 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   12 pools, 265 pgs
    objects: 493.10k objects, 748 GiB
    usage:   1.3 TiB used, 1.5 TiB / 2.8 TiB avail
    pgs:     265 active+clean
 
  io:
    client:   103 KiB/s rd, 1.4 MiB/s wr, 22 op/s rd, 14 op/s wr
```

**Environment**:

* OS (e.g. from /etc/os-release): Talos (v1.6.4)
* Kernel (e.g. `uname -a`): 6.1.74-talos
* Cloud provider or hardware configuration: VMware
* Rook version (use `rook version` inside of a Rook Pod): v1.13.3
* Storage backend version (e.g. for ceph do `ceph -v`): v18.2.2
* Kubernetes version (use `kubectl version`): v1.29.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by parth-gr** [comment] 2024-04-20 14:05
@jameshearttech can you share the `ceph osd df tree` outputs before and after resize.

**Comment by jameshearttech** [comment] 2024-04-20 22:25
For context there is [this Slack thread](https://rook-io.slack.com/archives/CK9CF5H2R/p1713371193372799). I see `ceph osd df` output from when there were 7 K8s nodes and OSDs (i.e., 1 OSD per node). Is the output there good enough? If not I'll have to attempt another resize and get the output at that time. Here is the current output from `ceph osd df tree`.

```
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/tool/ {print $1}') -n rook-ceph -- ceph osd df tree
ID   CLASS  WEIGHT   REWEIGHT  SIZE     RAW USE  DATA     OMAP     META     AVAIL    %USE   VAR   PGS  STATUS  TYPE NAME            
 -1         2.73438         -  2.8 TiB  1.1 TiB  1.0 TiB  493 MiB   16 GiB  1.7 TiB  40.42  1.00    -          root default         
 -5         0.34180         -  350 GiB  121 GiB  119 GiB   31 MiB  1.8 GiB  229 GiB  34.49  0.85    -              host mgmt-worker0
  0    ssd  0.34180   1.00000  350 GiB  121 GiB  119 GiB   31 MiB  1.8 GiB  229 GiB  34.49  0.85   89      up          osd.0        
 -9         0.34180         -  350 GiB  141 GiB  139 GiB   37 MiB  1.7 GiB  209 GiB  40.23  1.00    -              host mgmt-worker1
  2    ssd  0.34180   1.00000  350 GiB  141 GiB  139 GiB   37 MiB  1.7 GiB  209 GiB  40.23  1.00  109      up          osd.2        
 -3         0.34180         -  350 GiB  125 GiB  123 GiB   68 MiB  2.1 GiB  225 GiB  35.76  0.88    -              host mgmt-worker2
  1    ssd  0.34180   1.00000  350 GiB  125 GiB  123 GiB   68 MiB  2.1 GiB  225 GiB  35.76  0.88   92      up          osd.1        
 -7         0.34180         -  350 GiB  134 GiB  133 GiB   80 MiB  1.7 GiB  216 GiB  38.43  0.95    -              host mgmt-worker3
  3    ssd  0.34180   1.00000  350 GiB  134 GiB  133 GiB   80 MiB  1.7 GiB  216 GiB  38.43  0.95  102      up          osd.3        
-11         0.34180         -  350 GiB  132 GiB  129 GiB   72 MiB  2.3 GiB  218 GiB  37.68  0.93    -              host mgmt-worker4
  4    ssd  0.34180   1.00000  350 GiB  132 GiB  129 GiB   72 MiB  2.3 GiB  218 GiB  37.68  0.93  103      up          osd.4        
-13         0.34180         -  350 GiB  147 GiB  145 GiB   63 MiB  1.8 GiB  203 GiB  41.97  1.04    -              host mgmt-worker5
  5    ssd  0.34180   1.00000  350 GiB  147 GiB  145 GiB   63 MiB  1.8 GiB  203 GiB  41.97  1.04  100      up          osd.5        
-15         0.34180         -  350 GiB  137 GiB  134 GiB   64 MiB  2.3 GiB  213 GiB  39.11  0.97    -              host mgmt-worker6
  6    ssd  0.34180   1.00000  350 GiB  137 GiB  134 GiB   64 MiB  2.3 GiB  213 GiB  39.11  0.97  100      up          osd.6        
-17         0.34180         -  450 GiB  235 GiB  133 GiB   78 MiB  2.4 GiB  215 GiB  52.29  1.29    -              host mgmt-worker7
  7    ssd  0.34180   1.00000  450 GiB  235 GiB  133 GiB   78 MiB  2.4 GiB  215 GiB  52.29  1.29  100      up          osd.7        
-19               0         -      0 B      0 B      0 B      0 B      0 B      0 B      0     0    -              host mgmt-worker8
                        TOTAL  2.8 TiB  1.1 TiB  1.0 TiB  493 MiB   16 GiB  1.7 TiB  40.42
```

**Comment by parth-gr** [comment] 2024-04-22 04:33
The ceph side values are correct 
`TOTAL  2.8 TiB  1.1 TiB  1.0 TiB  493 MiB   16 GiB  1.7 TiB  40.42`

So it is the dashboard that probably has an error,
@rkachach one take a look?

**Comment by jameshearttech** [comment] 2024-04-22 06:18
I'm not following how you concluded that the Ceph side values are correct from:
`TOTAL  2.8 TiB  1.1 TiB  1.0 TiB  493 MiB   16 GiB  1.7 TiB  40.42`

The queries in the dashboard are pretty straight forward.
Query A: `ceph_cluster_total_bytes{cluster="$cluster"}-ceph_cluster_total_used_bytes{cluster="$cluster"}`
Query B: `ceph_cluster_total_used_bytes{cluster="$cluster"}`
Query C: `ceph_cluster_total_bytes{}`

The dashboard uses these queries to visualize available, used, and total capacity. How do we conclude that the dashboard is showing incorrect used/available capacity, but the Ceph CLI is showing correct used/available capacity? Is it an issue with the Prometheus metrics from Ceph?

**Comment by parth-gr** [comment] 2024-04-22 06:29
From your Screenshots:

                                   Available      Used     Total

Previous values:         1.51               1.23        2.73

New Values:                1.51               1.33       2.83

From ceph side          1.7                   1.1         2.8
(osd df tree)
(New values)

Which says `ceph side` values are increased correctly

**Comment by parth-gr** [comment] 2024-04-23 15:39
But if you see the ceph output the values are correct.
```
From ceph side          1.7                1.1         2.8
(osd df tree)
(New values)
```

**Comment by jameshearttech** [comment] 2024-04-23 20:24
Looking at the work I have been doing over the course of the day you can see that when I replace an OSD the total and available capacity move together, but when I resize they diverge.

![image](https://github.com/rook/rook/assets/67252279/cfc354df-1e0e-4246-9109-cd4dca748aa3)

**Comment by travisn** [comment] 2024-04-23 22:00
I spun up an AWS test cluster and confirmed that I see the same behavior...

The initial cluster has three OSDs:
```
sh-4.4$ ceph osd df
ID  CLASS  WEIGHT   REWEIGHT  SIZE    RAW USE  DATA     OMAP  META    AVAIL   %USE  VAR   PGS  STATUS
 1    ssd  0.00980   1.00000  10 GiB   27 MiB  724 KiB   0 B  26 MiB  10 GiB  0.26  1.00    1      up
 2    ssd  0.00980   1.00000  10 GiB   27 MiB  724 KiB   0 B  26 MiB  10 GiB  0.26  1.00    1      up
 0    ssd  0.00980   1.00000  10 GiB   27 MiB  720 KiB   0 B  26 MiB  10 GiB  0.26  1.00    1      up
                       TOTAL  30 GiB   81 MiB  2.1 MiB   0 B  79 MiB  30 GiB  0.26                  
```

After resizing, the OSD config is:
```
sh-4.4$ ceph osd df
ID  CLASS  WEIGHT   REWEIGHT  SIZE    RAW USE  DATA     OMAP     META    AVAIL   %USE   VAR   PGS  STATUS
 1    ssd  0.00980   1.00000  15 GiB  5.0 GiB  976 KiB    1 KiB  27 MiB  10 GiB  33.51  1.00    1      up
 2    ssd  0.00980   1.00000  15 GiB  5.0 GiB  976 KiB    1 KiB  27 MiB  10 GiB  33.51  1.00    1      up
 0    ssd  0.00980   1.00000  15 GiB  5.0 GiB  972 KiB    1 KiB  27 MiB  10 GiB  33.51  1.00    1      up
                       TOTAL  45 GiB   15 GiB  2.9 MiB  3.5 KiB  80 MiB  30 GiB  33.51                   
```

This would be a Ceph issue. Rook doesn't have any influence on the sizes the OSDs that are reported, and I don't see how the OSD resize could influence that incorrect raw size. Would you mind opening a [Ceph tracker](https://tracker.ceph.com/) for this?

**Comment by rkachach** [comment] 2024-04-24 07:53
@nizamial09 is this a know issue?

**Comment by jameshearttech** [comment] 2024-04-24 19:31
Sounds like @rkachach is checking if this is a known issue so I'm not going create one yet.

**Comment by jameshearttech** [comment] 2024-04-25 20:47
I found this: https://tracker.ceph.com/issues/63858

**Comment by jameshearttech** [comment] 2024-04-26 16:51
I got a response on [Ceph issue 65659](https://tracker.ceph.com/issues/65659) stating it is probably the same issue as [Ceph issue 63858](https://tracker.ceph.com/issues/63858). The suggested work around is [Ceph issue 63858 note 7](https://tracker.ceph.com/issues/63858#note-7).

**Comment by jameshearttech** [comment] 2024-04-27 01:24
[From [Igor Fedotov](https://tracker.ceph.com/users/2881)](https://tracker.ceph.com/issues/65659#note-11)

> Generally what you need is to shutdown OSD process in a non-graceful manner. And let it rebuild allocmap during the following restart. It has nothing about osd draining or node restart (unless you power it off which I'd prefer not to do).

> In bare metal setup this implies running kill -9 against ceph-osd process. You need to achieve the same in Rook environment. Sorry, I'm not an expert in it hence unable to provide more detailed guideline...

**Comment by jameshearttech** [comment] 2024-04-27 02:00
Following Igor's suggestion worked as expected.

```
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/osd-3/ {print $1}') -n rook-ceph -c osd -it -- sh
sh-4.4# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
65535         1  0.0  0.0    996     4 ?        Ss   Apr26   0:00 /pause
ceph        465  1.2  6.6 2665832 1644016 ?     Ssl  Apr26   6:53 ceph-osd --foreground --id 3 --fsid e1ebb901-75ad-4b7c-90d9-69edf914c04e --setuser ceph --setgroup ceph --crush-location=root=default host=mgmt-worker3 --default-log-to-stderr=true --default-err-
root        471  0.0  0.0  14096  2984 pts/0    Ss   Apr26   0:00 /bin/bash -x -e -m -c  CEPH_CLIENT_ID=ceph-osd.3 PERIODICITY=daily LOG_ROTATE_CEPH_FILE=/etc/logrotate.d/ceph LOG_MAX_SIZE=500M ROTATE=7  # edit the logrotate file to only rotate a specific daemo
root      29350  0.0  0.0  23144  1524 pts/0    S+   01:36   0:00 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 15m
root      29695  0.0  0.0  14228  3328 pts/0    Ss   01:42   0:00 sh
root      29757  0.0  0.0  49828  3708 pts/0    R+   01:43   0:00 ps aux
sh-4.4# kill -9 465
sh-4.4# command terminated with exit code 137
```

RAW USE is now the same size as DATA for OSD3.

```
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/tool/ {print $1}') -n rook-ceph -- ceph osd df tree
ID  CLASS  WEIGHT   REWEIGHT  SIZE     RAW USE  DATA     OMAP     META     AVAIL    %USE   VAR   PGS  STATUS  TYPE NAME            
-1         2.92978         -  3.3 TiB  1.0 TiB  1.0 TiB  391 MiB  7.6 GiB  2.3 TiB  31.30  1.00    -          root default         
-5         0.83009         -  850 GiB  290 GiB  289 GiB   63 MiB  1.9 GiB  560 GiB  34.17  1.09    -              host mgmt-worker0
 0    ssd  0.83009   1.00000  850 GiB  290 GiB  289 GiB   63 MiB  1.9 GiB  560 GiB  34.17  1.09  128      up          osd.0        
-9         0.83009         -  850 GiB  289 GiB  286 GiB  132 MiB  2.7 GiB  561 GiB  34.03  1.09    -              host mgmt-worker1
 1    ssd  0.83009   1.00000  850 GiB  289 GiB  286 GiB  132 MiB  2.7 GiB  561 GiB  34.03  1.09  146      up          osd.1        
-3         0.83009         -  850 GiB  294 GiB  292 GiB   83 MiB  2.2 GiB  556 GiB  34.59  1.11    -              host mgmt-worker2
 2    ssd  0.83009   1.00000  850 GiB  294 GiB  292 GiB   83 MiB  2.2 GiB  556 GiB  34.59  1.11  136      up          osd.2        
-7         0.43950         -  850 GiB  190 GiB  189 GiB  113 MiB  880 MiB  660 GiB  22.41  0.72    -              host mgmt-worker3
 3    ssd  0.43950   1.00000  850 GiB  190 GiB  189 GiB  113 MiB  880 MiB  660 GiB  22.41  0.72   97      up          osd.3        
                       TOTAL  3.3 TiB  1.0 TiB  1.0 TiB  391 MiB  7.6 GiB  2.3 TiB  31.30                                          
MIN/MAX VAR: 0.72/1.11  STDDEV: 5.14
```

Should we automate the work around?

**Comment by travisn** [comment] 2024-04-29 18:07
From the linked ceph tracker, since https://github.com/ceph/ceph/pull/55777 was merged to reef this is expected to be fixed in v18.2.3. 

Good to see that the workaround with `kill -9` in the pod fixed it. 

The `weight` of osd.3 looks about half the size of the other OSDs, which would explain why the PGs are not balanced. But since the raw size is the same for all the OSDs, I'm not sure why the weight would be smaller. It seems the weight is the same as before the resize? Try `ceph osd crush reweight` to adjust it.

**Comment by jameshearttech** [comment] 2024-04-29 18:27
```
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/tool/ {print $1}') -n rook-ceph -- ceph osd crush reweight
Invalid command: missing required parameter name(<string(goodchars [A-Za-z0-9-_.])>)
osd crush reweight <name> <weight:float> :  change <name>'s weight to <weight> in crush map
Error EINVAL: invalid command
command terminated with exit code 22
```

Not sure how this is supposed to work. Do I manually specify the new weight? For example, if I want it to be the same the other OSDs then specify 0.83009? However, if I do that then the OSDs do not sum to 2.92978. Should I reweight all the OSDs to 2.92978/4=0.732445? Why is it not doing this automatically such as when a new OSD is created?

**Comment by jameshearttech** [comment] 2024-04-29 18:33
```
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/tool/ {print $1}') -n rook-ceph -- ceph osd crush reweight osd.3 0.83009
reweighted item id 3 name 'osd.3' to 0.83009 in crush map
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/tool/ {print $1}') -n rook-ceph -- ceph osd df tree
ID  CLASS  WEIGHT   REWEIGHT  SIZE     RAW USE  DATA     OMAP     META     AVAIL    %USE   VAR   PGS  STATUS  TYPE NAME            
-1         3.32036         -  3.3 TiB  1.1 TiB  1.1 TiB  411 MiB   10 GiB  2.3 TiB  32.17  1.00    -          root default         
-5         0.83009         -  850 GiB  299 GiB  296 GiB   70 MiB  2.3 GiB  551 GiB  35.12  1.09    -              host mgmt-worker0
 0    ssd  0.83009   1.00000  850 GiB  299 GiB  296 GiB   70 MiB  2.3 GiB  551 GiB  35.12  1.09  127      up          osd.0        
-9         0.83009         -  850 GiB  297 GiB  294 GiB  130 MiB  3.0 GiB  553 GiB  34.95  1.09    -              host mgmt-worker1
 1    ssd  0.83009   1.00000  850 GiB  297 GiB  294 GiB  130 MiB  3.0 GiB  553 GiB  34.95  1.09  144      up          osd.1        
-3         0.83009         -  850 GiB  302 GiB  299 GiB   88 MiB  2.6 GiB  548 GiB  35.52  1.10    -              host mgmt-worker2
 2    ssd  0.83009   1.00000  850 GiB  302 GiB  299 GiB   88 MiB  2.6 GiB  548 GiB  35.52  1.10  133      up          osd.2        
-7         0.83008         -  850 GiB  196 GiB  194 GiB  123 MiB  2.1 GiB  654 GiB  23.10  0.72    -              host mgmt-worker3
 3    ssd  0.83008   1.00000  850 GiB  196 GiB  194 GiB  123 MiB  2.1 GiB  654 GiB  23.10  0.72  103      up          osd.3        
                       TOTAL  3.3 TiB  1.1 TiB  1.1 TiB  411 MiB   10 GiB  2.3 TiB  32.17
  ```

**Comment by jameshearttech** [comment] 2024-04-29 19:27
```
$ kubectl exec $(kubectl get pod -n rook-ceph | awk '/tool/ {print $1}') -n rook-ceph -- ceph osd df tree
ID  CLASS  WEIGHT   REWEIGHT  SIZE     RAW USE  DATA     OMAP     META     AVAIL    %USE   VAR   PGS  STATUS  TYPE NAME            
-1         3.32036         -  3.3 TiB  1.1 TiB  1.1 TiB  415 MiB  9.0 GiB  2.3 TiB  32.16  1.00    -          root default         
-5         0.83009         -  850 GiB  276 GiB  274 GiB   70 MiB  2.6 GiB  574 GiB  32.51  1.01    -              host mgmt-worker0
 0    ssd  0.83009   1.00000  850 GiB  276 GiB  274 GiB   70 MiB  2.6 GiB  574 GiB  32.51  1.01  122      up          osd.0        
-9         0.83009         -  850 GiB  279 GiB  277 GiB  130 MiB  1.9 GiB  571 GiB  32.86  1.02    -              host mgmt-worker1
 1    ssd  0.83009   1.00000  850 GiB  279 GiB  277 GiB  130 MiB  1.9 GiB  571 GiB  32.86  1.02  134      up          osd.1        
-3         0.83009         -  850 GiB  282 GiB  279 GiB   88 MiB  2.9 GiB  568 GiB  33.19  1.03    -              host mgmt-worker2
 2    ssd  0.83009   1.00000  850 GiB  282 GiB  279 GiB   88 MiB  2.9 GiB  568 GiB  33.19  1.03  125      up          osd.2        
-7         0.83008         -  850 GiB  256 GiB  254 GiB  127 MiB  1.7 GiB  594 GiB  30.08  0.94    -              host mgmt-worker3
 3    ssd  0.83008   1.00000  850 GiB  256 GiB  254 GiB  127 MiB  1.7 GiB  594 GiB  30.08  0.94  126      up          osd.3        
                       TOTAL  3.3 TiB  1.1 TiB  1.1 TiB  415 MiB  9.0 GiB  2.3 TiB  32.16                                          
MIN/MAX VAR: 0.94/1.03  STDDEV: 1.22
```

**Comment by travisn** [comment] 2024-04-29 19:47
By default, the weight of the OSD is based on the size, so this sounds expected. If it's off by such a small amount it shouldn't impact the PG placement enough to worry about. PGs will not be exactly perfectly distributed across OSDs anyway since it's based on hashing.

**Comment by jameshearttech** [comment] 2024-04-29 21:44
@travisn really appreciate your help. I'm closing this one out.

**Comment by zalsader** [comment] 2024-08-20 19:14
I am having the same issue. Upgrading to `18.2.4` does not automatically fix it. I still had to `kill -9` the osd process

**Comment by travisn** [comment] 2024-08-20 19:36
@jameshearttech Have you tried the resize on v18.2.4?

**Comment by jameshearttech** [comment] 2024-08-20 19:42
@travisn @zalsader we have upgraded Ceph to quay.io/ceph/ceph:v18.2.4-20240724, but I have not resized a virtual disk. The ticket I created in Ceph tracker was closed 5 days ago.

https://tracker.ceph.com/issues/65659#note-18

**Comment by zalsader** [comment] 2024-08-21 02:13
I checked rn. Ceph was upgraded to `18.2.4`. For the changes to take effect, the osd pods had to be restarted:
```
kubectl rollout restart deployment rook-ceph-osd-1 -n rook-ceph
```

Restarting the operator does not do this automatically. Is this expected? If so, I think it should be documented.

**Comment by travisn** [comment] 2024-08-21 05:17
> I checked rn. Ceph was upgraded to `18.2.4`. I resized my volumes, but the changes were not picked up (as opposed to showing up as used). For the changes to take effect, the osd pods had to be restarted:
> 
> ```
> kubectl rollout restart deployment rook-ceph-osd-1 -n rook-ceph
> ```
> 
> Restarting the operator does not do this automatically. Is this expected? If so, I think it should be documented.

At the time the OSDs were upgraded to v18.2.4, they would have been restarted. After that, Rook wouldn't restart them unless there is a change in the pod spec, such as another version update or setting change related to the OSD. Restarting the operator is not expected to restart all the daemons.

**Closed** 2024-10-28 20:02 UTC
Labels: bug, wontfix
