### ISSUE TITLE
Ceph cluster reconciling triggers every 9h10m

### ISSUE THREAD

**Issue by lbogdan** [rook/rook#13478] opened 2023-12-27 13:16 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph cluster reconciling triggers every 9h10m:

```
$ kubectl -n rook-ceph logs rook-ceph-operator-5698dc8c7c-jfsxc | grep 'ceph-cluster-controller: reconciling'
2023-12-24 10:06:43.790578 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-25 04:26:08.724244 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-25 13:35:51.213663 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-25 22:45:33.703315 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-26 07:55:16.192428 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-26 17:04:58.681978 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-27 02:14:41.171897 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-12-27 11:24:23.661629 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
```

This, in turn, restarts the active `mgr`:

```
# correlated with the last reconciling above ^^
2023-12-27T11:24:54.899548+0000 mon.a [INF] Active manager daemon a restarted
2023-12-27T11:24:54.899903+0000 mon.a [INF] Activating manager daemon a
2023-12-27T11:25:00.868368+0000 mon.a [INF] Active manager daemon a restarted
2023-12-27T11:25:00.868584+0000 mon.a [INF] Activating manager daemon a
2023-12-27T11:25:00.897805+0000 mon.a [INF] Manager daemon a is now available
```

Which, weirdly enough, causes the `rbd` `csi-provisioner` container to fail whenever creating / deleting a PVC with

```
I1227 12:29:44.853722       1 controller.go:1509] delete "pvc-8760d71d-a762-4afa-9608-bf66a17bae5c": started
E1227 12:29:44.855472       1 connection.go:142] Lost connection to unix:///csi/csi-provisioner.sock.
F1227 12:29:44.855661       1 connection.go:97] Lost connection to CSI driver, exiting
```

, restart, and introduce a ~3m delay in creating / deleting the PVC, because of #13475 .

**Expected behavior:**

Nothing of the above happens.

**How to reproduce it (minimal and precise):**

Create a new `rook` `v1.13.1` / `ceph` `v18.2.1` cluster and wait for 9h10m. 🙂

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu `22.04.3` LTS
* Kernel (e.g. `uname -a`): `6.2.0-39-generic`
* Cloud provider or hardware configuration: bare-metal Kubernetes cluster
* Rook version (use `rook version` inside of a Rook Pod): `v1.13.1`
* Storage backend version (e.g. for ceph do `ceph -v`): `v18.2.1`
* Kubernetes version (use `kubectl version`): `v1.28.5`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `kubeadm`-bootstrapped
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_OK`

Any idea how I can find out what triggers the reconciling?

**Comment by lbogdan** [comment] 2023-12-28 10:11
Did a bit more troubleshooting, after setting the operator's log level to `DEBUG`, I see this just before the reconciling:

```
2023-12-28 05:43:48.639721 D | ceph-spec: object "rook-config-override" matched on update
2023-12-28 05:43:48.639733 D | ceph-spec: do reconcile when the cm is rook-config-override
2023-12-28 05:43:48.639842 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
```

So it looks like _something_ is changing the `rook-config-override` configmap, triggering a cluster reconciling.

Indeed, I can reproduce if I manually edit the configmap, e.g. by adding a dummy label.

For now I added the `do_not_reconcile: "true"` label to the configmap after seeing [this code](https://github.com/rook/rook/blob/213dfaadde703e9ff7725a527926f9f5a2571037/pkg/operator/ceph/controller/predicate.go#L74-L79), which disables the reconciling on `rook-config-override` changes.

Still, 2 questions remain:

1. What's changing the `rook-config-override` every 9h10m?

2. Is it expected for the primary `mgr` to restart during reconciling? This also happens during the initial reconciling when the operator is restarted (operator pod deleted).

**Comment by travisn** [comment] 2024-01-19 22:28
> 1. What's updating the `rook-config-override` configmap every 9h10m?

Nothing in Rook should be updating the configmap. It's just created once by the operator, then never expected to be updated. Do you have custom settings in that configmap? If so, how are you setting it? Could that process be causing this every 9h?

> 2. Is it expected for the primary `mgr` to restart during reconciling? This also happens during the initial reconciling when the operator is restarted (operator pod deleted).

The mgr is not expected to restart unless something is actually changing. From the log, it looks like the mgr is just restarting internally and it's not a full pod restart? 

There are only two types of mgr restarts I can think of:
1. The mgr pod spec is updated during the reconcile, which would result in a new mgr pod creation. If this is your behavior, it would help to diff the pod spec before/after the update to see what setting is changing.
2. Some mgr modules are restarted individually (specifically the dashboard and prometheus modules) if some related settings changed. But I don't believe those module restarts would be related to your issue.

Any chance you see this line in your log? If so, it will be fixed by #13597. 
```
object "rook-ceph-exporter" matched on delete, reconciling
```

**Comment by briend** [comment] 2024-01-26 22:11
I'm seeing the same thing with Rook `1.12.0` (ceph `18.2.1`) and I suspect Rook `1.11.11` (ceph `17.2.6`) (although I don't have debug logs to confirm it on that version). I noticed the `rook-ceph-osd-prepare` pods being restarted every day at least...  and in the debug logs on Rook I see the same message about the `rook-config-override` triggering the reconcile:

```
2024-01-26 14:16:42.560352 D | ceph-spec: object "rook-config-override" matched on update
2024-01-26 14:16:42.560360 D | ceph-spec: do reconcile when the cm is rook-config-override
2024-01-26 14:16:42.560522 I | ceph-cluster-controller: reconciling ceph cluster in namespace "ceph-cluster1"
```

Which sure looks like it's hitting this codepath: https://github.com/rook/rook/blob/d6883b8aa9a5307e13bec39ed2db6a5a95ae0db3/pkg/operator/ceph/controller/predicate.go#L557

Our `rook-config-override` CM is empty and I can't imagine what would be modifying it.  I looked for related k8s events but didn't have much luck.  I didn't see any other ceph pods restarting, nor the mgr restart messages in the mgr logs.

I can't say is happening every `9h10m`, but it seems to be at least once a day.  One of our clusters hasn't reconciled for `20h`, FWIW.

```
apiVersion: v1
data:
  config: ""
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: ceph-cluster1
    meta.helm.sh/release-namespace: ceph-cluster1
  creationTimestamp: "2023-12-20T17:37:52Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rook-config-override
  namespace: ceph-cluster1
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: ceph-cluster1-rook-ceph-cluster
    uid: 60b6f041-3b2c-4575-81c6-68488db900cd
  resourceVersion: "979604622"
  uid: 3f108a42-a737-4676-8621-8b64716fa9e2
```

**Comment by travisn** [comment] 2024-01-30 23:03
In #13652 in an attempt to suppress these unnecessary reconciles, the operator will skip the reconcile at least if the configmap is empty. 

The cause of the configmap update could be in [populateConfigOverrideConfigMap()](https://github.com/rook/rook/blob/4a12234bbe3a37d7b8d2017bc54d0cca3d27f64d/pkg/operator/ceph/cluster/utils.go#L81-L90) where the helm chart labels are attempted to be added to the configmap labels if it was deployed by a helm chart. But it seems that should only cause a single update to the helm chart. Do you see this more than once in your operator log?
```
adding helm chart name <name> annotation to configmap
```

**Comment by BlaineEXE** [comment] 2024-01-31 22:44
FWIW, this is a feature of Controller Runtime. It sets all resources to re-reconcile every 10 hours plus/minus a jitter factor. Reconciling periodically means that an operator can make sure that the current state of the system doesn't drift over time when there are no user changes to configs.

**Comment by BlaineEXE** [comment] 2024-02-01 15:38
I read a bit more about this and came across this issue/discussion: https://github.com/kubernetes-sigs/controller-runtime/issues/521

One of the primary maintainers has the opinion that re-reconcile (called "resync") shouldn't be necessary for most controllers.

https://github.com/kubernetes-sigs/controller-runtime/issues/521#issuecomment-518457302
> All it does is force a re-reconcile of everything in the cache. Generally, you probably don't want to do this -- it's often expensive, it'll mask subtle bugs, and it's usually not necessary. It's actually probably fine to set this to never, except it might save you in production if you've got bugs in your reconcile logic because you didn't write a level-based controller.
>
> The only place, IMO, it's actually reasonable to use this knob, is if you're writing something that needs periodic reconcilation, like a horizontal pod autoscaler, but we'd recommend using RequeueAfter or a custom event source implementation to do this instead.

**Closed** 2024-02-05 07:13 UTC
Labels: bug
