### ISSUE TITLE
Helm repo is unavailable in browser

### ISSUE THREAD

**Issue by r-moiseev** [rook/rook#1798] opened 2018-06-19 14:04 UTC
* Bug Report

**Bug Report**

What happened:

`Error: [object Object]` on  https://charts.rook.io/alpha

**Comment by thecodeassassin** [comment] 2018-06-20 11:21
I can confirm this is still an issue

**Comment by galexrt** [comment] 2018-06-20 11:54
@r-moiseev @thecodeassassin  Is just the web view of the helm repo (e.g. S3 folder view) not working or are you also unable to install helm charts by using `helm install`?

**Comment by r-moiseev** [comment] 2018-06-20 11:57
helm is working now, yesterday was unavailable for few hours.

**Comment by thecodeassassin** [comment] 2018-06-20 12:58
@r-moiseev  For me, web view is not working. I wanted to check the default values.yaml.

**Comment by jbw976** [comment] 2018-06-20 17:58
@thecodeassassin on https://charts.rook.io/, are you seeing a page with just the content below?
> Error: [object Object]

This is what the chrome dev tools show me, I wonder if that is the cause:
```
Failed to load https://rook-charts.s3.amazonaws.com/?delimiter=/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://charts.rook.io' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by thecodeassassin** [comment] 2018-06-20 17:59
Yep, getting the same here.

Op wo 20 jun. 2018 19:58 schreef Jared Watts <notifications@github.com>:

**Comment by r-moiseev** [comment] 2018-06-21 10:49
And again i is unavailable with helm install

**Comment by jbw976** [comment] 2018-06-22 00:21
I'm looking into this again today, I still see the same error on https://charts.rook.io/.  I updated the CORS configuration as per https://stackoverflow.com/a/35278803/467462, but that did not resolve the error.  I can't imagine that a more complicated solution outlined in https://medium.com/statup/statups-workaround-long-term-solution-to-an-aws-cors-issue-68d0b68555db, that would be a bit ridiculous.

@r-moiseev what's the error that you see during a helm install, it it similar to what is shown in the browser on https://charts.rook.io/?  Please share the error output if you can, thanks.

**Comment by bjornryden** [comment] 2018-07-10 11:50
The rook-master still seems to have issues, but rook-alpha is working fine.

`09:35 $ helm search | grep rook-master
rook-master/rook                                  v0.7.0-136.gd13bc83                                       File, Block, and Object Storage Services for yo...
rook-master/rook-ceph                             v0.7.0-240.gc568dd6                                       File, Block, and Object Storage Services for yo...
:heavy_check_mark: ~/git/infrastructure [k8 ↑·79|✚ 12…7⚑ 2] 
09:35 $ helm install rook-master/rook
Error: failed to download "rook-master/rook" (hint: running `helm repo update` may help)
✘-1 ~/git/infrastructure [k8 ↑·79|✚ 12…7⚑ 2] 
09:35 $ helm install rook-master/rook-ceph
Error: failed to download "rook-master/rook-ceph" (hint: running `helm repo update` may help)`

**Comment by jbw976** [comment] 2018-07-10 15:15
@travisn the originally reported issue still exists, visiting https://charts.rook.io/ in a browser gives an error page that says `Error: [object Object]`.

**Comment by travisn** [comment] 2018-07-10 15:17
ah, i didn't look at the original title

**Comment by jbw976** [comment] 2018-07-10 15:22
## WORKAROUND
To list all the versions for a given Rook charts repo/channel, you can use the following curl commands:

master:
```console
curl -s https://s3.amazonaws.com/rook.charts/master/index.yaml | sed -n -e 's/^.*version: //p'
```
alpha:
```console
curl -s https://s3.amazonaws.com/rook.charts/alpha/index.yaml | sed -n -e 's/^.*version: //p'
```

**Comment by zehicle** [comment] 2018-09-12 19:10
If this is an ongoing issue, it may be good to update the documentation to not rely on the short links.

**Comment by bassam** [comment] 2018-12-03 05:31
this is fixed now.

**Closed by bassam** 2018-12-03 05:31 UTC
Labels: helm
