### ISSUE TITLE
ERROR: S3 error: 403 (AccessDenied)

### ISSUE THREAD

**Issue by billy98** [rook/rook#7028] opened 2021-01-21 03:20 UTC
Here are my steps, but I still can't upload the file to the bucket

```
[root@k8s-master-01 rook]# kubectl apply -f ceph/object.yaml 
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  preservePoolsOnDelete: false
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    instances: 1
    placement:
    annotations:
    labels:
    resources:
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
    livenessProbe:
      disabled: false



[root@k8s-master-01 ~]# kubectl -n rook-ceph get pod -l app=rook-ceph-rgw
NAME                                        READY   STATUS    RESTARTS   AGE
rook-ceph-rgw-my-store-a-557dbfb7c4-gjqxh   1/1     Running   0          6h12m

[root@k8s-master-01 rook]# kubectl apply -f ceph/storageclass-bucket-retain.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-retain-bucket
reclaimPolicy: Retain
parameters:
  region: us-east-1

[root@k8s-master-01 rook]# kubectl get sc
NAME                      PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-ceph-retain-bucket   rook-ceph.ceph.rook.io/bucket   Retain          Immediate           false                  9s


[root@k8s-master-01 rook]# kubectl apply -f ceph/object-bucket-claim-retain.yaml 
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-retain-bucket
spec:
  generateBucketName: ceph-bkt
  storageClassName: rook-ceph-retain-bucket
  additionalConfig:


[root@k8s-master-01 rook]# kubectl -n default get cm ceph-retain-bucket -o jsonpath='{.data.BUCKET_HOST}'
rook-ceph-rgw-my-store.rook-ceph.svc

[root@k8s-master-01 rook]# kubectl -n rook-ceph get svc rook-ceph-rgw-my-store
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
rook-ceph-rgw-my-store   ClusterIP   10.245.80.161   <none>        80/TCP    8h

[root@k8s-master-01 rook]# export AWS_HOST=$(kubectl -n default get cm ceph-retain-bucket -o jsonpath='{.data.BUCKET_HOST}')
[root@k8s-master-01 rook]# export AWS_ACCESS_KEY_ID=$(kubectl -n default get secret ceph-retain-bucket -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 --decode)
[root@k8s-master-01 rook]# export AWS_SECRET_ACCESS_KEY=$(kubectl -n default get secret ceph-retain-bucket -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 --decode)
[root@k8s-master-01 rook]# export AWS_ENDPOINT=$(kubectl -n rook-ceph get svc rook-ceph-rgw-my-store -o jsonpath='{.spec.clusterIP}')
[root@k8s-master-01 rook]# echo '10.245.80.161 rook-ceph-rgw-my-store.rook-ceph.svc' >> /etc/hosts


[root@k8s-master-01 rook]# radosgw-admin bucket list
[
    "ceph-bkt-50023a70-a903-428f-b374-05d30d407c8a",
    "rook-ceph-bucket-checker-a4e13245-5547-44b0-bec0-eafcbbe07789"
]


[root@k8s-master-01 rook]#  s3cmd put /tmp/rookObj --no-ssl --host=${AWS_HOST} --host-bucket=  s3://rook-ceph-bucket-checker-a4e13245-5547-44b0-bec0-eafcbbe07789/
upload: '/tmp/rookObj' -> 's3://rook-ceph-bucket-checker-a4e13245-5547-44b0-bec0-eafcbbe07789/rookObj'  [1 of 1]
 11 of 11   100% in    0s     2.91 KB/s  done
ERROR: S3 error: 403 (AccessDenied)
```

**Comment by thotz** [comment] 2021-01-21 10:20
@billy98 : I don't understand the bucket created by OBC will be `ceph-bkt-50023a70-a903-428f-b374-05d30d407c8a`, but you are putting to health checker bucket(used internally by rook)

**Comment by thotz** [comment] 2021-01-25 05:39
closing as not a bug

**Closed by thotz** 2021-01-25 05:39 UTC
Labels: bug
