### ISSUE TITLE
No new OSD on new nodes when useAllNodes set to true until rook-ceph-operator is restarted

### ISSUE THREAD

**Issue by snowmansora** [rook/rook#1998] opened 2018-08-07 11:08 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** 
No new OSD on new nodes when useAllNodes set to true

**Expected behavior:**
New OSD is started on new nodes when useAllNodes set to true

**How to reproduce it (minimal and precise):**

1. K8s cluster with 3 nodes
2. Deploy https://github.com/rook/rook/blob/release-0.8/cluster/examples/kubernetes/ceph/operator.yaml //set image: rook/ceph:v0.8.1 // set FLEXVOLUME_DIR_PATH
3. Deploy https://github.com/rook/rook/blob/release-0.8/cluster/examples/kubernetes/ceph/cluster.yaml // set mon count = 3 // set mon allowMultiplePerNode to false // set placement to node with my custom rook label
4. Deploy https://github.com/rook/rook/blob/release-0.8/cluster/examples/kubernetes/ceph/storageclass.yaml // set pool replicated size to 2 // set pool fstype to xfs
5. Add nodes to K8s cluster
6. No new OSD on new nodes after waiting for more than 15 mins
Workaround:
7. Delete/Restart rook-ceph-operator pod
8. New OSD spawned on new nodes

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
* Kernel (e.g. `uname -a`): 3.10.0-862.3.2.el7.x86_64
* Cloud provider or hardware configuration: AWS EC2 instances
* Rook version (use `rook version` inside of a Rook Pod): 0.8.1
* Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Deployed via kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by snowmansora** [comment] 2018-08-08 06:45
Also, I have tried similar procedure with rook 0.7.1, and new OSD is started on new nodes.
So, it may be a bug in 0.8.X?

**Comment by galexrt** [comment] 2018-08-08 07:14
@snowmansora Currently the operator does not pick up new nodes until restarted.
This is partly tracked in #1435.

/cc @travisn Is that the tracking issue?

**Comment by galexrt** [comment] 2018-09-06 14:20
Closing this as duplicate of #1435.

**Closed by galexrt** 2018-09-06 14:20 UTC
Labels: ceph
