### ISSUE TITLE
RBD provisioner stuck attempting to acquire leader lease for 30s

### ISSUE THREAD

**Issue by 0xAlcibiades** [rook/rook#13475] opened 2023-12-26 22:25 UTC
It's taking over 30s for a leader lease to be acquired and for an RBD to be provisioned, this is on rook 1.13 on a healthy cluster rke2 kubernetes v1.29

**Comment by lbogdan** [comment] 2023-12-27 08:07
I have the same issue. Looking at `csi-rbdplugin-provisioner` logs, it takes 163s (2m43s) for the `csi-provisioner` container to acquire the lease:

```
I1227 07:33:29.952395       1 leaderelection.go:250] attempting to acquire leader lease rook-ceph/rook-ceph-rbd-csi-ceph-com...
I1227 07:36:12.119748       1 leaderelection.go:260] successfully acquired lease rook-ceph/rook-ceph-rbd-csi-ceph-com
```

but this seems to be expected behavior, looking at its args: https://github.com/rook/rook/blob/0196001840a70df0815242d2626993b28a79895c/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L94-L96 - lease duration + retry period = 137s + 26s = 163s.

Out of curiosity, can you provide a `ceph status`? You can run it from a [toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/) pod or using the [kubectl plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin/).

```
kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph status
  cluster:
    id:     dafaa992-d49d-409f-bc40-e9d151040a7d
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 3d)
    mgr: a(active, since 5h), standbys: b
    osd: 6 osds: 6 up (since 3d), 6 in (since 3d)
 
  data:
    pools:   2 pools, 33 pgs
    objects: 3.23k objects, 11 GiB
    usage:   38 GiB used, 2.2 TiB / 2.2 TiB avail
    pgs:     33 active+clean
 
  io:
    client:   263 KiB/s wr, 0 op/s rd, 6 op/s wr
```

**Comment by 0xAlcibiades** [comment] 2023-12-27 15:42
> I have the same issue. Looking at `csi-rbdplugin-provisioner` logs, it takes 163s (2m43s) for the `csi-provisioner` container to acquire the lease:
> 
> ```
> I1227 07:33:29.952395       1 leaderelection.go:250] attempting to acquire leader lease rook-ceph/rook-ceph-rbd-csi-ceph-com...
> I1227 07:36:12.119748       1 leaderelection.go:260] successfully acquired lease rook-ceph/rook-ceph-rbd-csi-ceph-com
> ```
> 
> but this seems to be expected behavior, looking at its args:
> 
> https://github.com/rook/rook/blob/0196001840a70df0815242d2626993b28a79895c/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L94-L96
> 
> - lease duration + retry period = 137s + 26s = 163s.
> Out of curiosity, can you provide a `ceph status`? You can run it from a [toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/) pod or using the [kubectl plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin/).
> 
> ```
> $ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph status
>   cluster:
>     id:     dafaa992-d49d-409f-bc40-e9d151040a7d
>     health: HEALTH_OK
>  
>   services:
>     mon: 3 daemons, quorum a,b,c (age 3d)
>     mgr: a(active, since 5h), standbys: b
>     osd: 6 osds: 6 up (since 3d), 6 in (since 3d)
>  
>   data:
>     pools:   2 pools, 33 pgs
>     objects: 3.23k objects, 11 GiB
>     usage:   38 GiB used, 2.2 TiB / 2.2 TiB avail
>     pgs:     33 active+clean
>  
>   io:
>     client:   263 KiB/s wr, 0 op/s rd, 6 op/s wr
> ```

Ceph status is health OK.

```
bash-4.4$ ceph status
  cluster:
    id:     c341cb8b-4d9d-4530-a79f-13070fa69856
    health: HEALTH_OK

  services:
    mon: 1 daemons, quorum a (age 27h)
    mgr: a(active, since 19m)
    mds: 1/1 daemons up, 1 hot standby
    osd: 4 osds: 4 up (since 21h), 4 in (since 27h)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   15 pools, 265 pgs
    objects: 268.93k objects, 1.0 TiB
    usage:   1.5 TiB used, 54 TiB / 56 TiB avail
    pgs:     265 active+clean

  io:
    client:   54 KiB/s rd, 53 MiB/s wr, 41 op/s rd, 3.12k op/s wr
    ```
    
    Running YOLO mode with 1 mon right now as this is just exploratory/lab.

**Comment by lbogdan** [comment] 2023-12-27 15:44
From the

```
    mgr: a(active, since 19m)
```

line it looks like you have the same issue as #13478 .

**Comment by lbogdan** [comment] 2023-12-31 11:26
Nevermind, it looks like `csi-provisioner` losing connection to `unix:///csi/csi-provisioner.sock` 

```
I1227 12:29:44.853722       1 controller.go:1509] delete "pvc-8760d71d-a762-4afa-9608-bf66a17bae5c": started
E1227 12:29:44.855472       1 connection.go:142] Lost connection to unix:///csi/csi-provisioner.sock.
F1227 12:29:44.855661       1 connection.go:97] Lost connection to CSI driver, exiting
```

is not related to the `mgr` restarting - it's still happening after some inactivity period, even if I managed to prevent the `mgr` to restart.

**Comment by mbleichner** [comment] 2024-01-15 10:43
I'm also seeing this a lot after the 1.13.2 update.

Can we somehow reduce the wait times for leader election significantly to alleviate the problem in the meantime?

**Comment by Madhu-1** [comment] 2024-01-15 11:51
Sure, we can make the leader election flags as configurable but these values are not changed recently its there from some release. if you are hitting any bugs related to leader election check updating the sidecar image or check if csi-rbdplugin csi-cephfsplugin is crashing (in any case)

**Comment by mbleichner** [comment] 2024-01-15 21:03
Sweet, thank you very much for your work!

My temporary solution was to set `provisionerReplicas: 1` and create a Kyverno hack to change `--leader-election` to `false`. Seems to work alright and the provisioner pods start up without any delay.

Do you see any problems with this approach? If not, it may be reasonable to add this behavior to the helm values (so that when you set provisioner replicas to 1, leader election will be disabled completely).

**Comment by lbogdan** [comment] 2024-01-16 08:41
I think we should open an issue in https://github.com/ceph/ceph-csi to fix the root issue?

**Comment by Madhu-1** [comment] 2024-01-16 08:44
> I think we should open an issue in https://github.com/ceph/ceph-csi to fix the root cause?

@lbogdan i can take a look at this issue only, please check if you are affected with older csi-provisioner image https://github.com/rook/rook/issues/13458#issuecomment-1892024668. if not if we can get the required logs https://github.com/rook/rook/issues/13458#issuecomment-1892013847

**Comment by lbogdan** [comment] 2024-01-16 08:52
Oh, thanks, I completely missed that issue!

**Comment by Madhu-1** [comment] 2024-01-16 08:57
> Sweet, thank you very much for your work!
> 
> My temporary solution was to set `provisionerReplicas: 1` and create a Kyverno hack to change `--leader-election` to `false`. Seems to work alright and the provisioner pod starts up without any delay.
> 

it should be fine but you will not have any HA, in larger clusters its recommended to have deployment with at least replica 2.

> Do you see any problems with this approach? If not, it may be reasonable to add this behavior to the helm chart (so that when you set provisioner replicas to 1, leader election will be disabled completely).

we will have one side effect if we disable leader election with replica :1, if a node where the provisoner pod is scheduled and it goes to a bad and and the pods goes to terminating state but still able to process the PV request and a new pod comes on new node might also try to serve the same request, to avoid this kind of corner case it might be better to have leader election enabled but not disabled.

**Comment by Madhu-1** [comment] 2024-01-17 09:55
> I can confirm that upgrading to `sig-storage/csi-provisioner:v3.6.3` fixed the issue.
> 
> @mbleichner If you're using the helm chart, you can set the following in your `values.yaml`:
> 
> ```yaml
> csi:
>   provisioner:
>     image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.3
> ```
> 
> @Madhu-1 You should probably make that the default in the next `rook` release.

Sure, sending to PR to change the default in Rook.

**Comment by mbleichner** [comment] 2024-01-17 15:28
Thanks @lbogdan, v3.6.3 has been running without any crashes so far 👍

**Comment by mbleichner** [comment] 2024-01-18 12:49
@travisn Technically, the original problem (leader election taking very long to complete) isn't fixed by this. Only the frequent crashes that lead to unnecessary leader elections.

I don't know if you intend to change this, but I personally don't see a reason why leader election should take almost 3 minutes to complete.

**Comment by travisn** [comment] 2024-01-18 18:54
Reopening since the lease configuration options will be provided with #13573.

**Closed** 2024-01-18 18:55 UTC
Labels: bug

**Comment by travisn** [comment] 2024-01-18 18:56
And now #13573 is merged, so the lease options will be configurable in v1.13.3 planned for next week.
