### ISSUE TITLE
Operator log shows "failed to delete object in bucket"

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#7120] opened 2021-02-01 21:06 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator pod prints errors in sunny day case. 

**Expected behavior:**
There should not be any error messages in operator pod. 

**How to reproduce it (minimal and precise):**

Restart the operator pod. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
```
# knc logs -f rook-ceph-operator-7b56d6944f-kln7m | grep " E "
2021-02-01 20:54:40.233023 E | ceph-block-pool-controller: failed to reconcile. invalid pool CR "csireplpool" spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-01 20:54:42.308274 E | ceph-object-controller: failed to reconcile invalid object store "rook-ceph-store" arguments: invalid metadata pool spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-01 20:54:43.109367 E | ceph-file-controller: failed to reconcile invalid object filesystem "myfs" arguments: invalid metadata pool: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-01 20:54:43.707525 E | ceph-block-pool-controller: failed to reconcile. invalid pool CR "csireplpool" spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-01 20:54:43.707676 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',): exit status 1
2021-02-01 20:54:44.835298 E | ceph-object-controller: failed to reconcile invalid object store "rook-ceph-store" arguments: invalid metadata pool spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-01 20:57:48.406424 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
2021-02-01 20:57:48.406473 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
2021-02-01 20:57:51.699883 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
2021-02-01 20:57:51.699912 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
2021-02-01 20:58:55.399943 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
2021-02-01 20:58:55.399995 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
2021-02-01 20:58:58.323510 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
2021-02-01 20:58:58.323573 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
2021-02-01 21:00:00.803338 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
2021-02-01 21:00:00.803389 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
2021-02-01 21:00:03.851360 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
2021-02-01 21:00:03.851389 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
2021-02-01 21:01:06.375866 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed

```

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): Rook v1.5.6
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment] 2021-02-01 21:52
The first failures should be fixed by #7056, we will plan to include it in v1.5.7. 

@BlaineEXE Thoughts on this error? 
```
2021-02-01 20:58:58.323573 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
```

**Comment by yanchicago** [comment] 2021-02-23 17:08
The release 1.5.7 still has the error.
```
2021-02-23 17:01:39.336340 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
caused by: Delete http://rook-ceph-rgw-rook-ceph-store.rook-ceph.svc:9443/rook-ceph-bucket-checker-b2a4ba98-9aee-4b04-b53f-e16b7040b7fc/rookHealthCheckTestObject: EOF
2021-02-23 17:02:41.806375 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
caused by: Delete http://rook-ceph-rgw-rook-ceph-store.rook-ceph.svc:9443/rook-ceph-bucket-checker-b2a4ba98-9aee-4b04-b53f-e16b7040b7fc/rookHealthCheckTestObject: EOF
2021-02-23 17:02:41.806422 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
caused by: Delete http://rook-ceph-rgw-rook-ceph-store.rook-ceph.svc:9443/rook-ceph-bucket-checker-b2a4ba98-9aee-4b04-b53f-e16b7040b7fc/rookHealthCheckTestObject: EOF
2021-02-23 17:02:44.526841 E | ceph-object-controller: failed to delete object from bucket. RequestError: send request failed
caused by: Delete http://rook-ceph-rgw-rook-ceph-store.rook-ceph.svc:9443/rook-ceph-bucket-checker-b2a4ba98-9aee-4b04-b53f-e16b7040b7fc/rookHealthCheckTestObject: EOF
2021-02-23 17:02:44.526955 E | ceph-object-controller: failed to delete object in bucket. RequestError: send request failed
caused by: Delete http://rook-ceph-rgw-rook-ceph-store.rook-ceph.svc:9443/rook-ceph-bucket-checker-b2a4ba98-9aee-4b04-b53f-e16b7040b7fc/rookHealthCheckTestObject: EOF
```

**Comment by BlaineEXE** [comment] 2021-02-23 18:44
Please attach full operator logs and the `cluster.yaml` to help debug.

**Comment by yanchicago** [comment] 2021-02-23 19:57
[cluster.yaml.txt](https://github.com/rook/rook/files/6031523/cluster.yaml.txt)
[operator.log0223.txt](https://github.com/rook/rook/files/6031524/operator.log0223.txt)

**Comment by yanchicago** [comment] 2021-02-23 19:58
Attached is the cluster.yaml and operator log. This is a new deploy. Similar failure log is shown after upgrade.

**Comment by BlaineEXE** [comment] 2021-02-23 21:34
You say this happens after upgrade also. Is there a version of Rook you have running where this does work?

**Comment by yanchicago** [comment] 2021-02-23 22:43
Could you please include the ticket about the above "k8s network config" ?

**Comment by yanchicago** [comment] 2021-02-24 15:25
rook 1.4.8 has below error messages when operator starts up. There's no other error messages. This was tested in the same k8s cluster as with rook 1.5.6/1.5.7. 
```
# knc logs -f rook-ceph-operator-5699f4fd48-rk2h5 | egrep " E "

2021-02-24 02:05:52.506467 E | ceph-block-pool-controller: failed to reconcile invalid pool CR "csireplpool" spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-24 02:05:53.710051 E | ceph-object-controller: failed to reconcile invalid object store "rook-ceph-store" arguments: invalid metadata pool spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-24 02:05:53.710612 E | ceph-file-controller: failed to reconcile invalid object filesystem "myfs" arguments: invalid metadata pool: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
2021-02-24 02:05:54.413280 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',): exit status 1
2021-02-24 02:05:55.125311 E | ceph-block-pool-controller: failed to reconcile invalid pool CR "csireplpool" spec: failed to get crush map: failed to get crush map. Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
```

**Comment by BlaineEXE** [comment] 2021-02-25 16:36
Let's figure out what the issue is in your case, and then we can include information in the k8s network config section. What k8s distribution and CNI are you using?

**Closed** 2021-06-02 20:46 UTC
Labels: bug, ceph, object bucket claims (OBC), objectstore, wontfix
