### ISSUE TITLE
module  not  found

### ISSUE THREAD

**Issue by ywd1988** [rook/rook#13616] opened 2024-01-24 13:52 UTC
![image](https://github.com/rook/rook/assets/92080991/8d12d71d-7aa3-4b02-b7ac-e6e0e3158d7e)
![image](https://github.com/rook/rook/assets/92080991/7a79cae8-5ccb-4e5c-9fb6-808416d75bc0)
![image](https://github.com/rook/rook/assets/92080991/f73ba06f-e0a9-4618-a4c4-1183600bf352)

**Comment by travisn** [comment] 2024-01-24 14:40
Looks like a duplicate of #13527

**Comment by rkachach** [comment] 2024-01-25 09:32
Duplicate https://github.com/rook/rook/issues/13527

**Closed by rkachach** 2024-01-25 09:32 UTC
Labels: bug
