### ISSUE TITLE
cephobjectstore removal problem: too liberal label selector

### ISSUE THREAD

**Issue by zerkms** [rook/rook#7365] opened 2021-03-08 00:41 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I run 5 `cephobjectstore`s (with quite a bunch of buckets there). Then I created another 6th `cephobjectstore`.

I did not use it for anything and after several minutes I decided I don't need it anymore.

I run a `kubectl delete` command which blocked in finalizer, and in the operator logs there is a following repeating entry:

```
2021-03-08 00:28:03.131643 E | ceph-object-controller: failed to delete object store. buckets for objectstore "<new objectsore name>" in namespace "rook-ceph" are not cleaned up. remaining buckets: [...]
```

where "remaining buckets" enumerates 89 buckets from all 5 existing `cephobjectstore` in use.

It looks like it happens because selector here https://github.com/rook/rook/blob/2a192300e240911affe12e976428f7d059612291/pkg/operator/ceph/object/controller.go#L470 is too vague

```yaml
  labels:
    bucket-provisioner: rook-ceph.ceph.rook.io-bucket
```
as this label is set to every `OBC`.

It looks like that method needs another loop to filter out `OBC`s by `spec.storageClassName`.

**Expected behavior:**

It should only check for buckets that belong to the `cephobjectstore`

**How to reproduce it (minimal and precise):**

1. Create 2 `cephobjectstore`
2. Create an `OBC` in one of them
3. Try to remove the other `cephobjectstore`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.4.8
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.19.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by zerkms** [comment] 2021-06-06 21:55
Totally not stale

**Comment by travisn** [comment] 2021-06-07 20:47
@BlaineEXE related to proper detection of dependent resources...

**Comment by BlaineEXE** [comment] 2021-06-07 22:57
Yes! I actually moved the priority of this one up and began working on it this morning.

**Comment by BlaineEXE** [comment] 2021-06-07 23:10
Related to #8066

**Comment by fzhan** [comment] 2021-07-06 07:14
Any follow up on this issue?

I actually have a test cluster where the bucket / pool could not be removed. Any instruction to help with bucket deletion?

Thanks in advance,

**Comment by thotz** [comment] 2021-07-06 10:11
IMO this https://github.com/rook/rook/pull/8112 will fix above issue. It is merged in master. And is targetted for rook v1.7

**Comment by travisn** [comment] 2021-07-12 16:48
@BlaineEXE Is there a scoped fix for this issue we could backport to 1.6, or does this need to wait for 1.7?

**Comment by BlaineEXE** [comment] 2021-07-12 17:12
I could look into a scoped fix, but it would have to be a newly-created solution. The solution for 1.7 is based solely on bucket presence and doesn't actually use the k8s API to find OBCs.

Given that the issue is fixed in 1.7, I wonder if a workaround is acceptable for users of 1.6 where they remove the finalizer on the `CephObjectStore` when they want to delete it, and then remove the pools for the store using the toolbox and the `ceph` CLI.

**Comment by zerkms** [comment] 2021-10-15 06:38
Not stale.

**Comment by BlaineEXE** [comment] 2021-10-29 21:55
This was closed by https://github.com/rook/rook/pull/8112 for v1.7. The new approach is to block on presence of user buckets, which may be created by OBCs or by users directly. This ensures that Rook will not delete user data in object stores regardless of the initial source.

For 1.6, users must remove the finalizer on the object store and then remove pools related to that object store if they want to remove the data that exists in Ceph.

**Closed by BlaineEXE** 2021-10-29 21:55 UTC
Labels: bug, ceph, objectstore, object bucket claims (OBC)
