### ISSUE TITLE
[hostNetwork] new mon come up with 127.0.0.1

### ISSUE THREAD

**Issue by bryanlarsen** [rook/rook#1548] opened 2018-03-05 17:50 UTC
Bug Report

What happened:

I rebooted a machine, and it was down long enough to trigger a mon rollover.   The new mon came up on 127.0.0.1 and in a bad state.

What you expected to happen:

a new mon comes up in a good state.

How to reproduce it (minimal and precise):

With a 4 machine kubernetes cluster, shut down one of your machines.

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 16.04
* Kernel (e.g. `uname -a`): 4.13.0-32-generic
* Cloud provider or hardware configuration: ThreadRippper bare metal
* Rook version (use `rook version` inside of a Rook Pod): v0.6.0-204.gc62747d
* Kubernetes version (use `kubectl version`): v1.9.2+coreos.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

rookctl status

```
NAME             ADDRESS                 IN QUORUM   STATUS
rook-ceph-mon3   127.0.0.1:6790/0        true        OK
rook-ceph-mon0   192.168.100.93:6790/0   true        OK
rook-ceph-mon2   192.168.100.95:6790/0   true        OK
```

operator logs

```
E0305 16:46:02.179049       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
E0305 16:46:02.179778       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
E0305 16:46:02.180044       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
E0305 16:46:02.180303       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
E0305 16:46:02.180879       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
E0305 16:46:02.180915       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
E0305 16:46:02.180929       7 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=2495, ErrCode=NO_ERROR, debug=""
2018-03-05 16:46:48.669015 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:46:48.669049 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:47:34.023946 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:47:34.023975 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:48:19.391703 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:48:19.391889 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:49:04.746534 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:49:04.746563 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:49:50.129352 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:49:50.129388 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:50:35.484356 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:50:35.484407 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:51:20.982597 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:51:20.982631 W | op-mon: mon rook-ceph-mon1 NOT found in quorum, STILL in mon out timeout
2018-03-05 16:52:06.345015 W | op-mon: mon rook-ceph-mon1 NOT found in quorum. {Quorum:[0 2] MonMap:{Mons:[{Name:rook-ceph-mon0 Rank:0 Address:192.168.100.93:6790/0} {Name:rook-ceph-mon1 Rank:1 Address:192.168.100.94:6790/0} {Name:rook-ceph-mon2 Rank:2 Address:192.168.100.95:6790/0}]}}
2018-03-05 16:52:06.345048 I | op-mon: Failing over monitor rook-ceph-mon1
2018-03-05 16:52:06.345055 I | op-mon: starting new mon rook-ceph-mon3
2018-03-05 16:52:06.375746 I | op-mon: mon rook-ceph-mon3 running at None:6790
2018-03-05 16:52:06.390855 I | op-mon: Found 1 running nodes without mons
2018-03-05 16:52:06.402100 I | op-mon: mons created: 1
2018-03-05 16:52:06.402132 I | op-mon: waiting for mon quorum
2018-03-05 16:52:06.402325 I | exec: Running command: ceph mon_status --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/632396222
2018-03-05 16:52:06.724099 W | op-mon: failed to find initial monitor rook-ceph-mon3 in mon map
2018-03-05 16:52:11.724510 I | exec: Running command: ceph mon_status --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/354655237
2018-03-05 16:52:20.403025 I | op-mon: Ceph monitors formed quorum
2018-03-05 16:52:20.403069 I | op-mon: ensuring removal of unhealthy monitor rook-ceph-mon1
2018-03-05 16:52:20.420899 I | exec: Running command: ceph mon remove rook-ceph-mon1 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/065905568
2018-03-05 16:52:20.894881 I | exec: removing mon.rook-ceph-mon1 at 192.168.100.94:6790/0, there will be 3 monitors
2018-03-05 16:52:20.895047 I | op-mon: removed monitor rook-ceph-mon1
2018-03-05 16:52:20.899161 I | op-mon: dead mon service rook-ceph-mon1 was already gone
2018-03-05 16:52:20.924123 I | op-mon: saved mon endpoints to config map map[maxMonId:3 mapping:{"node":{"rook-ceph-mon0":{"Name":"serv093","Hostname":"serv093","Address":"192.168.100.93"},"rook-ceph-mon2":{"Name":"serv095","Hostname":"serv095","Address":"192.168.100.95"},"rook-ceph-mon3":{"Name":"serv099","Hostname":"serv099","Address":"192.168.100.99"}},"port":{"serv093":6790,"serv095":6790,"serv099":6790}} data:rook-ceph-mon0=192.168.100.93:6790,rook-ceph-mon2=192.168.100.95:6790]
2018-03-05 16:52:20.924568 I | cephmon: writing config file /var/lib/rook/rook/rook.config
2018-03-05 16:52:20.924680 I | cephmon: generated admin config in /var/lib/rook/rook
2018-03-05 16:52:20.924879 I | cephmon: writing config file /var/lib/rook/rook/rook.config
2018-03-05 16:52:20.924991 I | cephmon: generated admin config in /var/lib/rook/rook
2018-03-05 16:53:06.294937 W | op-mon: mon rook-ceph-mon3 not in source of truth and not in quorum, not enough mons to remove now (wanted: 3, current: 3)
```

last line repeats indefinitely

kubectl -n rook get cluster rook -o yaml:

```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rook.io/v1alpha1","kind":"Cluster","metadata":{"annotations":{},"name":"rook","namespace":"rook"},"spec":{"backend":"ceph","dataDirHostPath":"/var/lib/rook","hostNetwork":true,"monCount":3,"resources":null,"storage":{"deviceFilter":null,"location":null,"metadataDevice":null,"nodes":[{"directories":[{"path":"/mnt/rook-1"},{"path":"/mnt/rook-2"}],"name":"serv093"},{"directories":[{"path":"/mnt/rook-1"},{"path":"/mnt/rook-2"}],"name":"serv094"},{"directories":[{"path":"/mnt/rook-1"},{"path":"/mnt/rook-2"}],"name":"serv095"},{"directories":[{"path":"/mnt/rook-1"},{"path":"/mnt/rook-2"}],"name":"serv099"}],"storeConfig":{"storeType":"bluestore"},"useAllDevices":false,"useAllNodes":false}}}
  clusterName: ""
  creationTimestamp: 2018-03-05T12:51:43Z
  finalizers:
  - cluster.rook.io
  generation: 0
  name: rook
  namespace: rook
  resourceVersion: "3446137"
  selfLink: /apis/rook.io/v1alpha1/namespaces/rook/clusters/rook
  uid: f4840872-2073-11e8-b956-107b4492e419
spec:
  backend: ceph
  dataDirHostPath: /var/lib/rook
  hostNetwork: true
  monCount: 3
  placement:
    all:
      tolerations: null
    api:
      tolerations: null
    mgr:
      tolerations: null
    mon:
      tolerations: null
    osd:
      tolerations: null
  resources:
    api: {}
    mgr: {}
    mon: {}
    osd: {}
  storage:
    nodes:
    - directories:
      - path: /mnt/rook-1
      - path: /mnt/rook-2
      name: serv093
      resources: {}
      storeConfig: {}
    - directories:
      - path: /mnt/rook-1
      - path: /mnt/rook-2
      name: serv094
      resources: {}
      storeConfig: {}
    - directories:
      - path: /mnt/rook-1
      - path: /mnt/rook-2
      name: serv095
      resources: {}
      storeConfig: {}
    - directories:
      - path: /mnt/rook-1
      - path: /mnt/rook-2
      name: serv099
      resources: {}
      storeConfig: {}
    storeConfig:
      storeType: bluestore
    useAllDevices: false
status:
  state: Created
```

**Comment by bryanlarsen** [comment] 2018-03-05 17:54
https://rook-io.slack.com/archives/C46Q5UC05/p1520270168000697

**Comment by jbw976** [comment] 2018-03-07 16:16
do we understand the root cause of this issue yet?  do we have a good workaround that we can document here until a fix can be put in place?

**Comment by galexrt** [comment] 2018-03-07 16:18
@jbw976 I'm currently implementing a fix in the code and writing a documentation to fix the issue until the fix is in the code and released.

**Closed** 2018-03-08 20:15 UTC
Labels: bug, operator
