### ISSUE TITLE
How can I resize pv created by "ceph.rook.io/block"

### ISSUE THREAD

**Issue by ghost** [rook/rook#3133] opened 2019-05-08 04:37 UTC
How can I resize a pv with preserving data. PV is created dynamically through storageclass.
`provisioner: ceph.rook.io/block`

**Comment by RainFlying** [comment] 2019-05-12 06:02
For now I guess you need to create a new PV and migrate the data to the new PV.
Resizing of Ceph PVs provisioned by rook will be available in Rook 1.1, according to this

https://github.com/rook/rook/milestone/12

**Comment by dimm0** [comment] 2019-05-13 18:49
Login to rook toolbox pod, run `rbd resize <pv_id> --size=<size, f.e. 1T>`
Then either go to a node where this PV is mapped to, if it's being used, or `rbd map <pv> && mount /dev/... /mnt` in toolbox pod
Then `xfs_growfs mount_point`
Unmount, unmap if that was in toolbox. For running pods no need to stop pod - can be done on active one

Now sure how to do for ext4, I've done it for XFS only

**Comment by jonashartwig** [comment] 2019-05-29 06:44
Hi, here is a list of commands executed in the toolbox pod:

```bash
rbd resize pvc-0785a7e1-731b-11e9-aa6e-0050568292c7 --size=200G --pool=replicapool
rbd map replicapool/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7
mount /dev/rbd0 /mnt
xfs_growfs /mnt
umount /mnt
rbd unmap replicapool/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7
```

which seem to work (xfs_growfs stated: blocks changed from 2621440 to 52428800). However my pod still thinks it is out of disk. What am I missing?

regards

**Comment by HaveFun83** [comment] 2019-05-29 10:17
> Hi, here is a list of commands executed in the toolbox pod for xfs:
> 
> ```shell
> rbd resize pvc-0785a7e1-731b-11e9-aa6e-0050568292c7 --size=200G --pool=replicapool
> rbd map replicapool/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7
> mount /dev/rbd0 /mnt
> xfs_growfs /mnt
> umount /mnt
> rbd unmap replicapool/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7
> ```
> 
> which seem to work (xfs_growfs stated: blocks changed from 2621440 to 52428800).
> A status gives me this:
> 
> ```shell
> rbd info replicapool/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7
> rbd image 'pvc-0785a7e1-731b-11e9-aa6e-0050568292c7':
> 	size 200 GiB in 51200 objects
> 	order 22 (4 MiB objects)
> 	id: f4116b8b4567
> 	block_name_prefix: rbd_data.f4116b8b4567
> 	format: 2
> 	features: layering
> 	op_features: 
> 	flags: 
> 	create_timestamp: Fri May 10 11:59:14 2019
> 
> rbd du replicapool/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7
> warning: fast-diff map is not enabled for pvc-0785a7e1-731b-11e9-aa6e-0050568292c7. operation may be slow.
> NAME                                     PROVISIONED    USED 
> pvc-0785a7e1-731b-11e9-aa6e-0050568292c7     200 GiB 8.2 GiB 
> ```
> 
> However my pod still thinks it is out of disk. What am I missing?
> 
> EDIT
> I had to go to the node the pod was on. I ran: `bash cat /etc/mtab` and found my volume: `bash /dev/rbd0 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7 xfs rw,seclabel,relatime,attr2,inode64,sunit=8192,swidth=8192,noquota 0 0`.
> 
> I then ran `bash xfs_growfs /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-0785a7e1-731b-11e9-aa6e-0050568292c7`and the pod started again.
> 
> regards

How do you extend the pvc within kubernetes?
I got the following error
```
error: persistentvolumeclaims "wp-pv-claim" could not be patched: persistentvolumeclaims "wp-pv-claim" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
You can run `kubectl replace -f /tmp/kubectl-edit-yrbrz.yaml` to try this update again.
```

**Comment by jonashartwig** [comment] 2019-05-29 11:00
you do not need to. it works fine without.

**Comment by HaveFun83** [comment] 2019-05-29 11:44
> you do not need to. it works fine without.
> 
> EDIT
> Well i am using dynamically provisioned persistent volumes so i can edit that field. I did not need to but i could.

Thanks for the info. can you show me your storageclass object?
I use the storageclass provide by the rook docu https://rook.io/docs/rook/v1.0/ceph-block.html

**Comment by jonashartwig** [comment] 2019-05-29 11:50
Hi, I use the very same. However I do not define any persistent volume. only persistent volume claims. That way they are dynamically provisioned and can be changed.

**Comment by Steuf** [comment] 2019-06-13 12:10
Other simply method (with ext4) :

- On ceph dashboard, edit image and change the size
- Delete the deployment used by volume
- Run this job: https://pastebin.com/viKFsdW5
- Re-deploy your app with the volume

If you add the package "resize2fs" on your app container, you can just run on it "resize2fs /dev/rbd[number]" after resize the image on Ceph admin for avoid service downtime.

**Comment by ceyhunn** [comment] 2019-08-15 08:17
Hi @jonashartwig, I resized the pvc 10GB to 12GB. Pod works fine, but kubectl pvc shows me 10GB. Is it ok?
![Screenshot from 2019-08-15 12-15-19](https://user-images.githubusercontent.com/5506156/63082173-963a3300-bf56-11e9-81cc-942035b8394f.png)

**Comment by dimm0** [comment] 2019-08-15 17:23
Yup, that's fine. It doesn't matter much after it's been allocated.

**Comment by phanhuy1502** [comment] 2019-09-26 08:51
I tried to resize ext4 format. Here the steps that work for me:

1. stop the pods which are currently using the volume 

2. get the rbd image name
```sh
 kubectl describe pv <pv-name> | grep RBDImage
```

3. login to the rook ceph tool container

```sh
# replace "rook-ceph" with the rook namespace 
kubectl -n rook-ceph exec -it $(kubectl -n rook-ceph get pods | grep tool | tr -s ' ' | cut -d ' ' -f 1) bash
```

4. in the ceph tool container 
```sh
# resize the rbd image
DEVICE=$(rbd resize <rbd-image-name> --size=<size, e.g. 1Gi>)

# map the rbd image
rbd map <rbd-image-name>

e2fsck -f $DEVICE

resize2fs $DEVICE

# unmap
rbd unmap <rbd-image-name>
```

5. restart the pod

**Comment by travisn** [comment] 2020-02-06 21:52
Resize is working in both the flex and csi drivers now, so closing this issue.

**Closed by travisn** 2020-02-06 21:52 UTC
Labels: ceph -

**Comment by MatthiasLohr** [comment] 2020-03-26 08:08
Is there any tutorial/documentation how to get this working?

**Comment by mumrau** [comment] 2020-04-06 09:43
@MatthiasLohr https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/
This might help. 
Nonetheless, I would tend to think that a piece of documentation on the `rook` side would be a great benefit. For instance, the first resize I ran failed (probably due to https://superuser.com/questions/1359254/how-to-update-e2fsck-correctly , I had the error when manually doing the steps after my PVC has been expanded on the k8s side). And I, as of today, haven't found any piece of log that could help me debugging or finding the reason it did not work.

**Comment by Martin-Hogge** [comment] 2020-04-09 09:07
I agree that some documentation on the `rook` size would really help.
I tried to resize my volume using @phanhuy1502 method but I'm actually stuck on

```
rbd map  <rbd-image> -p replicapool
rbd: failed to set udev buffer size: (1) Operation not permitted
rbd: sysfs write failed
rbd: error opening pool 'replicapool�': (2) No such file or directory
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (30) Read-only file system
```

Does anyone knows what could be the cause of this issue ? Thanks.

**Comment by jonashartwig** [comment] 2020-04-15 05:22
Hi, I got the same issue just a few days ago. Actually that step can be skipped completely. You just go on and resize the local kubernetes/docker mounts and you should be fine.

**Comment by stemid** [comment] 2022-02-14 09:34
Sorry for adding on to this thread but I found it through google having the same issue as everyone else, I wasn't aware that Rook Ceph CSI driver could not do volume expansion.

The methods listed do not work for me using kubernetes 1.21 and rook ceph release 1.8.

This method is for when you have a running Pod with the PVC mounted, otherwise you could probably use rbd map to mount the PVC inside the rook-ceph-tools container.

First of all the rbd image name is not the same as the PVC name, so first find the rbd image name like this.

```
kubectl get pv -n postgres-operator pvc-0463d6c3-112f-4cba-a84d-b637a244561a --template='{{.spec.csi.volumeAttributes.imageName}}'
csi-vol-b0c046ea-8a89-11ec-9a92-723fa3af7366
```

Now you can follow the rbd instructions above, but you need to prefix the pool name to the image id. It's "replicapool" by default.

```
rbd resize replicapool/csi-vol-b0c046ea-8a89-11ec-9a92-723fa3af7366 --size=100G
Resizing image: 100% complete...done.
```

And now since a Pod is running with this PVC you can just look in your k8s client to see which node the pod is running on, login to that node and find the device.

```
$ mount | grep pvc-0463d6c3-112f-4cba-a84d-b637a244561a
/dev/rbd0 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0463d6c3-112f-4cba-a84d-b637a244561a/globalmount/0001-0009-rook-ceph-0000000000000002-b0c046ea-8a89-11ec-9a92-723fa3af7366 type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered,_netdev)
$ sudo resize2fs /dev/rbd0
resize2fs 1.42.9 (28-Dec-2013)
Filsystem på /dev/rbd0 är monterat på /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0463d6c3-112f-4cba-a84d-b637a244561a/globalmount/0001-0009-rook-ceph-0000000000000002-b0c046ea-8a89-11ec-9a92-723fa3af7366, on-line-storleksändring krävs
old_desc_blocks = 9, new_desc_blocks = 13
Filsystemet på /dev/rbd0 är nu 26214400 block långt.
```

The PVC will still show the old size, not sure how to update that because I've already updated PostgresCluster.spec.instances.dataVolumeClaimSpec.resources.requests.storage as it says in the docs.
