### ISSUE TITLE
OSD: specifying disk by-path fails for some paths

### ISSUE THREAD

**Issue by intlabs** [rook/rook#5535] opened 2020-05-25 04:22 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When specifying devices using `/dev/disk/by-path/...` some paths do not appear to be parsed correctly resulting in errors, and the cluster is not formed.

**Expected behavior:**
To be able to specify block devices by their physical path for production environments.

**How to reproduce it (minimal and precise):**
Create a simple cluster and specify devices by their path, when those paths end in integers.

**File(s) to submit**:
```
ubuntu@harbor-rook:~/rook/cluster/examples/kubernetes/ceph$ kubectl  -n rook-ceph logs rook-ceph-osd-prepare-harbor-rook-2lwz8
failed to parse device list ("/dev/disk/by-path/pci-0000:05:00.0:1:::,/dev/disk/by-path/pci-0000:06:00.0:1:::,/dev/disk/by-path/pci-0000:07:00.0:1:::"): error DatabaseSizeMB ("00.0") to int: strconv.Atoi: parsing "00.0": invalid syntax
ubuntu@harbor-rook:~/rook/cluster/examples/kubernetes/ceph$ cat /tmp/cluster.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    osd_pool_default_size = 1
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: ceph/ceph:v15
    allowUnsupported: true
  mon:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "harbor-rook"
      devices:
      - name: "/dev/disk/by-path/pci-0000:05:00.0"
      - name: "/dev/disk/by-path/pci-0000:06:00.0"
      - name: "/dev/disk/by-path/pci-0000:07:00.0"
ubuntu@harbor-rook:~/rook/cluster/examples/kubernetes/ceph$ ls -lah /dev/disk/by-path/pci-0000:05:00.0
lrwxrwxrwx 1 root root 9 May 25 04:05 /dev/disk/by-path/pci-0000:05:00.0 -> ../../vdb
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Bionic/18.04.4 LTS
* Kernel (e.g. `uname -a`): 4.15.0-101-generic
* Cloud provider or hardware configuration: Libvirt/KVM pc-q35-4.2
* Rook version (use `rook version` inside of a Rook Pod): v1.3.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph/ceph:v15 image
* Kubernetes version (use `kubectl version`): v1.18.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): N/A

**Comment by intlabs** [comment] 2020-05-28 21:29
@leseb not sure if you've seen this before or have any pointers?

**Comment by denisok** [comment] 2020-06-18 18:41
https://github.com/rook/rook/issues/5056 ?

**Comment by BlaineEXE** [comment] 2020-07-14 20:18
I believe this is indeed a duplicate of #5056

**Closed** 2020-07-17 22:38 UTC
Labels: bug, ceph -, ceph-osd, duplicate
