### ISSUE TITLE
rook-ceph: failed to create clone from snapshot

### ISSUE THREAD

**Issue by haslersn** [rook/rook#8883] opened 2021-09-29 21:45 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When creating a PVC with `dataSource` being a (ready) VolumeSnapshot, provisioning fails with the following relevant log:

```
csi-provisioner I0929 21:31:46.758705       1 controller.go:1317] provision "test-namspace/test-pvc-clone" class "ssd-fs": started
csi-provisioner I0929 21:31:46.758921       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test-namspace", Name:"test-pvc-clone", UID:"2471c4f6-242c-49a0-a0e6-8f5dc16b8903", APIVersion:"v1", ResourceVersion:"446481105", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "test-namspace/test-pvc-clone"
csi-provisioner W0929 21:31:46.956630       1 controller.go:943] Retrying syncing claim "2471c4f6-242c-49a0-a0e6-8f5dc16b8903", failure 0
csi-provisioner E0929 21:31:46.956702       1 controller.go:966] error syncing claim "2471c4f6-242c-49a0-a0e6-8f5dc16b8903": failed to provision volume with StorageClass "ssd-fs": rpc error: code = Aborted desc = pending
csi-provisioner I0929 21:31:46.956721       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test-namspace", Name:"test-pvc-clone", UID:"2471c4f6-242c-49a0-a0e6-8f5dc16b8903", APIVersion:"v1", ResourceVersion:"446481105", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ssd-fs": rpc error: code = Aborted desc = pending
csi-cephfsplugin E0929 21:31:46.956102       1 controllerserver.go:69] ID: 122 Req-ID: pvc-2471c4f6-242c-49a0-a0e6-8f5dc16b8903 failed to create clone from snapshot csi-snap-7fee3c7d-2168-11ec-b737-de52ee8d938f: pending
```

The PVC stays in status Pending.

**Expected behavior:**

The PV should be provisioned and the PVC should enter status Bound.

**How to reproduce it (minimal and precise):**

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-pvc-snap
  namespace: test-namespace
spec:
  volumeSnapshotClassName: ssd-fs-snapclass
  source:
    persistentVolumeClaimName: test-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-clone
  namespace: test-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ssd-fs
  resources:
    requests:
      storage: 64Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: test-pvc-snap
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian 10
* Kernel (e.g. `uname -a`): 4.19.0-17-amd64
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): v1.6.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph/ceph:v15.2.13
* Kubernetes version (use `kubectl version`): v1.19.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
  ```
  HEALTH_WARN mons are allowing insecure global_id reclaim; 1 MDSs report oversized cache; 1 clients failing to respond to cache pressure; mons a,f are low on available space
  ```

**Comment by leseb** [comment] 2021-09-30 07:18
@Madhu-1 PTAL. Perhaps it's more appropriate to open this in https://github.com/ceph/ceph-csi for better visibility since it seems ceph-csi related.

**Comment by haslersn** [comment] 2021-09-30 07:48
I tried it again and this time the PVC could be bound after over 8 minutes. Log: https://gist.github.com/haslersn/c9e915985b2fcefbce2583139e5d3002

Is this normal behaviour, or is there something wrong?

Also, I think yesterday it didn't work, even when waiting longer. I'll try to reproduce.

**Comment by haslersn** [comment] 2021-09-30 07:56
On a 2nd attempt to reproduce, the PVC was again bound after around 8:30 minutes.

**Comment by Madhu-1** [comment] 2021-09-30 07:58
@haslersn cephfs clone is a full copy and has some limitation of 4 threads in ceph fs. you can create 4 clone PVC parallelly and the time taken to create clone depends on the size of the PVC and small files inside that ceph fs subvolume

**Comment by Madhu-1** [comment] 2021-09-30 07:59
@haslersn if you are planning to try/reproduce it please set CSI_LOG_LEVEL to 5 https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L42 before creating clones.

**Comment by haslersn** [comment] 2021-10-01 21:09
Seems to be working as intended. But the UX could be better: I don't expect errors in the log for something that works as intended.

**Comment by Madhu-1** [comment] 2021-11-30 10:34
>error syncing claim "bfdb3f9b-de34-4bf3-a8ac-36b334ca7994": failed to provision volume with StorageClass "rook-cephfs": rpc error: code = Aborted desc = pending

@gmartynov pending is a normal error message as the clone is in progress. the cephfs clone creation depends on the subvolume's size and also the number of small files in the PVC. you can check the clone status in `ceph fs clone status <clone name>` in the ceph cluster.

**Comment by gmartynov** [comment] 2021-11-30 12:13
if i run ceph fs commands from my rook-ceph-tools pod i don't see any clones or snapshots, because it asks me for a subvolume name, which I don't have:

```
ceph> fs volume ls
[
{
"name": "myfs"
}
]
ceph> fs subvolume ls myfs
[]
ceph> fs subvolume snapshot ls myfs
Invalid command: missing required parameter sub_name(<string>)
fs subvolume snapshot ls <vol_name> <sub_name> [<group_name>] : List subvolume snapshots
```

**Comment by Madhu-1** [comment] 2021-11-30 12:14
@gmartynov you need to pass `--group_name=csi` when running subvolume commands

**Comment by gmartynov** [comment] 2021-11-30 13:20
thanks! now i found a subvolume and can see long list of snapshots, as for mine it says:

```
sh-4.4# ceph fs subvolume snapshot info myfs --group_name=csi csi-vol-c380d3c4-e63e-11eb-867f-e6679e3815ec csi-snap-7bd32159-51b1-11ec-8941-5a1cee888301
{
    "created_at": "2021-11-30 07:45:27.031174",
    "data_pool": "myfs-data0",
    "has_pending_clones": "yes",
    "size": 165345590880
}
```

if we check ceph docs:
has_pending_clones: “yes” if snapshot clone is in progress otherwise “no”

i didn't really launched any clone operations of this snapshot, i've just created a snapshot from k8s manifest as I wrote above, but anyway - if i try to get clone status 

```
sh-4.4# ceph fs clone status myfs csi-vol-c380d3c4-e63e-11eb-867f-e6679e3815ec --group_name=csi
Error ENOTSUP: operation 'clone-status' is not allowed on subvolume 'csi-vol-c380d3c4-e63e-11eb-867f-e6679e3815ec' of type subvolume
```

don't know maybe i use wrong clone name, but there's no clone listing command... :(

**Comment by Madhu-1** [comment] 2021-11-30 13:22
The clone name is just a ceph fs subvolume name. check `pv -oyaml output` for the cephfs subvolume name`

**Comment by mihele95** [comment] 2021-11-30 18:47
according to @gmartynov  question
what if we haven't PV for cloned pvc?

```
$ k get pvc -n default
NAME         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
restored     Pending                                                                        rook-cephfs    22h
test         Bound     pvc-1bef27c2-b554-4772-a64f-76d0cbd55664   5Gi        RWX            rook-cephfs    23h
```


```
$ k get pv | grep default
pvc-1bef27c2-b554-4772-a64f-76d0cbd55664   5Gi        RWX            Delete           Bound    default/test
  rook-cephfs                        23h
```
```
$ k get pvc restored -oyaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"restored","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"dataSource":{"apiGroup":"snapshot.storage.k8s.io","kind":"VolumeSnapshot","name":"snapshot-2021-11-29-23-03"},"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"rook-cephfs"}}
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2021-11-29T20:04:01Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: restored
  namespace: default
  resourceVersion: "51065654"
  uid: 82ccae85-aad5-423d-a42c-bdd656dca48d
spec:
  accessModes:
  - ReadWriteMany
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: snapshot-2021-11-29-23-03
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
status:
  phase: Pending
```

**Comment by Madhu-1** [comment] 2021-12-01 08:27
@gmartynov is this working fine or do still you have an issue? @haslersn if you are not facing the issue can we close this one?

**Closed** 2021-12-01 21:05 UTC
Labels: bug, csi

**Comment by gmartynov** [comment] 2022-02-03 07:18
@Madhu-1 hello, no it's not, i found clone name in .meta file /cephfs/volumes/csi/<vol-name>
[clone snaps]
07aa8314-683e-4035-8dae-788a58cbaebe = csi-snap-5874942e-7b8f-11ec-882f-e6dab1b9e9d3

but command still not working, i cant see stats of clone, cant cancel it and snapshot seems is stuck in cephfs forever:
ceph fs clone status --group_name=csi myfs csi-vol-ad90f921-049e-11ec-a8dd-8e3cfc20cbd4 07aa8314-683e-4035-8dae-788a58cbaebe
Error ENOENT: subvolume group '07aa8314-683e-4035-8dae-788a58cbaebe' does not exist

this CLI is really weird

**Comment by Madhu-1** [comment] 2022-02-03 07:22
@kotreshhr any idea about the above error message?

**Comment by kotreshhr** [comment] 2022-02-03 10:37
> @Madhu-1 hello, no it's not, i found clone name in .meta file /cephfs/volumes/csi/
> [clone snaps] 
> 07aa8314-683e-4035-8dae-788a58cbaebe = csi-snap-5874942e-7b8f-11ec-882f-e6dab1b9e9d3
> 

The metadata file stores
```
[clone snaps] 
<uuid> = <snap-name>
This is for internal clone tracking. The <uuid> is not the clone name.
```


The user would generally know the clone name. If not, you could list all the subvolumes using below command and
find out the clone name. Please make sure to provide the correct group name where the clone is created.
```
ceph fs subvolume ls <volname> --group-name=<group_name>
```

> but command still not working, i cant see stats of clone, cant cancel it and snapshot seems is stuck in cephfs forever: ceph fs clone status --group_name=csi myfs csi-vol-ad90f921-049e-11ec-a8dd-8e3cfc20cbd4 07aa8314-683e-4035-8dae-788a58cbaebe Error ENOENT: subvolume group '07aa8314-683e-4035-8dae-788a58cbaebe' does not exist
> 
> this CLI is really weird
