### ISSUE TITLE
Dynamic provisioning for CephFS storage

### ISSUE THREAD

**Issue by caisan** [rook/rook#3263] opened 2019-06-05 10:26 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently, the ceph filesystem supports in Rook requires the user to create a external storage cephfs provisioner to provision cephfs volume that will be consumed by a pod. The user has to look up the IP address of the Mon IP address, run a external storagre provisioner pod , etc., which is a cumbersome experience. This could be improved by intergrating a dynamic provisioner in rook operator that would automiatically do those actions for the user and generate a PV without user intervention. All the user who wants to request a PVC needs to do is deploying ceph filesystem firstly and declare a PVC with a storageclass.

**Comment by galexrt** [comment] 2019-09-06 15:42
Closing as duplicate of #1125.

**Closed by galexrt** 2019-09-06 15:42 UTC
Labels: ceph -, feature
