### ISSUE TITLE
Bucket quotas are ignored when a bucket is created in a non-primary zone with object multisite

### ISSUE THREAD

**Issue by lgyurci** [rook/rook#14816] opened 2024-10-08 07:59 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Bucket quotas are ignored when a bucket is created in a non-primary zone with object multisite
**Expected behavior:**
Bucket quotas should not be ignored when a bucket is created in a non-primary zone with object multisite
**How to reproduce it (minimal and precise):**
1. Connect two clusters with object multisite, as described in the docs
2. Create an ObjectbucketClaim CRD in one of the clusters acting as a non-primary zone, with some kind of quota enabled (in our testing, we used max_size)
3. Get the owner of the created bucket: `radosgw-admin bucket stats --bucket=<created-bucket-name> --rgw-realm=multisite-realm`
4. Get the user info for the bucket owner: `radosgw-admin user info --uid=<uid-of-owner> --rgw-realm=multisite-realm`
5. Observe, that the user has no quotas enabled. You can do the same procedure, creating the OBC in the primary zone, and you can see, that the quota is applied to the rgw user normally, and the quota is synced across the zones.

**Environment**:
* OS: Rocky Linux 9.4
* Kernel: Linux 5.14.0-427.24.1.el9_4.x86_64
* Cloud provider or hardware configuration: "Bare-metal" machines, issue is not dependent on hardware
* Rook version: v1.15.0
* Storage backend version: 18.2.2
* Kubernetes version: v1.28.13+rke2r1
* Kubernetes cluster type: RKE2
* Storage backend status: HEALTH_WARN 3 OSD(s) have spurious read errors

**Comment by BlaineEXE** [comment] 2024-10-08 15:01
I'm not sure if RGW mirrors quotas between multiple sites. @cbodley, is this normal RGW mirroring behavior?

**Comment by cbodley** [comment] 2024-10-08 15:16
> 2\. Create an ObjectbucketClaim CRD in one of the clusters acting as a non-primary zone, with some kind of quota enabled (in our testing, we used max_size)

i don't know how object bucket claim works here. but in general, bucket quota is stored in the bucket metadata, and metadata changes on the _primary_ zone get replicated to other zones

**Comment by BlaineEXE** [comment] 2024-10-08 15:21
As I was writing up a reply to Casey, I remembered that I think OBCs use the admin ops API to apply quotas to users currently. This is probably the mismatch in expectations. I have wondered why OBCs were designed to use user quotas instead of bucket quotas (or both).

@lgyurci do you feel comfortable using radosgw-admin applying bucket size quotas?

I have some concerns that if Rook changes the implementation for OBCs, there could be some unintended side effects. At any rate, before we change it, we will have to do some research.

**Comment by BlaineEXE** [comment] 2024-10-08 15:53
Thanks for the clarification. It sounds like I didn't read carefully enough at first. 

My understanding after clarification and deeper reading is that when an S3 user is created in a non-primary zone, quotas aren't registered in the user metadata. @cbodley is this expected behavior?

**Comment by BlaineEXE** [comment] 2024-10-10 17:28
@lgyurci Ceph's issue tracker info is here: https://docs.ceph.com/en/reef/dev/developer_guide/issue-tracker/

It sounds like this would be best opened there. I don't think there's anything Rook can do, but this issue report will hopefully help any users experiencing the same symptoms. If that sounds right, I can close this with won't fix, and we can reopen if needed.

**Closed** 2024-12-17 20:02 UTC
Labels: bug, wontfix
