### ISSUE TITLE
ci: intermittent failure on webhook cert

### ISSUE THREAD

**Issue by leseb** [rook/rook#7955] opened 2021-05-20 08:11 UTC
See:

```
2021-05-20 07:56:14.714780 D | exec: mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
2021-05-20 07:56:14.788262 D | exec: validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
2021-05-20 07:56:15.010505 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:16.459057 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:17.715942 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:18.949203 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:20.127921 D | exec: No resources found in cert-manager namespace.
2021-05-20 07:56:27.556431 D | exec: Deploying webhook config
2021-05-20 07:56:28.271270 D | exec: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
2021-05-20 07:56:28.271304 D | exec: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
2021-05-20 07:56:28.531375 D | exec: warning: deleting cluster-scoped resources, not scoped to the provided namespace
2021-05-20 07:56:28.541436 D | exec: Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "rook-ceph-webhook" not found
2021-05-20 07:56:29.072739 D | exec: Error from server (NotFound): certificates.cert-manager.io "rook-admission-controller-cert" not found
```

Seen in https://github.com/rook/rook/pull/7953/checks?check_run_id=2627814259

**Comment by subhamkrai** [comment] 2021-05-20 08:17
@leseb duplicate of #7876?
and to update I was talking with @vbnrh about this ...we'll try to repo and update.

**Comment by leseb** [comment] 2021-05-20 08:19
> @leseb duplicate of #7876?
> and to update I was talking with @vbnrh about this ...we'll try to repo and update.

The error looks different.

**Comment by subhamkrai** [comment] 2021-05-20 08:24
> > @leseb duplicate of #7876?
> > and to update I was talking with @vbnrh about this ...we'll try to repo and update.
> 
> The error looks different.

right...I'll look into both issues.

**Closed** 2021-06-02 05:23 UTC
Labels: bug
