### ISSUE TITLE
Ceph mgr test intermittently fails with no nodes or devices available

### ISSUE THREAD

**Issue by travisn** [rook/rook#5877] opened 2020-07-22 16:36 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CephMgrSuite intermittently fails with errors such as the following:
```
--- FAIL: TestCephMgrSuite (238.55s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (0.85s)
        ceph_mgr_test.go:195: 
            	Error Trace:	ceph_mgr_test.go:195
            	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc00074d060), Stderr:[]uint8{0x45, 0x72, 0x72, 0x6f, 0x72, 0x20, 0x45, 0x4e, 0x4f, 0x45, 0x4e, 0x54, 0x3a, 0x20, 0x4e, 0x6f, 0x20, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x20, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x20, 0x28, 0x74, 0x72, 0x79, 0x20, 0x60, 0x63, 0x65, 0x70, 0x68, 0x20, 0x6f, 0x72, 0x63, 0x68, 0x20, 0x73, 0x65, 0x74, 0x20, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x60, 0x29, 0xa, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x20, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x65, 0x78, 0x69, 0x74, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x32, 0xa}}
            	Test:       	TestCephMgrSuite/TestCreateOSD
        ceph_mgr_test.go:201: 
            	Error Trace:	ceph_mgr_test.go:201
            	Error:      	Expected nil, but got: &json.SyntaxError{msg:"invalid character '.' looking for beginning of value", Offset:1}
            	Test:       	TestCephMgrSuite/TestCreateOSD
        ceph_mgr_test.go:217: 
            	Error Trace:	ceph_mgr_test.go:217
            	Error:      	Should not be: ""
            	Test:       	TestCephMgrSuite/TestCreateOSD
            	Messages:   	No devices available to create test OSD
        ceph_mgr_test.go:218: 
            	Error Trace:	ceph_mgr_test.go:218
            	Error:      	Should not be: ""
            	Test:       	TestCephMgrSuite/TestCreateOSD
            	Messages:   	No nodes available to create test OSD
```

See the example failure [here](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5837/runs/12/nodes/57/steps/124/log/?start=0).

**Expected behavior:**
Integration tests should pass consistently.

**Comment by travisn** [comment] 2020-07-22 16:47
The [operator log](https://jenkins.rook.io/job/rook/job/rook/job/PR-5837/12/artifact/_output/tests/CephMgrSuite_TestStatus_aws_1.15.x_mgr-ns-system_rook-ceph-operator-5b8bc47b94-9dw8q_1595434622.log) shows that the rook module failed to be enabled:
```
2020-07-22 16:15:36.584845 E | op-config: failed to update cluster condition to {Type:Ready Status:True Reason:ClusterCreated Message:Cluster created successfully LastHeartbeatTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:0001-01-01 00:00:00 +0000 UTC}. Operation cannot be fulfilled on cephclusters.ceph.rook.io "mgr-ns": the object has been modified; please apply your changes to the latest version and try again
2020-07-22 16:15:37.638652 E | op-mgr: failed modules: "balancer". failed to configure module "balancer": failed to set balancer module mode to "upmap": failed to set mgr module mode "upmap" even after 5 retries: failed to set balancer mode "upmap": exit status 22
2020-07-22 16:15:37.764997 E | op-mgr: failed modules: "mgr module(s) from the spec". failed to enable mgr module "rook": failed to enable mgr module "rook" even after 5 retries: failed to enable mgr module "rook": exit status 2
```

**Comment by satoru-takeuchi** [comment] 2020-09-08 16:06
I reproduced this problem in my local environment many times and found that it happened even when rook module seemed to be loaded properly. I'll investigate whether #5884 is the proper fix of this problem.

**Comment by varshar16** [comment] 2020-09-18 10:36
#5884 doesn't fix the issue. Even if `rook` is enabled it fails to create osd. As `ceph orch device ls --format json` doesn't work. https://tracker.ceph.com/issues/47495
```
=== RUN   TestCephMgrSuite/TestCreateOSD
2020-09-18 15:39:59.957556 I | integrationTest: Testing .... <ceph orch create OSD>
2020-09-18 15:39:59.958442 D | exec: Running command: kubectl exec -i rook-ceph-tools -n mgr-ns -- ceph orch device ls --format json --connect-timeout=15
2020-09-18 15:40:00.623395 I | integrationTest: output = [{"addr": "minikube", "devices": [], "labels": [], "name": "minikube"}]
    ceph_mgr_test.go:262: 
        	Error Trace:	ceph_mgr_test.go:262
        	Error:      	Should not be: ""
        	Test:       	TestCephMgrSuite/TestCreateOSD
        	Messages:   	No devices available to create test OSD
    ceph_mgr_test.go:263: 
        	Error Trace:	ceph_mgr_test.go:263
        	Error:      	Should not be: ""
        	Test:       	TestCephMgrSuite/TestCreateOSD
        	Messages:   	No nodes available to create test OSD
```

**Comment by satoru-takeuchi** [comment] 2020-09-18 10:45
@varshar16 I'm trying to fix this problem. Please wait for a while. Probably I'll send a PR next week.

**Comment by varshar16** [comment] 2020-10-01 11:09
@satoru-takeuchi Any updates?

**Comment by satoru-takeuchi** [comment] 2020-10-01 21:25
@varshar16 Still investigating, Sorry it's taking so long. I guess this problem may come from Ceph'S mgr module or rook module. However, I've not found what is the root cause yet.

@travisn I found read following mail in the ceph-devel.

https://marc.info/?l=ceph-devel&m=160140792722813
```
Some questions have come up recently about issues in the Rook
orchestrator module and its state of disrepair.
...
The fundamental question then is, **what scenarios require the Rook
orchestrator mgr module**? The module is not enabled by default in
Rook clusters and I am not aware of upstream users consuming it.
...
```

I guess we can leave this issue as is until the end of the aforementioned discussion. Any idea?

**Comment by travisn** [comment] 2020-10-02 16:48
@satoru-takeuchi I did clarify with the ceph dashboard team that there is still a scenario for starting rook clusters based on the ceph mgr so these tests are still valuable to get going again, thanks!

What errors are you hitting now when running the mgr test?

**Comment by satoru-takeuchi** [comment] 2020-10-07 10:58
> What errors are you hitting now when running the mgr test?

Same as the following message when I tried about one weeks ago.

https://github.com/rook/rook/issues/5877#issuecomment-694792928

I'll re-enable mgr test of master branch and will run this test tomorrow.

**Comment by varshar16** [comment] 2020-10-21 14:58
@satoru-takeuchi It is not an issue with ceph mgr rook module.
It just calls up ceph rook client to get list of devices based on configmap.
https://github.com/ceph/ceph/blob/656386e9c0dd1d212221ac030b0060dac6b2bf10/src/pybind/mgr/rook/rook_cluster.py#L193-L195
https://github.com/ceph/ceph/blob/656386e9c0dd1d212221ac030b0060dac6b2bf10/src/pybind/mgr/rook/rook_cluster.py#L235-L253
```
dict_values([{'api_version': None,
 'binary_data': None,
 'data': {'devices': '[]'},
 'kind': None,
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2020, 10, 21, 13, 33, 36, tzinfo=tzlocal()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'initializers': None,
              'labels': {'app': 'rook-discover', 'rook.io/node': 'minikube'},
              'managed_fields': [{'api_version': 'v1',
                                  'fields': None,
                                  'manager': 'rook',
                                  'operation': 'Update',
                                  'time': datetime.datetime(2020, 10, 21, 13, 33, 36, tzinfo=tzlocal())}],
              'name': 'local-device-minikube',
              'namespace': 'rook-ceph',
              'owner_references': [{'api_version': 'apps/v1',
                                    'block_owner_deletion': None,
                                    'controller': None,
                                    'kind': 'DaemonSet',
                                    'name': 'rook-discover',
                                    'uid': '606ed8b3-8521-4094-b70c-679dd8530e34'}],
              'resource_version': '605',    
              'self_link': '/api/v1/namespaces/rook-ceph/configmaps/local-device-minikube',
              'uid': '9b298514-5936-4eee-8501-5e94cf9ee479'}}])
```
rook-discover logs
Here also no devices are listed
```
varsha@varsha-Standard-PC-Q35-ICH9-2009:~$ kubectl logs -n rook-ceph rook-discover-8sbcf
2020-10-21 13:33:33.180901 I | rookcmd: starting Rook v1.4.0-alpha.0.499.g40068a95-dirty with arguments '/usr/local/bin/rook discover --discover-interval 60m --use-ceph-volume'
2020-10-21 13:33:33.180981 I | rookcmd: flag values: --discover-interval=1h0m0s, --help=false, --log-flush-frequency=5s, --log-level=INFO, --operator-image=, --service-account=, --use-ceph-volume=true
2020-10-21 13:33:33.182406 I | rook-discover: updating device configmap
2020-10-21 13:33:33.188951 W | inventory: skipping device "loop0". diskType is empty
2020-10-21 13:33:33.192001 W | inventory: skipping device "loop1". diskType is empty
2020-10-21 13:33:33.193974 W | inventory: skipping device "loop2". diskType is empty
2020-10-21 13:33:33.196205 W | inventory: skipping device "loop3". diskType is empty
2020-10-21 13:33:33.198749 W | inventory: skipping device "loop4". diskType is empty
2020-10-21 13:33:33.200914 W | inventory: skipping device "loop5". diskType is empty
2020-10-21 13:33:33.203055 W | inventory: skipping device "loop6". diskType is empty
2020-10-21 13:33:33.205065 W | inventory: skipping device "loop7". diskType is empty
2020-10-21 13:33:33.207365 W | inventory: skipping device "sr0". unsupported diskType rom
2020-10-21 13:33:33.227131 I | inventory: skipping device "vda" because it has child, considering the child instead.
2020-10-21 13:33:33.290321 I | rook-discover: localdevices: "vda1, vda2, vda3, vda5, vda6"
2020-10-21 13:33:33.290414 I | rook-discover: Getting ceph-volume inventory information
2020-10-21 13:33:36.647852 I | rook-discover: available devices: []
2020-10-21 13:33:36.669445 I | rook-discover: using the regular expressions ["(?i)dm-[0-9]+" "(?i)rbd[0-9]+" "(?i)nbd[0-9]+"]
```
Though osd was successfully deployed
```
$ kubectl get pods -n rook-ceph
NAME                                            READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-provisioner-859c666579-xv7nn   6/6     Running     0          56m
csi-cephfsplugin-xnkbg                          3/3     Running     0          56m
csi-rbdplugin-provisioner-7c6d5c76cd-92drx      6/6     Running     0          56m
csi-rbdplugin-vgsfk                             3/3     Running     0          56m
rook-ceph-mgr-a-7d75758b48-gz85v                1/1     Running     0          55m
rook-ceph-mon-a-86f785b85f-wvfvx                1/1     Running     0          55m
rook-ceph-operator-86756d44-7lxj8               1/1     Running     0          58m
rook-ceph-osd-0-86b68d6668-9t92q                1/1     Running     0          54m
rook-ceph-osd-prepare-minikube-mp2m6            0/1     Completed   0          55m
rook-ceph-tools-78cdfd976c-dkqw7                1/1     Running     0          55m
rook-discover-8sbcf                             1/1     Running     0          57m
```
From osd prepare pod

```
2020-10-21 13:37:10.355540 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2020-10-21 13:37:10.811509 D | cephosd: {
    "0": [
        {
            "devices": [
                "/dev/vda3"
            ],
            "lv_name": "osd-data-f7be49c2-01fb-4674-a960-caa9021cab23",
            "lv_path": "/dev/ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2/osd-data-f7be49c2-01fb-4674-a960-caa9021cab23",
            "lv_size": "25.14g",
            "lv_tags": "ceph.block_device=/dev/ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2/osd-data-f7be49c2-01fb-4674-a960-caa9021cab23,ceph.block_uuid=HwaV3X-Xgab-jk1f-h2bi-mmaV-NQWB-IkZvxD,ceph.cephx_lockbox_secret=,ceph.cluster_fsid=890b08dc-202a-4c0c-b729-7417b8beaeb8,ceph.cluster_name=ceph,ceph.crush_device_class=None,ceph.encrypted=0,ceph.osd_fsid=4f17daa4-e058-4577-b727-1c99f0633f85,ceph.osd_id=0,ceph.osdspec_affinity=,ceph.type=block,ceph.vdo=0",
            "lv_uuid": "HwaV3X-Xgab-jk1f-h2bi-mmaV-NQWB-IkZvxD",
            "name": "osd-data-f7be49c2-01fb-4674-a960-caa9021cab23",
            "path": "/dev/ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2/osd-data-f7be49c2-01fb-4674-a960-caa9021cab23",
            "tags": {
                "ceph.block_device": "/dev/ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2/osd-data-f7be49c2-01fb-4674-a960-caa9021cab23",
                "ceph.block_uuid": "HwaV3X-Xgab-jk1f-h2bi-mmaV-NQWB-IkZvxD",
                "ceph.cephx_lockbox_secret": "",
                "ceph.cluster_fsid": "890b08dc-202a-4c0c-b729-7417b8beaeb8",
                "ceph.cluster_name": "ceph",
                "ceph.crush_device_class": "None",
                "ceph.encrypted": "0",
                "ceph.osd_fsid": "4f17daa4-e058-4577-b727-1c99f0633f85",
                "ceph.osd_id": "0",
                "ceph.osdspec_affinity": "",
                "ceph.type": "block",
                "ceph.vdo": "0"
            },
            "type": "block",
            "vg_name": "ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2"
        }
    ]
}
2020-10-21 13:37:10.811648 I | cephosd: osdInfo has 1 elements. [{Name:osd-data-f7be49c2-01fb-4674-a960-caa9021cab23 Path:/dev/ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2/osd-data-f7be49c2-01fb-4674-a960-caa9021cab23 Tags:{OSDFSID:4f17daa4-e058-4577-b727-1c99f0633f85 Encrypted:0 ClusterFSID:890b08dc-202a-4c0c-b729-7417b8beaeb8} Type:block}]
2020-10-21 13:37:10.811663 I | cephosd: 1 ceph-volume lvm osd devices configured on this node
2020-10-21 13:37:10.811682 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list /mnt/minikube --format json
2020-10-21 13:37:11.561138 D | cephosd: {}
2020-10-21 13:37:11.561177 I | cephosd: 0 ceph-volume raw osd devices configured on this node
2020-10-21 13:37:11.561244 I | cephosd: devices = [{ID:0 Cluster:ceph UUID:4f17daa4-e058-4577-b727-1c99f0633f85 DevicePartUUID: BlockPath:/dev/ceph-f0e4c14b-c021-473c-8f07-5280116aa1d2/osd-data-f7be49c2-01fb-4674-a960-caa9021cab23 MetadataPath: WalPath: SkipLVRelease:false Location: LVBackedPV:false CVMode:lvm Store:bluestore}]
```
This is an issue either with listing of devices by rook or ceph-volume. As no devices are listed in configmap.
```
varsha@varsha-Standard-PC-Q35-ICH9-2009:~/go/src/github.com/rook/rook$ kubectl -n rook-ceph describe configmap -l app=rook-discover
Name:         local-device-minikube
Namespace:    rook-ceph
Labels:       app=rook-discover
              rook.io/node=minikube
Annotations:  <none>

Data
====
devices:
----
[]
Events:  <none>
```

**Comment by satoru-takeuchi** [comment] 2020-10-21 21:13
@varshar16 Thank you for your help! And sorry for taking long time to fix this issue. Recentlu I've tuckiling on fixing other critical CI failures. I'll restart to handle this issue next week.

**Comment by satoru-takeuchi** [comment] 2020-10-27 05:54
Surprisingly, this problem disappeared in my local environment. I'll try to reproduce this problem in CI environment (#6496)

**Comment by satoru-takeuchi** [comment] 2020-10-28 05:48
In CI environment, mgr suite failed in all k8s versions.

https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6496/1/pipeline

Here are the backtraces in failure..

v1.15:
```
--- FAIL: TestCephMgrSuite (375.57s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (153.36s)
        ceph_mgr_test.go:229: 
            	Error Trace:	ceph_mgr_test.go:229
            	Error:      	Expected nil, but got: &errors.errorString{s:"Giving up waiting for pods with label app=rook-ceph-osd in namespace mgr-ns"}
            	Test:       	TestCephMgrSuite/TestCreateOSD
    --- PASS: TestCephMgrSuite/TestDeviceLs (0.60s)
    --- PASS: TestCephMgrSuite/TestHostLs (0.61s)
    --- PASS: TestCephMgrSuite/TestServiceLs (0.68s)
    --- PASS: TestCephMgrSuite/TestStatus (1.08s)
```

v1.16:
```
--- FAIL: TestCephMgrSuite (317.64s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (151.84s)
        ceph_mgr_test.go:229: 
            	Error Trace:	ceph_mgr_test.go:229
            	Error:      	Expected nil, but got: &errors.errorString{s:"Giving up waiting for pods with label app=rook-ceph-osd in namespace mgr-ns"}
            	Test:       	TestCephMgrSuite/TestCreateOSD
    --- PASS: TestCephMgrSuite/TestDeviceLs (0.79s)
    --- PASS: TestCephMgrSuite/TestHostLs (1.27s)
    --- PASS: TestCephMgrSuite/TestServiceLs (1.28s)
    --- PASS: TestCephMgrSuite/TestStatus (0.63s)
```

v1.17:
```
--- FAIL: TestCephMgrSuite (324.56s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (167.25s)
        ceph_mgr_test.go:229: 
            	Error Trace:	ceph_mgr_test.go:229
            	Error:      	Expected nil, but got: &errors.errorString{s:"Giving up waiting for pods with label app=rook-ceph-osd in namespace mgr-ns"}
            	Test:       	TestCephMgrSuite/TestCreateOSD
    --- PASS: TestCephMgrSuite/TestDeviceLs (0.61s)
    --- PASS: TestCephMgrSuite/TestHostLs (0.63s)
    --- PASS: TestCephMgrSuite/TestServiceLs (0.66s)
    --- PASS: TestCephMgrSuite/TestStatus (0.67s)
```

v1.18:
```
--- FAIL: TestCephFlexSuite (586.55s)
    --- PASS: TestCephFlexSuite/TestBlockStorageMountUnMountForDifferentAccessModes (147.76s)
    --- PASS: TestCephFlexSuite/TestBlockStorageMountUnMountForStatefulSets (75.72s)
    --- FAIL: TestCephFlexSuite/TestFileSystem (166.39s)
        ceph_base_file_test.go:491: 
            	Error Trace:	ceph_base_file_test.go:491
            	            				ceph_base_file_test.go:265
            	            				ceph_flex_test.go:113
            	Error:      	Expected nil, but got: &errors.errorString{s:"kubectl exec command bash failed on pod rook-ceph-tools in namespace flex-ns. Failed to run: kubectl [exec -n flex-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') $(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}'):/ /tmp/testrook] : exit status 32"}
            	Test:       	TestCephFlexSuite/TestFileSystem
...
--- FAIL: TestCephHelmSuite (868.90s)
    --- PASS: TestCephHelmSuite/TestARookInstallViaHelm (0.04s)
    --- PASS: TestCephHelmSuite/TestBlockStoreOnRookInstalledViaHelm (225.41s)
    --- FAIL: TestCephHelmSuite/TestFileStoreOnRookInstalledViaHelm (223.08s)
        ceph_base_file_test.go:353: 
            	Error Trace:	ceph_base_file_test.go:353
            	            				ceph_helm_test.go:104
            	Error:      	Received unexpected error:
            	            	Could Not create resource in args : [apply -f -] -- Failed to run stdin: kubectl [apply -f -] : The StorageClass "cephfs-storageclass" is invalid: * parameters: Forbidden: updates to parameters are forbidden.* provisioner: Forbidden: updates to provisioner are forbidden.
            	Test:       	TestCephHelmSuite/TestFileStoreOnRookInstalledViaHelm
        ceph_base_file_test.go:354: 
            	Error Trace:	ceph_base_file_test.go:354
            	            				ceph_helm_test.go:104
            	Error:      	Received unexpected error:
            	            	Could Not create resource in args : [apply -f -] -- Failed to run stdin: kubectl [apply -f -] : The StorageClass "cephfs-storageclass" is invalid: * parameters: Forbidden: updates to parameters are forbidden.* provisioner: Forbidden: updates to provisioner are forbidden.
            	Test:       	TestCephHelmSuite/TestFileStoreOnRookInstalledViaHelm
        ceph_base_file_test.go:145: 
            	Error Trace:	ceph_base_file_test.go:145
            	            				ceph_base_file_test.go:356
            	            				ceph_helm_test.go:104
            	Error:      	Should be true
            	Test:       	TestCephHelmSuite/TestFileStoreOnRookInstalledViaHelm
            	Messages:   	Make sure PVC is Bound
    --- PASS: TestCephHelmSuite/TestObjectStoreOnRookInstalledViaHelm (170.76s)
    ceph_installer.go:570: 
        	Error Trace:	ceph_installer.go:570
        	            				ceph_installer.go:524
        	            				ceph_base_deploy_test.go:188
        	            				ceph_helm_test.go:85
        	            				suite.go:106
        	            				suite.go:139
        	            				ceph_helm_test.go:52
        	Error:      	Received unexpected error:
        	            	failed to wait for clean up jobs to complete. timed out waiting for the condition
        	Test:       	TestCephHelmSuite
...
--- FAIL: TestCephMgrSuite (174.41s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (2.37s)
        ceph_mgr_test.go:216: 
            	Error Trace:	ceph_mgr_test.go:216
            	Error:      	Should not be: ""
            	Test:       	TestCephMgrSuite/TestCreateOSD
            	Messages:   	No devices available to create test OSD
        ceph_mgr_test.go:217: 
            	Error Trace:	ceph_mgr_test.go:217
            	Error:      	Should not be: ""
            	Test:       	TestCephMgrSuite/TestCreateOSD
            	Messages:   	No nodes available to create test OSD
    --- PASS: TestCephMgrSuite/TestDeviceLs (1.30s)
    --- PASS: TestCephMgrSuite/TestHostLs (15.32s)
    --- PASS: TestCephMgrSuite/TestServiceLs (0.65s)
    --- PASS: TestCephMgrSuite/TestStatus (0.98s)
```

v1.19:
```
--- FAIL: TestCephMgrSuite (301.89s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (152.92s)
        ceph_mgr_test.go:229: 
            	Error Trace:	ceph_mgr_test.go:229
            	Error:      	Expected nil, but got: &errors.errorString{s:"Giving up waiting for pods with label app=rook-ceph-osd in namespace mgr-ns"}
            	Test:       	TestCephMgrSuite/TestCreateOSD
    --- PASS: TestCephMgrSuite/TestDeviceLs (1.53s)
    --- PASS: TestCephMgrSuite/TestHostLs (0.63s)
    --- PASS: TestCephMgrSuite/TestServiceLs (0.67s)
    --- PASS: TestCephMgrSuite/TestStatus (0.66s)
```

**Comment by varshar16** [comment] 2020-11-02 07:05
@satoru-takeuchi Hi, are you working on fixing these failures ?

**Comment by satoru-takeuchi** [comment] 2020-11-02 10:23
@varshar16 Yes, any hints are welcome.

**Comment by satoru-takeuchi** [comment] 2020-11-02 10:40
@varshar16 Do you have any opinion whether the bugs listed in the following link is related to this issue or not?

https://github.com/rook/rook/issues/6270#issuecomment-715348553

**Comment by varshar16** [comment] 2020-11-02 10:53
> @varshar16 Do you have any opinion whether the bugs listed in the following link is related to this issue or not?
> 
> [#6270 (comment)](https://github.com/rook/rook/issues/6270#issuecomment-715348553)

They are not related to this issue.

**Comment by varshar16** [comment] 2020-11-02 10:54
> @varshar16 Yes, any hints are welcome.

Please see my comment here: https://github.com/rook/rook/issues/5877#issuecomment-713639078

**Comment by satoru-takeuchi** [comment] 2020-11-27 01:09
Sorry I've not had enough time to investigate this issue for several weeks. I restarted to handle this issue.

**Comment by leseb** [comment] 2020-11-27 08:04
> Sorry I've not had enough time to investigate this issue for several weeks. I restarted to handle this issue.

No problem, thanks for looking into this :)

**Comment by varshar16** [comment] 2020-12-11 17:36
@satoru-takeuchi Hi, let me know  if you need any help.

**Comment by satoru-takeuchi** [comment] 2020-12-14 09:56
@varshar16 Thank you! Currently there is no problem. I'm bisecting which commit introduced this problem.

I found `ceph orch device ls` don't work as you said and also found that Rook v1.3.0 works well.

Rook master and Ceph v15.2.7
```
# ceph orch host ls
HOST    ADDR    LABELS  STATUS
ubuntu  ubuntu
# ceph orch device ls ubuntu
```

Rook v1.3.0 and Ceph v15.2.0
```
# ceph orch host ls
HOST    ADDR    LABELS  STATUS
ubuntu  ubuntu
# ceph orch device ls
HOST    PATH       TYPE   SIZE  DEVICE  AVAIL  REJECT REASONS
ubuntu  /dev/vdb   hdd   10.0G  None    False  not empty
ubuntu  /dev/dm-1  hdd    980M  None    False  not empty
ubuntu  /dev/dm-0  hdd   49.0G  None    False  not empty
# 
```

Next I'll try to reproduce this problem in v1.4.0. I guess I can indentify the problematic commit.

I apologize you. It takes so long time to resolve this problem even though you've gave me many hints. I've been extremely busy due to #6530, just after I said "I restarted to handle this issue", Haha.

**Comment by satoru-takeuchi** [comment] 2020-12-14 13:46
This problematic commit seems to be introduced between v1.4.0 and v1.5.0. And this commit wasn't backported to v1.4 branch.

- Rook v1.4.0 & Ceph v15.2.0: succeeded to list devices by `ceph orch host ls` from toolbox 
- Rook v1.4.4 & Ceph v15.2.0: succeeded
- Rook v1.4.6 & Ceph v15.2.0: succeeded
- Rook v1.4.6 & Ceph v15.2.7: succeeded
- Rook v1.4.8 & Ceph v15.2.0: succeeded
- Rook v1.5.0 & Ceph v15.2.0: failed

One more point. If this empty-device-list problem exists, the mgr suite should fail consistently. However, this issue is originally reported as an intermittent failure. So there would be two problems, but I'm not sure yet.

**Comment by varshar16** [comment] 2020-12-15 07:56
@satoru-takeuchi Thanks for looking into it.

**Comment by satoru-takeuchi** [comment] 2020-12-25 13:47
There are 265 merge commits between v1.4.0 and v1.5.0. Today I tried the following commits.

#133: 259505cb8: PASS
#198: 788709f67: PASS
#230: f91616f1e: PASS
#248: 22da5e299: PASS

It means the root cause is between the merge commit 249 and 265.

Here 248 is merged in Aug 3 and this issue is opened in Jul 23. So I guess there are at least two problems.

**Comment by satoru-takeuchi** [comment] 2020-12-26 05:17
I found that #6589 introduced this problem.

https://github.com/ceph/ceph/blob/656386e9c0dd1d212221ac030b0060dac6b2bf10/src/pybind/mgr/rook/rook_cluster.py#L195

Rook module gets device information from "rook-discover" cm, that is created by the discovery daemon.  However, this daemon is disabled by this commit.

I'm looking for other ways to get the device information.

**Comment by satoru-takeuchi** [comment] 2021-01-07 12:26
@travisn I'd like to get your advice.

As I described above, the root cause is the missing of rook-discover cm and the corresponding pods. This problem can simply be fixed by force-enabling discovery daemon if rook mgr module is used. Does it make sense? Or do you have better solutions?

**Comment by travisn** [comment] 2021-01-07 19:56
Agreed, for the CephMgrSuite test suite let's enable the discovery daemon since it is requirement.

**Closed** 2021-04-23 20:02 UTC
Labels: bug, ceph, wontfix
