### ISSUE TITLE
the discovery service did not discover my disk and ignored it

### ISSUE THREAD

**Issue by 1998729** [rook/rook#9501] opened 2021-12-28 02:14 UTC
I have enabled the daemonset function according to the disk discovery mechanism, and the service is running normally, but there is obviously a new disk on my current machine and it has not been initialized, but he always does not mount it for me

![image](https://user-images.githubusercontent.com/88186802/147520249-3362fbc2-f73f-4c90-8cd5-7490aaa4cafb.png)

**Comment by 1998729** [comment] 2021-12-28 02:14
![image](https://user-images.githubusercontent.com/88186802/147520276-1fe5fd04-439d-4c14-a985-7eab8388e3df.png)

**Comment by 1998729** [comment] 2021-12-28 02:15
![image](https://user-images.githubusercontent.com/88186802/147520347-8d9c6253-6e79-429b-9e02-f2bdde5b0f55.png)

**Comment by 1998729** [comment] 2021-12-28 02:19
![image](https://user-images.githubusercontent.com/88186802/147520598-b395c988-0a50-4a1c-b50d-68611b76df05.png)

**Comment by leseb** [comment] 2022-01-03 13:55
This is probably a duplicate of https://github.com/rook/rook/issues/9493.

**Comment by leseb** [comment] 2022-01-03 13:55
Which Rook version are you running on?

**Closed** 2022-01-04 16:53 UTC
Labels: bug
