### ISSUE TITLE
If you delete the resource pool of cephfs and rebuild it, a problem will occur and the pool created by cephfilesystem will not be usable.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6618] opened 2020-11-12 08:45 UTC
If you delete the cephfs resource pool and rebuild it, a problem will occur and you will not be able to use the pool created by cephfilesystem.

The manifest used is as follows.

```cephfs.yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
spec:
  metadataPool:
    replicated:
      size: 2
      requireSafeReplicaSize: true
  dataPools:
    - failureDomain: osd
      replicated:
        size: 2
        requireSafeReplicaSize: true
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

```

```storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-cephfs
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  # clusterID is the namespace where operator is deployed.
  clusterID: rook-ceph

  fsName: myfs

  pool: myfs-data0


  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  # uncomment the following line for debugging
  #- debug
```

```pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
```

kubectl delete -f <filename>

The pool created by cephfs with the above command could not be deleted!
So I deleted the pool with the following command.

```
ceph fs rm myfs --yes-i-really-mean-it
ceph osd pool delete myfs-data0 myfs-data0 --yes-i-really-really-mean-it
ceph osd pool delete myfs-metadata myfs-metadata --yes-i-really-really-mean-it
```

However, even after rebuilding the resource, pvc is still giving the following error.

```
Events:
  Type     Reason                Age                   From                                                                                                             Message
  ----     ------                ----                  ----                                                                                                             -------
  Warning  ProvisioningFailed    52m (x6 over 76m)     rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-786c55674-vh85x_a61583f5-1ee3-45b7-a530-4af167a55409  (combined from similar events): failed to provision volume with StorageClass "rook-cephfs": rpc error: code = Internal desc = an error (exit status 2) occurred while running ceph args: [fs subvolume create myfs csi-vol-871dab3a-24bb-11eb-83b8-a2a2d03a0d73 10737418240 --group_name csi --mode 777 -m 10.43.238.86:6789,10.43.3.26:6789,10.43.190.156:6789 -c /etc/ceph/ceph.conf -n client.csi-cephfs-provisioner --keyfile=***stripped*** --pool_layout myfs-data0]
  Normal   Provisioning          2m10s (x25 over 81m)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-786c55674-vh85x_a61583f5-1ee3-45b7-a530-4af167a55409  External provisioner is provisioning volume for claim "default/cephfs-pvc-csi"
  Normal   ExternalProvisioning  64s (x322 over 81m)   persistentvolume-controller                                                                                      waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
```

Is there a way to fix this problem and make the cephfilesystem available?

**Comment by vdi-kakui** [comment] 2020-11-12 09:41
It is desciribe of mds. Do you know the cause of this error and how to resolve it?

```
Name:         rook-ceph-mds-myfs-b-78f9cccc76-5xwxb
Namespace:    rook-ceph
Priority:     0
Node:         ＃＃＃＃＃＃＃＃＃＃＃＃
Start Time:   Thu, 12 Nov 2020 07:13:38 +0000
Labels:       app=rook-ceph-mds
              ceph_daemon_id=myfs-b
              ceph_daemon_type=mds
              mds=myfs-b
              pod-template-hash=78f9cccc76
              rook_cluster=rook-ceph
              rook_file_system=myfs
Annotations:  cni.projectcalico.org/podIP: 10.42.9.52/32
Status:       Running
IP:           10.42.9.52
IPs:
  IP:           10.42.9.52
Controlled By:  ReplicaSet/rook-ceph-mds-myfs-b-78f9cccc76
Init Containers:
  chown-container-data-dir:
    Container ID:  docker://35f737847a8067038abecaa4f50fa8fbcb17f7c0c1452dcd16b143b423c1a080
    Image:         ceph/ceph:v15.2.5
    Image ID:      docker-pullable://ceph/ceph@sha256:939a46c06b334e094901560c8346de33c00309e3e3968a2db240eb4897c6a508
    Port:          <none>
    Host Port:     <none>
    Command:
      chown
    Args:
      --verbose
      --recursive
      ceph:ceph
      /var/log/ceph
      /var/lib/ceph/crash
      /var/lib/ceph/mds/ceph-myfs-b
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 12 Nov 2020 07:13:40 +0000
      Finished:     Thu, 12 Nov 2020 07:13:40 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/ceph from rook-config-override (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mds-myfs-b-keyring (ro)
      /var/lib/ceph/crash from rook-ceph-crash (rw)
      /var/lib/ceph/mds/ceph-myfs-b from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f6wbv (ro)
Containers:
  mds:
    Container ID:  docker://9d710624b1b28675b3ade538ecc666b505c531bbda2dc9d41d8390ab3f8ed5bf
    Image:         ceph/ceph:v15.2.5
    Image ID:      docker-pullable://ceph/ceph@sha256:939a46c06b334e094901560c8346de33c00309e3e3968a2db240eb4897c6a508
    Port:          <none>
    Host Port:     <none>
    Command:
      ceph-mds
    Args:
      --fsid=1bdb57b5-7f80-4de6-bfc1-aa9306386f0e
      --keyring=/etc/ceph/keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --id=myfs-b
      --setuser=ceph
      --setgroup=ceph
      --foreground
    State:          Running
      Started:      Thu, 12 Nov 2020 07:13:42 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       exec [env -i sh -c ceph --admin-daemon /run/ceph/ceph-mds.myfs-b.asok status] delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      CONTAINER_IMAGE:                ceph/ceph:v15.2.5
      POD_NAME:                       rook-ceph-mds-myfs-b-78f9cccc76-5xwxb (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
    Mounts:
      /etc/ceph from rook-config-override (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mds-myfs-b-keyring (ro)
      /var/lib/ceph/crash from rook-ceph-crash (rw)
      /var/lib/ceph/mds/ceph-myfs-b from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f6wbv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  rook-config-override:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      rook-config-override
    ConfigMapOptional:  <nil>
  rook-ceph-mds-myfs-b-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-mds-myfs-b-keyring
    Optional:    false
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/log
    HostPathType:
  rook-ceph-crash:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/crash
    HostPathType:
  ceph-daemon-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-f6wbv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-f6wbv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 5s
```

**Comment by travisn** [comment] 2020-11-12 16:28
@vdi-kakui If you want to purge the filesystem when the CR is deleted, you need to set:
```
preserveFilesystemOnDelete: false
```
Currently it is set to true in your yaml. Since the filesystem is in a bad state I would suggest removing it and trying again.

**Comment by vdi-kakui** [comment] 2020-11-12 23:59
Thank you God.

**Comment by leseb** [comment] 2020-11-13 11:08
Looks like the issue is solved. Closing.

**Closed by leseb** 2020-11-13 11:08 UTC
Labels: bug
