### ISSUE TITLE
MGR crashing due to Prometheus module not found 

### ISSUE THREAD

**Issue by xavi-clovr** [rook/rook#13559] opened 2024-01-11 12:39 UTC
I did a fresh install using Ceph 18.2.1 and Rook v1.13.1. MGR module is having some issues with the Prometheus module.
The crashes are in a loop so the amount of crashes grows and grows.
In the Ceph dashboard I'm unable to see any metrics (even if I connected correctly my Prometheus as I did in previous versions of Rook and Ceph and also I'm able to see in the Prometheus UI all ceph metrics correctly). 
```
bash-4.4$ ceph crash info 2024-01-11T12:18:03.970167Z_2239ed5c-71b8-4ebd-80ba-9d3f89d32acf
{
    "backtrace": [
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1657, in _oremote\n    return mgr.remote(o, meth, *args, **kwargs)",
        "  File \"/usr/share/ceph/mgr/mgr_module.py\", line 2228, in remote\n    args, kwargs)",
        "ImportError: Module not found",
        "\nDuring handling of the above exception, another exception occurred:\n",
        "Traceback (most recent call last):",
        "  File \"/usr/share/ceph/mgr/prometheus/module.py\", line 649, in __init__\n    self.modify_instance_id = self.get_orch_status() and self.get_module_option(",
        "  File \"/usr/share/ceph/mgr/prometheus/module.py\", line 869, in get_orch_status\n    return self.available()[0]",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1586, in inner\n    completion = self._oremote(method_name, args, kwargs)",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1661, in _oremote\n    f_set = self.get_feature_set()",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1586, in inner\n    completion = self._oremote(method_name, args, kwargs)",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1657, in _oremote\n    return mgr.remote(o, meth, *args, **kwargs)",
        "  File \"/usr/share/ceph/mgr/mgr_module.py\", line 2228, in remote\n    args, kwargs)",
        "ImportError: Module not found"
    ],
    "ceph_version": "18.2.1",
    "crash_id": "2024-01-11T12:18:03.970167Z_2239ed5c-71b8-4ebd-80ba-9d3f89d32acf",
    "entity_name": "mgr.a",
    "mgr_module": "prometheus",
    "mgr_module_caller": "ActivePyModule::load",
    "mgr_python_exception": "ImportError",
    "os_id": "centos",
    "os_name": "CentOS Stream",
    "os_version": "8",
    "os_version_id": "8",
    "process_name": "ceph-mgr",
    "stack_sig": "6f4033c8739c625d3935380854c7945f8bd28267f6a4d03fc2017bc8815c257c",
    "timestamp": "2024-01-11T12:18:03.970167Z",
    "utsname_hostname": "rook-ceph-mgr-a-5ddbc86cf9-slkrr",
    "utsname_machine": "x86_64",
    "utsname_release": "5.15.0-89-generic",
    "utsname_sysname": "Linux",
    "utsname_version": "#99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023"
}
```

```
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
prometheus-operated                      ClusterIP   None            <none>        9090/TCP            20h
rook-prometheus                          NodePort    10.43.74.75     <none>        9090:30900/TCP      20h
```

```
bash-4.4$ ceph dashboard get-prometheus-api-host
http://10.43.74.75:9090
```

Not sure what's going on cause using Ceph 18.2.0 I was not having this problem with same config.
Any idea what can be the root cause? Maybe a bad config from my side but right now I'm not able to find it... Any help would be super appreciated!

**Comment by xavi-clovr** [comment] 2024-01-11 12:48
Okay I think this is related to https://github.com/rook/rook/issues/13527 as I see the that prometheus module is loading before than rook one. My bad, maybe we can close this as duplicated. Sorry for the inconveniences!

**Comment by rkachach** [comment] 2024-01-11 13:44
Closing because this is duplicate of https://github.com/rook/rook/issues/13527.

**Closed by rkachach** 2024-01-11 13:44 UTC
Labels: bug
