### ISSUE TITLE
resourceLimits not getting applied to the OSDs when the storageClassDeviceSets are updated

### ISSUE THREAD

**Issue by ashishranjan738** [rook/rook#4643] opened 2020-01-09 12:01 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The resource limits to OSDs are not getting applied when the resource limits in the storageClassDeviceSets are updated.

**Expected behavior:**
The operator should update the OSD's deployments with the resource limits applied to their corresponding storageClassDeviceSet.

**How to reproduce it (minimal and precise):**

Step 1: create a ceph cluster with no resource limits in the storageClassDeviceSet in cephcluster CR.
Step 2: once the provisioning is successful with step 1, update the storageClassDeviceSet with resource limits in the cephCluster CR.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by ashishranjan738** [comment] 2020-01-09 12:03
**Note: The currently known workaround is to delete the already provisioned OSD deployments  after updating the cephCluster yaml with resource limits.

**Comment by AXington** [comment] 2020-01-09 20:34
I have ran into this issue as well.

**Comment by leseb** [comment] 2020-01-22 08:48
@ashishranjan738 @AXington do you know if this is only happening on PVC? Thanks.

**Comment by AXington** [comment] 2020-01-23 01:42
@leseb unfortunately, I do not know, all my clusters are PVC backed, so I have nothing to compare with.

**Comment by jti989** [comment] 2020-01-23 08:25
We ran into this problem as well. Deleting the operator pod helped, when it restarted the osds were restarted with the limits. Now the OSDs don't come up again, staying at CrashLoopBackOff. I will open a separate issue for that.

**Comment by ashishranjan738** [comment] 2020-01-23 10:51
> @ashishranjan738 @AXington do you know if this is only happening on PVC? Thanks.

yeah, I haven't seen this problem without PVC.

**Comment by leseb** [comment] 2020-01-23 14:08
@ashishranjan738 are you working on fixing this? Can I assign it to you?

**Comment by ashishranjan738** [comment] 2020-01-24 07:57
> @ashishranjan738 are you working on fixing this? Can I assign it to you?

yeah i can try.

**Comment by satoru-takeuchi** [comment] 2020-06-01 17:33
@AXington @jti989 @ashishranjan738 I couldn't reproduce this problem. Could you tell me the following information?

- The exact version that you encountered this issue.
- How to reproduce this problem in detail.

I tried the following environments.

- v1.3.4
- v1.2.7
- v1.2.0
- v1.1.9

Step to reproduce:

1. Create a cluster that has one OSD created with storageClassDeviceSets.
2. Edit CephCluster to add "storageClassDeviceSets->resources->limits->cpu: 1"
3. Wait for a while, at most about 30 seconds in my case.

With all the above-mentioned versions, the OSD pod was restarted automatically and the resource limit exists.

**Comment by satoru-takeuchi** [comment] 2020-06-07 23:55
@travisn 

Since no one haven't answered and this problem seems not to happen on the recent two stable release, how about closing this issue for now and reopen this after someone report this problem again?

**Comment by travisn** [comment] 2020-06-08 22:55
@satoru-takeuchi Thanks for investigating, sounds good to close since it does not repro

**Closed by travisn** 2020-06-08 22:55 UTC
Labels: bug, keepalive
