### ISSUE TITLE
Question about of using partitions on PVC-based osd

### ISSUE THREAD

**Issue by R-omk** [rook/rook#8494] opened 2021-08-05 13:37 UTC
_Originally posted by @leseb in https://github.com/rook/rook/discussions/7349#discussioncomment-425956_
I created a new issue because on disscusion page : "This conversation has been locked and limited to collaborators."

Now I have a cluster with OSD on a PVC   (rook/cephv1.3.3   ; ceph 14.2.9),
a separate partition is allocated for bluefs db metadata (without lvm) and whole raw device (sda) for main data, for each of them created pv, like this:

```
# export COLUMNS="CLASS:.spec.storageClassName,PATH:.spec.local.path,HOST:.spec.nodeAffinity.required.nodeSelectorTerms"


# kubectl get pv  host11-ceph-set5-ssd-block -o=custom-columns=$COLUMNS
CLASS                 PATH                                                                   HOST
ceph-set5-ssd-block   /dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-00000_S3W8NX0M106586-part2   [map[matchExpressions:[map[key:kubernetes.io/hostname operator:In values:[host11]]]]]


# kubectl get pv  host11-ceph-set2-ssd-block-metadata -o=custom-columns=$COLUMNS
CLASS                          PATH                                                                   HOST
ceph-set2-ssd-block-metadata   /dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-00000_S3W8NX0M106586-part1   [map[matchExpressions:[map[key:kubernetes.io/hostname operator:In values:[host11]]]]]

# kubectl get pv  host11-ceph-set2-hdd-block-data -o=custom-columns=$COLUMNS
CLASS                      PATH                                               HOST
ceph-set2-hdd-block-data   /dev/disk/by-id/ata-ST4000NM0245-1Z2107_ZC18L7BB   [map[matchExpressions:[map[key:kubernetes.io/hostname operator:In values:[host11]]]]]


```

This works with current versions. 
Should I be worried about the issue mentioned in the discussion? Or does it only apply to lvm?

If this concerns my case, then if I upgrade to rook^1.6  and ceph to at least v14.2.14 or v15.2.9 , can I use the described approach when creating an OSD?

**Comment by BlaineEXE** [comment] 2021-09-16 14:36
Closing this issue, as the discussion is now unlocked. 

It sounds like you are using OSDs on PVC, which is not a bugged use case and has had no changes related to the discussion.

**Closed by BlaineEXE** 2021-09-16 14:36 UTC
