### ISSUE TITLE
Erasure-coded pool unusable

### ISSUE THREAD

**Issue by dimm0** [rook/rook#1500] opened 2018-02-15 18:17 UTC
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
I was trying to create the standard rbd pool for blockstorage with erasureCode: codingChunks: 2  dataChunks: 3. Right after it was created, a PV claim failed with:

`
create operation with name "provision-perfsonar/cassandra-data-esmond-cassandra-0[18f9ba57-1226-11e8-9422-0cc47a6be994]". An operation with that name failed at 2018-02-15 08:13:58.518435913 +0000 UTC m=+2659.454813747. No retries permitted until 2018-02-15 08:16:00.518435913 +0000 UTC m=+2781.454813747 (2m2s). Last error: "Failed to create rook block image rbd/pvc-18f9ba57-1226-11e8-9422-0cc47a6be994: failed to create image pvc-18f9ba57-1226-11e8-9422-0cc47a6be994 in pool rbd of size 53687091200: Failed to complete : exit status 22. output: 2018-02-15 08:13:58.513932 7f68967fc700 -1 librbd::image::CreateRequest: 0x55e43607f990 handle_validate_overwrite: pool missing required overwrite support".
`

I went to rook toolbox and enabled overwrites:

`ceph osd pool set rbd allow_ec_overwrites true`

Then I've got another error:

```
2018-02-15 08:21:43.431625 7fc87b7fe700 -1 librbd::image::CreateRequest: 0x5634747857e0 handle_create_image: error writing header: (95) Operation not supported
E0215 08:21:43.441781       7 goroutinemap.go:165] Operation for "provision-perfsonar/cassandra-data-esmond-cassandra-0[3c2b74f9-1229-11e8-9422-0cc47a6be994]" failed. No retries permitted until 2018-02-15 08:21:44.441750212 +0000 UTC m=+3125.378128042 (durationBeforeRetry 1s). Error: Failed to create rook block image rbd/pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994: failed to create image pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994 in pool rbd of size 53687091200: Failed to complete : exit status 95. output: 2018-02-15 08:21:43.413833 7fc87b7fe700 -1 librbd::image::CreateRequest: 0x5634747857e0 handle_add_image_to_directory: error adding image to directory: (95) Operation not supported
2018-02-15 08:21:43.431625 7fc87b7fe700 -1 librbd::image::CreateRequest: 0x5634747857e0 handle_create_image: error writing header: (95) Operation not supported
2018-02-15 08:21:56.901681 I | op-provisioner: creating volume with configuration {pool:rbd clusterName:rook fstype:xfs}
2018-02-15 08:21:56.901726 I | exec: Running command: rbd create rbd/pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994 --size 51200 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring
E0215 08:21:58.649955       7 controller.go:801] Failed to provision volume for claim "perfsonar/cassandra-data-esmond-cassandra-0" with StorageClass "rook-block": Failed to create rook block image rbd/pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994: failed to create image pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994 in pool rbd of size 53687091200: Failed to complete : exit status 95. output: 2018-02-15 08:21:58.620402 7fd4c2ffd700 -1 librbd::image::CreateRequest: 0x5621ce48f7e0 handle_add_image_to_directory: error adding image to directory: (95) Operation not supported
E0215 08:21:58.650049       7 goroutinemap.go:165] Operation for "provision-perfsonar/cassandra-data-esmond-cassandra-0[3c2b74f9-1229-11e8-9422-0cc47a6be994]" failed. No retries permitted until 2018-02-15 08:22:00.650015791 +0000 UTC m=+3141.586393619 (durationBeforeRetry 2s). Error: Failed to create rook block image rbd/pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994: failed to create image pvc-3c2b74f9-1229-11e8-9422-0cc47a6be994 in pool rbd of size 53687091200: Failed to complete : exit status 95. output: 2018-02-15 08:21:58.620402 7fd4c2ffd700 -1 librbd::image::CreateRequest: 0x5621ce48f7e0 handle_add_image_to_directory: error adding image to directory: (95) Operation not supported
```

What you expected to happen:
Erasure-coded pools to be usable same way as reblicated pools

How to reproduce it (minimal and precise):
Follow all steps to set up rook, create erasure-coded pool for storageclass, create a pod with PVC.

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`):
Linux 4.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Jan 23 20:28:26 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Baremetal
* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.6.0-219.g09dc9b8
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm

**Comment by jbw976** [comment] 2018-02-15 18:43
@dimm0 are you using filestore by any chance?

**Comment by dimm0** [comment] 2018-02-15 19:07
bluestore

**Comment by dimm0** [comment] 2018-02-15 19:07
https://github.com/dimm0/prp_k8s_config/blob/master/rook/rook-nautilus.yaml

**Comment by jbw976** [comment] 2018-02-28 23:38
I believe this is a duplicate of #1129, please follow that issue which is part of the 0.8 milestone.

**Closed by jbw976** 2018-02-28 23:38 UTC
