### ISSUE TITLE
Rook Ceph with Bluestore using Local Disk GKE

### ISSUE THREAD

**Issue by mikosa** [rook/rook#6433] opened 2020-10-14 04:22 UTC
**Is this a bug report or feature request?**
* Feature Request
Allow the use of pre-formatted devices for bluestore

**What should the feature do:**
rook-ceph-osd-prepare detects the local disk on GKE but refuses to use it as a device as it is pre-formatted 
 ```
cephosd: skipping device "sdb" because it contains a filesystem "ext4"
```

**What is use case behind this feature:**
Need to be able to use local ssd in GKE as bluestore devices

**Environment**:
This is GKE Kubernetes 1.17

**Comment by travisn** [comment] 2020-10-14 04:43
@mikosa This is expected. Ceph requires a raw disk as explained in the [pre-requisites](https://rook.github.io/docs/rook/v1.4/ceph-prerequisites.html). Formatted devices are not supported.

**Comment by leseb** [comment] 2020-10-14 07:29
Closing, not a bug.

**Closed by leseb** 2020-10-14 07:29 UTC
Labels: feature
