### ISSUE TITLE
failed reading obj info from .rgw.root:zone_info.XXXX: (2) No such file or directory

### ISSUE THREAD

**Issue by ausias-armesto** [rook/rook#12512] opened 2023-07-13 16:36 UTC
**Is this a bug report or feature request?**
* Bug Report
I had an initial setup of Rook-ceph working(but not used) with the Object Storage, but for some circumstances I had to disable (remove) it for some months. Now I'm trying to enable again the ObjectStore but Kubernetes resource CephObjectStore is not able to become `Succeed`.

````
$  kubectl get Cephobjectstores
NAME               PHASE
ceph-objectstore   Failure

````

And any command line to `radosgw-admin` shows this message at the beginning
````
[rook@rook-ceph-tools-589f5689bc-f2hxq /]$ radosgw-admin realm list
2023-07-13T14:11:51.990+0000 76c8527d1500  0 failed reading obj info from .rgw.root:zone_info.62eb0482-4bdd-43ff-b3be-f22390f7e4a3: (2) No such file or directory
{
    "default_info": "c9e2e922-7657-4194-9181-a2fb4fa0711a",
    "realms": [
        "ceph-objectstore"
    ]
}
````

On the other side the deployment `rook-ceph-rgw` is not created by the operator

````
[rook@rook-ceph-tools-589f5689bc-f2hxq /]$ rados -p .rgw.root ls --all
	realms_names.ceph-objectstore
	default.zonegroup.c9e2e922-7657-4194-9181-a2fb4fa0711a
	realms.c9e2e922-7657-4194-9181-a2fb4fa0711a.control
	zonegroup_info.df48d9ce-deb2-4b92-947d-975da84bffda
	periods.2c20de9f-e8eb-48b5-b591-c6e722050195.1
	default.realm
	zone_names.ceph-objectstore
	zonegroups_names.ceph-objectstore
	period_config.c9e2e922-7657-4194-9181-a2fb4fa0711a
	periods.2c20de9f-e8eb-48b5-b591-c6e722050195.latest_epoch
	periods.c9e2e922-7657-4194-9181-a2fb4fa0711a:staging
	realms.c9e2e922-7657-4194-9181-a2fb4fa0711a
	zone_info.a2a7cc4d-df0c-4f5b-965c-e7cd23b702a1
	default.zone.c9e2e922-7657-4194-9181-a2fb4fa0711a
	periods.34b6db0c-fc01-4561-a6f0-b9eef82611b9.1
	periods.34b6db0c-fc01-4561-a6f0-b9eef82611b9.latest_epoch
````

**How to reproduce it (minimal and precise):**
Not sure how to reproduce the bug in a clean environment

**File(s) to submit**:

<details>
<summary>CephObjectStore</summary>

```
  apiVersion: ceph.rook.io/v1
  kind: CephObjectStore
  metadata:
    annotations:
      meta.helm.sh/release-name: rook-ceph-cluster
      meta.helm.sh/release-namespace: rook-ceph
    creationTimestamp: "2023-07-11T07:44:26Z"
    finalizers:
    - cephobjectstore.ceph.rook.io
    generation: 3
    labels:
      app.kubernetes.io/managed-by: Helm
    name: ceph-objectstore
    namespace: rook-ceph
    resourceVersion: "60900555"
    uid: f9776f5c-9fc3-4bbe-8226-63ad7a52d128
  spec:
    dataPool:
      erasureCoded:
        codingChunks: 1
        dataChunks: 2
      failureDomain: host
      mirroring: {}
      quotas: {}
      replicated:
        size: 0
      statusCheck:
        mirror: {}
    gateway:
      instances: 1
      placement: {}
      port: 80
      priorityClassName: system-cluster-critical
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
    healthCheck: {}
    metadataPool:
      erasureCoded:
        codingChunks: 0
        dataChunks: 0
      failureDomain: host
      mirroring: {}
      quotas: {}
      replicated:
        size: 3
      statusCheck:
        mirror: {}
    preservePoolsOnDelete: true
    zone:
      name: ""
```
</details>

**Logs to submit**:
Operator Logs can be found here https://drive.google.com/file/d/1_dDctaCGz-o8lsNKfXBt1P9ocTGf0DNv/view?usp=drive_link

**Cluster Status to submit**:
<details>
<summary>ceph status</summary>

```
[rook@rook-ceph-tools-589f5689bc-f2hxq /]$ ceph status
  cluster:
    id:     dc8366ab-488f-4694-968c-510a1ef591a0
    health: HEALTH_OK
  services:
    mon: 3 daemons, quorum b,c,f (age 2d)
    mgr: b(active, since 4h), standbys: a
    mds: 2/2 daemons up, 2 hot standby
    osd: 3 osds: 3 up (since 4h), 3 in (since 5w)
  data:
    volumes: 2/2 healthy
    pools:   14 pools, 217 pgs
    objects: 49.28k objects, 61 GiB
    usage:   186 GiB used, 1.0 TiB / 1.2 TiB avail
    pgs:     217 active+clean
  io:
    client:   691 KiB/s rd, 2.4 MiB/s wr, 6 op/s rd, 198 op/s wr
```
</details>

**Environment**:
* OS: Debian GNU/Linux 11 (bullseye)
* Kernel: Linux server-stage-fsn1-002 5.10.0-9-amd64 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
* Cloud provider or hardware configuration: Hetzner Dedicated servers
* Rook version: v1.10.7
* Ceph version: v17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version: v1.24.6
* Kubernetes cluster type: Kubespray

**Comment by parth-gr** [comment] 2023-07-14 08:53
PLease share the describe of `kubectl describe Cephobjectstores`

**Comment by ausias-armesto** [comment] 2023-07-14 10:14
````
Name:         ceph-objectstore
Namespace:    rook-ceph
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: rook-ceph-cluster
              meta.helm.sh/release-namespace: rook-ceph
API Version:  ceph.rook.io/v1
Kind:         CephObjectStore
Metadata:
  Creation Timestamp:  2023-07-11T07:44:26Z
  Finalizers:
    cephobjectstore.ceph.rook.io
  Generation:  3
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cephobjectstore.ceph.rook.io":
      f:spec:
        f:dataPool:
          f:mirroring:
          f:quotas:
          f:replicated:
            .:
            f:size:
          f:statusCheck:
            .:
            f:mirror:
        f:gateway:
          f:placement:
        f:metadataPool:
          f:erasureCoded:
            .:
            f:codingChunks:
            f:dataChunks:
          f:mirroring:
          f:quotas:
          f:statusCheck:
            .:
            f:mirror:
        f:zone:
          .:
          f:name:
    Manager:      rook
    Operation:    Update
    Time:         2023-07-11T07:44:27Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:dataPool:
          .:
          f:erasureCoded:
            .:
            f:codingChunks:
            f:dataChunks:
          f:failureDomain:
        f:gateway:
          .:
          f:instances:
          f:port:
          f:priorityClassName:
          f:resources:
            .:
            f:limits:
              .:
              f:cpu:
              f:memory:
            f:requests:
              .:
              f:cpu:
              f:memory:
        f:healthCheck:
        f:metadataPool:
          .:
          f:failureDomain:
          f:replicated:
            .:
            f:size:
        f:preservePoolsOnDelete:
    Manager:      helm
    Operation:    Update
    Time:         2023-07-13T12:07:07Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:endpoints:
          .:
          f:insecure:
          f:secure:
        f:phase:
    Manager:         rook
    Operation:       Update
    Subresource:     status
    Time:            2023-07-14T10:04:00Z
  Resource Version:  61270421
  UID:               f9776f5c-9fc3-4bbe-8226-63ad7a52d128
Spec:
  Data Pool:
    Erasure Coded:
      Coding Chunks:  1
      Data Chunks:    2
    Failure Domain:   host
    Mirroring:
    Quotas:
    Replicated:
      Size:  0
    Status Check:
      Mirror:
  Gateway:
    Instances:  1
    Placement:
    Port:                 80
    Priority Class Name:  system-cluster-critical
    Resources:
      Limits:
        Cpu:     1
        Memory:  2Gi
      Requests:
        Cpu:     500m
        Memory:  1Gi
  Health Check:
  Metadata Pool:
    Erasure Coded:
      Coding Chunks:  0
      Data Chunks:    0
    Failure Domain:   host
    Mirroring:
    Quotas:
    Replicated:
      Size:  3
    Status Check:
      Mirror:
  Preserve Pools On Delete:  true
  Zone:
    Name:  
Status:
  Endpoints:
    Insecure:
      http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
    Secure:
  Phase:  Failure
Events:
  Type     Reason           Age                   From                         Message
  ----     ------           ----                  ----                         -------
  Warning  ReconcileFailed  9m54s (x80 over 18h)  rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/ceph-objectstore". failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store ["ceph-objectstore"]: failed to commit config changes after creating multisite config for CephObjectStore "rook-ceph/ceph-objectstore": failed to commit RGW configuration period changes%!(EXTRA []string=[]): exit status 22
````

**Comment by parth-gr** [comment] 2023-07-14 12:15
>failed to commit RGW configuration period changes%!(EXTRA []string=[]): exit status 22

Seems like some of you helm CR config is not having right formatting, 

@alimaredia when we can see this commit error?

**Comment by alimaredia** [comment] 2023-07-14 15:24
@ausias-armesto this is happening in just a plain object-store deployment right on a single Ceph cluster? There is no multisite configuration replicating data across two data Ceph clusters right?

@parth-gr I don't think I completely understand your question. That error should be reproducible if you run `radosgw-admin period update --commit`. 

If the proper pools aren't being created in earlier steps in the operator I would focus on that issue before trying to address the period not being committed.

**Comment by ausias-armesto** [comment] 2023-07-14 21:46
The deployment is simple, I'm just using one CephCluster and is the only object-store in that cluster.
I hope this answered your question

**Comment by ausias-armesto** [comment] 2023-07-18 07:36
Yes I do, here it is my osd tree.
<img width="653" alt="Screenshot 2023-07-18 at 09 35 11" src="https://github.com/rook/rook/assets/29434949/b7bd1214-5408-4da9-a90a-917aed27a313">

**Comment by ausias-armesto** [comment] 2023-08-28 17:59
Hi,

It's been awhile since last comment and I still have the issue. I've analysed the logs and the command that seems to fail is:
```
2023-08-28 17:53:02.093403 D | exec: Running command: radosgw-admin period update --rgw-realm=ceph-objectstore --rgw-zonegroup=ceph-objectstore --rgw-zone=ceph-objectstore --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
2023-08-28 17:53:02.152315 D | ceph-object-controller: RGW config period diff:
map[string]any{
  	... // 2 ignored entries
  	"master_zone": strings.Join({
- 		"62eb0482-4bdd-43ff-b3be-f22390f7e4a3",
+ 		"a2a7cc4d-df0c-4f5b-965c-e7cd23b702a1",
  	}, ""),
  	"master_zonegroup": strings.Join({
- 		"85860956-bc7c-4bd4-921b-2ad3475e4e3c",
+ 		"df48d9ce-deb2-4b92-947d-975da84bffda",
  	}, ""),
  	"period_config": map[string]any{"anonymous_ratelimit": map[string]any{"enabled": bool(false), "max_read_bytes": float64(0), "max_read_ops": float64(0), "max_write_bytes": float64(0), ...}, "bucket_quota": map[string]any{"check_on_raw": bool(false), "enabled": bool(false), "max_objects": float64(-1), "max_size": float64(-1), ...}, "bucket_ratelimit": map[string]any{"enabled": bool(false), "max_read_bytes": float64(0), "max_read_ops": float64(0), "max_write_bytes": float64(0), ...}, "user_quota": map[string]any{"check_on_raw": bool(false), "enabled": bool(false), "max_objects": float64(-1), "max_size": float64(-1), ...}, ...},
  	"period_map": map[string]any{
  		"id": string("34b6db0c-fc01-4561-a6f0-b9eef82611b9"),
  		"short_zone_ids": []any{
- 			map[string]any{
- 				"key": string("62eb0482-4bdd-43ff-b3be-f22390f7e4a3"),
- 				"val": float64(2.822659734e+09),
- 			},
+ 			map[string]any{
+ 				"key": string("a2a7cc4d-df0c-4f5b-965c-e7cd23b702a1"),
+ 				"val": float64(1.001186079e+09),
+ 			},
  		},
  		"zonegroups": []any{
  			map[string]any{
  				... // 3 identical entries
  				"hostnames":           []any{},
  				"hostnames_s3website": []any{},
  				"id": strings.Join({
- 					"85860956-bc7c-4bd4-921b-2ad3475e4e3c",
+ 					"df48d9ce-deb2-4b92-947d-975da84bffda",
  				}, ""),
  				"is_master": string("true"),
  				"master_zone": strings.Join({
- 					"62eb0482-4bdd-43ff-b3be-f22390f7e4a3",
+ 					"a2a7cc4d-df0c-4f5b-965c-e7cd23b702a1",
  				}, ""),
  				"name":              string("ceph-objectstore"),
  				"placement_targets": []any{map[string]any{"name": string("default-placement"), "storage_classes": []any{string("STANDARD")}, "tags": []any{}}},
  				"realm_id":          string("c9e2e922-7657-4194-9181-a2fb4fa0711a"),
  				"sync_policy":       map[string]any{"groups": []any{}},
  				"zones": []any{
  					map[string]any{
  						"bucket_index_max_shards": float64(11),
  						"endpoints":               []any{string("http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80")},
  						"id": strings.Join({
- 							"62eb0482-4bdd-43ff-b3be-f22390f7e4a3",
+ 							"a2a7cc4d-df0c-4f5b-965c-e7cd23b702a1",
  						}, ""),
  						"log_data": string("false"),
  						"log_meta": string("false"),
  						... // 6 identical entries
  					},
  				},
  			},
  		},
  	},
  	... // 2 ignored and 3 identical entries
2023-08-28 17:53:02.152330 I | ceph-object-controller: committing changes to RGW configuration period for CephObjectStore "rook-ceph/ceph-objectstore"
2023-08-28 17:53:02.152339 D | exec: Running command: radosgw-admin period update --commit --rgw-realm=ceph-objectstore --rgw-zonegroup=ceph-objectstore --rgw-zone=ceph-objectstore --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
  }

```

Do you have any idea while it is failing just by identifying the diff of the objects to be committed?
Is there any other place where I can see the logs produced internally by executing those commands ?

Any help will be grateful, Thanks

**Comment by ausias-armesto** [comment] 2023-08-29 06:03
It looks like there is some kind of data corrupted somewhere as I created a new `CephObjectStore` with different name and it worked smoothly. 
I did another test:
- Remove failing CephObjectStore
- Remove all the pools of the CephObjectStore
- Create the CephObjectStore with the same name 
- Did not work, with the same error above mentioned

**Comment by travisn** [comment] 2023-08-30 21:56
When you deleted the pools, you deleted even the `.rgw.root` pool? That pool seems likely to be persisting this issue if you see it when re-creating. But if you even deleted that pool, not sure where the issue is. Good to hear you at least have a workaround to create the store with a different name.

**Comment by ausias-armesto** [comment] 2023-08-31 11:34
No, I didn't delete that pool. Just deleted the pools containing the pattern of the object store name.

**Comment by travisn** [comment] 2023-08-31 17:51
Ok at least we understand why the issue persistent. If you had any other object stores, it definitely would not be desired to delete the .rgw.root pool though.

**Closed by travisn** 2023-08-31 17:51 UTC
Labels: bug
