### ISSUE TITLE
cephfsplugin-provisioner-0 goes to CrashLoopBackOff when many PVC are created with csi-cephfs storageclass

### ISSUE THREAD

**Issue by ekuric** [rook/rook#3381] opened 2019-07-02 15:41 UTC
**Is this a bug report or feature request?**
* Bug Report
Only visible with `csi-cephfs` storageclass

Issue not visible if same test is executed with `csi-rbd` storageclass.

**Deviation from expected behavior:**
PVC are not created and `cephfsplugin-provisioner-0` pod goes in `CrashLoopBackOff` status
**Expected behavior:**
PVC to get created 

**How to reproduce it (minimal and precise):**

Testing to create 900 Pods/PVC on top of `csi-cephfs` storageclass and it leads to `csi-cephfsplugin-provisioner-0` pod to to in `CrashLoopBackOff` state. 

Logs for `csi-provisioner` and `csi-cephfsplugin` when this happen are 

[csi-cephfsplugin ](https://gist.github.com/ekuric/957f6eb4e7470aa767e6005f02120081)
[csi-provisioner](https://gist.github.com/ekuric/283b26bcc4d4edec21204e444692d139)

**Environment**: 
* OS (e.g. from /etc/os-release):

* Kernel (e.g. `uname -a`):
`
* Cloud provider or hardware configuration:
OCP v4.2 aws installation
 
* Rook version (use `rook version` inside of a Rook Pod):
`rook version
 rook: v1.0.0-159.gd1de0d8`

* Kubernetes version (use `kubectl version`):
`
kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+dafd0c6", GitCommit:"dafd0c6", GitTreeState:"clean", BuildDate:"2019-04-10T03:10:23Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+81fc896", GitCommit:"81fc896", GitTreeState:"clean", BuildDate:"2019-04-21T23:18:54Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`OpenShift`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
`
$ ceph -s 
  cluster:
    id:     f59ba1d2-20d0-4e7b-84b3-5ada343e89d3
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 8h)
    mgr: a(active, since 8h)
    mds: myfs:1 {0=myfs-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 8h), 3 in (since 8h)
 
  data:
    pools:   3 pools, 300 pgs
    objects: 1.07k objects, 11 MiB
    usage:   3.0 GiB used, 2.9 TiB / 2.9 TiB avail
    pgs:     300 active+clean
 
  io:
    client:   2.9 KiB/s rd, 3 op/s rd, 0 op/s wr
 
sh-4.2$ ceph versions
{
    "mon": {
        "ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)": 3
    },
    "mgr": {
        "ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)": 1
    },
    "osd": {
        "ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)": 3
    },
    "mds": {
        "ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)": 2
    },
    "overall": {
        "ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)": 9
    }
}
`

**Comment by ShyamsundarR** [comment] 2019-07-02 20:03
The crash messages from the logs look as below,
```
E0702 10:53:02.584003       1 controllerserver.go:88] validation and extraction of volume options failed: an error occurred while running (5446) ceph [-m 172.30.75.105:6789,172.30.11.77:6789,172.30.37.56:6789 --id admin --key=***stripped*** -c /etc/ceph/ceph.conf fs get myfs --format=json]: exit status 1: can't start new thread
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1266, in <module>
    run_in_thread(cluster_handle.shutdown)
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1310, in run_in_thread
    t.start()
  File "/usr/lib64/python2.7/threading.py", line 747, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
E0702 10:53:02.584135       1 utils.go:109] GRPC error: rpc error: code = InvalidArgument desc = an error occurred while running (5446) ceph [-m 172.30.75.105:6789,172.30.11.77:6789,172.30.37.56:6789 --id admin --key=***stripped*** -c /etc/ceph/ceph.conf fs get myfs --format=json]: exit status 1: can't start new thread
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1266, in <module>
    run_in_thread(cluster_handle.shutdown)
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1310, in run_in_thread
    t.start()
  File "/usr/lib64/python2.7/threading.py", line 747, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
I0702 10:53:02.593234       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0702 10:53:02.593354       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-b88e14a2-9ca8-11e9-8a85-022a2db783fc","parameters":{"clusterID":"rook-ceph","fsName":"myfs","pool":"myfs-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["noexec"]}},"access_mode":{"mode":1}}]}
I0702 10:53:02.596258       1 util.go:49] cephfs: EXEC ceph [-m 172.30.75.105:6789,172.30.11.77:6789,172.30.37.56:6789 --id admin --key=***stripped*** -c /etc/ceph/ceph.conf fs get myfs --format=json]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10e2d53]

goroutine 620 [running]:
github.com/ceph/ceph-csi/pkg/cephfs.execCommand(0x1381547, 0x4, 0xc000d237f0, 0xb, 0xb, 0x2f, 0xc000d23750, 0x444db7, 0xc0003cf8f6, 0xc000627800, ...)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/pkg/cephfs/util.go:53 +0x283
github.com/ceph/ceph-csi/pkg/cephfs.execCommandJSON(0x1171ba0, 0xc000347540, 0x1381547, 0x4, 0xc000d237f0, 0xb, 0xb, 0x6, 0xc000d23810)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/pkg/cephfs/util.go:66 +0x77
github.com/ceph/ceph-csi/pkg/cephfs.getFscID(0xc0004f8dc0, 0x36, 0xc000347520, 0xc0004701fc, 0x4, 0xc000347520, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/pkg/cephfs/cephfs_util.go:40 +0x15d
github.com/ceph/ceph-csi/pkg/cephfs.newVolumeOptions(0xc000626120, 0x28, 0x40000000, 0xc00068e840, 0xc00068e870, 0x1, 0x179, 0x0)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/pkg/cephfs/volumeoptions.go:157 +0x217
github.com/ceph/ceph-csi/pkg/cephfs.(*ControllerServer).CreateVolume(0xc0003d2020, 0x1574580, 0xc00068e780, 0xc000664150, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/pkg/cephfs/controllerserver.go:85 +0x1b6
github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1(0x1574580, 0xc00068e780, 0x1321860, 0xc000664150, 0xc000d23b18, 0x1, 0x1, 0x0)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:4947 +0x86
github.com/ceph/ceph-csi/pkg/csi-common.logGRPC(0x1574580, 0xc00068e780, 0x1321860, 0xc000664150, 0xc0003d2760, 0xc0003d2780, 0xc000c7cba8, 0x51c20a, 0x12ccf40, 0xc00068e780)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/pkg/csi-common/utils.go:107 +0x158
github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler(0x1321700, 0xc0003d2020, 0x1574580, 0xc00068e780, 0xc000096d20, 0x1415fd8, 0x1574580, 0xc00068e780, 0xc000d48000, 0xcd)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:4949 +0x158
github.com/ceph/ceph-csi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002aa900, 0x158d3c0, 0xc0002f2480, 0xc000618400, 0xc00037b5c0, 0x20e80c0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:998 +0x470
github.com/ceph/ceph-csi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0002aa900, 0x158d3c0, 0xc0002f2480, 0xc000618400, 0x0)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1278 +0xda6
github.com/ceph/ceph-csi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000470030, 0xc0002aa900, 0x158d3c0, 0xc0002f2480, 0xc000618400)
	/home/travis/gopath/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:717 +0x9f
created by github.com/ceph/ceph-csi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
/home/travis/gopath/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:715 +0xa1
```

It looks like python is unable to start a new thread is one of the problems, but subsequently the cephfs plugin also crashed in a go routine.

Still need to debug this to its root cause, but current thoughts is around  some resource leak or resource starvation on these pods causing it to not have enough resources available.

**Comment by galexrt** [comment] 2019-07-02 20:28
I think this seems to be like the same problem as Rook operator has when many RBD volumes are created and / or deleted.
The operator in that case runs out of resources (memory if I remember correctly) and / or number of files allowed to open.

Having a (configurable) rate limit in the Ceph CSI provision driver sounds like a good idea to prevent this, if the issue is the same.

**Comment by Madhu-1** [comment] 2019-07-03 03:48
@travisn can you transfer this issue to the ceph-csi repo?

**Comment by travisn** [comment] 2019-07-03 05:11
@Madhu-1 We can't transfer the issue directly, so feel free to open one there and then we can close this one. Thanks.

**Comment by Madhu-1** [comment] 2019-07-03 05:22
@ekuric @travisn created an issue in ceph-csi https://github.com/ceph/ceph-csi/issues/455

**Closed** 2019-07-04 12:33 UTC
Labels: bug
