### ISSUE TITLE
gofmt failure, with Go 1.16 (Aarch64) + patching, on behalf of go-reflect package

### ISSUE THREAD

**Issue by advancedwebdeveloper** [rook/rook#7364] opened 2021-03-07 23:00 UTC
[rook_go-reflect.diff.zip](https://github.com/rook/rook/files/6098117/rook_go-reflect.diff.zip)

**Comment by advancedwebdeveloper** [comment] 2021-03-07 23:01
[unit-tests.zip](https://github.com/rook/rook/files/6098119/unit-tests.zip)

**Comment by advancedwebdeveloper** [comment] 2021-03-08 00:10
Hi.
I am using Go 1.16 on an Aarch64 server.

> oceanfish81@ams1-c2:~/rook$ make    
> === helm package rook-ceph
> ==> Linting /home/oceanfish81/rook/_output/rook-ceph
> 1 chart(s) linted, 0 chart(s) failed
> Successfully packaged chart and saved it to: /home/oceanfish81/rook/_output/charts/rook-ceph-v1.5.0-alpha.0.590.g2a192300e-dirty.tgz
> === helm index
> === ensuring modules are tidied
> === go vet
> diff -u pkg/daemon/ceph/client/pool_test.go.orig pkg/daemon/ceph/client/pool_test.go
> --- pkg/daemon/ceph/client/pool_test.go.orig	2021-03-07 22:50:25.081808943 +0000
> +++ pkg/daemon/ceph/client/pool_test.go	2021-03-07 22:50:25.081808943 +0000
> @@ -16,8 +16,8 @@
>  package client
>  import (
> -	"os/exec"
>  	reflect "github.com/goccy/go-reflect"
> +	"os/exec"
>  	"strconv"
>  	"testing"
> diff -u pkg/operator/cassandra/sidecar/sidecar.go.orig pkg/operator/cassandra/sidecar/sidecar.go
> --- pkg/operator/cassandra/sidecar/sidecar.go.orig	2021-03-07 22:50:25.261806937 +0000
> +++ pkg/operator/cassandra/sidecar/sidecar.go	2021-03-07 22:50:25.261806937 +0000
> @@ -19,10 +19,10 @@
>  import (
>  	"context"
>  	"fmt"
> +	reflect "github.com/goccy/go-reflect"
>  	"net/url"
>  	"os"
>  	"os/exec"
> -	reflect "github.com/goccy/go-reflect"
>  	"time"
>  	"github.com/coreos/pkg/capnslog"
> diff -u pkg/operator/ceph/cluster/mon/health_test.go.orig pkg/operator/ceph/cluster/mon/health_test.go
> --- pkg/operator/ceph/cluster/mon/health_test.go.orig	2021-03-07 22:50:25.401805376 +0000
> +++ pkg/operator/ceph/cluster/mon/health_test.go	2021-03-07 22:50:25.401805376 +0000
> @@ -19,9 +19,9 @@
>  import (
>  	"context"
>  	"fmt"
> +	reflect "github.com/goccy/go-reflect"
>  	"io/ioutil"
>  	"os"
> -	reflect "github.com/goccy/go-reflect"
>  	"sync"
>  	"testing"
>  	"time"
> diff -u pkg/operator/ceph/cluster/mon/mon_test.go.orig pkg/operator/ceph/cluster/mon/mon_test.go
> --- pkg/operator/ceph/cluster/mon/mon_test.go.orig	2021-03-07 22:50:25.445804886 +0000
> +++ pkg/operator/ceph/cluster/mon/mon_test.go	2021-03-07 22:50:25.445804886 +0000
> @@ -19,10 +19,10 @@
>  import (
>  	"context"
>  	"fmt"
> +	reflect "github.com/goccy/go-reflect"
>  	"io/ioutil"
>  	"os"
>  	"path"
> -	reflect "github.com/goccy/go-reflect"
>  	"strconv"
>  	"strings"
>  	"sync"
> diff -u pkg/operator/ceph/cluster/operator_watchers.go.orig pkg/operator/ceph/cluster/operator_watchers.go
> --- pkg/operator/ceph/cluster/operator_watchers.go.orig	2021-03-07 22:50:25.477804529 +0000
> +++ pkg/operator/ceph/cluster/operator_watchers.go	2021-03-07 22:50:25.477804529 +0000
> @@ -18,8 +18,8 @@
>  package cluster
>  import (
> -	"os"
>  	reflect "github.com/goccy/go-reflect"
> +	"os"
>  	opcontroller "github.com/rook/rook/pkg/operator/ceph/controller"
>  	"github.com/rook/rook/pkg/operator/k8sutil"
> diff -u pkg/operator/ceph/file/filesystem_test.go.orig pkg/operator/ceph/file/filesystem_test.go
> --- pkg/operator/ceph/file/filesystem_test.go.orig	2021-03-07 22:50:25.797800962 +0000
> +++ pkg/operator/ceph/file/filesystem_test.go	2021-03-07 22:50:25.797800962 +0000
> @@ -20,10 +20,10 @@
>  	"context"
>  	"errors"
>  	"fmt"
> +	reflect "github.com/goccy/go-reflect"
>  	"io/ioutil"
>  	"os"
>  	"path"
> -	reflect "github.com/goccy/go-reflect"
>  	"strings"
>  	"testing"
> diff -u pkg/operator/nfs/controller_test.go.orig pkg/operator/nfs/controller_test.go
> --- pkg/operator/nfs/controller_test.go.orig	2021-03-07 22:50:26.173796770 +0000
> +++ pkg/operator/nfs/controller_test.go	2021-03-07 22:50:26.173796770 +0000
> @@ -18,8 +18,8 @@
>  import (
>  	"context"
> -	"path"
>  	reflect "github.com/goccy/go-reflect"
> +	"path"
>  	"testing"
>  	nfsv1alpha1 "github.com/rook/rook/pkg/apis/nfs.rook.io/v1alpha1"
> diff -u pkg/operator/nfs/provisioner_test.go.orig pkg/operator/nfs/provisioner_test.go
> --- pkg/operator/nfs/provisioner_test.go.orig	2021-03-07 22:50:26.201796458 +0000
> +++ pkg/operator/nfs/provisioner_test.go	2021-03-07 22:50:26.201796458 +0000
> @@ -18,8 +18,8 @@
>  import (
>  	"context"
> -	"os"
>  	reflect "github.com/goccy/go-reflect"
> +	"os"
>  	"testing"
>  	rookclient "github.com/rook/rook/pkg/client/clientset/versioned"
> make[1]: *** [build/makelib/golang.mk:160: go.fmt] Error 1
> make: *** [Makefile:100: build.common] Error 2

**Comment by travisn** [comment] 2021-03-08 21:15
@advancedwebdeveloper I didn't see any issues with `go vet` when building with 1.16. PR #7371 is opened with the changes that I made to enable it. Could there potentially be something else in your enlistment with your local changes causing that issue?

**Comment by advancedwebdeveloper** [comment] 2021-03-08 23:31
> @advancedwebdeveloper I didn't see any issues with `go vet` when building with 1.16.

Well, the original source code (**before** I have patched anything), from a cloned master branch, allowed to build Rook (using minikube, minikube, k8s) and run some unit, integration tests.
So yes - I can try to reproduce all the steps, for the original source code, to see where I could find any problems.
Hence that not all tests where successful - so something could be missconfigured.


>  PR #7371 is opened with the changes that I made to enable it. 

Well done, @travisn .

> Could there potentially be something else in your enlistment with your local changes causing that issue?

I am super sure that it actually is something is not logged, for the Makefile.
It would assume patching the Makefile (perhaps you would assume using other build systems?):

> https://github.com/rook/rook/blob/e320c31cc97930fedf4bac15011c04022f6e0a2d/build/makelib/golang.mk#L81

That is badly written and very uncertain.
I do not see any executable, which is named different then "gofmt"

**Comment by travisn** [comment] 2021-03-09 18:02
If you modify the previous line to use gofmt 1.16, does it fix the issue? We should really use the same version for gofmt as the build, I don't think it was intentional to use a different version.

**Comment by advancedwebdeveloper** [comment] 2021-03-09 18:04
OK,
I see that this is about debugging a Makefile.

What would you like me to trace?
Please specify how could I collect some logs.

**Comment by travisn** [comment] 2021-03-09 18:06
If you change [this line](https://github.com/rook/rook/blob/e320c31cc97930fedf4bac15011c04022f6e0a2d/build/makelib/golang.mk#L77) to 1.16, does it help?

**Comment by advancedwebdeveloper** [comment] 2021-03-09 18:12
Change to which value?

**Comment by travisn** [comment] 2021-03-09 18:18
`GOFMT_VERSION := 1.16`

**Comment by advancedwebdeveloper** [comment] 2021-03-09 23:07
[rook_make_debug.log](https://github.com/rook/rook/files/6111917/rook_make_debug.log)
[rook_make_var.log](https://github.com/rook/rook/files/6111919/rook_make_var.log)

Not rely.

**Comment by advancedwebdeveloper** [comment] 2021-03-10 19:35
Give me an hour - I shall re-check.

**Comment by advancedwebdeveloper** [comment] 2021-03-10 23:08
I could build, run unit and some integration tests with such a patch:

> diff --git a/build/makelib/golang.mk b/build/makelib/golang.mk
> index 28c05b7ed..088081b3d 100644
> --- a/build/makelib/golang.mk
> +++ b/build/makelib/golang.mk
> @@ -48,7 +48,7 @@ GO_TEST_FLAGS ?=
>  # ====================================================================================
>  # Setup go environment
>  
> -GO_SUPPORTED_VERSIONS ?= 1.15
> +GO_SUPPORTED_VERSIONS ?= 1.16
>  
>  GO_PACKAGES := $(foreach t,$(GO_SUBDIRS),$(GO_PROJECT)/$(t)/...)
>  GO_INTEGRATION_TEST_PACKAGES := $(foreach t,$(GO_INTEGRATION_TESTS_SUBDIRS),$(GO_PROJECT)/$(t)/integration)
> @@ -74,7 +74,7 @@ GO_FULL_VERSION := $(shell $(GO) version)
>  
>  # we use a consistent version of gofmt even while running different go compilers.
>  # see https://github.com/golang/go/issues/26397 for more details
> -GOFMT_VERSION := 1.11
> +GOFMT_VERSION := 1.16
>  ifneq ($(findstring $(GOFMT_VERSION),$(GO_VERSION)),)
>  GOFMT := $(shell which gofmt)
>  else
> diff --git a/go.mod b/go.mod
> index 7709efbc4..f82defef6 100644
>

**Comment by advancedwebdeveloper** [comment] 2021-03-10 23:12
It might sound stupid but: perhaps I have patched source code.

I shall add few patched files (hence the original diff - it contains various modifications) and see whether gofmt would crash.

**Comment by advancedwebdeveloper** [comment] 2021-03-10 23:19
It builds with a small patch:

> diff --git a/build/makelib/golang.mk b/build/makelib/golang.mk
> index 28c05b7ed..088081b3d 100644
> --- a/build/makelib/golang.mk
> +++ b/build/makelib/golang.mk
> @@ -48,7 +48,7 @@ GO_TEST_FLAGS ?=
>  # ====================================================================================
>  # Setup go environment
>  
> -GO_SUPPORTED_VERSIONS ?= 1.15
> +GO_SUPPORTED_VERSIONS ?= 1.16
>  
>  GO_PACKAGES := $(foreach t,$(GO_SUBDIRS),$(GO_PROJECT)/$(t)/...)
>  GO_INTEGRATION_TEST_PACKAGES := $(foreach t,$(GO_INTEGRATION_TESTS_SUBDIRS),$(GO_PROJECT)/$(t)/integration)
> @@ -74,7 +74,7 @@ GO_FULL_VERSION := $(shell $(GO) version)
>  
>  # we use a consistent version of gofmt even while running different go compilers.
>  # see https://github.com/golang/go/issues/26397 for more details
> -GOFMT_VERSION := 1.11
> +GOFMT_VERSION := 1.16
>  ifneq ($(findstring $(GOFMT_VERSION),$(GO_VERSION)),)
>  GOFMT := $(shell which gofmt)
>  else
> diff --git a/go.mod b/go.mod
> index 7709efbc4..a114100b7 100644
> --- a/go.mod
> +++ b/go.mod
> @@ -11,6 +11,7 @@ require (
>         github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
>         github.com/go-ini/ini v1.51.1
>         github.com/go-sql-driver/mysql v1.5.0
> +       github.com/goccy/go-reflect v1.1.0
>         github.com/google/go-cmp v0.5.2
>         github.com/google/uuid v1.1.2
>         github.com/hashicorp/vault/api v1.0.5-0.20200902155336-f9d5ce5a171a
> diff --git a/go.sum b/go.sum
> index 6f03c6f57..40d38bf96 100644
> --- a/go.sum
> +++ b/go.sum
>

**Comment by advancedwebdeveloper** [comment] 2021-03-10 23:47
[transactional_diff4rook.log](https://github.com/rook/rook/files/6119453/transactional_diff4rook.log)

Adding some more modifications - and still able to build

**Comment by advancedwebdeveloper** [comment] 2021-03-10 23:50
Aha! I think I found something:

> oceanfish81@ams1-c2:~/rook$ make
> === helm package rook-ceph
> ==> Linting /home/oceanfish81/rook/_output/rook-ceph
> 
> 1 chart(s) linted, 0 chart(s) failed
> Successfully packaged chart and saved it to: /home/oceanfish81/rook/_output/charts/rook-ceph-v1.5.0-alpha.0.623.gc0eacc89d-dirty.tgz
> === helm index
> === ensuring modules are tidied
> === go vet
> diff -u pkg/daemon/ceph/client/pool_test.go.orig pkg/daemon/ceph/client/pool_test.go
> --- pkg/daemon/ceph/client/pool_test.go.orig	2021-03-10 23:49:11.399329184 +0000
> +++ pkg/daemon/ceph/client/pool_test.go	2021-03-10 23:49:11.399329184 +0000
> @@ -16,8 +16,8 @@
>  package client
>  
>  import (
> -	"os/exec"
>  	reflect "github.com/goccy/go-reflect"
> +	"os/exec"
>  	"strconv"
>  	"testing"
>  
> make[1]: *** [build/makelib/golang.mk:160: go.fmt] Error 1
> make: *** [Makefile:100: build.common] Error 2
> 

[transactional2_diff4rook.log](https://github.com/rook/rook/files/6119492/transactional2_diff4rook.log)

**Comment by parth-gr** [comment] 2021-03-12 07:59
Hy @advancedwebdeveloper , I faced the same bug before while building the `Ceph` image.

The issue is caused because of not **proper formatting** up the Go code while doing the changes.
Try building image with **no changes** then you will have **no errors**.

If your adding changes to it try to format your Go file  correctly by saving file with `**Ctrl+ s**` and deleting any auto save plugin if added.

Looking at your errors:
ex:`diff -u pkg/daemon/ceph/client/pool_test.go.orig pkg/daemon/ceph/client/pool_test.go`
So inside **pool_test.go** 

Trying importing like this:
``` 
import (
	"os/exec"
	"strconv"
	"testing"

	reflect "github.com/goccy/go-reflect"

	"github.com/pkg/errors"
	cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	rookv1 "github.com/rook/rook/pkg/apis/rook.io/v1"
	exectest "github.com/rook/rook/pkg/util/exec/test"
	"github.com/stretchr/testify/assert"

	"github.com/rook/rook/pkg/clusterd"
)
```
Hope this solves your issue.

**Comment by subhamkrai** [comment] 2021-03-12 08:33
> Hy @advancedwebdeveloper , I faced the same bug before while building the `Ceph` image.
> 
> The issue is caused because of not **proper formatting** up the Go code while doing the changes.
> Try building image with **no changes** then you will have **no errors**.
> 
> If your adding changes to it try to format your Go file correctly by saving file with `**Ctrl+ s**` in vs code.
> Looking at your errors:
> ex:`diff -u pkg/daemon/ceph/client/pool_test.go.orig pkg/daemon/ceph/client/pool_test.go`
> So inside **pool_test.go**
> 
> Try importing like this:
> 
> ```
> import (
> 	"os/exec"
> 	"strconv"
> 	"testing"
> 
> 	reflect "github.com/goccy/go-reflect"
> 
> 	"github.com/pkg/errors"
> 	cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
> 	rookv1 "github.com/rook/rook/pkg/apis/rook.io/v1"
> 	exectest "github.com/rook/rook/pkg/util/exec/test"
> 	"github.com/stretchr/testify/assert"
> 
> 	"github.com/rook/rook/pkg/clusterd"
> )
> ```
> 
> Hope this solves your issue.


And, also some time mixing `space` with `tab` can cause this error too.

**Comment by advancedwebdeveloper** [comment] 2021-03-12 10:46
> Hy @advancedwebdeveloper , I faced the same bug before while building the `Ceph` image.
> 
> The issue is caused because of not **proper formatting** up the Go code while doing the changes.
> Try building image with **no changes** then you will have **no errors**.
> 
> If your adding changes to it try to format your Go file correctly by saving file with `**Ctrl+ s**` in vs code.
> Looking at your errors:
> ex:`diff -u pkg/daemon/ceph/client/pool_test.go.orig pkg/daemon/ceph/client/pool_test.go`
> So inside **pool_test.go**
> 
> Try importing like this:
> 
> ```
> import (
> 	"os/exec"
> 	"strconv"
> 	"testing"
> 
> 	reflect "github.com/goccy/go-reflect"
> 
> 	"github.com/pkg/errors"
> 	cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
> 	rookv1 "github.com/rook/rook/pkg/apis/rook.io/v1"
> 	exectest "github.com/rook/rook/pkg/util/exec/test"
> 	"github.com/stretchr/testify/assert"
> 
> 	"github.com/rook/rook/pkg/clusterd"
> )
> ```
> 
> Hope this solves your issue.

It did not help:

> === go vet
> diff -u pkg/daemon/ceph/client/pool_test.go.orig pkg/daemon/ceph/client/pool_test.go
> --- pkg/daemon/ceph/client/pool_test.go.orig    2021-03-12 10:38:21.223467677 +0000
> +++ pkg/daemon/ceph/client/pool_test.go 2021-03-12 10:38:21.223467677 +0000
> @@ -16,19 +16,19 @@
>  package client
> 
>  import (
> -    "os/exec"
> -    "strconv"
> -    "testing"
> +       "os/exec"
> +       "strconv"
> +       "testing"
> 
> -    reflect "github.com/goccy/go-reflect"
> +       reflect "github.com/goccy/go-reflect"
> 
> -    "github.com/pkg/errors"
> -    cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
> -    rookv1 "github.com/rook/rook/pkg/apis/rook.io/v1"
> -    exectest "github.com/rook/rook/pkg/util/exec/test"
> -    "github.com/stretchr/testify/assert"
> +       "github.com/pkg/errors"
> +       cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
> +       rookv1 "github.com/rook/rook/pkg/apis/rook.io/v1"
> +       exectest "github.com/rook/rook/pkg/util/exec/test"
> +       "github.com/stretchr/testify/assert"
> 
> -    "github.com/rook/rook/pkg/clusterd"
> +       "github.com/rook/rook/pkg/clusterd"
>  )
> 
>  func TestCreateECPoolWithOverwrites(t *testing.T) {
> make[1]: *** [build/makelib/golang.mk:160: go.fmt] Error 1
> make: *** [Makefile:100: build.common] Error 2

@ianlancetaylor, perhaps a patch for gofmt would help?

**Comment by ianlancetaylor** [comment] 2021-03-12 16:35
I don't know what the problem is.  It's extremely unlikely that this will be fixed by a patch to gofmt.  It's much more likely that there is some sort of version discrepancy.

**Comment by advancedwebdeveloper** [comment] 2021-03-12 23:36
How could I track it down?

**Comment by advancedwebdeveloper** [comment] 2021-03-13 23:29
@ianlancetaylor , I had to use [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) tool - and it allowed to get rid of the error, eventually.
Had to apply to each previously patched Go source file, with -w option.

Here is my latest summary:

[rook_go-reflect.zip](https://github.com/rook/rook/files/6135778/rook_go-reflect.zip)
(contains the .diff file)
.
Here are compressed source folder and compressed resulting(dist.) folders:
https://drive.google.com/file/d/18osXXr0KJnoSv4lwoIjLLryHueEva0XK/view?usp=sharing
https://drive.google.com/file/d/1HVa67874y23tX2yIsfbxJxdWgx47Hy9l/view?usp=sharing
.

How could I benchmark those reflection functional calls?

@subhamkrai , @parth-gr , @travisn : could these resulting build of Rook be benchmarked, as a product, on your side?
Despite I have an access to servers - I doubt that I could arrange 3 nodes, for a cluster (like for Ceph).

**Comment by travisn** [comment] 2021-03-15 18:28
You'll want to use `goimports` to help auto-format and avoid the errors. 

What's the request? If you need feedback on some changes, please open a PR so we can easily see the diff, then no need to attach the source here.

**Comment by advancedwebdeveloper** [comment] 2021-03-16 18:20
Opened https://github.com/rook/rook/issues/7424

**Closed** 2021-04-13 13:33 UTC
Labels: bug
