### ISSUE TITLE
Create a boolean configuration setting to disable CRUSH rule changes for existing pools

### ISSUE THREAD

**Issue by mohitrajain** [rook/rook#13854] opened 2024-03-04 10:15 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
In v1.12.8, a feature was released to update the pool deviceClass: 
[pool: allow updating deviceClass on existing pool](https://github.com/rook/rook/pull/13069).

This feature request proposes an additional flag that allows administrators to opt for the proposed changes from the aforementioned change. Optionally, it could log the recommended state changes for pools upon each evaluation, providing insights into required adjustments. Our clusters are dynamic, with deviceClasses added at later stages. Since the aforementioned feature was not available previously, manual adjustments were made. We aim to avoid disrupting the production cluster by preventing re-mapping of objects due to new crush rules.

**What is use case behind this feature:**
After updating our staging Rook cluster to v1.12.8, which had undergone manual pool modifications in the past, we encountered some unexpected changes:

```
2024-03-01 11:20:10.879837 I | cephclient: creating a new crush rule for changed deviceClass on crush rule "rbd-hdd-new"
2024-03-01 11:20:10.879851 I | cephclient: updating pool ".mgr" failure domain from "host" to "host" with new crush rule ".mgr_host_hdd"
2024-03-01 11:20:10.879855 I | cephclient: crush rule "rbd-hdd-new" will no longer be used by pool ".mgr"
- A new rule was created even though the hdd deviceClass was specified, due to the bug fix detailed [here](https://github.com/rook/rook/pull/13772 )
---
2024-03-01 11:20:56.454723 I | cephclient: creating a new crush rule for changed deviceClass on crush rule "rbd-ssd-new"
2024-03-01 11:20:56.454740 I | cephclient: updating pool "rbd-ssd" failure domain from "host" to "host" with new crush rule "rbd-ssd_host_ssd"
2024-03-01 11:20:56.454744 I | cephclient: crush rule "rbd-ssd-new" will no longer be used by pool "rbd-ssd"
- A new rule was created even though the hdd deviceClass was specified, due to the bug fix detailed [here](https://github.com/rook/rook/pull/13772)
---
2024-03-01 11:20:28.973957 I | cephclient: creating a new crush rule for changed deviceClass on crush rule "rbd-hdd-new"
2024-03-01 11:20:28.973972 I | cephclient: updating pool "rbd-hdd" failure domain from "host" to "host" with new crush rule "rbd-hdd_host"
2024-03-01 11:20:28.973976 I | cephclient: crush rule "rbd-hdd-new" will no longer be used by pool "rbd-hdd"
- A new rule got created because no deviceClass was mentioned but they were initially set to HDD class manually and it switched to default deviceClass i.e. mix of both
--- other logs have been omitted 
```

The message described above was observed for all the pools in our cluster. Initially, we had omitted specifying the device class for some pools, which subsequently were affected, as indicated by the logs. 

The above crush rule changes led to data being re-mapped across the cluster. It's noteworthy that this issue has been addressed in version [1.13.5](https://github.com/rook/rook/pull/13772) with the implementation of "pool: Skip crush rule update when not needed."

We aim to mitigate any unintended effects on existing pools without a comprehensive understanding of the implications on crush rules. Implementing logging and a toggle flag would facilitate more informed decisions.

**Environment**:
Mix device class environment. 

![image](https://github.com/rook/rook/assets/20745774/f3f458b5-a980-4a4f-bd9a-5c4242dea0b1)

**Comment by subhamkrai** [comment] 2024-03-04 11:20
@mohitrajain Since the issue is fixed in the latest version as you mentioned, so why not upgrade to the fixed version?

**Comment by mohitrajain** [comment] 2024-03-04 11:42
@subhamkrai We need to evaluate the new version in our staging cluster. However, before applying changes to the production cluster, having this feature would be beneficial. It would enable us to preserve manual adjustments on specific pools.

**Comment by travisn** [comment] 2024-03-04 18:26
@anthonyeleven So you're hitting this issue in v1.12.8, and you would prefer to get the fix in a v1.12.x release before you upgrade to v1.13? We could likely backport #13772 to v1.12 and make that happen.

**Comment by anthonyeleven** [comment] 2024-03-04 18:54
No, not asking for a backport.  The 1.13.x fix should suffice if we can skip 1.12.8.  The cluster where this matters for us currently runs Rook v1.10.5.  Can we go straight to 1.13.x from this release?

The RFE to completely disable modifying existing pools is intended to forestall any future rude awakenings when new functionality is added.

**Comment by travisn** [comment] 2024-03-04 18:58
in the [upgrade guide](https://rook.github.io/docs/rook/v1.13/Upgrade/rook-upgrade/) it is recommended not to skip minor rook releases. It might work, but I'd recommend testing the upgrade yourself. Our testing does not cover skipping minor releases. Instead, you might consider: v1.10.5 --> v1.11.x --> v1.12.7 --> v1.13.x

**Comment by anthonyeleven** [comment] 2024-03-04 19:02
We're testing upgrades in a small lab cluster, but there's only so closely we can align that to prod.  `v1.10.5 --> v1.11.x --> v1.12.7 --> v1.13.x` should be feasible for us.

**Comment by BlaineEXE** [comment] 2024-06-11 15:47
We discussed this in huddle today and are considering the implementation.

**Closed** 2024-06-17 18:20 UTC
Labels: feature
