### ISSUE TITLE
rook-block PVs stay pending after upate to k8s 1.14.1

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3142] opened 2019-05-08 19:10 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Provisioned rook-block PV's stay pending

**Expected behavior:**
Those become available after being provisioned

**How to reproduce it (minimal and precise):**
Create PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dimm-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: rook-block
```

See it stay pending.

Logs:
```
I0508 18:58:34.445458       6 controller.go:1196] provision "wifire/dimm-test2" class "rook-block": started
2019-05-08 18:58:34.454791 I | op-provisioner: creating volume with configuration {blockPool:rbd clusterNamespace:rook fstype:xfs dataBlockPool:}
2019-05-08 18:58:34.454809 I | exec: Running command: rbd create rbd/pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994 --size 10 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring
I0508 18:58:34.454914       6 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test2", UID:"45fb5437-71c3-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335546514", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "wifire/dimm-test2"
2019-05-08 18:58:34.855436 I | op-provisioner: Rook block image created: pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994, size = 10000000
2019-05-08 18:58:34.855473 I | op-provisioner: successfully created Rook Block volume &FlexPersistentVolumeSource{Driver:rook.io/rook-system,FSType:xfs,SecretRef:nil,ReadOnly:false,Options:map[string]string{clusterNamespace: rook,dataBlockPool: ,image: pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994,pool: rbd,storageClass: rook-block,},}
I0508 18:58:34.855499       6 controller.go:1303] provision "wifire/dimm-test2" class "rook-block": volume "pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994" provisioned
I0508 18:58:34.855516       6 controller.go:1320] provision "wifire/dimm-test2" class "rook-block": succeeded
I0508 18:58:34.855535       6 volume_store.go:187] Trying to save persistentvolume "pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994"
I0508 18:58:34.861592       6 volume_store.go:194] persistentvolume "pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994" saved
I0508 18:58:34.861649       6 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test2", UID:"45fb5437-71c3-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335546514", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994
```

```
(⎈ |nautilus:wifire)➜  ~ k get pvc
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
dimm-test        Pending                                      rook-block     13m
dimm-test2       Pending                                      rook-block     10m
postgres10-pvc   Pending                                      rook-block     38m
postgres9-pvc    Pending                                      rook-block     44m

(⎈ |nautilus:wifire)➜  ~ k describe pv pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994
Name:            pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: rook.io/block
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    rook-block
Status:          Pending
Claim:           wifire/dimm-test2
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        9Mi
Node Affinity:   <none>
Message:
Source:
    Type:       FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:     rook.io/rook-system
    FSType:     xfs
    SecretRef:  nil
    ReadOnly:   false
    Options:    map[clusterNamespace:rook dataBlockPool: image:pvc-45fb5437-71c3-11e9-84cd-0cc47a6be994 pool:rbd storageClass:rook-block]
Events:         <none>
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.0
* Kubernetes version (use `kubectl version`): 1.14.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm

**Comment by dimm0** [comment] 2019-05-08 19:37
Controller-manager logs are full of:
```
I0508 19:37:05.275465       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test", UID:"de96bc46-71c2-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335542043", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
I0508 19:37:05.276132       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test3", UID:"5f247a60-71c8-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335605876", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
I0508 19:37:20.263153       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test2", UID:"45fb5437-71c3-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335546514", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
I0508 19:37:20.265470       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test", UID:"de96bc46-71c2-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335542043", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "rook.io/block" or manually created by system administrator
I0508 19:37:20.266244       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"wifire", Name:"dimm-test3", UID:"5f247a60-71c8-11e9-84cd-0cc47a6be994", APIVersion:"v1", ResourceVersion:"335605876", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
```

**Comment by dimm0** [comment] 2019-05-08 19:38
Also I found that volumes are not formatted. I formatted one manually, but it's still pending

**Comment by travisn** [comment] 2019-05-08 23:25
From the operator logs reported in slack:
```
I0508 21:41:10.806161       9 controller.go:1196] provision "monitoring/prometheus-stable-grafana" class "rook-ceph-block": started
I0508 21:41:10.809886       9 controller.go:1205] provision "monitoring/prometheus-stable-grafana" class "rook-ceph-block": persistentvolume "pvc-5c2a85c1-719d-11e9-b383-d43d7ee301e3" already exists, skipping
I0508 21:41:10.809886       9 controller.go:1205] provision "monitoring/prometheus-prometheus-stable-promethe-prometheus-db-prometheus-prometheus-stable-promethe-prometheus-0" class "rook-ceph-block": persistentvolume "pvc-64c1ce25-719d-11e9-b383-d43d7ee301e3" already exists, skipping
```

These messages about the PVC already existing come from the external provisioner [here](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/release-1.14/controller/controller.go#L1205). We did update the version of the external provisioner we're using in rook 1.0. It is the same version that is supposed to work with 1.14. Still not clear where the issue is...

**Comment by dimm0** [comment] 2019-05-09 17:08
Any hope to get this looked at today? Appreciate your help

**Comment by travisn** [comment] 2019-05-09 19:42
Can someone running k8s 1.14 confirm that PVCs are working ok for them? If we can find more clues about the repro steps it would help find and verify a fix. 

Time is short while I'm traveling today so if someone else familiar with the provisioner could take a look it would be very helpful. @jbw976? As soon as we find the fix I'd like to get 1.0.1 released with this and a couple other fixes.

**Comment by travisn** [comment] 2019-05-10 16:00
I just created over 100 pvcs in minikube 1.14.1 and they were all bound. Still digging, but if anyone has more repro steps or an environment I can take a closer look at, let me know!

**Comment by dimm0** [comment] 2019-05-10 17:50
Found that it started magically working again at some point, probably after the operator restart (not sure about that). Now PVC's are bound properly.
Closing until can reproduce

**Comment by dimm0** [comment] 2019-05-10 17:59
Another case is still available

**Comment by sandrich** [comment] 2019-05-10 20:19
I had similar issues. I found an error in my PVC declaration. I was using `10G` instead of `10Gi` which seems to cause the issue.

**Comment by travisn** [comment] 2019-05-10 20:21
@dimm0 @sandrich thanks, let's close this for now until we hear if there is another repro

**Closed by travisn** 2019-05-10 20:21 UTC
Labels: bug

**Comment by dimm0** [comment] 2019-05-13 22:54
> I had similar issues. I found an error in my PVC declaration. I was using `10G` instead of `10Gi` which seems to cause the issue.

Same here. The user said he was using "10G" in the previous version fine. Seems like it changed.

**Comment by tvvignesh** [comment] 2020-01-30 11:17
@travisn @dimm0 Hi. I am trying to use Rook with Ceph on GKE (version 1.15.4-gke.22) with Ubuntu-cos image and the PVs stay pending and does not provision the storage.

Using the default `cluster.yaml` `flex/storageclass.yaml` 

Have set flexvolume in `operator.yaml` like this:
```
name: FLEXVOLUME_DIR_PATH
          value: "/home/kubernetes/flexvolume"
```

This is my `pvc.yaml` (Tried both ReadWriteOnce and ReadWriteMany)
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rook-ceph-test
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

All resources have been applied to the cluster and no errors seen so far except for a warning in the operator which I have repored in https://github.com/rook/rook/issues/4317#issuecomment-580202578

![Screenshot from 2020-01-30 16-27-43](https://user-images.githubusercontent.com/1165845/73444751-3fe37400-437f-11ea-9271-69f66e949ec7.png)

Storage class has been applied:

![Screenshot from 2020-01-30 16-43-33](https://user-images.githubusercontent.com/1165845/73444968-b41e1780-437f-11ea-89d1-9dd4f8d49ada.png)

PVC stays in pending state for more than 30 minutes for just 1 Gi to be provisioned (ofcourse doesn't get provisioned even after that):

![Screenshot from 2020-01-30 16-28-29](https://user-images.githubusercontent.com/1165845/73444826-6d302200-437f-11ea-96d9-c0c2c55358ba.png)

Any help on how to solve this please? Thanks.
