### ISSUE TITLE
multi node dev environment for Mac

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1540] opened 2018-03-01 01:53 UTC
Similar to what @leseb enabled on Linux hosts with #1405, it would be really beneficial to have a development environment with multiple nodes running on a host Mac.  I'm not sure of the exact reasons preventing that solution from working on Mac, so it would probably be wise to start there and see if something could be done for cheap.

Otherwise, a solution using vagrant and kubeadm should be feasible.  The vagrant portion that starts up VMs and adds virtual disks can be found at https://github.com/quantum/coreos-vagrant.

**Comment by inv8r** [comment] 2018-03-21 03:45
@jbw976 can you assign this ticket to me please? I work on a mac and am in the process of setting up my multi node development environment. I can take this opportunity to make a first contribution. Thanks.

**Comment by jbw976** [comment] 2018-03-21 16:43
That would be awesome @inv8r! a few of us contributors to the project would be personally grateful for this improvement.  I know i'd use it frequently.

you should see an invitation to join the Rook organization, apparently Github doesn't allow you to assign issues to someone unless they are a member of the organization.

**Comment by galexrt** [comment] 2018-06-03 18:29
@jbw976 What about this solution for Kubernetes multi node cluster? https://github.com/kubernetes-sigs/kubeadm-dind-cluster.
At least from their README it seems to work in Mac as long as Docker is "installed" (e.g. Docker for Mac), and `md5sha1sum` is installed, see https://github.com/kubernetes-sigs/kubeadm-dind-cluster#mac-os-x-considerations.

**Comment by jbw976** [comment] 2018-06-04 17:30
good question @galexrt,  @dangula and @aramisjohnson originally had the end to end integration tests running in a setup that was using the dind approach.  it had some issues back then with RBD attach operations hanging, and I don't think we've tried it since then.  That was also on Linux machines.

I'm not sure how exactly this would work on the Mac with things that require kernel module operations (such as RBD).  Does the underlying Docker for Mac hypervisor support things like that?  I'm expecting there would be issues there, but I don't know for certain.

**Comment by galexrt** [comment] 2018-06-08 21:32
@inv8r Due to demand for upgrade testings, I have quickly built this project together https://github.com/galexrt/k8s-vagrant-multi-node.
@travisn and @jbw976 have confirmed that it works on Mac (except a few weird warnings from Vagrant), and I now also think that I have squashed most bugs out of the project.

What do you think about creating a script (such as the `minikube.sh`) to integrate with my k8s-vagrant-multi-node project and use it for testing (especially for multi node + multiple disks scenarios)?

**Comment by jbw976** [comment] 2018-06-19 16:53
Letting @galexrt take this issue over with his recent effort on the vagrant multi-node solution.

**Comment by jbw976** [comment] 2019-02-05 22:47
What's left for this issue now that the https://github.com/galexrt/k8s-vagrant-multi-node repo is established?  Adding documentation in Rook to point at the project and summarize the developer focused workflow?

**Comment by jbw976** [comment] 2019-02-06 18:43
possibly, but i'm wondering if the right integration point should be similar to minikube, i.e. a script under `./test/scripts` instead of Makefile integration.

**Comment by galexrt** [comment] 2019-02-12 10:17
A script like `minikube.sh` would certainly be a good idea as one doesn't have to remember the commands then.
@jbw976 @travisn is that fine with you?

**Comment by mykaul** [comment] 2019-02-12 11:36
I wonder if we can use Kubespray or some similar standard way to deploy K8S, then add on top of it Rook?
It has already Vagrant support (https://github.com/kubernetes-sigs/kubespray/blob/master/Vagrantfile) for example.

**Comment by noahdesu** [comment] 2019-02-13 01:13
@mykaul i spent a full day trying to get kubespray to work with vagrant and filed / updated new tickets. https://github.com/galexrt/k8s-vagrant-multi-node worked for me on fc29 out of the box.

**Comment by jbw976** [comment] 2019-02-13 04:43
yes @galexrt, i'd be supportive of a script like that for the multi-node setup.

@mykaul, the k8s-vagrant-multi-node project uses `kubeadm` to create/init the k8s cluster, which I believe to be a very standard way now.

**Comment by galexrt** [comment] 2019-03-05 14:23
@jbw976 I opened a PR for a basic script, see #2763.

**Closed** 2019-03-18 14:54 UTC
Labels: docs, help wanted, test, tools
