### ISSUE TITLE
OSD Prepare fails due to "unparsable uuid"

### ISSUE THREAD

**Issue by alyti** [rook/rook#10219] opened 2022-05-05 23:14 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook-ceph-osd-prepare fails due to "unparsable uuid", leaves behind dirty drives and ignores them on retry, CephCluster has no OSDs

**Expected behavior:**
OSDs get prepared and CephCluster is alive and well.

**How to reproduce it (minimal and precise):**

single-node k3s cluster on dedi with 2 hdd dedicated to ceph, in my case this is managed by a rook-ceph-cluster helm-release

**File(s) to submit**:

* Cluster CR (custom resource): [cluster.yaml](https://github.com/rook/rook/files/8636469/cluster.yaml.txt) [values.yaml](https://github.com/rook/rook/files/8636563/values.yaml.txt) (values used in rook-ceph-cluster helm-release)
* Operator's logs, if necessary: [rook-ceph-operator-7499bf8579-ksltg.log](https://github.com/rook/rook/files/8636471/rook-ceph-operator-7499bf8579-ksltg.log)
* Crashing pod(s) logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 22.04 LTS`
* Kernel (e.g. `uname -a`): `Linux ... 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Hetzner AX-51 /w 2 NVMEs for system & 2 HDDs for Ceph
* Rook version (use `rook version` inside of a Rook Pod): `v1.9.2`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s ?
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_WARN Reduced data availability: 32 pgs inactive; OSD count 0 < osd_pool_default_size 1`

I've been given following issues that seem similar: #9646 & #8023 
However both have different errors.

**Comment by parth-gr** [comment] 2022-05-12 14:53
@alyti can you mention the operator logs, where you see it's unparsable,

And also what you provided in the yaml's(cluster.yaml,etc)

**Comment by alyti** [comment] 2022-05-13 05:16
> @alyti can you mention the operator logs, where you see it's unparsable,
> 
> And also what you provided in the yaml's(cluster.yaml,etc)

All the yamls are in the issue. I've since given up on trying to run rook on my server, instead I opted for longhorn that has been working without any issues for a week now.

Operator logs with error:
```Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid 87e0ecf7-b40b-42d2-b157-407ca37ccb58 --setuser ceph --setgroup ceph
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 2962224517 != actual 1963126265
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 2962224517 != actual 1963126265
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 2962224517 != actual 1963126265
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.0 --yes-i-really-mean-it
 stderr: purged osd.0
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()

**Comment by travisn** [comment] 2022-05-13 13:37
@alyti If in k3s, I believe you'll want to follow the [cluster-on-pvc](https://github.com/rook/rook/blob/master/deploy/examples/cluster-on-pvc.yaml) example (make sure to change the storage class to your environment), then rook will generate the needed PVCs to back the OSDs, instead of needing to attach the static disks.

**Comment by logan2211** [comment] 2022-05-13 16:04
I have the same "unparsable uuid" error when deploying new OSDs on 1.9.3. I've been deploying Rook clusters for years with:
```
      storage:
        devicePathFilter: "^/dev/disk/by-partlabel/OSD[0-9]+"
```

The particular cluster I'm experiencing this issue on currently was deployed with 1.8.9. Then, after upgrading to 1.9.3, it will no longer add new OSDs because of the unparsable uuid error. Existing OSDs work fine. It doesn't seem feasible to completely rebuild using PVCs. I'm using k3s on bare metal @travisn.

**Comment by travisn** [comment] 2022-05-13 17:30
@logan2211 Thanks for the data point that this is a regression. This seems to be related to #10212, not sure there is a workaround other than sticking with v1.9.2. 
@satoru-takeuchi Can you take a look? Sounds like a number of users are hitting this.

**Comment by satoru-takeuchi** [comment] 2022-05-13 22:08
@travisn OK, I'll investigate this issue next week..

**Comment by satoru-takeuchi** [comment] 2022-05-15 14:04
"_read_fsid unparsable uuid" itself is not a bug. It is also shown when osd preparation succeeds.

```
...
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid a8c30bd5-acae-49fa
-8cba-07ab9f51ea90 --setuser ceph --setgroup ceph
 stderr: 2022-05-15T13:17:30.971+0000 7f58c22d0080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
--> ceph-volume raw clear prepare successful for: /dev/sdc1
2022-05-15 13:17:33.261204 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2022-05-15 13:17:33.610800 D | cephosd: {}
2022-05-15 13:17:33.610826 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2022-05-15 13:17:33.610873 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2022-05-15 13:17:34.225929 D | cephosd: {
    "a8c30bd5-acae-49fa-8cba-07ab9f51ea90": {
        "ceph_fsid": "f0c6110a-e1b3-4a7b-b14f-54d3d67fdde1",
        "device": "/dev/sdc1",
        "osd_id": 0,
        "osd_uuid": "a8c30bd5-acae-49fa-8cba-07ab9f51ea90",
        "type": "bluestore"
    }
}
2022-05-15 13:17:34.226077 D | exec: Running command: lsblk /dev/sdc1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2022-05-15 13:17:34.227808 I | cephosd: setting device class "hdd" for device "/dev/sdc1"
2022-05-15 13:17:34.227911 I | cephosd: 1 ceph-volume raw osd devices configured on this node
2022-05-15 13:17:34.227990 I | cephosd: devices = [{ID:0 Cluster:ceph UUID:a8c30bd5-acae-49fa-8cba-07ab9f51ea90 DevicePartUUID: DeviceClass:hdd BlockPath:/dev/sdc1 MetadataPath: WalPath: SkipLVRelease:true Location:root=default host=ubuntu2004 LVBackedPV:false CVMode:raw Store:bluestore TopologyAffinity:}]
...
```

The messages indicating each problem are in the previous lines.

```
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 2962224517 != actual 1963126265
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 2962224517 != actual 1963126265
 stderr: 2022-05-05T22:42:46.413+0000 7fb83eaf8080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 2962224517 != actual 1963126265
```

However, I couldn't reproduce this problem yet. My condition is as follows.

- Rook v1.8.9, v1.9.2, and v1.9.3
- Ceph v16.2.7
- How to specify disk; `devices.name: "/dev/disk/by-id/XXXXXX"` and `devicePathFilter: "^/dev/disk/by-partlabel/OSD[0-9]+"` 
- The target device is formatted with following [the official way].(https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md#delete-the-data-on-hosts)

In all combinations, OSD started without any problems.

@alyti Did you remember the contents of the target device before creating the rook/ceph cluster?

@logan2211 Could you show me the operator log which indicates why OSD creation failed?

@travisn There seems to be multiple problems in OSD creation. At least it isn't only come from #10212 because this change is not in v1.9.2 but @alyti 's problem and the problem in #10160 happened in 1.9.2 or older. I'm not sure if the root cause is in rook or ceph. Anyway, I'll handle both this issue and #10160.

**Comment by alyti** [comment] 2022-05-15 18:00
> @alyti Did you remember the contents of the target device before creating the rook/ceph cluster?

I ran `wipefs` on both devices before doing a helm-release /w cluster. So I'd assume there was nothing there.

**Comment by frittentheke** [comment] 2022-05-15 18:47
We observe this issue with a "regular" Ceph deployment on Ubuntu Focal using `ceph-osd --mkfs`. There I observe this unparsable UUID issue at random as well.

I was about to raise an issue on the ceph issue tracker about this when I found this here ...

**Comment by logan2211** [comment] 2022-05-16 00:54
> @logan2211 Could you show me the operator log which indicates why OSD creation failed?

```
rook-ceph-osd-prepare-host-1-46fjf provision Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/keyring
rook-ceph-osd-prepare-host-1-46fjf provision Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/
rook-ceph-osd-prepare-host-1-46fjf provision Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 2ed38de9-367f-4883-9ad1-d5a0221b971f --setuser ceph --setgroup ceph
rook-ceph-osd-prepare-host-1-46fjf provision  stderr: 2022-05-16T00:32:14.961+0000 7f3a76bb5080 -1 bluestore(/var/lib/ceph/osd/ceph-1//block) _read_bdev_label bad crc on label, expected 608112536 != actual 946372990
rook-ceph-osd-prepare-host-1-46fjf provision  stderr: 2022-05-16T00:32:14.961+0000 7f3a76bb5080 -1 bluestore(/var/lib/ceph/osd/ceph-1//block) _read_bdev_label bad crc on label, expected 608112536 != actual 946372990
rook-ceph-osd-prepare-host-1-46fjf provision  stderr: 2022-05-16T00:32:14.961+0000 7f3a76bb5080 -1 bluestore(/var/lib/ceph/osd/ceph-1//block) _read_bdev_label bad crc on label, expected 608112536 != actual 946372990
rook-ceph-osd-prepare-host-1-46fjf provision  stderr: 2022-05-16T00:32:14.961+0000 7f3a76bb5080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _read_fsid unparsable uuid
rook-ceph-osd-prepare-host-1-46fjf provision --> Was unable to complete a new OSD, will rollback changes
rook-ceph-osd-prepare-host-1-46fjf provision Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
rook-ceph-osd-prepare-host-1-46fjf provision  stderr: purged osd.1
rook-ceph-osd-prepare-host-1-46fjf provision Traceback (most recent call last):
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/sbin/ceph-volume", line 11, in <module>
rook-ceph-osd-prepare-host-1-46fjf provision     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
rook-ceph-osd-prepare-host-1-46fjf provision     self.main(self.argv)
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
rook-ceph-osd-prepare-host-1-46fjf provision     return f(*a, **kw)
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
rook-ceph-osd-prepare-host-1-46fjf provision     terminal.dispatch(self.mapper, subcommand_args)
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
rook-ceph-osd-prepare-host-1-46fjf provision     instance.main()
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
rook-ceph-osd-prepare-host-1-46fjf provision     terminal.dispatch(self.mapper, self.argv)
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
rook-ceph-osd-prepare-host-1-46fjf provision     instance.main()
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
rook-ceph-osd-prepare-host-1-46fjf provision     self.safe_prepare(self.args)
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
rook-ceph-osd-prepare-host-1-46fjf provision     self.prepare()
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
rook-ceph-osd-prepare-host-1-46fjf provision     return func(*a, **kw)
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
rook-ceph-osd-prepare-host-1-46fjf provision     tmpfs,
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
rook-ceph-osd-prepare-host-1-46fjf provision     db=db
rook-ceph-osd-prepare-host-1-46fjf provision   File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 481, in osd_mkfs_bluestore
rook-ceph-osd-prepare-host-1-46fjf provision     raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
rook-ceph-osd-prepare-host-1-46fjf provision RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 2ed38de9-367f-4883-9ad1-d5a0221b971f --setuser ceph --setgroup ceph: exit status 1
```

I confirmed that v1.8.9 works normally. I tested v1.9.0, 1.9.1, 1.9.2, and 1.9.3 and all produce the error above when preparing the OSD.

**Comment by satoru-takeuchi** [comment] 2022-05-17 14:57
I've not reproduced this problem yet in both v1.8.9 and v1.9.2.

@alyti @logan2211 @frittentheke Could you give me the first 100MB of your device on which rook fails to create an OSD? It can be got by the following command.

```console
dd if=/dev/<devname> of=dev.img bs=1M count=100
```

My aim is to inject this image into a block device and try to create an OSD on this device.

**Comment by satoru-takeuchi** [comment] 2022-05-22 23:57
I suspect that this problem may be related to bluefs_buffered_io parameter. All my tests were done with disabling this parameter, its the default value in Rook.

**Comment by satoru-takeuchi** [comment] 2022-05-23 07:51
> I suspect that this problem may be related to bluefs_buffered_io parameter. All my tests were done with disabling this parameter, its the default value in the recent Rook releases.

Unfortunately, this problem didn't happen with bluefs_buffered_io=true.

**Comment by satoru-takeuchi** [comment] 2022-05-23 13:16
rook v1.9.3 + k3s + ubuntu22.04 + the following cluster-test.yaml reproduced "bad crc on label" but osd creations succeeded.

```yaml:cluster-test.yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph # namespace:cluster
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  dashboard:
    enabled: true
    urlPrefix: /
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector: {}
  mgr:
    allowMultiplePerNode: true
    count: 1
    modules:
      - enabled: true
        name: pg_autoscaler
  mon:
    allowMultiplePerNode: true
    count: 1
  monitoring: {}
  network: {}
  security:
    kms: {}
  storage:
    config:
      osdsPerDevice: '1'
    nodes:
      - devices:
        - name: /dev/disk/by-id/scsi-14d53465420202020f4984f994f3efd46b306f782e315f407
        - name: /dev/disk/by-id/scsi-14d53465420202020b701175ffd20604fad6e664f1c618800
        - name: /dev/disk/by-id/scsi-14d53465420202020087ed9e77ff4a04ea0f357d697862b77
        name: ubuntu2004
  waitTimeoutForHealthyOSDInMinutes: 10
```

operator log:
```
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid a2b7d726-d797-48d4-a301-00186c6a0
291 --setuser ceph --setgroup ceph
 stderr: 2022-05-23T13:08:05.983+0000 7f1050204080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 1467599974 != actual 1255294174
 stderr: 2022-05-23T13:08:05.983+0000 7f1050204080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 1467599974 != actual 1255294174
 stderr: 2022-05-23T13:08:05.983+0000 7f1050204080 -1 bluestore(/var/lib/ceph/osd/ceph-0//block) _read_bdev_label bad crc on label, expected 1467599974 != actual 1255294174
 stderr: 2022-05-23T13:08:05.983+0000 7f1050204080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
--> ceph-volume raw clear prepare successful for: /dev/sdb
```

**Comment by satoru-takeuchi** [comment] 2022-05-30 23:33
@frittentheke 

> I was about to raise an issue on the ceph issue tracker about this when I found this here ...

Have you already open an issue?

**Comment by caffeinism** [comment] 2022-06-02 09:08
Slightly different question, but I'm curious as to why you used the bluefs_buffered_io=false option.
I also turned that option off for performance issues, and I reached this thread with the same issue.

**Comment by satoru-takeuchi** [comment] 2022-06-02 13:18
Rook originally keeped this option as default (true). However, we turned this option off as default as a result of hitting this problem in CI and some reports from users.

https://github.com/rook/rook/pull/8185

This problem was reported in Ceph's issue tracker. But it's not fixed yet.
https://tracker.ceph.com/issues/54019

**Comment by frittentheke** [comment] 2022-06-09 15:58
> @frittentheke
> 
> > I was about to raise an issue on the ceph issue tracker about this when I found this here ...
> 
> Have you already open an issue?

No, but I will contribute to https://tracker.ceph.com/issues/54019 which is apparently tracking this.

**Comment by Tyler-Cash** [comment] 2022-08-18 11:20
Just in case someone stumbles into this. I'm running a bare metal k3s cluster (on a proxmox hypervisor if that's relevant).

I tried everything to get raw drives detected. 

I tried passing them through in Proxmox and also mounted them on the host then created a virtual disk and mounted that to my VM. Both instances had a whole raw 4TB disk that would be recognized but then get this error. I must have tried this 20-30 times across my nodes.

In terms of wiping the disk I tried wipefs -a, dd zeros 50GB, etc. 

I also tried the option mentioned further up. For some reason that didn't work. I double checked the rook override ConfigMap which definitely had that set and I tried wiping and onboarding the drives over and over but it never worked :( I also tried both true/false in case I was misreading the recommendation. Didn't work, still got the error.

My understanding was the rook operator expected a blank disk without a fs. I'm confused why this worked.... I'm confused why if there's 1 partition or if the smaller partition is below 50GB~ the uuid error occurs.


**'Workaround'**
What ended up 'working' for me was this. I had to tweak the size of the partitions a fair amount too. For some reason I can't get it to recognize the larger partition when it's by itself. Also I had the same error come up when the smaller partition was really small. I'll keep trying to work out what the cutoff is, but <10% isn't a dealbreaker for me, although it's frustrating.
`
wipefs -a /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi3
parted /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi3
(parted) mklabel gpt
(parted) mkpart primary ext4 0% 90%
(parted) mkpart ext4 98% 100%
`

**Comment by satoru-takeuchi** [comment] 2022-08-19 03:58
@Tyler-Cash Thank you for your detailed explanation.

> I've got a dev.img generated by that command as well. Please let me know where I can share it.

Yes, please share me this image.

**Comment by Tyler-Cash** [comment] 2022-08-19 04:44
Shared it to your email address on your profile. Thanks

**Comment by Tyler-Cash** [comment] 2022-08-19 11:38
I was just double checking that if I run only a wipefs -a on the disk, to ensure v1.9.2 is able to onboard it successfully. Interestingly I actually still get this error. But the OSD manages to get setup correctly.
```
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-4/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-4/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 4 --monmap /var/lib/ceph/osd/ceph-4/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-4/ --osd-uuid a7e1293a-0b9c-4a70-86c0-47127f4709ef --setuser ceph --setgroup ceph
 stderr: 2022-08-19T11:20:27.668+0000 7f8fd2fc8080 -1 bluestore(/var/lib/ceph/osd/ceph-4//block) _read_bdev_label bad crc on label, expected 3544621908 != actual 3634463267
 stderr: 2022-08-19T11:20:27.668+0000 7f8fd2fc8080 -1 bluestore(/var/lib/ceph/osd/ceph-4//block) _read_bdev_label bad crc on label, expected 3544621908 != actual 3634463267
 stderr: 2022-08-19T11:20:27.668+0000 7f8fd2fc8080 -1 bluestore(/var/lib/ceph/osd/ceph-4//block) _read_bdev_label bad crc on label, expected 3544621908 != actual 3634463267
 stderr: 2022-08-19T11:20:27.672+0000 7f8fd2fc8080 -1 bluestore(/var/lib/ceph/osd/ceph-4/) _read_fsid unparsable uuid
--> ceph-volume raw clear prepare successful for: /dev/sdb
```

**Comment by satoru-takeuchi** [comment] 2022-08-30 08:31
@Tyler-Cash Sorry for the late reply. I tried to reproduce this problem with your image. However, rook succeeded to initialize an OSD without any problem. My environments are...

- Ceph v16.2.7
- Ceph v1.9.2 and v1.9.3
- Ubuntu 20.04 virtual machine on top of hyper-v
- A 4 TiB virtual disk attached to the above-mentioned VM. The beginning of this disk is filled with dev.img which you provided.

It's odd...

> Interestingly I actually still get this error. But the OSD manages to get setup correctly.

As describe in the following document, `_read_fsid unparsable_uuid` message itself is not an error.

https://github.com/rook/rook/issues/10219#issuecomment-1126948884

**Comment by satoru-takeuchi** [comment] 2022-08-30 08:46
@Tyler-Cash Could you tell me the result of `parted /dev/<raw disk device> p` and from which device you got dev.img?

**Comment by andy108369** [comment] 2022-09-01 10:52
I've just had the same issue, fixed by https://github.com/rook/rook/issues/10160#issuecomment-1234103306

and yeah, `_read_fsid unparsable_uuid` is not an error on its own.

rook-ceph 1.9.9

**Comment by kfox1111** [comment] 2022-10-04 01:40
I had the same problem. upping the memory limit resolved it. 1G wasn't enough. 2 was. so somewhere in between.

**Comment by satoru-takeuchi** [comment] 2022-10-04 22:56
@travisn Many users have hit this problem. So It seems to be better to add 'resource' field to prepare pods in CephCluster CR examples by default. Does it make sense?

**Comment by travisn** [comment] 2022-10-05 14:33
Please review #11103. My suggestion there is to increase the limits in the helm chart and add a note to the documentation about being generous with the limits when applied.

As a side note, I was wondering why we didn't hit this issue with downstream and I found that we aren't applying limits at all to the osd prepare job, which means it would never be OOM killed.

**Closed** 2022-10-05 19:00 UTC
Labels: bug
