### ISSUE TITLE
Fixing single OSD should not impact all OSDs on the same node

### ISSUE THREAD

**Issue by bzub** [rook/rook#508] opened 2017-03-24 21:41 UTC
A decision should be made if we want to keep this style of one-OSD-pod-per-node.  The advantage there is less complex, perhaps fewer networking issues because they can communicate on localhost.  The disadvantage is as @hunter pointed out in #397 that a problem with one OSD could necessitate restarting the whole pod to fix, including all the OSDs that are OK.

Common scenario for this might be a single drive failure.  OSD goes down, admin replaces and formats the drive.  In normal ceph operations the final step could be as simple as restarting that one OSD service.  I don't think that's possible with rookd right now.

So, either split the OSDs into individual pods or provide the ability (via rook API and client?) to restart a single OSD instance.

**Comment by jbw976** [comment] 2017-03-24 22:21
Totally agreed with this, it's good to have a formal ticket to capture the last item in https://github.com/rook/rook/wiki/Storage-Configuration-Design#implementation-phasesordering
> Improve upgrade story for Rook, including separating each OSD into its own pod

**Comment by jbw976** [comment] 2018-01-16 15:56
Although this was the earlier opened ticket, I'm going to close this one as a dupe of #1341 since that one has some architectural and design discussion with members of the Ceph team.

**Closed by jbw976** 2018-01-16 15:56 UTC
