### ISSUE TITLE
block mount data lost after remount

### ISSUE THREAD

**Issue by oskca** [rook/rook#429] opened 2017-02-24 04:29 UTC
rook block mount would not keep the data after the following sequence:

    rook block mount --name b --path m
    ls -l / > m/ls.txt 
    rook block unmount --path m
    rook block mount --name b --path m
    ls
    lost+found #only this directory would show up 

confirmed in root v0.2.2 and the lastest master branch

**Comment by jbw976** [comment] 2017-02-24 05:20
Yikes, sorry you ran into this issue @oskca but thank you for reporting it.  Hopefully this was just while kicking the tires with some test data.  Apologies either way.

#172 would definitely be a cause here, but the act of unmapping a ceph block image (which is what the `rook block unmount` command does) may be destructive to the file system on the block device as well on its own.  I need to look more into this.

For #172 we've discussed some user experience improvements for the whole flow.  The original intent was to make creating/mapping/formatting/mounting a single step and unmounting/unmapping/destroying a single step too with the hopes of the user having to run less commands.  But from this issue it's clear that the experience as designed can have unintended consequences for the user.

We'll look into improving this soon.  Do you have any suggestions for your ideal command flow/experience when using block devices in `rook`?  Thanks!

**Comment by oskca** [comment] 2017-02-24 05:38
Thanks for your quick reply.

I think the single step command flow is great and works the same way as `rook fs mount/unmount`.
As for #172, is there a way to force format the block device when it's mounted for the first time,
and let the optional `--format` reflects the user's will in the later `block mount|unmount`.

**Comment by DanKerns** [comment] 2017-03-27 15:47
Fixed with pull request #504

**Closed by DanKerns** 2017-03-27 15:47 UTC
Labels: block, cli
