### ISSUE TITLE
unable to get monitor info from DNS SRV with service name: ceph-mon

### ISSUE THREAD

**Issue by Hughen** [rook/rook#3595] opened 2019-08-09 04:17 UTC
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**
after logining in rook-ceph-tools container:
```bash
ceph --show-config --conf /dev/null
# unable to get monitor info from DNS SRV with service name: ceph-mon
# [errno 2] error connecting to the cluster
```
but `ceph -s` is normal.
the toolbox yaml configuration is the same as that provided on [rook.io](https://rook.io/docs/rook/v1.0/ceph-toolbox.html)

**Environment**:
* OS (e.g. from /etc/os-release): `Container Linux by CoreOS 1855.5.0 (Rhyolite)`
* Kernel (e.g. `uname -a`): `Linux p05 4.14.74-coreos #1 SMP Mon Oct 22 22:12:42 UTC 2018 x86_64 Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz GenuineIntel GNU/Linux`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.0.4`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)`
* Kubernetes version (use `kubectl version`):
```text
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-06-04T11:11:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by galexrt** [comment] 2019-08-09 21:06
@Hughen Rook Ceph does not create a Kubernetes Service named `ceph-mon`.

The toolbox has a script running that takes the ConfigMap `rook-ceph-mon-endpoints` to generate a `ceph.conf` at `/etc/ceph/ceph.conf`.
Is there a specific need for you to use the `--conf /dev/null` flag? If you leave that out, you should be able run `ceph` commands without a problem.

**Comment by Hughen** [comment] 2019-08-10 02:37
@galexrt 
Thank you very much for your reply
I want to get all the default configuration of the current ceph cluster, so I used this command.

**Comment by BlaineEXE** [comment] 2019-08-13 16:00
Closing. Not a bug.

**Closed by BlaineEXE** 2019-08-13 16:00 UTC
Labels: bug

**Comment by yizhishang** [comment] 2019-09-19 10:24
> @Hughen Rook Ceph does not create a Kubernetes Service named `ceph-mon`.
> 
> The toolbox has a script running that takes the ConfigMap `rook-ceph-mon-endpoints` to generate a `ceph.conf` at `/etc/ceph/ceph.conf`.
> Is there a specific need for you to use the `--conf /dev/null` flag? If you leave that out, you should be able run `ceph` commands without a problem.

what script？

**Comment by itsecforu** [comment] 2019-10-10 11:47
y

> 
> 
> > @Hughen Rook Ceph does not create a Kubernetes Service named `ceph-mon`.
> > The toolbox has a script running that takes the ConfigMap `rook-ceph-mon-endpoints` to generate a `ceph.conf` at `/etc/ceph/ceph.conf`.
> > Is there a specific need for you to use the `--conf /dev/null` flag? If you leave that out, you should be able run `ceph` commands without a problem.
> 
> what script？

Yes, what script?

**Comment by galexrt** [comment] 2019-10-10 12:07
https://github.com/rook/rook/blob/master/images/ceph/toolbox.sh and https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/toolbox.yaml#L22-L23

**Comment by Voolodimer** [comment] 2022-11-11 08:11
I have the same problem, after logining in `rook-ceph-mon-c` container i try to get `monmap_config` using `ceph mon getmap` and i get similar error:
```
unable to get monitor info from DNS SRV with service name: ceph-mon
2022-11-11T08:08:33.060+0000 7fd224cd9700 -1 failed for service _ceph-mon._tcp
2022-11-11T08:08:33.060+0000 7fd224cd9700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
```
Can anyone help me ?

**Comment by BlaineEXE** [comment] 2022-11-17 00:00
Only the toolbox pod is intended to allow interactively running commands. No other pods support that.
