### ISSUE TITLE
Support realm/zonegroup/zone for external cluster

### ISSUE THREAD

**Issue by leseb** [rook/rook#6342] opened 2020-09-29 09:05 UTC
If an external cluster has an rgw setup with realm/zonegroup/zone configured, when issuing radosgw-admin commands rook should populate these values accordingly.

**Comment by leseb** [comment] 2020-09-29 14:27
Actually, this still has to be implemented 😅

**Comment by MaXinjian** [comment] 2020-12-29 05:10
Hi @leseb, I'm trying to create OBC in external cluster, but seems failed due to this issue. So there is no way for us to  create
OB/OBC in external cluster?

**Comment by leseb** [comment] 2021-01-05 14:37
> Hi @leseb, I'm trying to create OBC in external cluster, but seems failed due to this issue. So there is no way for us to create
> OB/OBC in external cluster?

What is the issue? Do you have the operator's logs? Do you have a realm/zone/zonegroup setup?
The problem should manifest by a stack trace from the radosgw command when trying to perform s3 operations.

**Comment by MaXinjian** [comment] 2021-01-06 01:47
> What is the issue?
After I create OBC, OB will not be created
> Do you have the operator's logs? 
`
2020-12-18 14:03:47.085716 I | op-bucket-prov: initializing and setting CreateOrGrant services
2020-12-18 14:03:47.085772 I | op-bucket-prov: getting storage class "rook-ceph-delete-bucket" 
2020-12-18 14:03:47.119186 I | op-bucket-prov: Provision: creating bucket "ceph-bkt-acb2b680-ff53-4152-baf2-326573139a6e" for OBC "ceph-delete-bucket" 
E1218 14:03:47.243614       8 controller.go:197] error syncing 'default/ceph-delete-bucket': error provisioning bucket: Provision: can't create ceph user: no user name provided and unable to generate a unique name: error getting ceph user "ceph-user-dHSmVTi1": radosgw-admin command err. . 2020-12-18T14:03:47.231+0000 7f3019cde1c0  0 failed reading zonegroup info: ret -2 (2) No such file or directory
2020-12-18T14:03:47.231+0000 7f3019cde1c0  0 ERROR: failed to start notify service ((2) No such file or directory
2020-12-18T14:03:47.231+0000 7f3019cde1c0  0 ERROR: failed to init services (ret=(2) No such file or directory)
couldn't init storage provider: exit status 5, requeuing
`
> Do you have a realm/zone/zonegroup setup?
I use admin user to create Ceph Cluster at first. 
I comment out --from-literal="$MON_SECRET_CEPH_USERNAME_KEYNAME"="$ROOK_EXTERNAL_USERNAME" \ and --from-literal="$MON_SECRET_CEPH_SECRET_KEYNAME"="$ROOK_EXTERNAL_USER_SECRET" line and create secret/rook-ceph-mon before create Ceph Cluster
`
function importSecret() {
    kubectl -n "$NAMESPACE" \
    create \
    secret \
    generic \
    "$MON_SECRET_NAME" \
    --from-literal="$MON_SECRET_CLUSTER_NAME_KEYNAME"="$ROOK_EXTERNAL_CLUSTER_NAME" \
    --from-literal="$MON_SECRET_FSID_KEYNAME"="$ROOK_EXTERNAL_FSID" \
    --from-literal="$MON_SECRET_ADMIN_KEYRING_KEYNAME"="$ROOK_EXTERNAL_ADMIN_SECRET" \
    --from-literal="$MON_SECRET_MON_KEYRING_KEYNAME"="$ROOK_EXTERNAL_MONITOR_SECRET" 
}
`
After go through the code, I find only when admin user, realm/zone/zonegroup feature will be used. Seems
this issue is just the issue described in this page. 

Now I have find a workaround to solve this issue.  When create secret/rook-ceph-mon in normal user, then I give this normal 
user admin permits. Now everything works fine

**Comment by hase1128** [comment] 2021-03-15 12:32
> Now I have find a workaround to solve this issue. When create secret/rook-ceph-mon in normal user, then I give this normal
user admin permits. Now everything works fine

I think this is not best solution.(just work around).
I hope normal user can do this without temporary admin permission.

@leseb 
This Issue will be solved for v1.6?

**Comment by leseb** [comment] 2021-03-15 13:43
> > Now I have find a workaround to solve this issue. When create secret/rook-ceph-mon in normal user, then I give this normal
> > user admin permits. Now everything works fine
> 
> I think this is not best solution.(just work around).
> I hope normal user can do this without temporary admin permission.
> 
> @leseb
> This Issue will be solved for v1.6?

In one of the 1.6 releases probably not 1.6.0.

**Comment by thotz** [comment] 2022-06-21 07:44
I have tried to reproduce this issue in 1.8 and 1.9 releases with ceph v17 and not been able to reproduce the issue. For external RGW cluster we are not running any `radosgw-admin` commands but use rest interface via adminops API. The rest interface does not require any zone/zonegroup/realm information since it sends request directly to rgw server endpoint

@hase1128 have you seen this in above versions of rook or ceph?

**Comment by thotz** [comment] 2022-08-22 04:23
I am closing this issue, there is no need to support zone/zonegroup/realm config for external cluster

**Closed by thotz** 2022-08-22 04:23 UTC
Labels: feature, wontfix, ceph
