### ISSUE TITLE
Erasure coded StorageClass invalid option dataBlockPool for volume plugin rookVolumeProvisioner

### ISSUE THREAD

**Issue by JoshuaAndrew** [rook/rook#2426] opened 2018-12-26 07:26 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
   ```
    E1226 06:57:38.149387       7 controller.go:1079] Error scheduling operation "provision-default/mysql-pv-claim[5bbb205d-08d9-11e9-b890-005056852a45]": Failed to create operation with name "provision-default/mysql-pv-claim[5bbb205d-08d9-11e9-b890-005056852a45]". An operation with that name failed at 2018-12-26 06:56:53.300077329 +0000 UTC m=+14655.929390219. No retries permitted until 2018-12-26 06:58:55.300077329 +0000 UTC m=+14777.929390219 (2m2s). Last error: "invalid option \"dataBlockPool\" for volume plugin rookVolumeProvisioner".

 ```     
**Expected behavior:**
    
   ```
    dataBlockPool  is valid option for volume plugin rookVolumeProvisioner
   ```

**How to reproduce it (minimal and precise):**

  Step 1 
  ```
  kubectl  create -f  https://raw.githubusercontent.com/rook/rook/v0.9.0/cluster/examples/kubernetes/ceph/ec-storageclass.yaml
  ```

  Step 2 
   ```
   kubectl create -f 
    https://raw.githubusercontent.com/rook/rook/v0.9.0/cluster/examples/kubernetes/mysql.yaml
   ```

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):  Linux k8s-master-1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:  x86_64
* Rook version (use `rook version` inside of a Rook Pod):  v0.9.0
* Kubernetes version (use `kubectl version`):    v1.12.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  N/A
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
```

[root@k8s-node-1 /]# ceph -s
  cluster:
    id:     5aaf8ed7-95f7-4cf6-9677-ea89f3bae8a1
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,c,b
    mgr: a(active)
    osd: 6 osds: 6 up, 6 in
 
  data:
    pools:   2 pools, 200 pgs
    objects: 0  objects, 0 B
    usage:   49 GiB used, 393 GiB / 442 GiB avail
    pgs:     200 active+clean
```

**Comment by galexrt** [comment] 2018-12-26 11:14
Duplicate of #2370.
The PR #2393 which fixed #2370 has been merged to `master` and has been backported to the v0.9 branch, there will soon be a patch release for v0.9.

**Closed by galexrt** 2018-12-26 11:14 UTC
