### ISSUE TITLE
MGR MODULE ERROR:Module 'rook'has failed:(pv_name',)

### ISSUE THREAD

**Issue by ywd1988** [rook/rook#13600] opened 2024-01-22 06:27 UTC
There has always been this alarm![GR6}6X9%820YY7U107_} L7](https://github.com/rook/rook/assets/92080991/73a48c4e-1c5c-4aed-a134-1cc217580ab7)
![image](https://github.com/rook/rook/assets/92080991/2e5710fa-e503-4994-bb30-4827b49b4d8b)

**Comment by rkachach** [comment] 2024-01-23 10:00
@ywd1988 what version of Rook are you running? the crashing cod should not being called in recent versions anymore.

**Comment by ywd1988** [comment] 2024-01-23 10:44
> @ywd1988您运行的是哪个版本的 Rook 和 Ceph？在最近的版本中不应再调用崩溃代码。



> @ywd1988 what version of Rook and Ceph are you running? the crashing code should not being called in recent versions anymore.
![image](https://github.com/rook/rook/assets/92080991/0cc0cf28-a9d8-4c7d-b10d-dab8bdd60cb1)

![image](https://github.com/rook/rook/assets/92080991/d2997f78-7531-4450-bbdc-4d42d9f48f81)

**Comment by rkachach** [comment] 2024-01-23 11:31
I see, please, can you run the following command from a toolbox:

`ceph orch ls`

**Comment by ywd1988** [comment] 2024-01-23 11:34
> @ywd1988 what version of Rook and Ceph are you running? the crashing code should not being called in recent versions anymore.



> I see, please, can you run the following commands from a toolbox :
> 
> ```
> ceph mgr module enable rook && ceph orch set backend rook && ceph orch status
> ceph orch ls
> ```

![image](https://github.com/rook/rook/assets/92080991/c85cc16c-af46-4f69-9a60-51722cf9d0df)

**Comment by rkachach** [comment] 2024-01-23 11:39
The issue is coming from applying the spec `osd.cost_capacity`. In Rook, all the OSD managment must be done by the Rook operator by using the specs. In order to remove this faulty entry you have to run:

`ceph orch rm osd.cost_capacity`

**Comment by ywd1988** [comment] 2024-01-23 12:10
> The issue is coming from applying the spec `osd.cost_capacity`. In Rook, all the OSD managment must be done by the Rook operator by using the specs. In order to remove this faulty entry you have to run:
> 
> `ceph orch rm osd.cost_capacity`

![image](https://github.com/rook/rook/assets/92080991/826f854d-57df-4fb8-aefd-4cedad2a6d30)

**Comment by rkachach** [comment] 2024-01-23 14:42
@travisn @BlaineEXE I'll keep this issue open as I think we should disable/remove all the code that has to do with OSDs management from the rook operator. WDYT?

**Comment by travisn** [comment] 2024-01-23 15:00
@rkachach Did you mean to remove all OSD management from the rook mgr module? If so, sounds good.

**Comment by rkachach** [comment] 2024-01-23 15:28
> @rkachach Did you mean to remove all OSD management from the rook mgr module? If so, sounds good.

Yes, because it's buggy and not tested and users should be messing with OSDs from the rook orchestrator mgr module.

**Comment by BlaineEXE** [comment] 2024-01-23 15:33
100% agree

**Comment by rkachach** [comment] 2024-01-29 11:00
I opened the PR to address this issue: https://github.com/ceph/ceph/pull/55350

**Comment by rkachach** [comment] 2024-04-02 21:03
issue still active, waiting for a Ceph release with the fix.

**Comment by rkachach** [comment] 2024-06-04 07:18
issue still active, waiting for a Ceph release with the fix.

**Comment by rkachach** [comment] 2024-08-20 12:52
issue still active, waiting for a Ceph release with the fix.

**Comment by rkachach** [comment] 2024-08-20 12:58
@travisn I think the fix for this to be already included in `Ceph 18.2.4`

**Comment by travisn** [comment] 2024-08-20 13:27
> @travisn I think the fix for this to be already included in `Ceph 18.2.4`

Great to know it's in the latest release!

**Closed by travisn** 2024-08-20 13:27 UTC
Labels: bug, wontfix
