### ISSUE TITLE
Ceph MGR: 2 modules failed on default install

### ISSUE THREAD

**Issue by galexrt** [rook/rook#2335] opened 2018-12-05 14:16 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Two Ceph MGR modules failed to come up causing the Ceph cluster to report `HEALTH_ERROR` state.

See logs: https://gist.github.com/galexrt/3626102e96dddcef071060b71d94e280

**Expected behavior:**
The dashboard and prometheus modules to work fine.

**How to reproduce it (minimal and precise):**
1. Use the example `cluster.yaml`, in my case in a minikube environment on K8S `1.11.4`.

**Environment**:
* OS (e.g. from /etc/os-release): ```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`): `Linux minikube 4.15.0 #1 SMP Fri Oct 5 20:44:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `rook: v0.8.0-350.g18b2da5f` (freshly built from latest `master` this morning, https://github.com/rook/rook/commit/18b2da5fc5d7a303b9a48119ce55108b55af7f0e)
* Kubernetes version (use `kubectl version`): ```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `minikube`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): `HEALTH_ERROR` - `2 modules have failed`

**Comment by NickUfer** [comment] 2018-12-05 17:30
Same problem for me. Ports are binded and reachable with curl on 127.0.0.1 and pod ip.

```
Netid State      Recv-Q Send-Q   Local Address:Port                  Peer Address:Port              
tcp   LISTEN     0      128         10.0.16.95:6800                             *:*                  
tcp   LISTEN     0      5                   :::9283                            :::*                  
tcp   LISTEN     0      5                   :::8443                            :::*                  
```

**Comment by stucki** [comment] 2018-12-07 09:43
Had the same problem multiple times after starting over with a fresh setup.  
Try this as a workaround:

```
kubectl -n rook-ceph exec -it rook-ceph-tools -- ceph status     # reports HEALTH_ERR
kubectl -n rook-ceph exec -it rook-ceph-tools -- ceph mgr module disable prometheus
kubectl -n rook-ceph exec -it rook-ceph-tools -- ceph mgr module enable prometheus
kubectl -n rook-ceph exec -it rook-ceph-tools -- ceph status     # reports HEALTH_OK
```

**Comment by lastessa** [comment] 2018-12-10 21:33
the same problem on fresh ubuntu with k8s cluster and rook install.

**Comment by galexrt** [comment] 2018-12-10 21:37
@lastessa @NickUfer @stucki Could you please post your Rook Ceph MGR logs as an attachment or gist.

**Comment by lastessa** [comment] 2018-12-10 22:00
https://gist.github.com/lastessa/784153cfb132e8701250be7441e59387


[root@krs-1 /]#  ceph status
  cluster:
    id:     476b51c2-9edc-4831-8b3a-a7655997c5fd
    health: HEALTH_ERR
            2 modules have failed
 
  services:
    mon: 4 daemons, quorum b,d,c,a
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 57  objects, 140 MiB
    usage:   82 GiB used, 1.1 TiB / 1.2 TiB avail
    pgs:     100 active+clean

**Comment by based64god** [comment] 2018-12-11 00:58
Same issue here. I've managed to nail down some repro steps, but feel free to ask away if anything else is needed that I may have missed.

My cluster is currently running ubuntu 18.04.1 with kernel 4.15.0-42-generic and docker.io/weaveworks/weave-npc:2.5.0 for CNI on all machines. The cluster also has the latest prometheus operator v0.26.0 and the prometheus, prometheus-service, and service-monitor yaml running from commit fb557b0ffb66560f50d258da61647670a979ad26.

Installing the rook operator and cluster with the operator and cluster yaml in also in commit fb557b0ffb66560f50d258da61647670a979ad26 causes the prometheus and dashboard modules to report errors binding to ports 9283 and 8443, with logs being nearly verbatim to https://gist.github.com/galexrt/3626102e96dddcef071060b71d94e280.

Interesting notes: Disabling and re-enabling the modules as described by @stucki temporarily fixes the problem for ~30 seconds. I get the same output as @NickUfer 's `ss` for both the 30 seconds of success, as well as the failure afterwards.

**Comment by travisn** [comment] 2018-12-12 07:18
Ok, I was able to repro in minikube simply by using the default cluster yaml (that configures mimic), then looking at the cluster health in the toolbox. Within the first 30-60 seconds the mgr modules are fine, but then the prometheus and dashboard modules fail and the ceph status reports HEALTH_ERR with the two module failures. This does not repro when launching luminous. This does repro with nautilus.

@sebastian-philipp Could you take a look at this issue? I'm still trying to narrow down if there was some recent change in rook that could have caused this failure, but your input would be very helpful, thanks.

**Comment by jbw976** [comment] 2018-12-12 07:53
We saw this also today during the demo at the Rook intro session at Kubecon Seattle :)

**Comment by sebastian-philipp** [comment] 2018-12-13 18:42
Ok, this seems to be closely related to CherryPy. Which exact CherryPy version is installed in the containers?

**Comment by sebastian-philipp** [comment] 2018-12-13 18:47
Upstream: http://tracker.ceph.com/issues/37651

**Comment by sinqinc** [comment] 2018-12-13 18:50
root@rook-ceph-mgr-a-55bb9c6474-9ddpn /]# python -c "import cherrypy;print cherrypy.__version__"
3.2.2

**Comment by sebastian-philipp** [comment] 2018-12-13 18:52
> root@rook-ceph-mgr-a-55bb9c6474-9ddpn /]# python -c "import cherrypy;print cherrypy.**version**"
> 3.2.2

This version is kind of old. Do you get the same error with 3.5.0 or newer?

**Comment by sebastian-philipp** [comment] 2018-12-13 18:56
As this is a CentOS based image, @epuertat have you seen this in your RH downstream testing?

**Comment by pennpeng** [comment] 2018-12-14 10:06
+1

**Comment by epuertat** [comment] 2018-12-14 10:38
> As this is a CentOS based image, @epuertat have you seen this in your RH downstream testing?

I've seen that, but my common setup has been, you know, CentOS7 + custom Luminous backport of the dashboard.

Just run a search and found that this was also happening in [Luminous 12.2.5's Prometheus module](https://tracker.ceph.com/issues/24395) and [dashboard too](https://tracker.ceph.com/issues/20216). But it was mostly fixed with https://github.com/ceph/ceph/pull/15588.

In the past I was able to work around this issue by setting the listening IP to a specific local address, instead of the default `0.0.0.0` or `::/128`.

With `master` I can see a similar error with the restful module (I forced that by immediately disabling and enabling the dashboard module):
```
2018-12-14 10:33:08.550 7fab244ef700  0 mgr[restful] Traceback (most recent call last):
  File "/ceph/src/pybind/mgr/restful/module.py", line 255, in serve
    self._serve()
  File "/ceph/src/pybind/mgr/restful/module.py", line 330, in _serve
    ssl_context=(cert_fname, pkey_fname),
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 486, in make_server
    passthrough_errors, ssl_context)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 410, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

**Comment by Amos-85** [comment] 2018-12-14 12:00
I have the same issue and same ceph mgr errors like @galexrt publish in gist
[https://gist.github.com/galexrt/3626102e96dddcef071060b71d94e280](url)
+1

**Comment by Amos-85** [comment] 2018-12-15 19:01
@liejuntao001 as far as I understand from the community, we'll need to wait for ceph to publish docker version 13.2.3 in order to solve the prometheus & ceph dashboard bugs in mimic.
they suppose to publish it around Jan 2019.

**Comment by sebastian-philipp** [comment] 2018-12-17 16:17
@epuertat :  @travisn was able to reproduce this with Nautilus

**Comment by sebastian-philipp** [comment] 2018-12-18 17:14
@lenzgr fyi.

**Comment by travisn** [comment] 2018-12-19 06:52
Ok, I believe I have prototyped the fix... The setting on the mgr modules for `server_addr` needs to be set to the pod IP. By default the dashboard and prometheus modules are binding to `::` (all interfaces) as seen [here](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/module.py#L109), which is causing the issues in the k8s clusters. 

The fix can be tested by running the following commands from the toolbox:
```
# Get the IP of the mgr pod:
kubectl -n rook-ceph get pod -l app=rook-ceph-mgr -o wide

# Set the server_addr for the two modules (replacing the pod ip queried above)
ceph config set mgr.a mgr/prometheus/server_addr <podIP>
ceph config set mgr.a mgr/dashboard/server_addr  <podIP>

# Restart the mgr pod:
kubectl -n rook-ceph delete pod -l app=rook-ceph-mgr
```

Now to automate this when the mgr pod starts up...

**Comment by lastessa** [comment] 2018-12-19 10:36
After restart mgr pod 
kubectl -n rook-ceph delete pod -l app=rook-ceph-mgr

it's get another ip address different from ceph config set settings

**Comment by travisn** [comment] 2018-12-19 15:03
@lastessa I updated the instructions to restart the pod without deleting it. Does that work for you?

**Closed** 2018-12-21 14:43 UTC
Labels: ceph

**Comment by akashkov** [comment] 2019-02-06 19:14
Hi,
If somebody still interested, I had similar dashboard issue for mimic. Mon nodes run mgr roles in mimic.
Apparently there are some IPv6 dependency for dashboard module, and IPv6 should be enable on mom nodes during installation/configuration. I usually disable IPv6 and as result run into dashboard and Prometheus issues. To fix an issues you need to:
1. Enable IPv6 on all monitor nodes
2. You need to check mgr database records "ceph config dump"
3. Clean it if needed and make sure that there is a records for each mon node: mon1 is a, mon2 is b and ...
 mgr/dashboard/a/server_addr "mon node IPv4"
 mgr/dashboard/a/server_addr "port for dashboard 7000"
4. There are should be two general records for dashboard module without a, b .. with reference to IPv6 all addresses ::
 mgr/dashboard/server_addr   ::
 mgr/dashboard/server_port   7000
