### ISSUE TITLE
Rook Secrets needed when using StorageClass in a new namespace 

### ISSUE THREAD

**Issue by Lain92** [rook/rook#769] opened 2017-06-29 08:07 UTC
Hi,

When using Rook's StorageClass, to attach the persistent volume to a pod, the kubelet asks for the rook-user secret.
The problem is that this secret is only generated by rook-api for the rook cluster namespace (by default rook).

```
Jun 28 17:09:51 k8s-rook-s1 kubelet[16368]: E0628 17:09:51.012253   16408 rbd.go:455] failed to get secret from ["b-b"/"rook-rook-user"]
Jun 28 17:09:51 k8s-rook-s1 kubelet[16368]: E0628 17:09:51.012270   16408 rbd.go:111] Couldn't get secret from b-b/&LocalObjectReference{Name:rook-rook-user,}

```
In this example, rbd expects the secret rook-rook-user to be present in the b-b namespace.
Rook should manage this secret to be shared through namespaces. In fact, we have to manually create the rook-rook-user secret in each namespace which wants to use the StorageClass.

**Comment by bzub** [comment] 2017-06-29 16:32
#475 :)

**Comment by jbw976** [comment] 2017-06-30 01:14
Thanks for the issue report and the details @Lain92.  As @bzub mentioned, we plan to cover this in #475 in the current v0.5 milestone.  Closing this one as a duplicate of #475.

**Closed by jbw976** 2017-06-30 01:14 UTC

**Comment by Lain92** [comment] 2017-06-30 03:05
My bad, didn't see the existing issue, thank yoi very much :)
