### ISSUE TITLE
Pod problem using pvc provisioned by rook-ceph

### ISSUE THREAD

**Issue by danilorsilva** [rook/rook#4282] opened 2019-11-07 20:08 UTC
Hello,

I have a kubernetes (RKE) cluster installed and rook ceph deployed successfully.

When i try to create a pvc it works fine. I can see the pvc created.

When i use this pvc for a pod, the pod keep in ContainerCreating status forever.

Anyone experiencing this problem?

Thanks!

**Comment by rajatsingh25aug** [comment] 2019-11-08 09:10
@danilorsilva can you please describe the pod so it'll be easier to understand.
run `oc describe pod <podname>` scroll down and please tell the message that you get.
Thanks

**Comment by irikeish** [comment] 2019-11-09 09:55
@rajatsingh25aug  I am facing the same issue, here is the description of the pod which is failing to create:
`
        6m50s (x206 over 10h)  kubelet, c105599         Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], unattached volumes=[mysql-persistent-storage default-token-rbf2c]: timed out waiting for the condition

  Warning  FailedAttachVolume  6m26s (x159 over 10h)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7018a001-4a14-4c30-8adc-1d2e5bcfb21d" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000001-e36f235f-0271-11ea-afc3-8a42b6491e72

  Warning  FailedMount         1s (x72 over 10h)      kubelet, c105599         Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], unattached volumes=[default-token-rbf2c mysql-persistent-storage]: timed out waiting for the condition
`
**kubelet log:**
`
 72077 goroutinemap.go:150] Operation for "/data/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi-provisioner.sock" failed. No retries permitted until 2019-11-09 03:37:00.206797332 -0500 EST m=+39190.620590866 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /data/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi-provisioner.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"

Nov 09 03:36:04 c105599 kubelet[72077]: E1109 03:36:04.515737   72077 kubelet.go:1682] Unable to attach or mount volumes for pod "wordpress-mysql-b9ddd6d4c-gnsjp_default(f1a41c23-ff7d-4acf-90af-d486e2b0a458)": unmounted volumes=[mysql-persistent-storage], unattached volumes=[mysql-persistent-storage default-token-rbf2c]: timed out waiting for the condition; skipping pod

Nov 09 03:36:04 c105599 kubelet[72077]: E1109 03:36:04.515859   72077 pod_workers.go:191] Error syncing pod f1a41c23-ff7d-4acf-90af-d486e2b0a458 ("wordpress-mysql-b9ddd6d4c-gnsjp_default(f1a41c23-ff7d-4acf-90af-d486e2b0a458)"), skipping: unmounted volumes=[mysql-persistent-storage], unattached volumes=[mysql-persistent-storage default-token-rbf2c]: timed out waiting for the condition

Nov 09 03:36:09 c105599 kubelet[72077]: I1109 03:36:09.436480   72077 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-7018a001-4a14-4c30-8adc-1d2e5bcfb21d" (UniqueName: "kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-e36f235f-0271-11ea-afc3-8a42b6491e72") pod "wordpress-mysql-b9ddd6d4c-gnsjp" (UID: "f1a41c23-ff7d-4acf-90af-d486e2b0a458")

Nov 09 03:36:09 c105599 kubelet[72077]: E1109 03:36:09.439160   72077 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-e36f235f-0271-11ea-afc3-8a42b6491e72\"" failed. No retries permitted until 2019-11-09 03:38:11.439073446 -0500 EST m=+39261.852866938 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-7018a001-4a14-4c30-8adc-1d2e5bcfb21d\" (UniqueName: \"kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-e36f235f-0271-11ea-afc3-8a42b6491e72\") pod \"wordpress-mysql-b9ddd6d4c-gnsjp\" (UID: \"f1a41c23-ff7d-4acf-90af-d486e2b0a458\") "

`

`
kubectl get pvc: 

mysql-pv-claim   Bound    pvc-7018a001-4a14-4c30-8adc-1d2e5bcfb21d   20Gi       RWO            csi-cephfs     12h
`
`
kubectl get pv 

pvc-7018a001-4a14-4c30-8adc-1d2e5bcfb21d   20Gi       RWO            Delete           Bound    default/mysql-pv-claim   csi-cephfs              12h
`

**system info**
Kubernetes v1.16.2

**Comment by aland-zhang** [comment] 2019-11-26 14:31
I encountered the same problem.
Unable to attach or mount volumes: unmounted volumes=[test], unattached volumes=[mon-endpoint-volume test default-token-x4d4b dev sysbus libmodules]: timed out waiting for the condition
rook/ceph:v1.1.7-6.g755b10a
Kubernetes v1.16.2

kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2019-11-26T12:53:54Z"
  name: rook-ceph-block
  resourceVersion: "25442802"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/rook-ceph-block
  uid: eedc997a-7507-4cb3-95e8-1ade5517d84a
mountOptions:
- discard
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  imageFeatures: layering
  imageFormat: "2"
  pool: rbd
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1

uname -r                                                                                                                                    
5.1.11-1.el7.elrepo.x86_64
ceph 14.2.4

**Comment by aland-zhang** [comment] 2019-11-26 14:55
After I restart both services, the problem is gone.
systemctl restart docker 
systemctl restart kubelet

**Comment by rajatsingh25aug** [comment] 2019-12-13 11:53
can I close this @aland-zhang ?

**Comment by galexrt** [comment] 2020-01-02 14:47
Ping @danilorsilva what is your status on the issue? Are you still experiencing it?

**Comment by dimm0** [comment] 2020-01-14 08:39
Having this after updating to k8s 1.17 for CSI volumes

**Comment by Madhu-1** [comment] 2020-01-14 08:56
am closing this one as the issue template is not filled, difficult to debug based on the info provided. please create a separate issue and don't forget to fill template which helps in debugging

**Closed by Madhu-1** 2020-01-14 08:56 UTC
Labels: ceph -, csi
