### ISSUE TITLE
rook-api doesn't update monmap

### ISSUE THREAD

**Issue by jpds** [rook/rook#1102] opened 2017-10-18 09:36 UTC
Hello,

I noticed that my rook-api pod seemed to be reading data from my old mons (1, 2, 3) and not what was in the monmap which were 3,4,5.

After deleting the rook-api pod, it reread the monmap correctly.

**Comment by galexrt** [comment] 2017-10-18 09:43
@jpds This should had been fixed by #1069 but an issue caused this to be first correctly fixed in #1080 (see [pkg/api/daemon.go Line 80-82](https://github.com/rook/rook/pull/1080/files#diff-9c28ce19d2d3cdbaecd218d04572d969R80)).

**Comment by jbw976** [comment] 2017-10-18 20:40
Closing this as a duplicate of #990 since @galexrt has now fixed it.  Let us know if you still see this in the latest master builds. Thanks!

**Closed by jbw976** 2017-10-18 20:40 UTC
