### ISSUE TITLE
Ceph: ObjectBucket Provisioner leaderelection lost causing operator failure

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#4158] opened 2019-10-23 15:56 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator log snippet:
```
I1021 21:25:38.521312       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"ceph.rook.io-block", UID:"b1fa2af5-dcec-4315-b944-7c79e2614bc4", APIVersion:"v1", ResourceVersion:"287600", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d88617c-f444-11e9-9dba-6a031b31d915 stopped leading
I1021 21:25:38.523121       6 leaderelection.go:263] failed to renew lease upgrade-ns-system/ceph.rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
I1021 21:25:38.473251       6 leaderelection.go:263] failed to renew lease upgrade-ns-system/rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
I1021 21:25:38.619623       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"rook.io-block", UID:"fe926b7c-16d9-4996-9810-0cce29020854", APIVersion:"v1", ResourceVersion:"287599", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d8986d5-f444-11e9-9dba-6a031b31d915 stopped leading
F1021 21:25:38.643191       6 controller.go:847] leaderelection lost
F1021 21:25:38.693123       6 controller.go:847] leaderelection lost
```

When the operator encounters these errors, it crashes and restarts, and I have never seen the operator recover from the error after a restart; it keeps encountering the issue repeatedly.

**Expected behavior:**
The operator should be able to retry whatever is going on when leader election is lost for object bucket claims

**How to reproduce it (minimal and precise):**
I encounter this issue when installing Rook and then updating Ceph and/or Rook a couple times. believe repro needs an environment with limited resouces, like a single node with 2 vCPUs or less and 2GB RAM or less.

**Comment by BlaineEXE** [comment] 2019-10-23 16:01
@travisn I'm not sure who to tag on this to take a look. I don't see Jeff Vance suggested on GitHub or in slack.

**Comment by travisn** [comment] 2019-10-23 16:19
Actually, i'm not seeing now that it would be related to the object bucket provisioner. The reference to endpoints includes the name `ceph.rook.io-block`, which looks more like a csi driver than related to object. There isn't anything else in the operator log indicating failure?

**Comment by BlaineEXE** [comment] 2019-10-23 16:23
No. Here's the whole log. There is a `became leader` message early on, but nothing more about it until the failures.
```
2019-10-21 20:50:33.663559 I | rookcmd: starting Rook v1.0.6 with arguments '/usr/local/bin/rook ceph operator'
2019-10-21 20:50:33.666433 I | rookcmd: flag values: --alsologtostderr=false, --csi-attacher-image=quay.io/k8scsi/csi-attacher:v1.0.1, --csi-cephfs-image=quay.io/cephcsi/cephfsplugin:v1.0.0, --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner.yaml, --csi-enable-cephfs=true, --csi-enable-rbd=true, --csi-provisioner-image=quay.io/k8scsi/csi-provisioner:v1.0.1, --csi-rbd-image=quay.io/cephcsi/rbdplugin:v1.0.0, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner.yaml, --csi-registrar-image=quay.io/k8scsi/csi-node-driver-registrar:v1.0.2, --csi-snapshotter-image=quay.io/k8scsi/csi-snapshotter:v1.0.1, --help=false, --log-flush-frequency=5s, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --log_file=, --logtostderr=true, --mon-healthcheck-interval=10s, --mon-out-timeout=15s, --skip_headers=false, --stderrthreshold=2, --v=0, --vmodule=
2019-10-21 20:50:33.678205 I | cephcmd: starting operator
2019-10-21 20:50:34.153059 I | op-agent: getting flexvolume dir path from FLEXVOLUME_DIR_PATH env var
2019-10-21 20:50:34.153083 I | op-agent: flexvolume dir path env var FLEXVOLUME_DIR_PATH is not provided. Defaulting to: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
2019-10-21 20:50:34.153095 I | op-agent: discovered flexvolume dir path from source default. value: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
2019-10-21 20:50:34.153107 I | op-agent: no agent mount security mode given, defaulting to 'Any' mode
2019-10-21 20:50:34.153119 W | op-agent: Invalid ROOK_ENABLE_SELINUX_RELABELING value "". Defaulting to "true".
2019-10-21 20:50:34.153130 W | op-agent: Invalid ROOK_ENABLE_FSGROUP value "". Defaulting to "true".
2019-10-21 20:50:34.254509 I | op-agent: rook-ceph-agent daemonset already exists, updating ...
2019-10-21 20:50:34.325584 I | op-discover: rook-discover daemonset already exists, updating ...
2019-10-21 20:50:34.384255 I | operator: Ceph CSI driver is enabled, validate csi param
2019-10-21 20:50:34.411463 W | operator: failed to start Ceph csi drivers: failed to load rbd plugin template: template: rbdplugin:27:71: executing "rbdplugin" at <.DriverNamePrefix>: can't evaluate field DriverNamePrefix in type csi.Param
2019-10-21 20:50:34.419326 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir
2019-10-21 20:50:34.419952 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir
2019-10-21 20:50:34.419973 I | operator: Watching all namespaces for cluster CRDs
I1021 20:50:34.422975       6 leaderelection.go:217] attempting to acquire leader lease  upgrade-ns-system/ceph.rook.io-block...
2019-10-21 20:50:34.420801 I | op-cluster: start watching clusters in all namespaces
2019-10-21 20:50:34.424103 I | op-cluster: Enabling hotplug orchestration: ROOK_DISABLE_DEVICE_HOTPLUG=
2019-10-21 20:50:34.426526 I | op-cluster: skipping watching for legacy rook cluster events (legacy cluster CRD probably doesn't exist): the server could not find the requested resource (get clusters.ceph.rook.io)
I1021 20:50:34.435572       6 leaderelection.go:217] attempting to acquire leader lease  upgrade-ns-system/rook.io-block...
2019-10-21 20:50:34.820676 I | op-cluster: starting cluster in namespace upgrade-ns
2019-10-21 20:50:40.906381 I | op-k8sutil: waiting for job rook-ceph-detect-version to complete...
I1021 20:50:51.098923       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"ceph.rook.io-block", UID:"b1fa2af5-dcec-4315-b944-7c79e2614bc4", APIVersion:"v1", ResourceVersion:"283042", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d88617c-f444-11e9-9dba-6a031b31d915 became leader
I1021 20:50:51.100055       6 leaderelection.go:227] successfully acquired lease upgrade-ns-system/ceph.rook.io-block
I1021 20:50:51.104739       6 controller.go:769] Starting provisioner controller ceph.rook.io/block_rook-ceph-operator-7f49d5bf5d-rkdwv_6d88617c-f444-11e9-9dba-6a031b31d915!
I1021 20:50:51.649803       6 leaderelection.go:227] successfully acquired lease upgrade-ns-system/rook.io-block
I1021 20:50:51.650617       6 controller.go:769] Starting provisioner controller rook.io/block_rook-ceph-operator-7f49d5bf5d-rkdwv_6d8986d5-f444-11e9-9dba-6a031b31d915!
I1021 20:50:51.650694       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"rook.io-block", UID:"fe926b7c-16d9-4996-9810-0cce29020854", APIVersion:"v1", ResourceVersion:"283045", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d8986d5-f444-11e9-9dba-6a031b31d915 became leader
I1021 20:50:51.751405       6 controller.go:818] Started provisioner controller rook.io/block_rook-ceph-operator-7f49d5bf5d-rkdwv_6d8986d5-f444-11e9-9dba-6a031b31d915!
I1021 20:50:51.805422       6 controller.go:818] Started provisioner controller ceph.rook.io/block_rook-ceph-operator-7f49d5bf5d-rkdwv_6d88617c-f444-11e9-9dba-6a031b31d915!
2019-10-21 20:51:23.240349 I | op-cluster: Detected ceph image version: 14.2.4 nautilus
2019-10-21 20:51:23.258507 I | op-cluster: CephCluster upgrade-ns status: Creating
2019-10-21 20:51:23.889863 I | op-mon: start running mons
2019-10-21 20:51:23.932953 I | op-mon: parsing mon endpoints: a=10.99.215.100:6789,b=10.96.48.61:6789,c=10.110.172.144:6789
2019-10-21 20:51:23.933061 I | op-mon: loaded: maxMonID=2, mons=map[a:0xc00090c840 b:0xc00090c880 c:0xc00090c8e0], mapping=&{Node:map[a:0xc00095db90 b:0xc00095dc20 c:0xc00095dc50] Port:map[]}
2019-10-21 20:51:23.974207 I | op-mon: saved mon endpoints to config map map[data:a=10.99.215.100:6789,b=10.96.48.61:6789,c=10.110.172.144:6789 maxMonId:2 mapping:{"node":{"a":{"Name":"k8s-master-0","Hostname":"k8s-master-0","Address":"172.60.2.228"},"b":{"Name":"k8s-master-0","Hostname":"k8s-master-0","Address":"172.60.2.228"},"c":{"Name":"k8s-master-0","Hostname":"k8s-master-0","Address":"172.60.2.228"}},"port":{}}]
2019-10-21 20:51:24.047532 I | cephconfig: writing config file /var/lib/rook/upgrade-ns/upgrade-ns.config
2019-10-21 20:51:24.047661 I | cephconfig: copying config to /etc/ceph/ceph.conf
2019-10-21 20:51:24.051354 I | cephconfig: generated admin config in /var/lib/rook/upgrade-ns
2019-10-21 20:51:25.578194 I | op-mon: targeting the mon count 3
2019-10-21 20:51:26.128331 I | op-mon: Found 0 running nodes without mons
2019-10-21 20:51:26.128441 I | op-mon: All nodes are running mons. Adding all 1 nodes to the availability.
2019-10-21 20:51:26.128463 I | op-mon: checking for basic quorum with existing mons
2019-10-21 20:51:26.607490 I | op-mon: mon a endpoint are [v2:10.99.215.100:3300,v1:10.99.215.100:6789]
2019-10-21 20:51:27.371248 I | op-mon: mon b endpoint are [v2:10.96.48.61:3300,v1:10.96.48.61:6789]
2019-10-21 20:51:28.570707 I | op-mon: mon c endpoint are [v2:10.110.172.144:3300,v1:10.110.172.144:6789]
2019-10-21 20:51:29.030009 I | op-mon: saved mon endpoints to config map map[data:a=10.99.215.100:6789,b=10.96.48.61:6789,c=10.110.172.144:6789 maxMonId:2 mapping:{"node":{"a":{"Name":"k8s-master-0","Hostname":"k8s-master-0","Address":"172.60.2.228"},"b":{"Name":"k8s-master-0","Hostname":"k8s-master-0","Address":"172.60.2.228"},"c":{"Name":"k8s-master-0","Hostname":"k8s-master-0","Address":"172.60.2.228"}},"port":{}}]
2019-10-21 20:51:30.386310 I | cephconfig: writing config file /var/lib/rook/upgrade-ns/upgrade-ns.config
2019-10-21 20:51:30.386523 I | cephconfig: copying config to /etc/ceph/ceph.conf
2019-10-21 20:51:30.386792 I | cephconfig: generated admin config in /var/lib/rook/upgrade-ns
2019-10-21 20:51:30.387253 I | cephconfig: writing config file /var/lib/rook/upgrade-ns/upgrade-ns.config
2019-10-21 20:51:30.387442 I | cephconfig: copying config to /etc/ceph/ceph.conf
2019-10-21 20:51:30.391699 I | cephconfig: generated admin config in /var/lib/rook/upgrade-ns
2019-10-21 20:51:30.463927 I | op-mon: deployment for mon rook-ceph-mon-a already exists. updating if needed
2019-10-21 20:51:30.493009 I | op-k8sutil: updating deployment rook-ceph-mon-a
2019-10-21 20:51:32.614111 I | op-k8sutil: finished waiting for updated deployment rook-ceph-mon-a
2019-10-21 20:51:32.633287 I | op-mon: deployment for mon rook-ceph-mon-b already exists. updating if needed
2019-10-21 20:51:32.636504 I | op-k8sutil: updating deployment rook-ceph-mon-b
2019-10-21 20:51:34.687024 I | op-k8sutil: finished waiting for updated deployment rook-ceph-mon-b
2019-10-21 20:51:34.716957 I | op-mon: deployment for mon rook-ceph-mon-c already exists. updating if needed
2019-10-21 20:51:34.719856 I | op-k8sutil: updating deployment rook-ceph-mon-c
2019-10-21 20:51:36.843192 I | op-k8sutil: finished waiting for updated deployment rook-ceph-mon-c
2019-10-21 20:51:36.843219 I | op-mon: mons created: 3
2019-10-21 20:51:36.843239 I | op-mon: waiting for mon quorum with [a b c]
2019-10-21 20:51:36.881813 I | op-mon: mons running: [a b c]
2019-10-21 20:51:36.890210 I | exec: Running command: ceph mon_status --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/163219535
2019-10-21 20:51:39.142999 I | op-mon: Monitors in quorum: [b a c]
2019-10-21 20:51:39.143035 I | exec: Running command: ceph version
2019-10-21 20:51:40.022706 I | exec: Running command: ceph versions
2019-10-21 20:51:40.840222 I | exec: Running command: ceph mon enable-msgr2
2019-10-21 20:51:42.234191 I | cephclient: successfully enabled msgr2 protocol
2019-10-21 20:51:42.245572 I | op-mgr: start running mgr
2019-10-21 20:51:42.248450 I | exec: Running command: ceph auth get-or-create-key mgr.a mon allow * mds allow * osd allow * --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/307192162
2019-10-21 20:51:43.122380 I | exec: Running command: ceph config-key get mgr/dashboard/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/305866585
2019-10-21 20:51:43.772822 I | exec: Error ENOENT: error obtaining 'mgr/dashboard/server_addr': (2) No such file or directory
2019-10-21 20:51:43.772993 I | exec: Running command: ceph config-key del mgr/dashboard/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/002534116
2019-10-21 20:51:44.502659 I | exec: no such key 'mgr/dashboard/server_addr'
2019-10-21 20:51:44.502775 I | op-mgr: clearing http bind fix mod=dashboard ver=12.0.0 luminous changed=false err=<nil>
2019-10-21 20:51:44.502870 I | exec: Running command: ceph config-key get mgr/dashboard/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/455454451
2019-10-21 20:51:45.838378 I | exec: Error ENOENT: error obtaining 'mgr/dashboard/a/server_addr': (2) No such file or directory
2019-10-21 20:51:45.838524 I | exec: Running command: ceph config-key del mgr/dashboard/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/606136758
2019-10-21 20:51:46.450386 I | exec: no such key 'mgr/dashboard/a/server_addr'
2019-10-21 20:51:46.450555 I | op-mgr: clearing http bind fix mod=dashboard ver=12.0.0 luminous changed=false err=<nil>
2019-10-21 20:51:46.450630 I | exec: Running command: ceph config get mgr.a mgr/dashboard/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/033510813
2019-10-21 20:51:47.306391 I | exec: Running command: ceph config rm mgr.a mgr/dashboard/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/859639896
2019-10-21 20:51:48.270555 I | op-mgr: clearing http bind fix mod=dashboard ver=13.0.0 mimic changed=true err=<nil>
2019-10-21 20:51:48.270638 I | exec: Running command: ceph config get mgr.a mgr/dashboard/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/821828055
2019-10-21 20:51:48.917471 I | exec: Running command: ceph config rm mgr.a mgr/dashboard/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/978409802
2019-10-21 20:51:49.737414 I | op-mgr: clearing http bind fix mod=dashboard ver=13.0.0 mimic changed=true err=<nil>
2019-10-21 20:51:49.738940 I | exec: Running command: ceph config-key get mgr/prometheus/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/789478433
2019-10-21 20:51:50.498575 I | exec: Error ENOENT: error obtaining 'mgr/prometheus/server_addr': (2) No such file or directory
2019-10-21 20:51:50.499299 I | exec: Running command: ceph config-key del mgr/prometheus/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/228840204
2019-10-21 20:51:51.530613 I | exec: no such key 'mgr/prometheus/server_addr'
2019-10-21 20:51:51.531492 I | op-mgr: clearing http bind fix mod=prometheus ver=12.0.0 luminous changed=false err=<nil>
2019-10-21 20:51:51.531607 I | exec: Running command: ceph config-key get mgr/prometheus/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/863920891
2019-10-21 20:51:52.534546 I | exec: Error ENOENT: error obtaining 'mgr/prometheus/a/server_addr': (2) No such file or directory
2019-10-21 20:51:52.534826 I | exec: Running command: ceph config-key del mgr/prometheus/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/128786974
2019-10-21 20:51:53.133122 I | exec: no such key 'mgr/prometheus/a/server_addr'
2019-10-21 20:51:53.133219 I | op-mgr: clearing http bind fix mod=prometheus ver=12.0.0 luminous changed=false err=<nil>
2019-10-21 20:51:53.133289 I | exec: Running command: ceph config get mgr.a mgr/prometheus/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/952658149
2019-10-21 20:51:53.802256 I | exec: Running command: ceph config rm mgr.a mgr/prometheus/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/918848768
2019-10-21 20:51:55.000373 I | op-mgr: clearing http bind fix mod=prometheus ver=13.0.0 mimic changed=false err=<nil>
2019-10-21 20:51:55.001166 I | exec: Running command: ceph config get mgr.a mgr/prometheus/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/315419231
2019-10-21 20:51:55.572193 I | exec: Running command: ceph config rm mgr.a mgr/prometheus/a/server_addr --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/651687474
2019-10-21 20:51:56.122071 I | op-mgr: clearing http bind fix mod=prometheus ver=13.0.0 mimic changed=false err=<nil>
2019-10-21 20:51:56.196955 I | op-mgr: deployment for mgr rook-ceph-mgr-a already exists. updating if needed
2019-10-21 20:51:56.211001 I | op-k8sutil: updating deployment rook-ceph-mgr-a
2019-10-21 20:51:58.250724 I | op-k8sutil: finished waiting for updated deployment rook-ceph-mgr-a
2019-10-21 20:51:58.251895 I | exec: Running command: ceph mgr module enable orchestrator_cli --force --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/281384425
2019-10-21 20:52:00.341872 I | exec: module 'orchestrator_cli' is already enabled (always-on)
2019-10-21 20:52:00.368738 I | exec: Running command: ceph mgr module enable rook --force --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/779831860
2019-10-21 20:52:02.755625 I | exec: module 'rook' is already enabled
2019-10-21 20:52:02.774998 I | exec: Running command: ceph orchestrator set backend rook --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/063204355
I1021 21:25:38.521312       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"ceph.rook.io-block", UID:"b1fa2af5-dcec-4315-b944-7c79e2614bc4", APIVersion:"v1", ResourceVersion:"287600", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d88617c-f444-11e9-9dba-6a031b31d915 stopped leading
I1021 21:25:38.523121       6 leaderelection.go:263] failed to renew lease upgrade-ns-system/ceph.rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
I1021 21:25:38.473251       6 leaderelection.go:263] failed to renew lease upgrade-ns-system/rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
I1021 21:25:38.619623       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"rook.io-block", UID:"fe926b7c-16d9-4996-9810-0cce29020854", APIVersion:"v1", ResourceVersion:"287599", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d8986d5-f444-11e9-9dba-6a031b31d915 stopped leading
F1021 21:25:38.643191       6 controller.go:847] leaderelection lost
F1021 21:25:38.693123       6 controller.go:847] leaderelection lost
```

**Comment by travisn** [comment] 2019-10-23 16:29
Looks like there was a gap in the log, as if it's hung on setting the rook orchestrator backend.
```
2019-10-21 20:52:02.774998 I | exec: Running command: ceph orchestrator set backend rook --connect-timeout=15 --cluster=upgrade-ns --conf=/var/lib/rook/upgrade-ns/upgrade-ns.config --keyring=/var/lib/rook/upgrade-ns/client.admin.keyring --format json --out-file /tmp/063204355
I1021 21:25:38.521312       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"upgrade-ns-system", Name:"ceph.rook.io-block", UID:"b1fa2af5-dcec-4315-b944-7c79e2614bc4", APIVersion:"v1", ResourceVersion:"287600", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7f49d5bf5d-rkdwv_6d88617c-f444-11e9-9dba-6a031b31d915 stopped leading
```
The orchestrator module seems to be the one blocking continuing with the osd orchestration. 

Interestingly, there is also an error starting the csi driver:
```
2019-10-21 20:50:34.411463 W | operator: failed to start Ceph csi drivers: failed to load rbd plugin template: template: rbdplugin:27:71: executing "rbdplugin" at <.DriverNamePrefix>: can't evaluate field DriverNamePrefix in type csi.Param
```

**Comment by travisn** [comment] 2019-10-23 16:30
If it is caused by the mgr module hang, I would expect this to be fixed by #4021.

**Comment by BlaineEXE** [comment] 2019-10-23 19:44
I'll pull the latest master and start trying to test again in my env with limited resources to see if it gets fixed.

**Comment by BlaineEXE** [comment] 2019-10-23 20:51
Not caused by the mgr module hang. I repro-ed with masters' changes which include #4021.

**Comment by kzh** [comment] 2019-11-17 06:00
I'm having the same issue on my kubernetes cluster with rook-ceph v1.1.
```
csi-cephfsplugin-provisioner-75c965db4f-7g8sd   4/4     Running     15         99m
csi-cephfsplugin-provisioner-75c965db4f-k7tlb   4/4     Running     7          99m
csi-cephfsplugin-spj6n                          3/3     Running     0          99m
csi-rbdplugin-provisioner-56cbc4d585-jpt98      5/5     Running     10         99m
csi-rbdplugin-provisioner-56cbc4d585-rfndh      5/5     Running     21         99m
csi-rbdplugin-vr6hm                             3/3     Running     0          99m
rook-ceph-mgr-a-799cd96bdd-vc8dj                1/1     Running     9          98m
rook-ceph-mon-a-5fc6c66b55-b8g7v                1/1     Running     0          98m
rook-ceph-operator-d6d6b84dc-krt29              1/1     Running     11         103m
rook-ceph-osd-0-6496c4d87c-rhxpz                1/1     Running     0          97m
rook-ceph-osd-prepare-faust-fb4pc               0/1     Completed   0          4m27s
rook-discover-nhqm2                             1/1     Running     0          103m
```
These pods have been constantly crashing and restarting due to:
```
I1117 05:48:54.274816       6 leaderelection.go:263] failed to renew lease rook-ceph/rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
F1117 05:48:54.274890       6 controller.go:847] leaderelection lost
```
I'm running on a single node cluster. The specs are:
```
Intel® 2xE5 - 2660
16C/32T - 2.2/3.0GHz
256GB DDR3 Ram
```

**Closed** 2020-02-22 06:54 UTC
Labels: bug, ceph -, objectbucket, wontfix
