### ISSUE TITLE
attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.cephfs.csi.ceph.com not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by leiw324** [rook/rook#6155] opened 2020-08-25 15:41 UTC
Hello,

k8s version:
![image](https://user-images.githubusercontent.com/33790160/91196062-45921400-e72c-11ea-8d67-aa88828cbdf1.png)
![image](https://user-images.githubusercontent.com/33790160/91196086-4a56c800-e72c-11ea-92b3-003e0c3c74a2.png)

CentOS version:
![image](https://user-images.githubusercontent.com/33790160/91196138-56428a00-e72c-11ea-93ac-97ea1fdfbe8c.png)

rook-ceph version:
1.3.0

I had installed successfully wordpress deployment few days ago, but I just checked wordpress pod has problem:
![image](https://user-images.githubusercontent.com/33790160/91195689-cf8dad00-e72b-11ea-81e2-35b003f77604.png)
But three wordpress pods are running:
![image](https://user-images.githubusercontent.com/33790160/91195785-e8965e00-e72b-11ea-89a3-9cc20d8fe561.png)
https://paste.ubuntu.com/p/4f6h6gzqsw/

service
![image](https://user-images.githubusercontent.com/33790160/91206276-7b89c500-e739-11ea-9be0-d530c1e35272.png)
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app-service
spec:
  ports:
  - port: 80
    nodePort: 30315
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-deployment
  type: NodePort

I checked csi-attacher has error:
![image](https://user-images.githubusercontent.com/33790160/91195857-fcda5b00-e72b-11ea-82ad-2b5ccae35d2b.png)

I can't go to Wordpress with IP:30315, so I think is rook-ceph problem, what I can do ?

Thanks

**Comment by Madhu-1** [comment] 2020-09-09 14:42
I see error retrieving resource lock issues in the attacher pod. this is related to kubernetes as attacher is not able to connect to the kubernetes cluster.

>ceph.cephfs.csi.ceph.com not found in the list of registered CSI drivers

This issue can be fixed by restarting csi-cephfspluing pod on the node where the mount is failing

**Comment by Madhu-1** [comment] 2020-09-09 14:46
I see that application came up eventually I don't think its an issue with rook-ceph

**Comment by DjVinnii** [comment] 2020-12-04 13:21
I encountered the same problem: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.cephfs.csi.ceph.com not found in the list of registered CSI drivers. 


Currently I am running a single virtual machine running Ubuntu Server 20.04 with microk8s v1.19.3. I enabled the following microk8s add-ons: rbac, dns and the dashboard. Rook v1.5.2 was deployed by following the Ceph Storage Quickstart guide. However I used the cluster-test.yaml instead of the cluster.yaml.

The shared filesystem was deployed by following the Shared Filesytem guide. Again by using the filesystem-test.yaml instead of the filesystem.yaml.

Creating a Persistent Volume Claim works perfectly fine. But attaching the PVC to an pod gives the error.

When I run `kubectl get CSIDriver,` both the rbd and cephfs drivers are shown. 
![CSIDriver](https://user-images.githubusercontent.com/14043916/101168373-a5f1f500-363b-11eb-8252-3a853e3c705c.PNG)

When I checked the csi-attacher logs, no errors were showing up.
![csi-attacher logs](https://user-images.githubusercontent.com/14043916/101168533-dcc80b00-363b-11eb-94da-68b835b42459.PNG)

**Comment by Madhu-1** [comment] 2020-12-04 13:32
@DjVinnii do you see any error on cephfsplugin pod. you need to look into driver-registrar and cephfsplugin container. restarting cephfsplugin pod should also help sometimes.

**Comment by Madhu-1** [comment] 2020-12-04 13:34
@DjVinnii for microk8s kubelet path is not `/var/lib/kubelet` by default you need to adjust https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L68 to `/var/snap/microk8s/common/var/lib/kubelet` can you check the `root-dir` on the kubelet process on the microk8s nodes `ps -ef |grep kubelet` should help you

**Comment by DjVinnii** [comment] 2020-12-04 13:42
@Madhu-1 Thank you for the quick reply! Changing the `ROOK_CSI_KUBELET_DIR_PATH` to `/var/snap/microk8s/common/var/lib/kubelet` did the job.

**Closed** 2021-03-11 20:07 UTC
Labels: wontfix

**Comment by ArmitageW** [comment] 2021-05-08 02:23
I deployed ceph according to rook1.6, the version of kubernetes is 1.19, and the working directory of kubernetes is /var/lib/kubelet. But also encountered this problem. There is no error log for csi-rbdplugin. The csi driver name cannot be found when pvc is mounted.

![image](https://user-images.githubusercontent.com/40707671/117522550-b3dee400-afe6-11eb-9756-75babe559561.png)

Error log:
`Warning  FailedMount  60s (x392 over 13h)  kubelet, kube-master3  MountVolume.MountDevice failed for volume "pvc-961146b9-f661-4938-a216-6083c7424036" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers`

![image](https://user-images.githubusercontent.com/40707671/117522701-5a2ae980-afe7-11eb-9201-513519209c36.png)

**Comment by rsoika** [comment] 2021-06-11 15:18
did you found a solution? I have also the problem of the missing /var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock

**Comment by diskun00** [comment] 2021-06-12 19:44
I encountered similar issues today, yet it's due to arrange my pod on the master node which has noschedule taint. Though pod can be successfully assigned on the node, PVC can never be mounted. After I assign this pod to other nodes, the issue is gone:D therefore, we may also need to add tolerations for PVC or something

**Comment by yelnylee** [comment] 2022-03-04 08:41
> @DjVinnii for microk8s kubelet path is not `/var/lib/kubelet` by default you need to adjust https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L68 to `/var/snap/microk8s/common/var/lib/kubelet` can you check the `root-dir` on the kubelet process on the microk8s nodes `ps -ef |grep kubelet` should help you

in rook 1.8.6 ,need set the path to "kubeletDirPath" properties

**Comment by toresbe** [comment] 2023-05-30 17:00
I encountered this with Rook 1.11.6 deployed with a Helm chart.

The necessary modification to the rook-ceph chart from rook-release was:
`csi:
  kubeletDirPath: "/var/snap/microk8s/common/var/lib/kubelet"`
