### ISSUE TITLE
CSI is not able to communicate with ceph cluster

### ISSUE THREAD

**Issue by kariae** [rook/rook#3318] opened 2019-06-18 10:36 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PVC stuck in pending

**Expected behavior:**
Created PVC

**How to reproduce it (minimal and precise):**

Not sure how to reproduce it, the cluster was working fine until some pods (that use some PVCs stopped working), the logs of the provisioner container shows:
```
GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-7f0cdb89-91b1-11e9-ad2a-0007cb0b2965","parameters":{"adminid":"admin","fstype":"xfs","imageFeatures":"layering","imageFormat":"2","monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789","pool":"rbd","userid":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}}]}
I0618 10:14:18.560987       1 controller.go:191] GRPC response: {}
I0618 10:14:18.562281       1 controller.go:192] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
W0618 10:14:18.562456       1 controller.go:592] CreateVolume timeout: 10s has expired, operation will be retried
```

When I checked the processes on the `rbdplugin` container (as per @Madhu-1 ) I found some stuck processes there:
```
ps -ef |grep ceph
root         1     0  0 05:42 ?        00:00:01 /usr/local/bin/cephcsi-rbd --nodeid=bkpr-ams-meliodas --endpoint=unix:///csi/csi-provisioner.sock --v=5 --drivername=rbd.csi.ceph.com --containerized=true --metadatastorage=k8s_configmap
root       268     1  0 10:08 ?        00:00:00 rbd status pvc-c813ea67-918e-11e9-ad2a-0007cb0b2965 --pool rbd -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789 --id admin --key=AQC/eQhdSTjBEhAATknMoEmMyCqUqjc8ZIPbiA==
root       288     1  0 10:09 ?        00:00:00 rbd status pvc-1543dc68-91b1-11e9-ad2a-0007cb0b2965 --pool rbd -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789 --id kubernetes --key=AQASeghdnS4vCRAA5uVxh1Ho62PKbjyANQ7J7w==
root       312     1  0 10:11 ?        00:00:00 rbd status pvc-7f0cdb89-91b1-11e9-ad2a-0007cb0b2965 --pool rbd -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789 --id kubernetes --key=AQASeghdnS4vCRAA5uVxh1Ho62PKbjyANQ7J7w==
root       338   332  0 10:28 pts/3    00:00:00 grep ceph
```

```
sh-4.2# ps -ef |grep rbd
root         1     0  0 05:42 ?        00:00:01 /usr/local/bin/cephcsi-rbd --nodeid=bkpr-ams-meliodas --endpoint=unix:///csi/csi-provisioner.sock --v=5 --drivername=rbd.csi.ceph.com --containerized=true --metadatastorage=k8s_configmap
root       268     1  0 10:08 ?        00:00:00 rbd status pvc-c813ea67-918e-11e9-ad2a-0007cb0b2965 --pool rbd -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789 --id admin --key=AQC/eQhdSTjBEhAATknMoEmMyCqUqjc8ZIPbiA==
root       288     1  0 10:09 ?        00:00:00 rbd status pvc-1543dc68-91b1-11e9-ad2a-0007cb0b2965 --pool rbd -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789 --id kubernetes --key=AQASeghdnS4vCRAA5uVxh1Ho62PKbjyANQ7J7w==
root       312     1  0 10:11 ?        00:00:00 rbd status pvc-7f0cdb89-91b1-11e9-ad2a-0007cb0b2965 --pool rbd -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789 --id kubernetes --key=AQASeghdnS4vCRAA5uVxh1Ho62PKbjyANQ7J7w==
root       340   332  0 10:28 pts/3    00:00:00 grep rbd
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): Linux master-serv 4.9.93-mainline-rev1
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0
* Kubernetes version (use `kubectl version`): 1.14.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment] 2019-06-18 10:40
@travisn can you please tell how to proceed further? rbd commands are struck for long time

**Comment by travisn** [comment] 2019-06-18 22:55
Typically if the rbd commands are stuck, it's because the mons are either not accessible (network issue), the mons have lost quorum, or the driver doesn't have the latest list of mons. Since you probably created the cluster before #3271 was just merged, you may have outdated mons since that list had to be populated manually in the past. If the operator has failed over the mons, the list of mons may be different now.

**Comment by kariae** [comment] 2019-06-19 05:26
@travisn thanks for the explanation, so a turnaround for this would be to upgrade to master branch since the latest release doesn't include the PR?

Is there anyway to upgrade the current cluster, or should I remove it and re-create everything again?

**Comment by Madhu-1** [comment] 2019-06-19 06:20
@travisn as you can see `rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-b.rook-ceph.svc.cluster.local:6789,rook-ceph-mon-c.rook-ceph.svc.cluster.local:6789` CSI is using service URL to communicate with mon pods.

any pointer to check network issue on the quorum lost status?

@kariae can you paste operator pod logs?

**Comment by humblec** [comment] 2019-06-19 06:52
I am wondering `rook-ceph-mon-a.rook-ceph.svc.cluster.local` is a resolvable url or not ?

**Comment by Madhu-1** [comment] 2019-06-19 06:59
@humblec the above URL is resolvable we are using the same in csi 
https://github.com/ceph/ceph-csi/blob/7f993707ca9f575fabd78926806d3a6532d3e356/e2e/utils.go#L138

**Comment by humblec** [comment] 2019-06-19 07:00
> @humblec the above URL is resolvable we are using the same in csi
> https://github.com/ceph/ceph-csi/blob/7f993707ca9f575fabd78926806d3a6532d3e356/e2e/utils.go#L138

Yeah, I was pointing to this specific setup.

**Comment by LeoAdamek** [comment] 2019-08-09 13:37
I'm also having this exact same issue using CSI for CephFS. I've checked the `csi-cephfsplugin-provisioner-0` is able to resolve the mon addresses `rook-ceph-mon-{a,b,c}` and is able to connect to them. But I still get a timeout provisioning a new PVC>

**Comment by rjasper-frohraum** [comment] 2019-08-27 12:06
My system showed similar symptoms. The `rdb` command got stuck because I misconfigured the auth entry for `client.kubernetes`. However, the cause might not be the same since `--id admin --key=<admin key>` worked just fine in my case.

**Closed** 2019-12-02 13:19 UTC
Labels: bug, wontfix
