### ISSUE TITLE
Rook CSI RBD Plugin can't start on host nodes that lack the findmnt binary

### ISSUE THREAD

**Issue by rajha-korithrien** [rook/rook#3923] opened 2019-09-19 19:56 UTC
**Is this a bug report or feature request?**
* Bug Report
There is only one other issue that mentions ```findmnt``` #3726 but I don't think it is related.

**Deviation from expected behavior:**
csi-rdbplugin fails to start on any node in the cluster

**Expected behavior:**
csi-rbdplugin should start on all nodes in the cluster

**How to reproduce it (minimal and precise):**
Deploy Kubernetes via Rancher RKE onto some number of RancherOS (bare metal) nodes.
Some things to note:
* This will deploy kubernetes via Docker using ```hyperkube```
* RancherOS (by default) doesn't supply a ```findmnt``` binary or a ```stat``` binary
* Using Rook via the Flex Volume system works fine on Rancher

Ensure you pass "extra_binds" arguments so kubelet gains access to host directories (much as is done when using the Flex volume system).
```text
extra_binds:
      - "/usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
      - "/var/lib/kubelet/plugins_registry:/var/lib/kubelet/plugins_registry"
      - "/var/lib/kubelet/pods:/var/lib/kubelet/pods:shared,z"
```

I had a previously working Rook 1.0.6/Ceph 14.2.x installation and followed these upgrade instructions to move from 1.0.6 to 1.1.0. I had not used the Ceph CSI driver before now.

https://rook.io/docs/rook/v1.1/ceph-upgrade.html

At the step where the Rook operator is updated (I had to manually fix some minor RBAC issues  see #3868 ) the result is ```csi-rdbplugin``` fails to deploy on each cluster host node. The related ```driver-registrar``` and ```liveness-prometheus``` deploy correctly.

**File(s) to submit**:
* Crashing pod(s) logs, if necessary
This is the log from ```csi-rdbplugin```
```text
I0919 19:27:26.963369 19679 cephcsi.go:103] Driver version: v1.2.0 and Git version: c420ee6de9e2f90fcce97b2700c0fd57845225c3
E0919 19:27:26.965139 19679 cephcsi.go:128] Failed to get the PID limit, can not reconfigure: open /sys/fs/cgroup/pids/docker/e7caa2de7b1e1640df0b2382774a3bd653343364391fdfc99aa572dfaa6160f4/kubepods/besteffort/pod48425a55-daef-11e9-9ffd-e0db5570db32/8a9f453be111b13efed122df4bb56528d94f6c4a0662d56cd222ced80f4b3b39/pids.max: no such file or directory
I0919 19:27:26.965342 19679 cephcsi.go:158] Starting driver type: rbd with name: paas-rook-ceph.rbd.csi.ceph.com
I0919 19:27:26.976889 19679 mount_linux.go:170] Cannot run systemd-run, assuming non-systemd OS
I0919 19:27:26.976926 19679 mount_linux.go:171] systemd-run failed with: exit status 1
I0919 19:27:26.976953 19679 mount_linux.go:172] systemd-run output: Failed to create bus connection: No such file or directory
F0919 19:27:26.977175   19679 driver.go:145] failed to start node server, err unable to find findmnt
```
**Discussion**
I have tracked this down to the use of ```quay.io/cephcsi/cephcsi:v1.2.0``` which eventually calls into Kubernetes code (in ```nsenter```) that checks for the tools it needs:
```go
binaries := []string{
		"mount",
		"findmnt",
		"umount",
		"systemd-run",
		"stat",
		"touch",
		"mkdir",
		"sh",
		"chmod",
		"realpath",
}
// search for the required commands in other locations besides /usr/bin
for _, binary := range binaries {
	// check for binary under the following directories
	for _, path := range []string{"/", "/bin", "/usr/sbin", "/usr/bin"} {
		binPath := filepath.Join(path, binary)
		if _, err := os.Stat(filepath.Join(ne.hostRootFsPath, binPath)); err != nil {
			continue
		}
		ne.paths[binary] = binPath
		break
	}
	// systemd-run is optional, bailout if we don't find any of the other binaries
	if ne.paths[binary] == "" && binary != "systemd-run" {
		return fmt.Errorf("unable to find %v", binary)
	}
}
```
Which I am fairly sure gets its "hostRootFsPath" from the yaml Rook used to deploy ```csi-rbdplugin```
```yaml
env:
- name: HOST_ROOTFS
   value: /rootfs
...
volumeMounts:
- mountPath: /rootfs
   name: host-rootfs
...
volumes:
- hostPath:
      path: /
      type: ""
    name: host-rootfs
```
The binaries needed exist in the ```quay.io/cephcsi/cephcsi:v1.2.0``` image. Is there a way to configure the CephCSI driver to look for the binaries in the container rather than in a filesystem mounted from the host?

**Environment**:
* OS (e.g. from /etc/os-release):
```text
NAME="RancherOS"
VERSION=v1.5.1
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.1
PRETTY_NAME="RancherOS v1.5.1"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```
* Kernel (e.g. `uname -a`):
```Linux host-0 4.14.85-rancher #1 SMP Sat Dec 1 12:40:08 UTC 2018 x86_64 GNU/Linux```
* Cloud provider or hardware configuration:
Private bare metal
* Rook version (use `rook version` inside of a Rook Pod):
```rook: v1.1.0```
* Storage backend version (e.g. for ceph do `ceph -v`):
```ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)```
* Kubernetes version (use `kubectl version`):
```text
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Using Rancher 2.2.8
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```text
[root@host-0 /]# ceph health
HEALTH_OK
[root@host-0 /]#
```

**Comment by martinlindner** [comment] 2019-09-20 03:48
I'm seeing exactly the same behavior with a fresh installation (via the helm chart) of rook-ceph v1.1.0 on a Rancher 2.2.8-provisioned lab cluster.

Is there any workaround to get this running on RancherOS (except for going non-CSI with v1.0.x)?

* OS:
```
NAME="RancherOS"
VERSION=v1.5.4
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.4
PRETTY_NAME="RancherOS v1.5.4"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```
* Kernel:
```
Linux lab-worker1 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* Rook version:
```
rook: v1.1.0
```
* Storage backend version:
```
ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)
```
* Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Storage backend status:
```
HEALTH_OK
```

**Comment by Madhu-1** [comment] 2019-09-20 05:32
@martinlindner @ajha-korithrien I have  never tried Rancher is there I way to  deploy it using vagrant  so that I can reproduce locally and to fix and test it

there is a flag in csi to disable use of `nsenter`, can you try it out https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml#L57
edit the daemon set and set the above value to false (this is just a temp fix to  try out) let  me know if it works will make it as configurable

**Comment by rajha-korithrien** [comment] 2019-09-20 13:26
@Madhu-1 I have never used vargrant to setup Rancher, but the project has instructions for how to do it.

https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-vagrant/

However I doubt it is Rancher the Kubernetes as a Service project that is the issue, I believe it is RancherOS the tiny Linux distro. There is an out of support Github project for Vargrant and RancherOS

https://github.com/rancher/os-vagrant

Which says they officially support ```docker-machine``` with a number of different hypervisors.

https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/docker-machine/

**Comment by Madhu-1** [comment] 2019-09-20 13:33
https://github.com/rook/rook/pull/3931 removes the use of  `nsenter` which checks for binaries in rbd

**Comment by rajha-korithrien** [comment] 2019-09-20 13:36
@Madhu-1 @martinlindner I can confirm that setting ```--containerized=false``` from the current default of ```--containerized=true``` does cause ```csi-rbdplugin``` to deploy properly. I will test that it correctly allocates volumes are report back.

**Comment by rajha-korithrien** [comment] 2019-09-20 17:01
@Madhu-1 I doubt this is related but while I have running csi-rdbplugin pods, ```rook-ceph-osd-prepare-*``` pods fail with the following error in their logs:

```text
2019-09-20 16:45:59.209876 I | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 --block-db-size 5242880000 /dev/zd0 --db-devices /dev/zd16 --report
2019-09-20 16:46:16.393841 I | --> AttributeError: 'MixedType' object has no attribute 'total_available_db_space'
failed to configure devices. failed to configure devices with ceph-volume. failed to initialize devices. failed ceph-volume report. Failed to complete '': exit status 1.
```
At first glance this seems related to #2659 but it is not as I had a perfectly working 1.0.6 deployment before the upgrade.

**Comment by rajha-korithrien** [comment] 2019-09-22 13:54
@Madhu-1 I can confirm that after fixing the "AttributeError: 'MixedType' issue, your fix for ```--containerized=false``` works correctly.

I now have a properly operating Rook 1.1.0 cluster using the CSI RBD Plugin system.

**Comment by Madhu-1** [comment] 2019-09-23 04:57
@rajha-korithrien Thanks for testing this one. once https://github.com/rook/rook/pull/3931 is merged this will be fixed

**Comment by Madhu-1** [comment] 2019-09-23 04:58
> @Madhu-1 I can confirm that after fixing the "AttributeError: 'MixedType' issue, your fix for `--containerized=false` works correctly.
> 
> PVC are now correctly bound however they do not make it into the pod. With the error:
> 
> ```
> driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers
> ```
> 
> Is this issue related?

seeing this for the first time. can you check the driver-register log in rbd plugin pod?

**Comment by martinlindner** [comment] 2019-09-23 07:20
@Madhu-1 @rajha-korithrien
I finally had some time to play with this, too, and I can confirm that `--containerized=false` fixes the initial deployment issue with `csi-rdbplugin`.

Furthermore I'm also seeing the `driver .. not found` issue, for _both_ `cephfs` and `rbd`.

Apparently this is fairly specific to [RKE](https://github.com/rancher/rke) clusters:
RKE runs `kubelet` in a container with `--root-dir=/opt/rke/var/lib/kubelet` and matching bind mount to the same dir on the host. Since rook's `csi-*plugin` have `/var/lib/kubelet/` paths hardcoded, the CSI drivers and sockets end up in a location where the kubelet can't see them. As a quick test, i patched all paths in the `csi-*plugin` daemonsets and things started working for me ..

For reference, it looks like the Rancher devs ran into a similar issue with their own [Longhorn](https://github.com/longhorn/longhorn) storage engine a while ago:
https://github.com/longhorn/longhorn/issues/198

Apparently their fix was to auto-detect the kubelet's `root-dir` during deployment:
https://github.com/longhorn/longhorn-manager/pull/242

Do you think something similar would be possible for Rook's CSI driver deployers?

**Comment by Madhu-1** [comment] 2019-09-23 07:37
@martinlindner we made kubelet path configurable during deployment in rook see https://github.com/rook/rook/pull/3927

**Comment by martinlindner** [comment] 2019-09-23 10:08
@Madhu-1:
Great. Sorry, I did't notice you had already added that. 

I just did a a fresh deployment from `master`, with the following added to `operator.yaml`:

```yaml
- name: FLEXVOLUME_DIR_PATH
  value: "/var/lib/kubelet/volumeplugins"

- name: ROOK_CSI_KUBELET_DIR_PATH
  value: "/opt/rke/var/lib/kubelet"
```

After putting `--containerized=false` into the `csi-rbdplugin` daemonset, things seem to work fine.  

I did a quick test with rbd.csi and cephfs.csi storage classes and the PVs did provision **and** attach to pods as expected.

So, here's hoping for your fix for the original `nsenter` issue to make it into `master` soon.

**Comment by jeffreyvdhondel** [comment] 2019-09-23 10:11
Having the same error when deploying to a digitalocean cluster 1.0 works fine.
Will wait for the 1.x fix for this 'problem'.

**Comment by Madhu-1** [comment] 2019-09-23 10:11
@martinlindner Thanks for testing it out, removal of `nsenter` is still under discussion in ceph-csi. will update PR once it's fixed.

**Comment by rajha-korithrien** [comment] 2019-09-23 16:40
@martinlindner Thanks for tackling where RKE puts stuff. I was still trying to use the ```extra_binds``` configuration with ```/var/lib/kubelet``` and had not even realized that RKE deployed kublet to ```/opt/rke/var/lib/kubelet```.

@Madhu-1 I can confirm that with the changes you provided for ```--containerized=false``` on ```csi-rbdplugin``` and setting ```ROOK_CSI_KUBELET_DIR_PATH``` as provided by martinlinder, everything works as expected.

**Closed** 2019-09-24 04:21 UTC
Labels: bug, ceph -

**Comment by Madhu-1** [comment] 2019-09-24 04:23
@rajha-korithrien @martinlindner @jeffreyvdhondel  this is now fixed in the master is it possible to give a try?

**Comment by martinlindner** [comment] 2019-09-25 07:23
@Madhu-1 Sure, I wanted to try out the helm chart anyways.

I can confirm that this works great with Rancher v2.2.8 (RKE v0.2.8) + RancherOS v1.5.4:

```bash
helm install \
  --namespace rook-ceph rook-master/rook-ceph \
  --version v1.1.0-beta.0.175.g9bcdbea \
  --set agent.flexVolumeDirPath=/var/lib/kubelet/volumeplugins \
  --set csi.kubeletDirPath=/opt/rke/var/lib/kubelet
```

Thanks a lot for getting this fixed so quickly.

**Comment by FinnGu** [comment] 2019-10-15 09:21
> Having the same error when deploying to a digitalocean cluster 1.0 works fine.
> Will wait for the 1.x fix for this 'problem'.

Did you get rook to work with digitalocean eventually?

**Comment by midacts** [comment] 2019-10-20 04:23
I am running Rancher k3s and I ran into this issue as well.
Updating the `operator.yaml` file with the below settings fixed the issue for me.

#4133 Thanks Madhu-1

```text
- name: ROOK_CSI_KUBELET_DIR_PATH
  value: "/var/lib/rancher/k3s/agent/kubelet"
```

**Comment by auguster** [comment] 2020-02-11 14:16
Would it be possible to have a nodeselector on this configuration env ?
I have a kubernetes cluster which mixes debian nodes (for Cuda) and rancheros nodes (for everything else). If I set this `ROOK_CSI_KUBELET_DIR_PATH` cluster wide it either work on rancheros or debian but cannot get it to work on both at the same time.

**Comment by Madhu-1** [comment] 2020-02-11 15:27
@auguster am not sure you can select different KUBELET_DIR_PATH for different nodes in your cluster

**Comment by auguster** [comment] 2020-02-11 15:56
Yeah, I don't think so either. I tried to mount bind the kubelet folder from `/var/lib/kubelet` to `/opt/rke/var/lib/kubelet` on debian (or the other way around on rancheros) but each time kubernetes cannot mount the volume with the error that some subpath "is not a directory". It looks like kubernetes manage to ignore my bind mount somehow. I tried symlinks but it fails the same way :/

**Comment by travisn** [comment] 2020-02-11 16:02
As long as we're using a daemonset for the driver, not sure a solution for this. If Rook were to create a deployment per-node instead of a daemonset, it could detect a node label and use it. Not exactly a trivial change, but seems possible...

**Comment by ShyamsundarR** [comment] 2020-02-11 16:16
> Yeah, I don't think so either. I tried to mount bind the kubelet folder from `/var/lib/kubelet` to `/opt/rke/var/lib/kubelet` on debian (or the other way around on rancheros) but each time kubernetes cannot mount the volume with the error that some subpath "is not a directory". It looks like kubernetes manage to ignore my bind mount somehow. I tried symlinks but it fails the same way :/

Bind mount or symlinks will not work, as the call to NodeStageVolume passes in the root-dir as the kubelet understands, and ceph CSI plugin searches for the passed in path, which is not available within the node plugin container (as this is set via ROOK_CSI_KUBELET_DIR_PATH).

IOW, the CSI NodeStageVolume call gets `/<root-dir>/...` and depending on your system this may not be a mounted volume within the nodeplugin container, causing the stage/mount to fail.

One _crude_ alternative for your case could be, to pass in both paths as volumes to the node plugin. Hence all daemon set pods get both, and depending on the kube `root-dir` setting on the node, one or the other will find the path and stage/mount the volume. IOW, add 2 more paths [here](https://github.com/ceph/ceph-csi/blob/8dcb6a6105f5f890c5f4e86e1208774262847070/deploy/rbd/kubernetes/csi-rbdplugin.yaml#L101-L106) and [here](https://github.com/ceph/ceph-csi/blob/8dcb6a6105f5f890c5f4e86e1208774262847070/deploy/rbd/kubernetes/csi-rbdplugin.yaml#L136-L143)

**Comment by auguster** [comment] 2020-02-11 16:35
I don't understand how I could provide two path with the same name. Furthermore I don't think my container can have the `Running` status if one of the mount fails.
I'm thinking of installing the same distro on each node...

**Comment by ShyamsundarR** [comment] 2020-02-11 16:39
> I don't understand how I could provide two path with the same name. Furthermore I don't think my container can have the `Running` status if one of the mount fails.

My comment assumes you create the non-root-dir path directory (a dummy, or soft link or bind mount), so that the volume mount to the nodeplugin pod does not fail. Further, you would provide additional names, not the same name for the volume mount (i.e plugin-dir-2 and `mountpoint-dir-2` or some such), and hence have both paths available within all nodeplugin containers.

> I'm thinking of installing the same distro on each node...

This is of course the better option :)

**Comment by rajha-korithrien** [comment] 2020-02-11 21:08
If you are using RKE / Rancher to deploy your Kubernetes on top of your Debian / RancherOS then there is a solution from the Rancher/RKE side. If you are not using these then this will not help.

You can tell Rancher / RKE to use the same kubelet rootdir setting by changing the configuration you give to RKE or by using the Rancher to change the yaml that defines your cluster.

```text
kubelet:
      extra_args:
        root-dir: /opt/rke/var/lib/kubelet
        volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      extra_binds:
         - '/usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec'
        - '/var/lib/kubelet/plugins_registry:/var/lib/kubelet/plugins_registry'
        - '/var/lib/kubelet/pods:/var/lib/kubelet/pods:shared,z'
        - '/opt/rke/var/lib/kubelet:/opt/rke/var/lib/kubelet:shared,z'
```

We force root-dir to be a uniform value, then we ensure that all the folders we need for flex and csi plugins get bind mounted into the kubelet container from the host.

I have an issue open with the Rancher team that is related. https://github.com/rancher/rancher/issues/24886

**Comment by zzvara** [comment] 2020-03-31 20:19
Kubelet root directory was changed on **some** of the nodes. Setting the `csi.kubeletDirPath: /data1/kubelet` did the trick. I also moved `kubelet` root directory for all nodes to `/data1`.
