### ISSUE TITLE
Prometheus annotations on MGR have moved and no longer work with default prometheus config

### ISSUE THREAD

**Issue by robertrbruno** [rook/rook#3477] opened 2019-07-18 18:21 UTC
In previous versions of Rook the prometheus annotations on the MGR deployment were in one of the metadata sections of a template section in the yaml (a few levels deep).  In Rook 1.0.4 (using ceph 14.2.1), the prometheus annotations are now at the top most annotation section of the deployment.

This location of annotations does not work with the default jobs in the prometheus helm chart while the old location did.  I edited the yaml and placed the annotations where they used to be and now prometheus is reading from rook just fine.

Any chance these can be moved back unless there is a specific reason for the move?

**Comment by galexrt** [comment] 2019-07-19 04:34
The issue has been fixed on `master` and backported to `release-1.0` branch, see below refs, by moving the MGR default annotations to be correctly set and moved down to the Pod Template Spec.

So seems like a duplicate of #3204. Related PRs: #3453 and #3464

**Comment by evrardjp** [comment] 2019-08-23 10:08
If this is a duplicate, should we close it?

**Closed** 2019-11-28 10:20 UTC
Labels: bug, wontfix
