### ISSUE TITLE
Bad disk should not cause osd pod to crash loop

### ISSUE THREAD

**Issue by aramisjohnson** [rook/rook#1331] opened 2017-12-19 19:00 UTC
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
The osd pod on the node that contains the bad disk will crashloop with the following error in its log

```
2017-12-19 17:54:11.270328 I | exec: Running command: lsblk /dev/sdn --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2017-12-19 17:54:11.278408 I | exec: Running command: blkid /dev/sdn1 -s PARTLABEL -o value
failed to get available devices. failed to get device sdn info. failed to get sdn partitions. failed to get partition label for device sdn1: Failed to complete blkid /dev/sdn1: exit status 2
```

What you expected to happen:
Rook should notify that there is a bad disk, continue starting osd processes and the osd pod should be in a running state.

How to reproduce it (minimal and precise):
Install bad disk on any node in the Rook cluster, install Rook.

**Feature Request**

Are there any similar features already existing:

What should the feature do:

What would be solved through this feature:
Rook should notify that there is a bad disk, continue starting osd processes and the osd pod should be in a running state.

Does this have an impact on existing features:
Cannot create an Object Store

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment] 2017-12-20 18:28
I think a good way for a notification to the user would be through the already existing metrics for the OSD status (up in this case), this in combination as @aramisjohnson wrote that the other OSDs are still started would do the trick to see failed disks then.

**Comment by jpds** [comment] 2017-12-26 12:16
This is a sort of duplicate of #718.

**Comment by jbw976** [comment] 2018-02-26 23:13
This behavior will be addressed by #1341

**Closed by jbw976** 2018-02-26 23:13 UTC
