### ISSUE TITLE
How does the nodeport approach of rook ceph dashboard enable https access under the hood

### ISSUE THREAD

**Issue by kubecto** [rook/rook#14350] opened 2024-06-18 03:36 UTC
How does the nodeport mode of rook ceph dashboard achieve https access at the bottom? Under normal circumstances, nodeport does not support https access. In many cases, nginx is used to mount the certificate in the configuration file and then forward it to the back-end server. You can access https

**Comment by sp98** [comment] 2024-06-18 06:16
A self signed certificate is created using the[ built-in ceph](https://github.com/rook/rook/blob/d74832d41cce230fbcd1fb36487afad738ac045c/pkg/operator/ceph/cluster/mgr/dashboard.go#L231) command if `c.spec.Dashboard.SSL ` is set to `true`.  
The [doc](https://rook.io/docs/rook/v1.14/Storage-Configuration/Monitoring/ceph-dashboard/#enable-the-ceph-dashboard) might have more answers.

**Comment by sp98** [comment] 2024-06-19 04:21
@kubecto Does that answer your question?  I would also suggest to close this if this is not a bug and move this to the `discussions`.

**Closed** 2024-07-05 08:52 UTC
Labels: bug
