### ISSUE TITLE
Ceph-mgr probe or listen on wrong network when host network is defined

### ISSUE THREAD

**Issue by oaudry** [rook/rook#8510] opened 2021-08-06 16:50 UTC
* Bug Report

hello

I'm using ceph rook with an overidded network config as explain here : https://rook.io/docs/rook/v1.7/ceph-advanced-configuration.html#osd-dedicated-network

```
config: |                                                                                               
  [global]                                                                                              
    public network = 192.168.211.0/24                                                                     
   cluster network = 192.168.211.0/24                                                                    
   public addr = ""                                                                                      
   cluster addr = ""         
```
Everything work fine except mgr witch is listening on the network defined in config : 

```
LISTEN    0         5            192.168.211.10:9283             0.0.0.0:*       users:(("ceph-mgr",pid=22659,fd=28))
```

But probing is done on the pod ip on a different network.
```
  Warning  Unhealthy  5m35s (x10 over 9m35s)  kubelet            Liveness probe failed: Get "http://192.168.208.10:9283/": dial tcp 192.168.208.10:9283: connect: connection refused
```

Mgr is listening on 192.168.211 but the pod is probing on 192.168.208

This is happening with rook 1.7. In rook 1.6 the mgr is listening on 0.0.0.0.

**Expected behavior:**

Or mgr listen on the k8s network or the probe is configured to probe the mgr on ceph host network.

**How to reproduce it (minimal and precise):**

- install rook in 1.7 with host network

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1","kind":"CephCluster","metadata":{"annotations":{},"name":"rook-ceph","namespace":"rook-ceph"},"spec":{"cephVersion":{"image":"ceph/ceph:v16.2.5"},"crashCollector":{"disable":true},"dashboard":{"enabled":true},"dataDirHostPath":"/var/lib/rook","mgr":{"modules":[{"enabled":true,"name":"pg_autoscaler"}]},"mon":{"allowMultiplePerNode":false,"count":3},"network":{"provider":"host"},"storage":{"config":{"osdsPerDevice":"1"},"deviceFilter":null,"nodes":[{"devices":[{"name":"nvme0n1p4"},{"name":"nvme1n1p4"}],"name":"smobe-gra-k8s40"},{"devices":[{"name":"nvme0n1p4"},{"name":"nvme1n1p4"}],"name":"smobe-rbx-k8s70"},{"devices":[{"name":"nvme0n1p4"},{"name":"nvme1n1p4"}],"name":"smobe-sbg-k8s10"}],"useAllDevices":false,"useAllNodes":false}}}
  creationTimestamp: "2021-08-06T16:07:00Z"
  finalizers:
  - cephcluster.ceph.rook.io
  generation: 3
  name: rook-ceph
  namespace: rook-ceph
  resourceVersion: "14583"
  uid: a5acf233-fef2-4b60-8a02-9664a6856155
spec:
  cephVersion:
    image: ceph/ceph:v16.2.5
  cleanupPolicy:
    sanitizeDisks: {}
  crashCollector:
    disable: true
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement: {}
  external: {}
  healthCheck:
    daemonHealth:
      mon: {}
      osd: {}
      status: {}
  logCollector: {}
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring: {}
  network:
    ipFamily: IPv4
    provider: host
  security:
    kms: {}
  storage:
    config:
      osdsPerDevice: "1"
    nodes:
    - devices:
      - name: nvme0n1p4
      - name: nvme1n1p4
      name: smobe-gra-k8s40
    - devices:
      - name: nvme0n1p4
      - name: nvme1n1p4
      name: smobe-rbx-k8s70
    - devices:
      - name: nvme0n1p4
      - name: nvme1n1p4
      name: smobe-sbg-k8s10
    useAllDevices: false
    useAllNodes: false
status:
  ceph:
    capacity:
      bytesAvailable: 3866865934336
      bytesTotal: 3866900717568
      bytesUsed: 34783232
      lastUpdated: "2021-08-06T16:46:15Z"
    health: HEALTH_OK
    lastChanged: "2021-08-06T16:33:51Z"
    lastChecked: "2021-08-06T16:46:15Z"
    previousHealth: HEALTH_WARN
    versions:
      mgr:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 1
      mon:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 3
      osd:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 6
      overall:
        ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable): 10
  conditions:
  - lastHeartbeatTime: "2021-08-06T16:46:16Z"
    lastTransitionTime: "2021-08-06T16:08:30Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  message: Cluster created successfully
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: nvme
  version:
    image: ceph/ceph:v16.2.5
    version: 16.2.5-0
```

**Environment**:
* OS (e.g. from /etc/os-release): debian 10
* Kernel (e.g. `uname -a`):5.10.0-0.bpo.8-amd64
* Cloud provider or hardware configuration: ovh infra 1
* Rook version (use `rook version` inside of a Rook Pod): 1.7
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.5
* Kubernetes version (use `kubectl version`): 1.21.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): on premise
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): OK

**Comment by ycy1766** [comment] 2021-08-10 05:20
I am in the same situation. So I changed the ceph version to 16.2.4 and it worked fine.

**Comment by travisn** [comment] 2021-08-10 18:21
I also confirmed that v16.2.4 listened on 0.0.0.0:
```
$ kubectl -n rook-ceph logs <mgr-pod> | grep 9283
[10/Aug/2021:18:17:08] ENGINE Serving on http://0.0.0.0:9283
```

But v16.2.5 listens on the host ip:
```
$ kubectl -n rook-ceph logs <mgr-pod> | grep 9283
[10/Aug/2021:18:06:02] ENGINE Serving on http://192.168.99.122:9283
```

@jmolmo @sebastian-philipp Can you confirm if this was an intentional change to the binding in v16.2.5? If so, Rook needs to change the liveness probe. 

In the meantime, the liveness probe can be disabled with [this setting](https://github.com/rook/rook/blob/release-1.7/cluster/examples/kubernetes/ceph/cluster.yaml#L271).

**Comment by idlezombie** [comment] 2021-09-04 11:56
This has been killing me trying to figure out why a fresh cluster identical to pervious deployment has not been working. Pretty sure this is due to a change in the Ceph image for 16.2.5.

Related:
https://tracker.ceph.com/issues/52117
https://tracker.ceph.com/issues/52002#Environment

and noticed they made a ton of changes to the dashboard as listed here: https://ceph.com/en/news/blog/2021/v16-2-5-pacific-released/

When I did a fresh deploy with 2 mgrs it also failed to generate a self-signed ssl, suspect thats related to the changes made here https://github.com/ceph/ceph/pull/41170 for 16.2.5 as well but probably a separate issue from the bindings.

Have seen a few other comments regarding IP bindings and issues with dashboard but haven't seen anyone aside from here talking about it in relation to the changes in 16.2.5. Not a programmer myself so not sure if this is even something that can be fixed on the rook side but maybe the docs should roll back to using 16.2.4 until its sorted?

Brand new k8s cluster, clean install of rook-ceph using example files with only change to disable cephfs component, everything comes up clean and cluster reports healthy in toolbox but no dashboard accessible, closest I could get was the 'Bad Gateway' message which if I recall was the bindings. Going to teardown and try clean deploy of 16.2.4  now.

**Comment by jmolmo** [comment] 2021-09-09 09:46
The change is intentional:
[mgr/cephadm: use real IP as host.addr whenever possible](https://github.com/ceph/ceph/pull/41483) ( merged in master May 28)
 
[pybind/mgr/mgr_module: fix get_mgr_ip()](https://github.com/ceph/ceph/pull/41636) (merged in master Jun 4)

Both prs [merged in Pacific](https://github.com/ceph/ceph/pull/41684) in June batch 1

It seems that the liveness probe that is failing is the one for the prometheus module.

**Comment by travisn** [comment] 2021-09-09 18:09
@jmolmo How could Rook detect the same ip that the prometheus/dashboard modules will bind to? The default liveness probe just uses the pod ip, so if it's different from that it's not clear how rook can detect it before the pod is created.

**Comment by jmolmo** [comment] 2021-09-10 15:51
mmm.. what about to use a command executed in the pod  instead an http get requests for the liveness probe?

**Comment by travisn** [comment] 2021-09-10 16:30
> mmm.. what about to use a command executed in the pod instead an http get requests for the liveness probe?

Agreed, the liveness probe will need to avoid using the ip. What ceph command would test if the mgr module(s) are responding? Ideally the test wouldn't need to check the mons, or else the liveness probe for the mgr would fail if the mons are out of quorum.

**Comment by jmolmo** [comment] 2021-09-15 11:51
> > mmm.. what about to use a command executed in the pod instead an http get requests for the liveness probe?
> 
> Agreed, the liveness probe will need to avoid using the ip. What ceph command would test if the mgr module(s) are responding? Ideally the test wouldn't need to check the mons, or else the liveness probe for the mgr would fail if the mons are out of quorum.

@travisn : yep you are right-. we have several possibilities. Taking into account that I do not want to create _"temp" config files_ or copy _keyrings_, in order to execute a more "classical" Ceph command I think that the best option is to use a command to interrogate directly the ceph daemon, in this case the mgr daemon. Then we have several possibilities:

1. In this case we can select any ceph mgr config setting. The important thing is that mgr returns something
```
[root@rook-ceph-mgr-a-68f56bcf88-w28lg /]# ceph daemon mgr.a config get mgr_data
{
    "mgr_data": "/var/lib/ceph/mgr/ceph-a"
}
```

2. With this other command, we continue interrogating only the mgr and we have an immediate response about the daemon performance.  Numbers does not matter, only that we have a response. :-)
```
[root@rook-ceph-mgr-a-68f56bcf88-w28lg ceph]# ceph daemonperf mgr.a 0 1
-----objecter------ objecter-0x56224b77 objecter-0x56224b77 objecter-0x56224b77 objecter-0x56224c22 objecter-0x56224c22 
actv rd   wr   rdwr|actv rd   wr   rdwr|actv rd   wr   rdwr|actv rd   wr   rdwr|actv rd   wr   rdwr|actv rd   wr   rdwr|
  0    0    0    0 |  0    0    0    0 |  0    0    0    0 |  0    0    0    0 |  0    0    0    0 |  0    0    0    0 
```

In the implemented solution I have chosen the second option. But we can discuss if it is better to use the first one... I really do not see any important advantage about to use one or another.

**Comment by travisn** [comment] 2021-09-15 16:52
Agreed, option 2 is good so we can use the admin socket. A question is added to the PR to confirm.

**Closed** 2021-09-20 23:05 UTC
Labels: bug
