### ISSUE TITLE
cephfs: rook-ceph.cephfs.csi.ceph.com RegisterPlugin error  unknown service pluginregistration.Registration

### ISSUE THREAD

**Issue by xonze** [rook/rook#5245] opened 2020-04-11 12:08 UTC
* Bug Report

K8S kubelet logs

I0411 11:59:23.181934    3310 reconciler.go:156] operationExecutor.RegisterPlugin started for plugin at "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock" (plugin details: &{/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock true 2020-04-11 11:35:10.555429827 +0000 UTC m=+64138.903334050})
I0411 11:59:23.182031    3310 operation_generator.go:193] parsed scheme: ""
I0411 11:59:23.182052    3310 operation_generator.go:193] scheme "" not registered, fallback to default scheme
I0411 11:59:23.182082    3310 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock 0  <nil>}] <nil>}
I0411 11:59:23.182101    3310 clientconn.go:577] ClientConn switching balancer to "pick_first"
I0411 11:59:23.182162    3310 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc003acec00, CONNECTING
I0411 11:59:23.182608    3310 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc003acec00, READY
E0411 11:59:23.183169    3310 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock" failed. No retries permitted until 2020-04-11 12:01:25.183146021 +0000 UTC m=+65713.531050251 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0411 11:59:23.183189    3310 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0411 11:59:33.184180    3310 reconciler.go:156] operationExecutor.RegisterPlugin started for plugin at "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" (plugin details: &{/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock true 2020-04-11 11:35:05.960591735 +0000 UTC m=+64134.308495957})
I0411 11:59:33.184250    3310 operation_generator.go:193] parsed scheme: ""
I0411 11:59:33.184262    3310 operation_generator.go:193] scheme "" not registered, fallback to default scheme
I0411 11:59:33.184284    3310 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock 0  <nil>}] <nil>}
I0411 11:59:33.184297    3310 clientconn.go:577] ClientConn switching balancer to "pick_first"
I0411 11:59:33.184350    3310 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc003076da0, CONNECTING
I0411 11:59:33.185110    3310 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc003076da0, READY
E0411 11:59:33.186701    3310 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2020-04-11 12:01:35.186652692 +0000 UTC m=+65723.534556954 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0411 11:59:33.186703    3310 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0411 11:59:34.501098    3310 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0411 12:00:34.524289    3310 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0411 12:01:25.211112    3310 operation_generator.go:193] parsed scheme: ""
I0411 12:01:25.211136    3310 operation_generator.go:193] scheme "" not registered, fallback to default scheme

**Environment**:
* OS (e.g. from /etc/os-release):centos7.5
* Kernel (e.g. `uname -a`):5.6.3-1.el7.elrepo.x86_64
* Rook version (use `rook version` inside of a Rook Pod): 1.2.7 and 1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`):14.2.8
* Kubernetes version (use `kubectl version`):1.16.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
  cluster:
    id:     53*********************
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 26m)
    mgr: a(active, since 27m)
    mds: myfs:1 {0=myfs-b=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 17h), 3 in (since 17h)
    rgw: 1 daemon active (my.store.a)

  data:
    pools:   10 pools, 176 pgs
    objects: 944 objects, 151 KiB
    usage:   203 GiB used, 1.8 TiB / 2.0 TiB avail
    pgs:     176 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr

**Comment by Madhu-1** [comment] 2020-04-11 13:18
This is not a bug, it's just a logging , it won't affect functionality. Closing

**Closed by Madhu-1** 2020-04-11 13:18 UTC
Labels: bug

**Comment by ujued** [comment] 2020-05-26 01:43
@Madhu-1 thanks. 

```
E0411 11:59:33.186701 3310 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2020-04-11 12:01:35.186652692 +0000 UTC m=+65723.534556954 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```

what caused this error log?

**Comment by yanchicago** [comment] 2020-07-06 23:46
@Madhu-1 Can this message be supressed? It's confusing. Is it rook or ceph-csi?

**Comment by KeithTt** [comment] 2021-07-27 08:04
I got similar message.

```text
Jul 27 16:01:28 m-69-224 kubelet[171051]: I0727 16:01:28.601122  171051 clientconn.go:577] ClientConn switching balancer to "pick_first"
Jul 27 16:01:28 m-69-224 kubelet[171051]: I0727 16:01:28.605722  171051 clientconn.go:104] parsed scheme: ""
Jul 27 16:01:28 m-69-224 kubelet[171051]: I0727 16:01:28.605744  171051 clientconn.go:104] scheme "" not registered, fallback to default scheme
Jul 27 16:01:28 m-69-224 kubelet[171051]: I0727 16:01:28.605764  171051 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock 0  <nil>}] <nil>}
```

What is the matter?
