### ISSUE TITLE
It should be possible to use the ReadWriteMany mode

### ISSUE THREAD

**Issue by luxas** [rook/rook#543] opened 2017-04-04 19:01 UTC
Right now the preferred mode seems to be ReadWriteOnce for a PV, but preferably Rook should be able to create RWX Volumes as well

Is this hard technically with Ceph or haven't you just highlighted it?

**Comment by bassam** [comment] 2017-04-04 19:08
Its technically possible as I understand it, however, it requires client side settings (at rbd level) to turn off caching. You wouldn't want two clients to be writing and run into consistency issues. Also this will likely impact performance.

**Comment by luxas** [comment] 2017-04-04 19:13
Seems like the k8s CephFS supports this but not RBD out-of-the-box: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by bassam** [comment] 2017-04-04 19:17
Yes for CephFS its straightforward since the MDS is policing every write to the file system.

**Comment by luxas** [comment] 2017-04-04 19:38
Ok, and CephFS for Rook is in the works, right?

**Comment by bassam** [comment] 2017-04-04 19:42
For K8S yes. CephFS is functional today in standalone mode. Im curious which scenario you care about for RWX. Can you elaborate?

**Comment by luxas** [comment] 2017-05-07 06:50
@bassam For example, I might want to run three WordPress replicas and let them share the same storage volume. When I upload new files, it shouldn't matter which replica I hit; they should all be able to write to the volume.

Is there any way to do this with RBD or do I have to use CephFS?
Also when will CephFS be usable with Kubernetes?

**Comment by luxas** [comment] 2017-05-07 06:51
I've also seen others who've asked for this feature...

**Comment by bassam** [comment] 2017-05-21 20:17
@kokhang can we add support for this in the rbd plugin before 1.7 freeze? I think it might be a matter of disabling fencing if RWM is set.

**Comment by jamiehannaford** [comment] 2017-06-14 15:06
@bassam @kokhang Thanks for working on this. Will this be ready for 1.7?

**Comment by hunter** [comment] 2017-06-14 15:37
I'd imagine 1.7 has feature frozen now that beta1 is out.

Could the external-storage CephFS provisioner be utilised (and/or ported for Rook)? https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs

**Comment by bassam** [comment] 2017-06-14 15:52
@hunter @jamiehannaford  the path we are taking here is to add a rook volume plugin to Kubernetes in the 1.8 timeframe. The plugin will support block (including ReadWriteMany) and filesystem. The design is outlined here https://github.com/rook/rook/issues/432#issuecomment-303912611 and the initial PR (which is still under design review by the Kubernetes team) is here https://github.com/kubernetes/kubernetes/pull/46843.

**Comment by jamiehannaford** [comment] 2017-06-14 16:11
@bassam Awesome, thanks for the update!

**Comment by hunter** [comment] 2017-06-14 16:13
Yep, understood @bassam.

I thought it might be worth sharing the external-storage plugin if anyone wants to test out RWM before 1.8. I'm sure there will be a few questions about it since we're still a ways off :)

**Comment by FaKod** [comment] 2017-10-02 10:16
[kubernetes/kubernetes#46843]( kubernetes/kubernetes#46843) has been closed by stating that the rook team will use a flexvolume. So ReadWriteMany will still be available with K8s 1.8? Or is the timeline independent from K8s now?

**Comment by bassam** [comment] 2017-10-02 14:32
@FaKod yes we are going to use a flex volume (the work is well underway see #882). ReadWriteMany will be support by the flex volume and is independent of K8S. One feature that would help RWM is the ability to mount devices directly into containers which looks like will come in v1.9.

What is you scenario for RWM? How do you plan to use it?

**Comment by luxas** [comment] 2017-10-02 14:39
@bassam When is the next Rook release scheduled?

**Comment by FaKod** [comment] 2017-10-03 06:25
@bassam I think there is no use case in microservice architectures. However, some customers are using file transfer from one container to another, are implementing distributed locks via filesystem or use a specific common (and slow) file store for pictures/videos. What I tested is to grab html files from a repository, store them in a "shared" volume and use it in a nginx container (just for testing and as an example in our Kubernetes training). The results are filesystem corruptions from time to time (in the volume). So it definitely doesn't work.

**Comment by kokhang** [comment] 2017-10-03 15:32
@FaKod The thing about RWX is that Kubernetes does not support returning raw block volumes. It is always expects a block volume formatted and mounted with a filesystem. So it cannot support RWX for block. Here is the feature that tracks this. https://github.com/kubernetes/features/issues/351

However, we rook you can create ceph filesystems. These are RWX. Can you leverage this for your use case instead?

**Comment by FaKod** [comment] 2017-10-04 15:44
@kokhang "with rook you can create ceph filesystems". Do you have an example how to do that?

**Comment by kokhang** [comment] 2017-10-04 17:41
@FaKod This is how you can setup and consume a filesystem. https://github.com/kokhang/rook/blob/master/Documentation/k8s-filesystem.md.

This is changing very soon and it is being made easier via CRD. https://github.com/rook/rook/pull/1029

**Comment by jbw976** [comment] 2017-10-05 17:31
@kokhang do we also have documentation for the current way (before Rook flexvolume plugin gets CephFS support) to use CephFS with a persistent volume claim for a pod?

**Comment by kokhang** [comment] 2017-10-09 17:43
@jbw976 ceph filesystem cannot be dynamically created with pvc.  This is created using a CRD. https://github.com/rook/rook/blob/master/Documentation/filesystem-crd.md
 
Now that we support multiple filesystem, perhaps we should leverage the PVC instead of CRD. But that is a different discussion.

**Comment by FaKod** [comment] 2017-10-10 04:49
@kokhang Which version do you mean? In the last release, there is no CRD other than cluster, right?

**Comment by jbw976** [comment] 2017-10-12 15:49
@FaKod in the last release (0.5.1) we only had cluster and pool CRDs.  But now in the latest master builds, we have added a couple new CRDs very recently to declaratively create other objects in a Rook cluster, such as object storage and shared filesystems.

Object store: https://rook.io/docs/rook/master/object-store-crd.html
Shared filesystem: https://rook.io/docs/rook/master/filesystem-crd.html

**Comment by galexrt** [comment] 2018-01-15 14:11
@luxas @kokhang @jbw976 @bassam As far as I understand the topic from the comments, this is about being able to create/use CephFS/Filesystem by a StorageClass and PVCs.
Anything against closing this issue and using #1125 to track this feature?
Also there has been a design doc (#1152) by @kokhang which is mentioned in #1125.

**Comment by t3hmrman** [comment] 2018-04-30 09:07
Hey all,

I'm not sure if this belongs here, but was looking through the issues -- I wanted to note that if I set up a PVC and use it from two different pods (in my case, actually 2 replicas in the same `Deployment`), the second replica fails with an error stating that the volume is attached to another pod (the first replica to boot), on rook `v0.7.0`.

I've confirmed that the PV is `RWX`, so I was a bit surprised that the second replica wasn't binding correctly. I can make a new issue if that's preferred but thought this issue might be more relevant

**Comment by galexrt** [comment] 2018-05-10 13:56
@t3hmrman Block storage is not available for `RWX`, that is where a network filesystem such as CephFS comes in.
Currently you can only use CephFS directly in the `volumes` section of a Deployment, #1125 covers usage of CephFS through PVCs.

***

Closing this issue as there have been no comments against closing this and using #1125 to track being able to consume CephFS through PVCs.

**Closed by galexrt** 2018-05-10 13:56 UTC

**Comment by t3hmrman** [comment] 2018-05-11 00:13
Hey @galexrt thank you very much for clarifying!
