### ISSUE TITLE
mgr prometheus not running.

### ISSUE THREAD

**Issue by ddhh8023** [rook/rook#13908] opened 2024-03-11 07:49 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**
I've use ceph cli command:  ceph mgr module enable  prometheus, The Mgr is not open 9283 port, so I checked log, it shows no module 'rook', then I checked rook moule, it is enabled, I re exec this command:  ceph mgr module enable  prometheus, It still not open the 9283 port.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

```
debug 2024-03-11T07:43:51.045+0000 7f7548b41700  0 [iostat DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-03-11T07:43:51.045+0000 7f7548b41700  1 mgr load Constructed class from module: iostat
debug 2024-03-11T07:43:51.048+0000 7f7548b41700  0 [nfs DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-03-11T07:43:51.048+0000 7f7548b41700  1 mgr load Constructed class from module: nfs
debug 2024-03-11T07:43:51.051+0000 7f7548b41700  0 [orchestrator DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-03-11T07:43:51.051+0000 7f7548b41700  1 mgr load Constructed class from module: orchestrator
debug 2024-03-11T07:43:51.053+0000 7f7548b41700  0 [pg_autoscaler DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-03-11T07:43:51.053+0000 7f7548b41700  1 mgr load Constructed class from module: pg_autoscaler
debug 2024-03-11T07:43:51.061+0000 7f7790390700  0 [pg_autoscaler INFO root] _maybe_adjust
debug 2024-03-11T07:43:51.070+0000 7f7548b41700  0 [progress DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-03-11T07:43:51.070+0000 7f7548b41700  1 mgr load Constructed class from module: progress
debug 2024-03-11T07:43:51.071+0000 7f7548b41700  0 [prometheus DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-03-11T07:43:51.072+0000 7f7548b41700 -1 no module 'rook'
debug 2024-03-11T07:43:51.073+0000 7f777f38e700  0 [progress INFO root] Loading...
debug 2024-03-11T07:43:51.079+0000 7f777f38e700  0 [progress INFO root] Loaded [<progress.module.GhostEvent object at 0x7f78536c54a8>] historic events
debug 2024-03-11T07:43:51.079+0000 7f7548b41700 -1 no module 'rook'
debug 2024-03-11T07:43:51.079+0000 7f7548b41700 -1 mgr load Failed to construct class in 'prometheus'
debug 2024-03-11T07:43:51.085+0000 7f754a344700  1 mgr.server send_report Not sending PG status to monitor yet, waiting for OSDs
debug 2024-03-11T07:43:51.088+0000 7f777f38e700  0 [progress INFO root] Loaded OSDMap, ready.
debug 2024-03-11T07:43:51.079+0000 7f7548b41700 -1 mgr load Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1657, in _oremote
    return mgr.remote(o, meth, *args, **kwargs)
  File "/usr/share/ceph/mgr/mgr_module.py", line 2228, in remote
    args, kwargs)
ImportError: Module not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/prometheus/module.py", line 649, in __init__
    self.modify_instance_id = self.get_orch_status() and self.get_module_option(
  File "/usr/share/ceph/mgr/prometheus/module.py", line 869, in get_orch_status
    return self.available()[0]
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1586, in inner
    completion = self._oremote(method_name, args, kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1661, in _oremote
    f_set = self.get_feature_set()
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1586, in inner
    completion = self._oremote(method_name, args, kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1657, in _oremote
    return mgr.remote(o, meth, *args, **kwargs)
  File "/usr/share/ceph/mgr/mgr_module.py", line 2228, in remote
    args, kwargs)
ImportError: Module not found
```

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by rkachach** [comment] 2024-03-11 09:03
Duplicate of: https://github.com/rook/rook/issues/13527

Please, read carefully the issue thread to understand what's going on and the available woraround.

**Closed by rkachach** 2024-03-11 09:03 UTC
Labels: bug
