### ISSUE TITLE
Copy over secrets to the namespace the user wants to use a PVC in

### ISSUE THREAD

**Issue by jamiehannaford** [rook/rook#737] opened 2017-06-14 16:26 UTC
When a user wants to deploy a PVC to a custom namespace, they often run into a bunch of Kubelet error messages which say the pod cannot access the Ceph user secret. This error is thrown in the mount stage [here](https://github.com/kubernetes/kubernetes/blob/1e1040b524dda1c97dad4faab1910972b71a5c79/pkg/volume/rbd/rbd.go#L113).

The implicit expectation on the user is for them to copy over the secret to the NS before creating the PVC, which a lot of folks will be unsure on how to do. Best case is that it takes them n amount of time to Google and copy paste.

Instead, could Rook copy over the secret before the PVC is created? I'm not sure whether that'd be the role of Rook, or the Ceph plugin driver. If it's the latter, I'm more than happy to open up an issue on the main repo. Just wanted to get some feedback first.

**Comment by travisn** [comment] 2017-06-15 06:29
This should be solved by #432 with the Rook volume plugin. However, we should also look for a short term solution to this as well such as #475

**Comment by jamiehannaford** [comment] 2017-06-15 10:02
Cool, I'll try to submit a PR for #475 when I next get some free time.

**Comment by kokhang** [comment] 2017-06-15 17:45
Closing this issue as it is a duplicate of #475. Thank you @jamiehannaford for looking at this. I am looking forward for a PR :)

**Closed by kokhang** 2017-06-15 17:45 UTC
Labels: duplicate
