### ISSUE TITLE
Integration tests broken: wipefs: error: 1: probing initialization failed: No such file or directory

### ISSUE THREAD

**Issue by jklippel** [rook/rook#13684] opened 2024-02-05 08:23 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The github workflow step "setup cluster resources" fails with:

```
+ sudo umount /mnt
+ sudo sed -i.bak '/\/mnt/d' /etc/fstab
+ PARTITION=1
+ sudo wipefs --all --force 1
wipefs: error: 1: probing initialization failed: No such file or directory
Error: Process completed with exit code 1.
```

**Expected behavior:**

```
+ sudo umount /mnt
+ sudo sed -i.bak '/\/mnt/d' /etc/fstab
+ PARTITION=/dev/sdb1
+ sudo wipefs --all --force /dev/sdb1
/dev/sdb1: 2 bytes were erased at offset 0x00000438 (ext4): 53 ef
```

**How to reproduce it (minimal and precise):**

Start an integration test or look at recent integration test results. E.g. https://github.com/rook/rook/actions/runs/7780853629/job/21214237941 (randomly chosen example of a failing test)

**File(s) to submit**:

I do not submit any of the following, as they can be viewed in the integration test results.
e.g. https://github.com/rook/rook/actions/runs/7780853629/job/21214237941 (randomly chosen example of a failing test)

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by jklippel** [comment] 2024-02-05 09:31
It seems as if the size of the second disc is now 75G.
PR coming up...

**Comment by subhamkrai** [comment] 2024-02-05 10:23
Hi @jklippel 

The pr to fix the issue is already in progress https://github.com/rook/rook/pull/13675

**Comment by subhamkrai** [comment] 2024-02-05 10:24
Thanks for opening the issue @jklippel

**Comment by travisn** [comment] 2024-02-05 17:30
Partially fixed with #13675.

**Comment by BlaineEXE** [comment] 2024-02-05 18:55
Regarding issue 3, this seems to be (at least in my current run) because both sda (the boot disk) and sdb are 75G, and it is trying to use sda as an OSD. We should get this fixed ASAP. I think the best way to fix this will be to use a better heuristic for detecting the "spare" disk.

**Comment by travisn** [comment] 2024-02-06 04:16
Reopening as there are still issues with:
- Multicluster suite
- Smoke suite
- Two canary tests

**Closed** 2024-02-06 14:16 UTC
Labels: bug, ci

**Comment by travisn** [comment] 2024-02-06 14:57
Hooray, green CI again! @BlaineEXE @subhamkrai Thanks!
