### ISSUE TITLE
mgr: watch-active can't recover if the standby mgr have the "active" label set

### ISSUE THREAD

**Issue by foyerunix** [rook/rook#13464] opened 2023-12-22 13:37 UTC
Hello,

First I would like to precise that while I will provide a synthetic way to reproduce the issue, I have no idea how I got there in the first place. I saw the issue while attempting to access the dashboard as I was sometime redirected to the pod address of the active mgr. After looking at the dashboard service, I saw that it had two endpoints rather than just one.

**To reproduce the issue synthetically:**

1. Get your current labels:

```
kubectl describe pod | grep -E '^Name:.+rook-ceph-mgr-|mgr_role'
Name:                 rook-ceph-mgr-a-78b6f645cd-75m49
                      mgr_role=active
Name:                 rook-ceph-mgr-b-654b4f7686-w2lff
                      mgr_role=standby
```

2. Set the "active" label to the passive mgr:

`kubectl patch pod rook-ceph-mgr-b-654b4f7686-w2lff --type='json' -p='[{"op": "replace", "path": "/metadata/labels/mgr_role", "value":"active"}]'`

3. Confirm the two mgr have the "active" label:

```
kubectl describe pod | grep -E '^Name:.+rook-ceph-mgr-|mgr_role'
Name:                 rook-ceph-mgr-a-78b6f645cd-75m49
                      mgr_role=active
Name:                 rook-ceph-mgr-b-654b4f7686-w2lff
                      mgr_role=active
```

**Current behavior:**

The labels never recover as watch-active see no issue with the current label:

```
2023-12-22 13:30:31.876279 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2023-12-22 13:30:31.876327 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2023-12-22 13:30:46.879549 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2023-12-22 13:30:47.253916 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2023-12-22 13:30:47.253956 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2023-12-22 13:31:02.268114 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2023-12-22 13:31:02.642043 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2023-12-22 13:31:02.642083 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2023-12-22 13:31:17.656251 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2023-12-22 13:31:18.031449 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2023-12-22 13:31:18.031492 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2023-12-22 13:31:33.045652 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2023-12-22 13:31:33.420561 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2023-12-22 13:31:33.420607 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2023-12-22 13:31:48.434905 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2023-12-22 13:31:48.809282 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2023-12-22 13:31:48.809324 I | cephcmd: successfully checked mgr_role label. checking again in 15s
```

**Expected behavior:**

watch-active detect the issue and we recover from this state.

Best Regards.

**Comment by rkachach** [comment] 2024-01-29 10:59
I'm closing this issue since the user didn't report a way to reproduce it in a normal operating situation and because there's a simple work around for it. Feel free to reopen in case you run in the same issue. In such case please provide the detailed steps to reproduce the BUG.

**Closed by rkachach** 2024-01-29 10:59 UTC
Labels: bug
