### ISSUE TITLE
Changing gateway port in CephObjectStore prevent ObjectBucketClaims from being created

### ISSUE THREAD

**Issue by betermieux** [rook/rook#4400] opened 2019-12-02 13:21 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I change `spec.gateway.port` from `80` to some other value, the rgw-object-store pods are correctly created. Whenever I create an `ObjectBucketClaim`, it gets picked up by the operator but the creation of the bucket hangs indefinitely (see last line of the operator logs).

**Expected behavior:**

The bucket is created correctly.

**How to reproduce it (minimal and precise):**

Change the gateway port and create an ObjectBucketClaim.

**File(s) to submit**:

* CephObjectStore CR
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: object-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  gateway:
    type: s3
    sslCertificateRef:
    port: 33221
    securePort:
    instances: 2
    allNodes: false
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage
              operator: Exists
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
```
* ObjectBucketClaim CR
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: default-bucket
  namespace: rook-ceph
spec:
  bucketName: default-bucket
  storageClassName: rook-ceph-bucket
```
* Operator's logs, if necessary
```
I1202 08:39:20.052353       8 controller.go:175]  "level"=0 "msg"="new Reconcile iteration" "key"="rook-ceph/default-bucket"
I1202 08:39:20.052482       8 helpers.go:78]  "level"=0 "msg"="getting claim for key" "key"="rook-ceph/default-bucket"
I1202 08:39:20.063883       8 helpers.go:61]  "level"=0 "msg"="validating claim for provisioning obc" "key"="rook-ceph/default-bucket" "default-bucket"=null
I1202 08:39:20.063973       8 helpers.go:192]  "level"=0 "msg"="getting ObjectBucketClaim's StorageClass" "key"="rook-ceph/default-bucket"
I1202 08:39:20.069580       8 helpers.go:197]  "level"=0 "msg"="got StorageClass" "key"="rook-ceph/default-bucket" "name"="rook-ceph-bucket"
I1202 08:39:20.069703       8 resourcehandlers.go:261]  "level"=0 "msg"="updating status:" "key"="rook-ceph/default-bucket" "new status"="pending" "obc"="rook-ceph/default-bucket" "old status"="pending"
I1202 08:39:20.076338       8 helpers.go:78]  "level"=0 "msg"="getting claim for key" "key"="rook-ceph/default-bucket"
I1202 08:39:20.081931       8 controller.go:285]  "level"=0 "msg"="provisioning" "key"="rook-ceph/default-bucket" "bucket"="default-bucket"
2019-12-02 08:39:20.082004 I | op-bucket-prov: initializing and setting CreateOrGrant services
2019-12-02 08:39:20.082029 I | op-bucket-prov: getting storage class "rook-ceph-bucket"
2019-12-02 08:39:20.097331 I | op-bucket-prov: Provision: creating bucket "default-bucket" for OBC "default-bucket"
2019-12-02 08:39:20.097456 I | op-object: Getting user: ceph-user-uO9LaUeq
2019-12-02 08:39:20.097487 I | exec: Running command: radosgw-admin user info --uid ceph-user-uO9LaUeq --rgw-realm=object-store --rgw-zonegroup=object-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
2019-12-02 08:39:20.630020 I | op-bucket-prov: creating Ceph user "ceph-user-uO9LaUeq"
2019-12-02 08:39:20.630066 I | op-object: Creating user: ceph-user-uO9LaUeq
2019-12-02 08:39:20.630104 I | exec: Running command: radosgw-admin user create --uid ceph-user-uO9LaUeq --display-name ceph-user-uO9LaUeq --rgw-realm=object-store --rgw-zonegroup=object-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
2019-12-02 08:39:21.259277 I | op-bucket-prov: successfully created Ceph user "ceph-user-uO9LaUeq" with access keys
2019-12-02 08:39:21.259929 I | op-bucket-prov: creating bucket "default-bucket"
```

**Environment**:
* OS (e.g. from /etc/os-release):
Container Linux by CoreOS 2247.7.0 (Rhyolite)
* Kernel (e.g. `uname -a`):
Linux cloud1.novalocal 4.19.84-coreos #1 SMP Tue Nov 19 20:51:06 -00 2019 x86_64 AMD EPYC 7351P 16-Core Processor AuthenticAMD GNU/Linux
* Cloud provider or hardware configuration:
Openstack onpremise
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`):
v1.16.3
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_OK

**Comment by travisn** [comment] 2019-12-02 16:44
@thotz can you take a look?

**Comment by thotz** [comment] 2019-12-05 10:14
@travisn Sure

**Comment by thotz** [comment] 2019-12-05 12:34
@betermieux : Thanks for testing out OBC. It is 100% reproducible.

following is the log post bucket request

op-bucket-prov: DEBUG: after s3 call, ok=true, aerr=RequestError: send request failed
caused by: Put http://rook-ceph-rgw-my-store.rook-ceph/ceph-bkt: dial tcp 10.99.75.185:80: i/o timeout
2019-12-05 12:23:18.342625 E | op-bucket-prov: error creating bucket "ceph-bkt". Bucket "ceph-bkt" could not be created: RequestError: send request failed
caused by: Put http://rook-ceph-rgw-my-store.rook-ceph/ceph-bkt: dial tcp 10.99.75.185:80: i/o timeout
E1205 12:23:18.342854       6 controller.go:243]  "msg"="cleaning up reconcile artifacts" "error"="error provisioning bucket: error creating bucket \"ceph-bkt\". Bucket \"ceph-bkt\" could not be created: RequestError: send request failed\ncaused by: Put http://rook-ceph-rgw-my-store.rook-ceph/ceph-bkt: dial tcp 10.99.75.185:80: i/o timeout" "key"="default/ceph-delete-bucket"

Looks like s3 api is trying to contact only the 80 port and the bucket create request got time out.
In the code I can't anywhere in which we mention abort port to s3 client which is getting created. May it is always uses default port.

**Comment by betermieux** [comment] 2019-12-05 19:41
I have changed the port number of the CephObjectStore in the first place as a kind of workaround for another problem. If the s3 API doesn't allow requests to non port 80 servers, then you should remove `spec.gateway.port` the from the CephObjectStore definition.

**Comment by leseb** [comment] 2019-12-11 15:11
Fixed on https://github.com/rook/rook/pull/4472

**Comment by leseb** [comment] 2019-12-11 15:50
Closing, will be in 1.2. Thanks.

**Closed by leseb** 2019-12-11 15:50 UTC
Labels: bug
