### ISSUE TITLE
Support IPv6 single stack for Ceph

### ISSUE THREAD

**Issue by travisn** [rook/rook#3850] opened 2019-09-13 21:37 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Rook operators will need to handle new IPv4/IPv6 dual stack feature that is coming in K8s 1.16. See the [IPv4/IPv6 dual stack](https://kubernetes-io-vnext-staging.netlify.com/docs/concepts/services-networking/dual-stack/) docs on the topic.

Ceph only supports either v4 or v6. See the `ms bind ipv6` setting on the [network config](https://docs.ceph.com/docs/master/rados/configuration/network-config-ref/) reference.

We may need a new setting in the cluster CR that indicates if the cluster should bind to v4 or v6. This setting would need to apply to both the ceph daemon pods and the csi driver so the clients will communicate over the same protocol.

**What is use case behind this feature:**
Support for dual stack network clusters.

**Comment by Frankkkkk** [comment] 2020-01-27 15:01
Hi,
As a workaround for now, we put the `ms bind ipv6` in the `rook-ceph-override` configmap and it actually works well.
But indeed, an option in the CR would actually be interesting and cleaner.

Cheers

**Comment by leseb** [comment] 2020-03-09 08:25
Moving to 1.4.

**Comment by stv0g** [comment] 2020-04-05 11:29
Can't we detect if the cluster is configured for IPv4, IPv6 or dual stack?
I think rook should be able to set the appropriate flag automatically..

So far the K8S dual feature gate does not support dual stack services.
Only pods are able to receive multiple addresses.

@travisn Should we update the issue title to reflect that the issue is not about dual stack?

**Comment by travisn** [comment] 2020-09-11 22:03
@sp98 Where did you get with this investigation? If you have changes that just need to be tested, perhaps we can go ahead and get a PR opened for the community to also help with testing.

**Comment by sp98** [comment] 2020-09-13 06:16
> @sp98 Where did you get with this investigation? If you have changes that just need to be tested, perhaps we can go ahead and get a PR opened for the community to also help with testing.

@travisn I had to stop this in between and work on a different task. I'll start this again and try to come up with a PR in the coming week.

**Comment by travisn** [comment] 2020-09-15 19:54
For now let's plan on limiting this to support for single stack IPv6. According to [this KEP comment](https://github.com/kubernetes/enhancements/issues/563#issuecomment-682316770), dual stack is being re-implemented in K8s 1.20.

**Closed** 2020-10-06 13:46 UTC
Labels: ceph, feature, keepalive
