### ISSUE TITLE
rework/refactor ci workflows and make targets.

### ISSUE THREAD

**Issue by obnoxxx** [rook/rook#14686] opened 2024-09-04 09:54 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

currently, the github ci workflows in the rook project contain a lot of the testing logic.

It would be convenient for developers to concentrate this logic  in make targets that can easily be invoked  locally prior to PR creation.  Ideally, these make targets should be named systematically, e. g. following a pattern like `check.foo`

Some concrete cases:

1.  Extract the 'check docs ' workflow  to a `check.docs` make target.
2.  Extract the 'check helm-docs'workflow to a `check.helm-docs`make target.
3. Extract the 'codegen' workflow to a `check.codegen` make target.
4. Extract the 'crds-gen' workflow to a `check.crds` make target.

To be perfectly clear, it is **not** the intention here to rename (code-, docs- or manifests-) generating make targets to
 something like `check foo`. Instead, the intention is to create new make targets of the naming pattern `check.foo` that would contain the original logic of the corresponding github workflow. If that workflow invoked generation actions, the same would be the case for the new targets. As a result, the workflow that now invokes the new make target, has not changed in behavior.

So while those new make targets might  not appear to be pure checker targets and do perform code or docs generation, there is no intent to replace existing targets. Here is how the `check.`prefix might make more sense:

1. the target checks that generation is working by running it.
2. the target checks if the generation run resulted in any uncommitted modified files.

As a part of these changes, the existing generating targets could be renamed more systematically:

* `docs` --> `gen.docs`
* `helm-docs`--> `gen.helm-docs`
* `crds`--> `gen.crds`
* `codegen` -->  `gen.codegen`
* `gen-rbac` --> `gen.rbac`
* maybe: `generate-docs-crds`--> `gen.crd-docs`

New checker targets to be used in the validating ci workflows would be:

* `check.docs`
* `check.helm-docs`
* `check.crds`
* `check.codegen`

 

**What is use case behind this feature:**

simplify local developer testing  workflow and systematize make target naming.

**Environment**:

rook developer environment.

**Comment by obnoxxx** [comment] 2024-09-04 10:05
I started to work on this already.
Below is an update where it is:

> **Is this a bug report or feature request?**
> 
>     * Feature Request
> 
> 
> **What should the feature do:**
> 
> currently, the github ci workflows in the rook project contain a lot of the testing logic.
> 
> It would be convenient for developers to concentrate in make targets that can easily be executed locally prior to PR creation. Ideally, these make targets should be named systematically, e. g. following a pattern like `check.foo`
> 
> Some concrete cases:
> 
>     1. Extract the 'check docs ' workflow  to a `check.docs` make target.

covered in PR #14672 and previous (merged) PRs.

> 
>     2. Extract the 'check helm-docs'workflow to a `check.helm-docs`make target.

covered in PR #14674  and previous (merged)  PRs



>     3. Extract the 'codegen' workflow to a `check.codegen` make target.

I hava a patch ready locally.
 
>     4. Extract the 'crds-gen' workflow to a `check.crds` make target.

I have a patch ready locally.
 
> 
> As part of this effort, the script `tests/scripts/validate_modified_files.sh`could be reworked/simplified a bit.

covered as part of PR #14672 
 
> **What is use case behind this feature:**
> 
> simplify local developer testing workflow and systematize make target naming.
> 
> **Environment**:
> 
> rook developer environment.

**Comment by obnoxxx** [comment] 2024-09-04 10:07
Further idea:

Extracct the 'shellcheck'worjflow into a `check.shell-scripts`make target.

**Comment by parth-gr** [comment] 2024-09-04 11:34
`check.codegen check.crds` will be locally checking whether the crds are updated or not?
Or it will replace current `crds and codegen ` make commands

If you are choosing the first option I would suggest,

To have both at a time`check.crds` and `build.crds`

**Comment by obnoxxx** [comment] 2024-09-04 14:04
> `check.codegen check.crds` will be locally checking whether the crds are updated or not?
> Or it will replace current `crds and codegen ` make commands

I have no intention to replace: like the existing workflows, it would call the corresponding generation target and then check for modified files.

> If you are choosing the first option I would suggest,
> 
> To have both at a time`check.crds` and `build.crds`

Do you mean to have one target check both or to change both in one commit or PR?

I would definitely keep the tatgets and ci workflows separate and as usual, I also prefer to add it in separate commits and PRs.

**Comment by parth-gr** [comment] 2024-09-04 14:48
Yaa you can address them on separate PRs,
But mine intention here is to have a common naming convention

**Comment by obnoxxx** [comment] 2024-09-04 15:02
@parth-gr  wrore:
> Yaa you can address them on separate PRs,

Glad we're on the same page here 👍🏼 

> But mine intention here is to have a common naming convention

Yes, That's one major Purpose of this issue!

* I have `check.docs` and `check.helm-docs`in PRs already.
* I have `check.codegen`and `check.crds`in local patches.

**Comment by obnoxxx** [comment] 2024-09-04 15:23
@parth-gr  wrote:

> If you are choosing the first option,I would suggest to have both at a time`check.crds` and `build.crds`

I missed the `build.` part in my first reply.

But sure we could add `build.foo` targets where we add or already have `check.foo`.

**Comment by travisn** [comment] 2024-09-04 21:24
Could we separate the two work items at least into separate PRs?
1. Enable `make` commands for items only the CI runs today
2. Refactor the `make` commands for consistency, naming improvements, etc

The first one is certainly helpful so devs can run as much validation as possible before checking if they would like. Although I think we agree let's not spend effort on running the integration tests locally.

For the second one, I'm not sure how much benefit there will be compared to all the effort and risk of regression? It feels like a rabbit hole where we may end up spending too much time.

**Comment by obnoxxx** [comment] 2024-09-05 10:14
@travisn  wrote:
> Could we separate the two work items at least into separate PRs?
> 
>     1. Enable `make` commands for items only the CI runs today
> 
>     2. Refactor the `make` commands for consistency, naming improvements, etc

As you know, I'm always in favor of splitting work into multiple PRs and commits.
And I had a different splitting than the one you are suggesting in mind:

I was thinking to add one commit/PR for each workflow to be extracted.

consistent naming would be a side effect.

I have PRs for 'check docs 'and 'check helm-docs' and local commits for 'check crds' and 'check codegen '. If maintainers request those to be combined into fewer PRs and commits, I would of course do that.


 



> 
> The first one is certainly helpful so devs can run as much validation as possible before checking if they would like.

I'm glad you seem to agree conceptually.

I take that as a sign that it makes sense for me to pursue the started efforts 😄 


> Although I think we agree let's not spend effort on running the integration tests locally.

Absolutely. While I would like to be able to run integration tests locally in general, I had not planned to work on that part.

 
> For the second one, I'm not sure how much benefit there will be compared to all the effort and risk of regression? It feels like a rabbit hole where we may end up spending too much time.


My approach was  to use the consistent naming right when extracting make targets from workflows in the first place. 

So this second one should be an automatic side effect of the first one if done right.

**Comment by obnoxxx** [comment] 2024-09-09 10:59
Next PR in this direction: #14700

**Comment by BlaineEXE** [comment] 2024-09-09 16:02
I would say that `check.codegen` and `check.crds` are inappropriate naming for these targets. These targets actually generate things and aren't checkers.

Anything that actually generates _stuff_ should not be named `check.X` IMO.

**Comment by obnoxxx** [comment] 2024-09-09 17:10
@BlaineEXE  wrote: 
> I would say that `check.codegen` and `check.crds` are inappropriate naming for these targets. These targets actually generate things and aren't checkers.

> 
> Anything that actually generates _stuff_ should not be named `check.X` IMO.

I agree  that the new targets extracted from github workflows are not purely checkers.
Like the original  workflow, they invoke the corresponding existing  generator targets (thereby **check**ing if that works or fails) before **check**ing if that resulted in uncommitted  changes





> 
> `codegen` is a commonly used name for running codegen in operators, so I think we should keep that, though we could add an alternate name like `gen.codegen` if you like. `crds` (sometimes `manifests`) is similarly a common target for operator projects. I'd suggest we keep `crds` as well, with an option to add an alternate name like `gen.crds`. Then potentially a top-level target just called `generate`/`generators`/`gen.all` to run all generators.


I had no intention of removing the existing targets `codegen` and `crds`, but will happily rename them to `gen.crds` and `gen.codegen`. That's nicely structured and consistent.

But I am wondering what to do with my original goal of check target extraction.

Are you suggesting to have the `gen.foo`targets also  perform the modified files validation, in addition to the actual generation?

**Comment by BlaineEXE** [comment] 2024-09-09 18:29
The wording in the issue description suggests to me that the proposal is to rename `codegen` to `check.codegen`, `crds-gen` to `check.crds`:

> 3. Extract the 'codegen' workflow to a check.codegen make target.
> 4. Extract the 'crds-gen' workflow to a check.crds make target.

If that isn't correct, please update the issue description to reflect the intent to create new targets to check whether codegen and crd gen are committed, or reflect renaming existing checker targets.

**Comment by BlaineEXE** [comment] 2024-09-09 18:34
> Further idea:
> 
> Extracct the 'shellcheck' workflow into a `check.shell-scripts`make target.

I would consider shellcheck a linter and not a checker.

**Comment by obnoxxx** [comment] 2024-09-10 11:27
@BlaineEXE  wrote:

> The wording in the issue description suggests to me that the proposal is to rename `codegen` to `check.codegen`, `crds-gen` to `check.crds`:
> 
> If that isn't correct, please update the issue description to reflect the intent to create new targets to check whether codegen and crd gen are committed, or reflect renaming existing checker targets.

Updated. I hop it is clearer now.

**Comment by obnoxxx** [comment] 2024-09-10 11:30
@BlaineEXE  wrote:
> > Further idea:
> > Extract the 'shellcheck' workflow into a `check.shell-scripts`make target.
> 
> I would consider shellcheck a linter and not a checker.

Right. I categorized it under check since I consider linting as checking for syntactic correctness.

How about introducing yet another make target namespace `lint.` in addition to `gen.`and `check.` ?

**Comment by BlaineEXE** [comment] 2024-09-10 15:59
> `codegen` is a commonly used name for running codegen in operators, so I think we should keep that, though we could add an alternate name like `gen.codegen` if you like. `crds` (sometimes `manifests`) is similarly a common target for operator projects. I'd suggest we keep `crds` as well, with an option to add an alternate name like `gen.crds`. Then potentially a top-level target just called `generate`/`generators`/`gen.all` to run all generators.

Adding clarification to my statement from before. We should keep `codegen` and `crds` targets. We can add additional names for consistency, but since those are commonly-used targets, we should not remove them.

**Closed** 2024-11-17 20:02 UTC
Labels: feature, wontfix
