### ISSUE TITLE
All Rook deployments/pods should use DNS to connect to mons

### ISSUE THREAD

**Issue by travisn** [rook/rook#355] opened 2017-01-30 17:57 UTC
OSDs, MDS, and RGW should all use the internal k8s DNS to find the mons. This way we can failover the mons without the need to update the consumers. Note that the mons themselves cannot use dns as their identity relies on the ip address.

**Comment by kokhang** [comment] 2017-02-22 18:43
The issue why addressing monitors via their domain name is not working is because there is a bug that prevents pods with `hostNetwork: true` to use the skydns on the resolv.conf. The kubernetes controller manager runs as a pod with hostNetwork and therefore the storage class volume plugin is not able to query the kube-dns server to resolve the monitor dns.

The workaround is either to supply a `cluster-dns` arg to kubelet so that it uses that as the nameserver.

There is a fix in docker and there is currently a PR on kubernetes to address this issue.
https://github.com/kubernetes/kubernetes/pull/29378

**Comment by bzub** [comment] 2017-02-28 15:37
Some IPs can be replaced with DNS, for the MON daemons at least, using SRV records and a headless service.

I made this service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-mons
  name: rook-mons
spec:
  ports:
  - name: ceph-mon
    port: 6790
    protocol: TCP
    targetPort: 6790
  selector:
    app: mon
    mon_cluster: rookcluster
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
```

And added `rook-mons.rook.svc.k8s.zbrbdl` this to the mon pod's `/etc/resolv.conf` (my cluster domain is k8s.zbrbdl where usually people use cluster.local I think):
```
$ kubectl -n rook exec mon0 -it sh                                                           ✓  2707  09:31:44 
/ # cat /etc/resolv.conf
search rook.svc.k8s.zbrbdl svc.k8s.zbrbdl k8s.zbrbdl default.svc.k8s.zbrbdl svc.k8s.zbrbdl default.cluster.local rook-mons.rook.svc.k8s.zbrbdl
nameserver 10.3.0.10
options ndots:5
```

And I get SRV records that are expected by mon daemons by default, possibly other ceph daemons/clients. (I confirmed you get SRV records in another container with `dig`)
```
$ kubectl -n rook exec mon0 -- nslookup _ceph-mon._tcp 

nslookup: can't resolve '(null)': Name does not resolve
Name:      _ceph-mon._tcp
Address 1: 10.2.247.20 mon0
Address 2: 10.2.136.146
Address 3: 10.2.6.18
```

So with that we'd just need an automated way to make sure the cluster domain is correct when that's added to resolv.conf.  I'll probably figure it out soon when I get a chance to look more.

Reference: http://docs.ceph.com/docs/master/rados/configuration/mon-lookup-dns/

**Comment by bzub** [comment] 2017-03-02 17:19
[Here's a demo](https://gist.github.com/bzub/b5ece2b19cac7cf7301b1d74e798c04f) I put together of how kubernetes/rook could be configured to use SRV records instead of IPs/Hostnames.

@travisn

**Comment by kokhang** [comment] 2017-03-02 18:35
Hey @bzub, nice work. But modifying the resolv.conf to add the kube-dns nameserver seems hacky.  You can also do this by adding the nameserver to the resolv.conf of the host.

kubernetes/kubernetes#29378 was just merged. I am hoping that this would solve the nameserver/resolv.conf issue

**Comment by kokhang** [comment] 2017-03-02 18:47
@bzub look at kubernetes/kubernetes#29378. I think that should do it.

**Comment by bzub** [comment] 2017-03-02 19:05
Allowing a pod to use kube-dns with `hostNetworking: true` helps many use-cases, but doesn't help if a Rook user cannot easily modify the Master components and servers.  I kind of assumed it was a general goal not to use hostNetworking unless absolutely necessary for pods in Kubernetes.

**Comment by bzub** [comment] 2017-03-02 19:10
To be honest though most Rook users will have admin capability in a cluster, though.  I wonder if there's any cloud platforms that make it difficult to modify resolv.conf on the nodes?  GKE?

**Comment by kokhang** [comment] 2017-03-02 19:25
It depends how your kubernetes is setup. If you have kubelet and the controller manager running on the host, then you would have to add the kube-dns nameserver to the host's resolve.conf. If you run kubernetes' component in a container (ie self hosted), then you set the pod DNS policy to `ClusterFirstWithHostNet`. And that should give you dns settings on the control-manager pod and therefore able to access your mon-service via hostname. I havent tried this yet but im hopeful this will solve this issue.

**Comment by kokhang** [comment] 2017-03-20 18:06
We are creating a volume plugin. Part of this volume plugin is to automatically discover monitor IPs within the Rook cluster. So rook will no longer leverage DNS to do this anymore. Closing.

**Closed by kokhang** 2017-03-20 18:06 UTC
Labels: operator

**Comment by sroze** [comment] 2017-04-04 22:28
What if we also support DNS so we are not locked to setup with an easy setup of flexvolume drivers? Could you also precise where, in the [volume plugin PR](https://github.com/rook/rook/pull/534), the monitor IPs are automatically discovered?

**Comment by kokhang** [comment] 2017-04-04 22:54
@sroze I am thinking of abandoning the flexvolume effort. That was just done for me to experiment if flexvolume was a good fit and if it has everything needed by Rook to integrate with kubernetes.

This is what im proposing now. https://github.com/rook/rook/issues/538#issuecomment-291282784.

To answer your question, the monitor endpoints will be discovered by the provisioner and passed to kubernetes (kubelet) through PersistentVolumeSource objects. Please take a look. https://github.com/rook/rook/issues/538#issuecomment-291282784
