### ISSUE TITLE
Unable to create shared file system because of HEALTH_ERR from mds daemons being down

### ISSUE THREAD

**Issue by zhangfei9734** [rook/rook#5967] opened 2020-08-05 02:29 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```shell
$ kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.3.8/cluster/examples/kubernetes/ceph/filesystem.yaml
$ kubectl -n rook-ceph get pod -l app=rook-ceph-mds
No resources found in rook-ceph namespace.
```

During the period, I set these resource limits (https://ceph.readthedocs.io/en/latest/start/hardware-recommendations/#minimum-hardware-recommendations)
a log that requires at least 4g of memory for mds occurred. Finally, I removed the resource limit for mds, but the mds pods were still not created.
And the delete command cannot end.
```shell
$ kubectl -n rook-ceph delete cephfilesystem myfs
cephfilesystem.ceph.rook.io "myfs" deleted

```
**Expected behavior:**
```shell
$ kubectl -n rook-ceph get pod -l app=rook-ceph-mds
NAME                                      READY     STATUS    RESTARTS   AGE
rook-ceph-mds-myfs-7d59fdfcf4-h8kw9       1/1       Running   0          12s
rook-ceph-mds-myfs-7d59fdfcf4-kgkjp       1/1       Running   0          12s
```
**How to reproduce it (minimal and precise):**

```shell
$ kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.3.8/cluster/examples/kubernetes/ceph/common.yaml
$ kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.3.8/cluster/examples/kubernetes/ceph/operator.yaml
$ kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.3.8/cluster/examples/kubernetes/ceph/cluster.yaml
$ kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.3.8/cluster/examples/kubernetes/ceph/filesystem.yaml
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
https://raw.githubusercontent.com/rook/rook/v1.3.8/cluster/examples/kubernetes/ceph/cluster.yaml
* Operator's logs, if necessary
[ceph-operator.txt](https://github.com/rook/rook/files/5025773/ceph-operator.txt)
* Crashing pod(s) logs, if necessary
[ceph-mgr.txt](https://github.com/rook/rook/files/5025775/ceph-mgr.txt)

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`): Linux stg-k8s-master01 5.4.49-200.el7.x86_64 #1 SMP Wed Jul 1 14:44:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.3.8
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.10
* Kubernetes version (use `kubectl version`): v1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_ERR 1 filesystem is offline; 1 filesystem is online with fewer MDS than max_mds; MDS_ALL_DOWN 1 filesystem is offline; fs myfs is offline because no MDS is active for it. MDS_UP_LESS_THAN_MAX 1 filesystem is online with fewer MDS than max_mds fs myfs has 0 MDS online, but wants 1

**Comment by travisn** [comment] 2020-08-05 21:04
@zhangfei9734 The operator log shows that there is a health err:
```
2020-08-05 01:17:34.325098 I | ceph-spec: ceph-file-controller: CephCluster "rook-ceph" found but skipping reconcile since ceph health is &{"HEALTH_ERR" map["MDS_ALL_DOWN":{"HEALTH_ERR" "1 filesystem is offline"} "MDS_UP_LESS_THAN_MAX":{"HEALTH_WARN" "1 filesystem is online with fewer MDS than max_mds"}] "2020-08-05T01:16:38Z" "2020-08-04T11:54:14Z" "HEALTH_OK"}
```

Of course, the mds is down since it hasn't been created yet. Can you try setting [skipUpgradeChecks: true](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L38) to see if that will workaround the issue?

**Comment by Falconx1000** [comment] 2020-08-08 00:03
I'm running into the same problem with rook 1.4.0 and ceph v15.2.4. Setting `skipUpgradeChecks: true` did not solve the error
`ceph-spec: ceph-file-controller: CephCluster "rook-ceph" found but skipping reconcile since ceph health is &{"HEALTH_ERR" map["MDS_ALL_DOWN":{"HEALTH_ERR" "1 filesystem is offline"} "MDS_UP_LESS_THAN_MAX":{"HEALTH_WARN" "1 filesystem is online with fewer MDS than max_mds"} "POOL_NO_REDUNDANCY":{"HEALTH_WARN" "2 pool(s) have no replicas configured"}] "2020-08-07T23:53:44Z" "2020-08-07T23:35:09Z" "HEALTH_WARN"}`
as this is a small test cluster I have set `requireSafeReplicaSize: false` so the WARN for the 2 pools is expected in my case

**Comment by bitfactory-henno-schooljan** [comment] 2020-08-20 12:07
Is there a way to start the MDS another way to resolve this deadlock?

**Comment by Falconx1000** [comment] 2020-08-20 14:31
I did some more testing and found that the same thing will happen on ceph 14.2.10 if the operator doesn't bring up the cluster correctly the first time. In my case I miss typed the ram limit so the operator skipped setting it up. This is still a problem if the operator skips setting up the mds or they are removed.

**Comment by bitfactory-henno-schooljan** [comment] 2020-08-20 15:38
I noticed that the operator will bring the MDS instances back up fairly quickly when you only remove the deployments, because it takes a while before the cluster enters the error state (reporting MDS being 'laggy' or crashed in the meantime). However, it becomes a problem when the operator is also down at this time.

It is definitely appreciated if it could still heal itself in this scenario, at least by manual intervention, e.g. by also skipping this check when `.spec.skipUpgradeChecks` is set on the CephCluster CR.

**Comment by LalitMaganti** [comment] 2020-10-25 12:25
This issue is essentially a dupe of #5846 and also occurs if you try and recreate a CephFilesytsem CRD for a filesystem which already exists. I ran into this when playing around with workarounds for #6492

IMO the correct way to tackle this is one of two ways:
1. By default the filesystem operator ignores FS_WITH_FAILED_MDS when deciding whether to reconcile. This would require no user intervention but feels a bit dangerous because it's easy to get something wrong and cause bigger issues with the cluster.
2. A  specific option (maybe something like `ignoreMdsAllDown`) is added to the CephFilesystem CRD directly. Overloading the `skipUpgradeChecks` option feels wrong to me as this has nothing to do with upgrades.

**Comment by travisn** [comment] 2020-10-27 00:06
@LalitMaganti The purpose of the health check during reconcile is really just to check if the cluster is more or less healthy before reconciling the filesystem CR (and other CRs). I would suggest that for the purpose of the reconcile check, we should always ignore the MDS all down error, and no need for a new setting in the CR.

**Closed** 2020-10-29 10:30 UTC
Labels: bug, ceph
