### ISSUE TITLE
Block storage is stale when not unmounted

### ISSUE THREAD

**Issue by kokhang** [rook/rook#376] opened 2017-02-08 01:20 UTC
A rook block storage, that is not unmounted before the server is deleted, become stuck and cannot be deleted.

Repro:
1- Create pod with rook-client. I used this https://github.com/rook/rook/blob/master/demo/kubernetes/rook-client/
2- Follow the step to create a block, mount it and write some data to it.
3- Delete the pod
4- Recreate the pod.
5- If you do `rook block ls` you will see the previous block . However you cannot do anything to it. If you try to mount it, it hangs. If you try to unmount it, it gives you errors.
```
# rook block unmount --path /tmp/rook-volume
failed to get device from mount point /tmp/rook-volume: <nil>
# rook block unmount --device rbd0
2017-02-08 00:23:31.707900 I | umount /dev/rbd0: umount: /dev/rbd0: not mounted
```

**Comment by kokhang** [comment] 2017-02-08 01:20
Doing this didnt release the block.
```castle12 ~ # echo "0" > /sys/bus/rbd/remove
-bash: echo: write error: Invalid argument```

**Comment by kokhang** [comment] 2017-02-08 01:21
@bassam recommended to add timeout on rbd mount. https://github.com/torvalds/linux/blob/6763afe4b9f39142bda2a92d69e62fe85f67251c/net/ceph/ceph_common.c#L257
https://github.com/torvalds/linux/blob/6763afe4b9f39142bda2a92d69e62fe85f67251c/net/ceph/ceph_common.c#L255
https://patchwork.kernel.org/patch/6403791/

**Comment by bassam** [comment] 2017-06-28 21:48
@kokhang this is quite painful. adding the timeout is something that would have to happen in rbd volume plugin? or can the provisioner add the timeout to mount options?

**Comment by kokhang** [comment] 2017-07-08 00:41
@bassam you can add mount options from the provisioner. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options.

**Comment by jbw976** [comment] 2017-07-20 21:01
The available timeout options appear to have changed across versions of the linux kernel.  In recent kernels (e.g. 4.11), there is also a `osd_request_timeout` option: https://github.com/torvalds/linux/blob/v4.11/net/ceph/ceph_common.c#L260

Note that this option is the only one that doesn't have a default, which makes me quite suspicious that it may be the culprit: https://github.com/torvalds/linux/blob/v4.11/include/linux/ceph/libceph.h#L72

The other options suggested earlier in this thread all already have timeouts, so I don't think they are the cause of zombie RBDs that don't go away until powering down the machine.  I'm going to try to set this `osd_request_timeout` option and see if that solves the issue.

On a 4.4 kernel however, this option doesn't exist, and I see no options that don't already have timeouts.  I'm not sure if there IS a solution for older kernels: https://github.com/torvalds/linux/blob/v4.4/include/linux/ceph/libceph.h#L68
Note the `osdtimeout` option is deprecated even back in 4.4, so that's not a solution either: https://github.com/torvalds/linux/blob/v4.4/net/ceph/ceph_common.c#L446

Ilya Dryomov hinted at a big rewrite in the 4.5 kernel in this post, which may be where the new `osd_request_timeout` option came from: http://lists.ceph.com/pipermail/ceph-users-ceph.com/2015-December/006612.html

I have a repro on my Ubuntu 16.04 machine that has a 4.4 kernel.  We can see that the osd client (osdc) is indeed sitting and watching the rbd_header object:
```
# for f in $(ls /sys/kernel/debug/ceph/*); do echo "***$f***"; cat /sys/kernel/debug/ceph/*/$f; echo; done
***client_options***
name=rook-rook-user,secret=<hidden>

***monc***
have osdmap 17
want next osdmap

***monmap***
epoch 3
	mon0	10.32.0.158:6790
	mon1	10.32.0.159:6790
	mon2	10.32.0.160:6790

***osdc***
5862	osd0	1.656f3ed6	rbd_header.10212ae8944a	3'73014444032	watch

***osdmap***
epoch 17
flags
pool 0 pg_num 2048 (2047) read_tier -1 write_tier -1
pool 1 pg_num 100 (127) read_tier -1 write_tier -1
osd0	10.32.0.163:6800	100%	(exists, up)	100%
```
I'm not sure what to do about < 4.5 kernels, but I will try the `osd_request_option` on newer kernels to see if that solves it.

**Comment by jbw976** [comment] 2017-07-20 21:06
Shoot, it looks like the `osd_request_timeout` option is only available in 4.11+ kernels: https://github.com/torvalds/linux/commit/7cc5e38f2f0b0b58a22a4c18a56348dd99a71270#diff-0546c1927e5cf5c002c52178cbb0a4ea

**Comment by jbw976** [comment] 2017-07-22 00:29
I tried using the `osd_request_timeout` option on a 4.11 kernel (CoreOS 1437.3.0).  Note that this is actually a map time option, not a mount time option, meaning that using the RBD volume plugin it is not possible to use this option (or any krbd option for that matter) since it does not pass any krbd options on the command line when it calls `rbd map`: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd_util.go#L297

Unfortunately, I still see the zombie RBD behavior where the RBD device does not get cleaned up if the cluster is brought down while the device is still mapped.  The `osd_request_timeout` krbd option does not seem to do what we were hoping for.

Some debugging output after the cluster (all mons/osds) is gone, but the RBD device is still mapped:
```
Every 2.0s: for f in $(ls /sys/kernel/debug/ceph/*); do echo "***$f***"; cat /sys/kernel/debug/ceph/*/$f; echo; done; echo ***lsblk***; lsblk -a | grep -E "NAME|rbd"                                                                       Sat Jul 22 00:24:44 2017

***client_options***
name=admin,secret=<hidden>,osd_request_timeout=60

***monc***
have monmap 3 want 4+
have osdmap 17 want 18
have fsmap.user 0
have mdsmap 0
fs_cluster_id -1

***monmap***
epoch 3
        mon0    10.2.24.5:6790
        mon1    10.2.67.4:6790
        mon2    10.2.67.5:6790

***osdc***
REQUESTS 1 homeless 0
412     osd1    0.5a567e37      [1]/1   [1]/1   rbd_header.106f74b0dc51 0x400024        1       0'0     watch-watch
LINGER REQUESTS
18446462598732840992    osd1    0.5a567e37      [1]/1   [1]/1   rbd_header.106f74b0dc51 0x20    0       W/0

***osdmap***
epoch 17 flags 0x48000
pool 0 'rbd' type 1 size 1 min_size 1 pg_num 2048 pg_num_mask 2047 flags 0x1 lfor 0 read_tier -1 write_tier -1
osd0    10.2.67.6:6800  100%    (exists, up)    100%
osd1    10.2.24.7:6800  100%    (exists, up)    100%

***lsblk***
NAME    MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
rbd0    253:0    0   10M  0 disk
```
Note that even though we have specified `osd_request_timeout=60`, the kernel module is waiting for a monmap update and is still watching a rbd_header, many minutes after the cluster has gone away.

I'm not sure how to solve this problem, I don't see any obvious way for krbd to just abandon and unmap the device if the cluster completely goes away.  I will probably pose this question to the ceph mailing lists.  Any other ideas?

**Comment by bassam** [comment] 2017-07-22 00:31
Let's ask ceph-devel

**Comment by kokhang** [comment] 2017-07-22 00:44
I wonder if we could try to at least mitigate the symptom by doing a clean up (unmap and/or unmount) right before we delete the rook-cluster (or osd pods). So once the osd pods are scheduled to be deleted, we could catch this signal from Kubernetes (i think it is a SIGTERM signal) and do the appropriate cleanup here like unmapping and/or unmounting. 

I have done cleanup work when pods are scheduled to be deleted. Here is an example. https://github.com/kokhang/kubernetes-service-loadbalancer/blob/master/loadbalancer-daemon/keepalived/keepalived.go#L115

**Comment by bassam** [comment] 2017-07-22 00:47
@idryomov would appreciate your input on this

**Comment by idryomov** [comment] 2017-07-22 09:58
If rbd device is not mounted, ```rbd unmap``` will time out after ```mount_timeout``` (default is 60) seconds on post-https://patchwork.kernel.org/patch/6403791/ kernels.  On kernels that don't have that patch, you should be able to just SIGINT or SIGKILL ```rbd unmap``` after giving it some time.

If rbd device is mounted, there is no good way to get rid of it.  ceph clusters typically don't come and go away completely, so this is just not something we've designed for.  If there is no in-flight (likely stuck because the OSDs are gone) I/O, ```rbd unmap -o force``` should get you past -EBUSY to trying to unwatch, which again will time out after ```mount_timeout``` seconds.  ```-o force``` is a fairly recent addition though (4.9 kernel).

There is no ```-o full-force``` or something like that for the case when there is stuck I/O (it's on the TODO list).  ```osd_request_timeout``` map option is there, but it is undocumented because it will time out *any* OSD request, which is dangerous if the cluster is severely degraded or just very slow.

My advice would be to do the proper umount/unmap cleanup.  There is no reason at all to play with potentially dangerous timeout settings or force options if you can reliably detect the "cluster is about to go" event.  There is nothing sane the rbd driver can do about the mounted filesystem, so even if there was a good way to get rid of the device itself, you'd still need to umount the filesystem afterwards to free up the data structures and get your pod into a normal state.

**Comment by jbw976** [comment] 2017-07-25 00:32
Thank you very much @idryomov for the detailed explanation of krbd behavior.  You are a very useful resource :)

We are going to look into any sort of graceful cleanup we can do when the cluster is bring brought down, in the hopes that all devices can be unmapped/unmounted cleanly before they lose contact with the mons/osds that are about to be destroyed. Thanks!

**Comment by bassam** [comment] 2017-07-25 00:51
@idryomov thanks so much for the quick response. Beyond graceful shutdown of the cluster, I'm curious what it would take to improve support for this scenario in krbd. I realize it was not designed for this, but I'd like to pick your brain on what we could do to improve it.

**Comment by idryomov** [comment] 2017-07-25 14:51
@bassam `rbd unmap -o force` is specified as `The driver will wait for running requests to complete and then unmap; requests sent to the driver after initiating the unmap will be failed.`  The plan is to add `rbd unmap -o full-force` that will abort in-flight requests, requests waiting for the exclusive lock, etc.  This should allow to get rid of the rbd device in any circumstances.

**Comment by bassam** [comment] 2017-07-25 15:36
> The plan is to add rbd unmap -o full-force

@idryomov excellent! is this planned for the mimic release? does it require work on the cluster side or just krbd?

**Comment by idryomov** [comment] 2017-07-25 16:03
@bassam Just krbd.  Probably mimic time frame, but no promises ;)

**Comment by jbw976** [comment] 2017-07-29 04:45
thanks for the updates @idryomov, we really appreciate your insight.

just to be clear, for the worst case scenario say in a dev VM cluster, when all the mons/osds have been blown away and krbd can't talk to anything in the ceph cluster...is there any way to shoot krbd in the head and get it back to a good state?  or is a hard power cycle needed each time?  that's the only way we've been able to get a stuck krbd back again.  even trying some backdoor options to get rid of `/dev/rbd0` such as the following do not work:
```
sudo echo "0" | sudo tee /sys/bus/rbd/remove_single_major
```
is there any secret sauce to unstick krbd?  that would be great to know, thanks @idryomov!

**Comment by idryomov** [comment] 2017-07-31 09:44
No.  `remove_single_major` is a stable and documented interface, not a backdoor ;)
If there is no in-flight I/O, you can do:
```
$ sudo rbd unmap -o force /dev/rbd0
# wait for it to time out or send SIGINT
$ sudo umount /mnt
```
If there is in-flight I/O, we expect the cluster to come back.  Currently there is nothing to tell krbd to throw out dirty pages -- that's what `rbd unmap -o full-force` is going to do.

**Comment by jbw976** [comment] 2017-11-04 01:24
Fixed in #1179

**Closed by jbw976** 2017-11-04 01:24 UTC
Labels: block, ceph, reliability

**Comment by caisan** [comment] 2019-01-30 01:59
nice ,this is helpful

**Comment by ValeriiVozniuk** [comment] 2020-10-08 19:41
> If there is in-flight I/O, we expect the cluster to come back. Currently there is nothing to tell krbd to throw out dirty pages -- that's what `rbd unmap -o full-force` is going to do.
Hi @idryomov ,
As I don't see this option present now, could you tell me please, was its addition cancelled for some reasons, or is it still in todo list?

**Comment by idryomov** [comment] 2020-10-08 20:07
It is still on the TODO list.

**Comment by ValeriiVozniuk** [comment] 2020-10-09 07:30
> It is still on the TODO list.

That's unfortunate, any ETA for implementing it? And could you tell me please, is there a more proper place where I can track development/status of that feature?

**Comment by idryomov** [comment] 2020-10-09 12:23
No, there is no ETA.  There is a significant amount of refactoring that needs to happen for it to be implemented cleanly.  The initial plan was to side step that and do a rather gross hack leaving some corner cases unhandled, but it was decided that it is not worth the trouble, given how rarely `rbd unmap -o full-force` would really be the right solution.

I have filed a ticket at https://tracker.ceph.com/issues/47808.

**Comment by ValeriiVozniuk** [comment] 2020-10-09 16:09
Thank you, will keep an eye on that ticket

**Comment by andy108369** [comment] 2022-11-19 23:13
> I have filed a ticket at https://tracker.ceph.com/issues/47808

Sadly there is still no update.. Looks like the only way is to reboot the system when the device got locked up with the in-flight I/O.
In our case it looks like that the `cephcsi` (`csi-rbdplugin`) got OOM killed, which locked up RADOS Block Device (RBD) driver.

(immediate update as am writing this):

FWIW, with the following two steps I've managed to remove `rbd0` without having to restart:
```
# rbd device unmap -o force /dev/rbd0  # replace rbd0 with yours
# hangs here

# kubectl -n rook-ceph delete pods --all
```

After few moments the /dev/rbd0 was gone as well as mountpoints.

In the worst case, if you still have to reboot, then you can accelerate this by "lazy" unmounting the stale devices and then rebooting:
```
# umount --lazy /dev/rbd0 ## replace with yours
# reboot
```
