### ISSUE TITLE
PG Autoscalar not working as expected

### ISSUE THREAD

**Issue by anmolsachan** [rook/rook#3041] opened 2019-04-24 15:51 UTC
On a fresh rook-ceph install with 3 nodes and 6 osd's (20 GB each), the autoscalar was not working as expected. Status as follows:

```
sh-4.2# ceph osd pool autoscale-status
 POOL    SIZE  TARGET SIZE  RATE  RAW CAPACITY   RATIO  TARGET RATIO  PG_NUM  NEW PG_NUM  AUTOSCALE 
 rbd       0                 2.0        114.0G  0.0000        0.3000      64              on        
sh-4.2# ceph -s
  cluster:
    id:     c4bb858f-f7aa-4337-af85-4f9856c56f52
    health: HEALTH_WARN
            too few PGs per OSD (21 < min 30)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 11m)
    mgr: a(active, since 10m)
    osd: 6 osds: 6 up (since 9m), 6 in (since 9m)
 
  data:
    pools:   1 pools, 64 pgs
    objects: 0 objects, 0 B
    usage:   6.1 GiB used, 108 GiB / 114 GiB avail
    pgs:     64 active+clean

```

After adding a new pool with 100p  PG's the cluster went into Healthy state but after some time, the cluster again went into the Warning state.

**Comment by anmolsachan** [comment] 2019-04-24 15:53
@liewegas @travisn Please have a look . Is this expected ?

**Comment by liewegas** [comment] 2019-04-24 15:56
Not expected.  Let me reproduce.

**Comment by leseb** [comment] 2019-04-24 16:01
I don't think that's a Rook bug but anyway...

**Comment by liewegas** [comment] 2019-04-24 18:39
To work around this, just add this to the [global] section of the configmap:
```
mon_pg_warn_min_per_osd = 10
```

**Comment by liewegas** [comment] 2019-04-24 18:41
IIUC, the root cause here is that the existing pools have their target_ratio set such that the sum of all pools' targets does not add to 1.0, so the sizing for the pools that *do* exist doesn't meet the configured min warning threshold.  This isn't a huge problem in general since the cluster isn't full and having a somewhat smaller number of PGs isn't that big a deal, so just lowering the warning is fine.  But problem the fix for this is to set the pools' target_ratios a bit more accurately.

**Closed** 2019-06-25 11:55 UTC
Labels: bug, ceph
