### ISSUE TITLE
osd are not upgrading from version 1.5.10 -> 1.6.1

### ISSUE THREAD

**Issue by psavva** [rook/rook#7750] opened 2021-04-24 10:30 UTC
* Bug Report
OSD is not upgrading, even after 24 hours, still showing mixed versions

Every 2.0s: kubectl -n rook-ceph get deployments -l rook_cluster=rook-ceph -o jsonpath={range .items[*]}{.metadata.name}{"  \tr...  Sat Apr 24 13:24:35 2021

```
rook-ceph-crashcollector-davila         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-crashcollector-flatro         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-crashcollector-roccas         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-mgr-a         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-mon-e         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-mon-h         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-mon-j         req/upd/avl: 1/1/1      rook-version=v1.6.1
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=v1.5.10
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=v1.5.10
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=v1.5.10

```

Same also applies to the ceph version

Every 2.0s: kubectl -n rook-ceph get deployments -l rook_cluster=rook-ceph -o jsonpath={range .items[*]}{.metadata.name}{"  \tr...  Sat Apr 24 13:25:26 2021

```
rook-ceph-crashcollector-davila         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-crashcollector-flatro         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-crashcollector-roccas         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-mgr-a         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-mon-e         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-mon-h         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-mon-j         req/upd/avl: 1/1/1      ceph-version=16.2.1-0
rook-ceph-osd-0         req/upd/avl: 1/1/1      ceph-version=15.2.11-0
rook-ceph-osd-1         req/upd/avl: 1/1/1      ceph-version=15.2.11-0
rook-ceph-osd-2         req/upd/avl: 1/1/1      ceph-version=15.2.11-0
```

**Expected behavior:**

All versions of OSDs must match that of the upgraded deployment version

**How to reproduce it (minimal and precise):**
Upgrade from 1.5.10 -> 1.6.1

**Environment**:
* OS (e.g. from /etc/os-release):
```
[root@FLATRO ceph]# cat  /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* Kernel (e.g. `uname -a`):
```
[root@FLATRO ceph]# uname -a
Linux FLATRO 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

* Cloud provider or hardware configuration:
Bare Metal installation of Kubernetes

* Rook version (use `rook version` inside of a Rook Pod):
```
 [root@rook-ceph-tools-57787758df-rt8w9 /]# rook version
rook: v1.6.1
go: go1.16.3

```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
[root@rook-ceph-tools-57787758df-rt8w9 /]# ceph -v
ceph version 16.2.1 (afb9061ab4117f798c858c741efa6390e48ccf10) pacific (stable).
```

* Kubernetes version (use `kubectl version`):
```
[root@FLATRO ceph]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
Bare Metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
[root@rook-ceph-tools-57787758df-rt8w9 /]# ceph -s
  cluster:
    id:     3bd7a445-c9b4-4524-b298-b96d25e09251
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum e,h,j (age 71m)
    mgr: a(active, since 71m)
    osd: 3 osds: 3 up (since 20m), 3 in (since 3w)

  data:
    pools:   2 pools, 33 pgs
    objects: 4.56k objects, 15 GiB
    usage:   47 GiB used, 853 GiB / 900 GiB avail
    pgs:     33 active+clean

  io:
    client:   78 KiB/s wr, 0 op/s rd, 5 op/s wr

```

**Comment by psavva** [comment] 2021-04-24 10:33
I have the following errors in the Operator:

```
[root@FLATRO ceph]# kubectl logs -n rook-ceph -l app=rook-ceph-operator
2021-04-24 10:27:13.372346 I | ceph-crashcollector-controller: created kubernetes crash collector secret for cluster "rook-ceph"
2021-04-24 10:27:13.871243 I | cephclient: successfully enabled msgr2 protocol
2021-04-24 10:27:13.871267 I | ceph-cluster-controller: upgrade in progress, notifying child CRs
2021-04-24 10:27:13.901081 I | op-mgr: start running mgr
2021-04-24 10:27:13.901136 I | cephclient: getting or creating ceph auth key "mgr.a"
2021-04-24 10:27:14.438396 I | op-mgr: deployment for mgr rook-ceph-mgr-a already exists. updating if needed
2021-04-24 10:27:14.443428 I | op-k8sutil: deployment "rook-ceph-mgr-a" did not change, nothing to update
2021-04-24 10:27:14.445595 I | op-mgr: setting services to point to mgr "a"
W0424 10:27:14.647643       6 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021-04-24 10:27:14.663037 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph mgr: failed to enable mgr services: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-mgr" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"
[root@FLATRO ceph]#

```

**Comment by psavva** [comment] 2021-04-24 11:08
I see that I started updating the Ceph version, without realising the rook-ceph installation did not complete.
I am rolling back the version of ceph to version "ceph/ceph:v15.2.11-20210419" and re-run the upgrade of rook-ceph again to 1.6.1 to try and resolve.

**Comment by psavva** [comment] 2021-04-24 11:14
The rollback does not work.  i get the following crash loop on the mon:

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 0.0 total, 0.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **

debug 2021-04-24T11:12:52.475+0000 7f54adf01700 -1 ERROR: on disk data includes unsupported features: compat={},rocompat={},incompat={13=pacific ondisk layout}
debug 2021-04-24T11:12:52.475+0000 7f54adf01700 -1 error checking features: (1) Operation not permitted


Reverting again back to ceph/ceph:v16.2.1-20210419

**Comment by travisn** [comment] 2021-04-24 14:38
@psavva Did you apply the latest common.yaml according to the [upgrade guide](https://rook.github.io/docs/rook/v1.6/ceph-upgrade.html)? If you still hit that error about the monitoring, you might try setting [monitoring.enabled: false](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L72-L74) as a temporary workaround, to move past this issue and complete the upgrade.

Downgrading from major upgrades of Ceph will lead to unsupported versions, so let's find a way to roll forward and complete the upgrade.

**Comment by cyclops8456** [comment] 2021-04-24 15:32
@psavva As @travisn mentioned above, if you either disable monitoring (edit your cluster config) as a workaround
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
spec:
  monitoring:
    enabled: false
```
or add RBAC config to resolve the issue you're seeing in the operator logs (example below, taken from the monitoring example)
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-monitor
  namespace: rook-ceph
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-monitor
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-monitor
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph
```
I hit the same issue when upgrading a test cluster.  Setting it up from new showed the issue up in a more obvious manner as the operator couldn't get past the initial cluster setup (OSDs weren't prepared etc).

**Comment by psavva** [comment] 2021-04-24 15:42
I have disabled the monitoring, and also created the new Role.
The upgrade of rook-ceph, and Ceph version are successfully completed.
Thank you very much for your help on this.

I suggest putting this fix in and document this for people who may face the same issue.

**Comment by cyclops8456** [comment] 2021-04-24 18:03
@psavva You should be able to re-enable monitoring with the above RBAC in place, on the assumption that you've got prometheus set up in your cluster (and so have the required CRDs for service monitor etc in place).

**Comment by LittleFox94** [comment] 2021-04-25 01:12
was bitten by this, too

as an additional info: I had monitoring enabled but do not use prometheus operator yet. In prior versions of rook, this enabled the prometheus module in mgr as intended, warned about not being able to create the rules and continued - now it errors instead of warning.

I know having prometheus operator is nice and plan to migrate to it, but maybe a way to enable the metrics endpoint in the mgr without having to use prometheus operator would be nice ^^'

**Comment by cyclops8456** [comment] 2021-04-25 13:23
@LittleFox94 I've been experimenting with this a bit today, and with monitoring set to false in the cluster CR, the metrics are still available with the appropriate service monitors set up for prometheus, so the metrics endpoint is available in the mgr pod.

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
spec:
  monitoring:
    enabled: false
```
Looking through the code in relation to the monitoring option, it looks like this is more to automatically create service monitors and prometheus rules, rather than enable the metrics (as the module looks to be loaded automatically with this set to false).  I'd previous set monitoring to true, as I presumed it was required to access the metrics, but this doesn't appear to be the case.  I create the service monitors as part of the prometheus setup, so this actually provides a better separation of config IMHO; going to leave monitoring set to false.

**Comment by LittleFox94** [comment] 2021-04-25 18:53
@cyclops8456 yes seems like enabling monitoring isn't anymore required to have the prometheus module enabled in the manager. I'm pretty sure it was, but I'm using rook since 0.4 or something x)

**Comment by BlaineEXE** [comment] 2021-04-29 20:36
There is also a `cluster/examples/kubernetes/ceph/monitoring/rbac.yaml`. Does the upgrade succeed if you apply that and restart the operator (delete the operator Pod, the operator Deployment will re-create (re-start) the operator Pod)?

**Comment by marklester** [comment] 2021-05-03 14:03
I tried this suggestion and it allowed the osd upgrade to proceed thanks!. Now I just have a
AUTH_INSECURE_GLOBAL_ID_RECLAIM_ALLOWED warning that I am not sure how to resolve.

**Comment by psavva** [comment] 2021-05-03 17:39
Hi @marklester 
See here how to resolve:
https://github.com/rook/rook/issues/7746

More specific: 
https://github.com/rook/rook/issues/7746#issuecomment-825919401

**Comment by BlaineEXE** [comment] 2021-07-27 18:04
I think this is an issue of documenting when the monitoring RBAC changes need applied. I think there are 2 options that aren't mutually exclusive...
1. Add an Updates/Upgrades section to the monitoring docs instructing users to update the RBAC with new Rook updates
   - this is good because it does not add clutter to the upgrade docs
2. Add a subsection to the Rook upgrade docs instructing users to update ancillary resources like RBAC for monitoring. (there may be other ancillary resources that could be updated from time-to-time)
   - this is good because it keeps the upgrade info in one location, but it also adds more clutter
3. (Mix of 1 and 2 above) Do 1 in full, and then add reference links to the upgrade guide. This may be the better option.

Either way, it is becoming time to do the upgrade docs for 1.7, and I propose moving this to 1.7, and we will also backport the change to 1.6.

**Closed** 2021-07-28 16:08 UTC
Labels: bug, ceph
