### ISSUE TITLE
Osd prepare pods stuck on limited resources

### ISSUE THREAD

**Issue by PCatinean** [rook/rook#4476] opened 2019-12-11 22:05 UTC
During the upgrade process from 1.1.1 to 1.1.7 I had beforehand an osd-prepare-pod that did not have enough resources to get allocated and was in Pending state.

After upgrading to 1.1.7 and updating the cluster to adjust the prepareosd pods limits and requests the pending osd prepare pod was stuck with the old limits.

Restarting the operator did not work nor deleting the osd prepare pod manually and then restarting the operator. It kept recreating the pod with the same limits (or better yet did not update the rs since the recreation was done in mere seconds)

My only solution was to free up resources until the pod landed on the node and finished the osd prepare. After this process the operator created prepare pods with the proper resources and limits.

Expected behavior:

Operator updates stuck rs regardless if it has pods which are stuck or not. It seemed to me the re-creation process only works after the pods exit successfully at east once.

**Comment by travisn** [comment] 2019-12-11 22:10
The issue is that the operator sometimes gets stuck retrying in the reconcile loop. A few possible remediations:
- The operator should check for updates to the CR before retrying the reconciliation. (this may require updating to the controller runtime) 
- The operator should not retry in some error conditions where user intervention is needed. In this case, while the osd was stuck waiting for more resources from the k8s scheduler, the operator wouldn't gain anything by retrying.

**Comment by travisn** [comment] 2020-03-11 03:21
This scenario will be fixed with #4939.

**Closed** 2020-06-17 04:58 UTC
Labels: bug, wontfix
