### ISSUE TITLE
docs: Include loading kernel module rbd required for block storage mount

### ISSUE THREAD

**Issue by patrickstjohn** [rook/rook#1320] opened 2017-12-15 17:35 UTC
Running RHEL 7.3 with Kubernetes 1.8.3 and latest rook master (v0.6.0). PCV's stuck in pending and rook toolbox mount command failed with errors relating to missing kernel module. A simple "modprobe rbd" on the host solves the problem. Might be worth adding it to the troubleshooting page or include documentation in the prerequisites section to document assumptions that are made for what is installed on the Kubernetes host.

**Comment by kokhang** [comment] 2017-12-15 18:15
@patrickstjohn this is a workaround but i would like to know what the root cause is. The rook-agent should be able to do this operation here: https://github.com/rook/rook/blob/master/pkg/daemon/agent/flexvolume/manager/ceph/manager.go#L80

I would like to know what in openshift is causing this to fail.

**Comment by patrickstjohn** [comment] 2017-12-16 18:37
Sorry, I should have mentioned this is a Rancher deployment on stock RHEL 7.3. We're running the most recent stable build of Rancher. I'll do some more testing this week and see if I can track down root cause or at least better error tracing.

**Comment by patrickstjohn** [comment] 2017-12-20 01:30
It looks like this was an error with an older kernel that RHEL was on. We upgraded from 3.x to 4.x and this kernel module loaded right up without a problem.

**Comment by galexrt** [comment] 2018-01-15 14:06
@patrickstjohn Is this still an issue for you or was it just an issue with an old kernel as you wrote in last comment?

**Comment by patrickstjohn** [comment] 2018-01-16 14:22
@galexrt That's correct. It was an old kernel problem. As soon as we upgraded our kernels everything worked as expected.

**Comment by galexrt** [comment] 2018-01-16 14:54
Thanks for the feedback on this! I think we can go ahead and close this then.

**Closed by galexrt** 2018-01-16 14:54 UTC
