### ISSUE TITLE
The dashboard module shows "No socket could be created" with hostnetwork=true

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#3474] opened 2019-07-17 21:47 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
"ceph status" shows "HEALTH_ERR" with message "Module 'dashboard' has failed: error('No socket could be created',)"

**Expected behavior:**
The dashboard port can be customized to an un-used port. The default port 8443 has been used by other containers in the system. 

**How to reproduce it (minimal and precise):**

Refer below cephcluster's config with hostnetwork = true and dashboard port as 8444. It's a regular deployment. The same deploy would succeed with "port:8443" and "hostNetwork: false"

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
```
spec:
    cephVersion:
      image: csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/ceph/ceph:v14.2.1-20190430
    dashboard:
      enabled: true
      port: 8444
      ssl: true
    dataDirHostPath: /data0/rook
    mon:
      allowMultiplePerNode: false
      count: 3
      preferredCount: 0
    network:
      hostNetwork: true
```
* Operator's logs, if necessary
Operator log shows no error and correctly identified the new port 8444.
```
2019-07-17 19:35:56.910331 I | exec: Running command: ceph config set mgr.a mgr/dashboard/server_port 8444 --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/421190482
```

* Crashing pod(s) logs, if necessary
All pods are up and running.  But mon pod shows below error.
```
audit 2019-07-17 19:36:06.936914 mon.b (mon.1) 52 : audit [DBG] from='mgr.14518 192.188.88.12:0/1' entity='mgr.a' cmd=[{"prefix": "config-key get", "key": "mgr/dashboard/accessdb_v1"}]: dispatch
audit 2019-07-17 19:36:06.937459 mon.b (mon.1) 53 : audit [DBG] from='mgr.14518 192.188.88.12:0/1' entity='mgr.a' cmd=[{"prefix": "config-key get", "key": "mgr/dashboard/crt"}]: dispatch
audit 2019-07-17 19:36:06.938053 mon.b (mon.1) 54 : audit [DBG] from='mgr.14518 192.188.88.12:0/1' entity='mgr.a' cmd=[{"prefix": "config-key get", "key": "mgr/dashboard/key"}]: dispatch
cluster 2019-07-17 19:36:06.941236 mon.a (mon.0) 114 : cluster [INF] Manager daemon a is now available
debug 2019-07-17 19:36:07.958 7f3fa8cfb700  0 log_channel(cluster) log [DBG] : mgrmap e23: a(active, since 2s)
cluster 2019-07-17 19:36:07.960292 mon.a (mon.0) 115 : cluster [DBG] mgrmap e23: a(active, since 2s)
cluster 2019-07-17 19:36:07.287131 mgr.a (mgr.14518) 1 : cluster [ERR] Unhandled exception from module 'dashboard' while running on mgr.a: error('No socket could be created',)
debug 2019-07-17 19:36:14.902 7f3fac502700  0 mon.a@0(leader) e3 handle_command mon_command({"prefix": "health"} v 0) v1
debug 2019-07-17 19:36:14.903 7f3fac502700  0 log_channel(audit) log [DBG] : from='client.? 192.188.88.13:0/150619327' entity='client.admin' cmd=[{"prefix": "health"}]: dispatch
audit 2019-07-17 19:36:14.903629 mon.a (mon.0) 116 : audit [DBG] from='client.? 192.188.88.13:0/150619327' entity='client.admin' cmd=[{"prefix": "health"}]: dispatch
```
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): 

* Kernel (e.g. `uname -a`): Linux ceph-control-01 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v1.0.2
* Storage backend version (e.g. for ceph do `ceph -v`):  v14.2.1-20190430
* Kubernetes version (use `kubectl version`):  v1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

# kubectl -n rook-ceph-system exec rook-ceph-operator-fbf59668d-8dw8s -- ceph status
  cluster:
    id:     61a99ef2-6cec-4526-9f03-c0bf1974d3ba
    health: HEALTH_ERR
            Module 'dashboard' has failed: error('No socket could be created',)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 2h)
    osd: 3 osds: 3 up (since 2h), 3 in (since 2h)
    rgw: 1 daemon active (radosgw.gateway)
 
  data:
    pools:   7 pools, 700 pgs
    objects: 202 objects, 4.0 KiB
    usage:   3.0 GiB used, 54 GiB / 57 GiB avail
    pgs:     700 active+clean

**Comment by noahdesu** [comment] 2019-07-17 23:51
this might be a dupe of this: https://github.com/rook/rook/issues/3334 if so let's close this one

**Comment by yanchicago** [comment] 2019-07-18 14:28
The hosts in my testing are IPv6 enabled, which is not the same as #3334

**Comment by noahdesu** [comment] 2019-07-18 17:26
@yanchicago could you provide the output of `ip addr`?

**Comment by yanchicago** [comment] 2019-07-18 18:31
Below is the output from mon-a pod. 
`
[root@ceph-control-01 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1600 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:3c:af:2d brd ff:ff:ff:ff:ff:ff
    inet 10.76.155.46/27 brd 10.76.155.63 scope global dynamic eth0
       valid_lft 58723sec preferred_lft 58723sec
    inet6 fe80::f816:3eff:fe3c:af2d/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:39:b2:30 brd ff:ff:ff:ff:ff:ff
    inet 192.188.88.6/26 brd 192.188.88.63 scope global dynamic eth1
       valid_lft 83312sec preferred_lft 83312sec
    inet6 fe80::f816:3eff:fe39:b230/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether 02:42:98:65:aa:50 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:98ff:fe65:aa50/64 scope link 
       valid_lft forever preferred_lft forever
6: vetha3b587c@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether aa:5a:e6:b2:15:3c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::a85a:e6ff:feb2:153c/64 scope link 
       valid_lft forever preferred_lft forever
264: vethe91f103@if263: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether 32:b9:d0:31:7b:9d brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::30b9:d0ff:fe31:7b9d/64 scope link 
       valid_lft forever preferred_lft forever
8: vethdd4434e@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether aa:e9:19:fb:18:3e brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::a8e9:19ff:fefb:183e/64 scope link 
       valid_lft forever preferred_lft forever
12: vethb887447@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether 2e:76:4a:f7:76:db brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::2c76:4aff:fef7:76db/64 scope link 
       valid_lft forever preferred_lft forever
14: veth47b30c9@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether ce:b1:20:59:43:21 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::ccb1:20ff:fe59:4321/64 scope link 
       valid_lft forever preferred_lft forever
16: veth2c090d7@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether 32:7e:d6:7b:fb:bd brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::307e:d6ff:fe7b:fbbd/64 scope link 
       valid_lft forever preferred_lft forever
18: vethbcfb3f7@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue master docker0 state UP group default 
    link/ether c6:6b:bf:4a:80:fa brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::c46b:bfff:fe4a:80fa/64 scope link 
       valid_lft forever preferred_lft forever
19: calif7d02fbfc8b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
20: cali62eba4f6743@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 8
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
21: calib6329006ea6@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 9
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
288: cali567fdc05184@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 10
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
215: cali1e5416b9908@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 15
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
216: cali50c16b2ba9d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 16
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
217: calia2e585878b5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1550 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 17
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
`

**Comment by yanchicago** [comment] 2019-07-24 14:27
Related issue: https://github.com/rook/rook/issues/3508
The customized ceph mgr port doesn't work regardless hostnetwork is true of false.

**Comment by noahdesu** [comment] 2019-08-12 20:08
The fix for changing the port is being tracked here #3603

**Comment by noahdesu** [comment] 2019-08-12 20:08
CC @jmolmo

**Closed** 2019-12-16 20:54 UTC
Labels: bug, wontfix
