### ISSUE TITLE
Deployment of default cluster on minikube does not succeed

### ISSUE THREAD

**Issue by F21** [rook/rook#1574] opened 2018-03-13 23:51 UTC
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
I tried to stand up a rook cluster following the [quick start](https://rook.io/docs/rook/master/quickstart.html). The `rook-ceph-mon` pod goes into a crash loop.

What you expected to happen:
The rook cluster should be created properly.

How to reproduce it (minimal and precise):
1. Start minikube 0.25.0
2. Switch to examples folder: `cd cluster/examples/kubernetes`
3. `kubectl create -f rook-operator.yaml`
4. Wait for the operator to launch
5. `kubectl create -f rook-cluster.yaml`.
6. See `rook-ceph-mon` pod in crash loop.

**Environment**:
* OS (e.g. from /etc/os-release): Windows 10 64-bit with Minikube 0.25.0 and VirtualBox 5.2.8
* Kernel (e.g. `uname -a`): n/a
* Cloud provider or hardware configuration: Intel Core i7 920 with 12GB RAM.
* Rook version (use `rook version` inside of a Rook Pod): `rook: v0.7.0-27.gbfc8ec6`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): minikube
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): n/a

**Comment by jbw976** [comment] 2018-03-13 23:58
Did you happen to have the mon pod logs available?  more details about full log collection can be found at https://rook.io/docs/rook/master/advanced-configuration.html#log-collection

**Comment by F21** [comment] 2018-03-14 00:05
Rook operator and rook mon logs as attached.
[logs-from-rook-ceph-mon-in-rook-ceph-mon0-8ghxn.txt](https://github.com/rook/rook/files/1809106/logs-from-rook-ceph-mon-in-rook-ceph-mon0-8ghxn.txt)
[logs-from-rook-operator-in-rook-operator-77cf655476-t9sgs.txt](https://github.com/rook/rook/files/1809107/logs-from-rook-operator-in-rook-operator-77cf655476-t9sgs.txt)

**Comment by jbw976** [comment] 2018-03-14 00:09
The logs indicate the monitor pod has no free space on the filesystem hosting its `/var/lib/rook` directory:
```
error: monitor data filesystem reached concerning levels of available storage space
```
Can you check on the free space for that dir?

**Comment by F21** [comment] 2018-03-14 00:23
I sshed into the minikube node. The `rook` directory does not exist under `/var/lib`.

**Comment by jbw976** [comment] 2018-03-14 00:43
what does `df -h` say when ssh'd into minikube?  I have:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.4G     0  1.4G   0% /dev
tmpfs           1.5G     0  1.5G   0% /dev/shm
tmpfs           1.5G   25M  1.5G   2% /run
tmpfs           1.5G     0  1.5G   0% /sys/fs/cgroup
tmpfs           1.5G  8.0K  1.5G   1% /tmp
/dev/sda1        17G  2.2G   13G  15% /mnt/sda1
/Users          466G   58G  408G  13% /Users
```

**Comment by F21** [comment] 2018-03-14 00:53
This is what I have:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        932M     0  932M   0% /dev
tmpfs          1001M     0 1001M   0% /dev/shm
tmpfs          1001M   17M  984M   2% /run
tmpfs          1001M     0 1001M   0% /sys/fs/cgroup
tmpfs          1001M  112M  889M  12% /tmp
/dev/sda1        17G 1016M   15G   7% /mnt/sda1
/c/Users        699G  299G  400G  43% /c/Users
```

**Comment by F21** [comment] 2018-03-14 02:16
I deleted the minikube cluster and recreated everything, but I am still seeing the problem.

**Comment by jbw976** [comment] 2018-03-14 20:09
It looks like the Ceph logic to check free space is getting unexpected results, like it's overflowing:
```
(available: -2147483648%!b(MISSING)ytes)
```
This is the call from the Ceph code to get filesystem stats: https://github.com/ceph/ceph/blob/master/src/ceph_mon.cc#L471

Maybe one of the Ceph team members has insight into why this would fail.  One possibility would be that it looks like you're running Minikube on Windows.  Has anyone else tried that with success before?

In the meantime, you could try to increase the logging for the monitor pod by first editing its replicaSet:
```
kubectl -n rook edit rs rook-ceph-mon0
```
That will bring up a text editor and you can add an argument for `--log-level=DEBUG`, so it will look similar to the following:
```
containers:
      - args:
        - mon
        - --config-dir=/var/lib/rook
        - --name=rook-ceph-mon0
        - --port=6790
        - --fsid=cf94de84-0e43-4b17-a130-e65b52947744
        - --log-level=DEBUG
```
Save that and then delete the existing pod to get a new mon pod going with the new debug level logging.  That could give more insight into what's going on here.

**Comment by travisn** [comment] 2018-03-14 20:11
@F21 what is your setting for `dataDirHostPath` in the cluster crd? You may need to use `/mnt/sda1/var/lib/rook` instead of the default `/var/lib/rook`

**Comment by jbw976** [comment] 2018-03-14 20:14
oh right that's a strong possibility.  From https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-cluster.yaml#L16:
> In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
I would have expected an error to be manifested before this behavior though if `/var/lib/rook` was unable to be created.

**Comment by F21** [comment] 2018-03-14 22:21
Updating `dataDirHostPath` to `/data/rook` worked for me!

**Comment by jbw976** [comment] 2018-03-15 00:09
Thanks for confirming @F21.  So this is a duplicate of #1192, thankfully @travisn was able to get to that more quickly than I could.  It sounds like we should improve the documentation (common issues section?) or experience here somehow if people are still running into this and it wasn't immediately known by the dev team what the issue was.

**Comment by galexrt** [comment] 2018-07-15 11:15
@F21 @jbw976 I don't have any issues using minikube with the default `cluster.yaml` in the `example/` directory (using latest `master`)..
Are we sure this is not an "issue" with Minikube for some reason having "different" partition layouts (e.g. `/`, under which the `dataDirHostPath` falls), only a few GB big in size causing the mons to not come up because of the critical "no disk space" available error?

**Comment by travisn** [comment] 2018-07-18 20:59
Looks like this issue was resolved already

**Closed by travisn** 2018-07-18 20:59 UTC
Labels: docs, help wanted, troubleshooting
