### ISSUE TITLE
Support RGW target placement

### ISSUE THREAD

**Issue by arttor** [rook/rook#14441] opened 2024-07-09 13:45 UTC
Probably related or duplicate to #12824 

**What should the feature do:**
Allow to set multiple OSD pools for a single `CephObjectStore` and define target placement for these pools, so clients will be able to use it as bucket `LocationConstraint` for `S3` or `X-Storage-Policy` for `SWIFT` as described in [Ceph doc](https://docs.ceph.com/en/latest/radosgw/placement/#adding-a-placement-target).

**What is use case behind this feature:**
Have a single Ceph Cluster with a single RGW allowing its clients to select target OSD pool placement for s3 bucket or swift container.

**Current workaround**
1. Create target placement pools with `CephBlockPool`  CRD according to naming convention for each `zone` `<zone>.rgw.buckets.data`, `<zone>.rgw.buckets.index`, `<zone>.rgw.buckets.non-ec`. Or create a single`CephObjectRealm` and multiple `CephObjectZoneGroup` - `CephObjectZone` pairs without linking it to `CephObjectStore`.
2. Add new target placement to each of created `zonegroup`: `radosgw-admin zonegroup placement add --placement-id <id> --rgw-zonegroup=<zonegroup>`.
3. Provide the zone placement info for each of that targets: 
  ```shell
   radosgw-admin zone placement add \
      --rgw-zone <zone> \
      --placement-id <id> \
      --data-pool <zone>.rgw.bucket.data \
      --index-pool <zone>.rgw.bukcet.index \
      --data-extra-pool <zone>.rgw.bucket.non-ec
```
4. Set default placement: `radosgw-admin zonegroup placement default --rgw-zonegroup <some-zone> --placement-id <id>`
5. Update the period: `radosgw-admin period update --commit`
6. Restart RGW pods.

**What is missing**
Ability to set target placements and default placement in Rook CRDs.
Probably [storage class](https://docs.ceph.com/en/latest/radosgw/placement/#adding-a-storage-class) also might be interesting for this use-case.

**Proposal**
Extend `CephObjectZone` CRD with placement target options:
```
kind: CephObjectZone
spec:
  zoneGroup: zonegroup-b
  metadataPool:
       ...
  dataPool:
      ...
  placementTraget:
    name: string # placement name (zone name can be used by default)
    default: true # sets placement as default
```

See also:
- Creating Data Placement Strategies in [RedHat storage docs](https://docs.redhat.com/en/documentation/red_hat_ceph_storage/3/html/ceph_object_gateway_for_production/assembly-developing-storage-strategies-rgw-adv#assembly-creating-data-placement-strategies-rgw-adv)

**Comment by travisn** [comment] 2024-07-09 20:52
Agreed, this does look like a duplicate of #https://github.com/rook/rook/issues/12824. After reading again through that issue and also the ceph docs, I do like the proposal to add the `placementTarget` settings to the `CephObjectZone`. This way, multiple zones can be added to an object store, each with their own data and metadata pools, and the default can be set. I haven't looked through the Rook implementation for zones to know how big this work item will be. Primarily, we will need to confirm that it does not cause any regressions for rgw multisite since it also is configured with the zones.

If the rgw pod really needs to be restarted after there is a change in the placement targets, this could be done by adding an env var to the rgw pod, which is a hash of all the zone settings for that object store. Then if the zone settings change, the hash will change when Rook updates the pod spec, and the rgw pod would be restarted by K8s. 

@arttor Are you interested in implementing the feature? I know @anthonyeleven would be very grateful, he has been pushing for this feature for a while.

**Comment by arttor** [comment] 2024-07-10 07:31
@travisn i would be happy to implement it! Do we need further discussion of implementation details?

**Comment by BlaineEXE** [comment] 2024-07-10 14:44
We should make sure to plan how removal/unset works also. That is often where Rook bugs happen, especially with `radosgw-admin` commands that don't have good desired-state functionality.

If `radosgw-admin zone placement add` isn't idempotent, then we also require `get`/`list` equivalent, and the json processing that goes with it. Plus the `rm` equivalent for removing configs.

I'd really like to see a deeper design so that we don't end up having to rehash things while a bunch of code is in PR, which often leads to frustration for everyone.

**Comment by BlaineEXE** [comment] 2024-07-10 14:52
> This way, multiple zones can be added to an object store, each with their own data and metadata pools, and the default can be set.

This diverges with how Ceph operates. From what I recall of conversations with Casey, a Zone (in Ceph terms) is a store. There can be multiple RGWs per Zone, but there can't be multiple Zones per RGW afaiu. Instead, from the docs, it looks like a single zone can have multiple RBD pool targets.

Rook could implement/approximate this by using multiple CephObjectStoreZone CRs, but I am hesitant. I think it would end up being easier for users to grok and compare Ceph-Rook functionality if Rook follows Ceph's structure here and adds a new list of additional pools, with target names.

I'm not sure immediately what to do with the existing pool spec. Maybe it's simplest to say that the base spec is the default, and it is always named `default-placement`. That would also prevent the case where users try to specify `default: true` for multiple placements.

**Comment by anthonyeleven** [comment] 2024-07-10 15:15
>if Rook follows Ceph's structure here and adds a new list of additional pools, with target names.

Agreed.  I don’t grok multisite, so I can’t contribute wrt zones, zonegroups, etc.


With Ceph proper it’s straightforward to add secondary placement targets / storage classes.  Storage classes are a standard thing with AWS S3 as well.  The shortcoming of Rook here is the inability to have multiple storage classes within a single RGW endpoint so that clients (or Lua code) can direct objects to storage tiers as desired.

**Comment by travisn** [comment] 2024-07-10 20:51
@BlaineEXE Thanks for the insight, now I see that it will cause confusion if we use the zone CRD to configure placements since it really is a different concept. We basically need to add the additional pool config as another placement target to the existing zone, rather than adding a new zone. And until there is a clear need to support this for multisite, let's just start simple and say it's not support for not on multisite. With that in mind, what about the following?
1. The additional pools are created with the CephBlockPool
2. The CephObjectStore CRD will have new settings for the additional placements, which takes all the needed fields directly as needed for creating the placements. This gives full flexibility for using the pools however needed, whether using the same metadata pools across placement targets, etc. This would be a list, so zero or more could be specified. For example:

```yaml
  spec:
    additionalPlacements:
    - placementID: <value>
      default: true|false
      dataPool: <value>
      indexPool: <value>
      dataExtraPool: <value>
```

Perhaps the default placement should always be the main pool(s) as specified in the CephObjectStore, though perhaps that is not flexible enough.

**Comment by anthonyeleven** [comment] 2024-07-11 00:25
I think that's a reasonable default, though, at least for now.  The head RADOS object for an RGW object always lives in the default SC/pool even if the payload (if any) is directed elsewhere, so the default bucket/SC pool *should* be on fast storage set up for small objects.  If the RGW object is very small it may even entirely be stored in the head object.

That arguably is policy, though, where here we're concerned with mechanism mostly.

I'm not sure how Ceph would react if the default SC's placement target were changed on a systemwide basis.  My sense is that it's best to not find out.

If one sets a non-default SC / PT for a *user*, that only takes effect for newly-created buckets.

**Comment by arttor** [comment] 2024-07-11 12:02
@travisn your suggestion maps better to our use-case since we are not using multisite. And it will be easier to implement when all placements managed under ObjectStore CRD. Just a couple of questions:
1. are `dataPool`, `indexPool`, and `dataExtraPool` are string names of pre-exising `CephBlockPool` or it could be [PoolSpec](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L743)?
2. do we have plans to support Ceph StorageClasses in the scope of this feature? 
3. how to handle multisite? In our workaround we use `CephObjectStore` name for `--rgw-zonegroup=` and `--rgw-zone=`. Because it is equal to default zone and zonegroup created for rgw. What should we do if `CephObjectStore.spec.zone.name` is set?

**Comment by arttor** [comment] 2024-07-11 13:20
what do you think about following workflow?

<img width="1041" alt="image" src="https://github.com/rook/rook/assets/18706293/22f2ca0a-0f9c-46cb-8562-0c36a5399791">

**Comment by BlaineEXE** [comment] 2024-07-11 15:12
> I see that it will cause confusion if we use the zone CRD to configure placements since it really is a different concept. We basically need to add the additional pool config as another placement target to the existing zone, rather than adding a new zone. And until there is a clear need to support this for multisite, let's just start simple and say it's not support for not on multisite. 

I wasn't trying to suggest that this shouldn't be done on the zone CRD. I was trying to just say that we can't use multiple zone CRDs. 

The Ceph configurations are done on a per-zone basis, so as a starting point, I think it makes sense to consider putting these on the zone CRD. I think that will also help users conceptualize the feature and how ceph features map to rook features.

I think that will also make it more likely that the feature will work with multisite, because someone will inevitably ask about it soon like they always do. And if we decide we need to move it, that will require deprecation of the config on the CephObjectStore. 

-----

As for the proposed workflow, I think `spec.Placement not changed` is exhibiting some logic ideas that don't work well with idempotency or controller theory (that is the basis of k8s operators), and logic that has often proven to have bugs. 

To write quality operator controllers, we have to keep focused on control flows that are always be the same, regardless of the input.

To do that, we should compare `spec.Placement` with the placement that is configured in Ceph's object zone, and take action to ensure Ceph's zone matches the configured input.

-----

I also think that we need to spend more time talking about the user/Rook API as well. I have reservations about defining pools that are likely to be reused between placements. I think it may be more straightforward to require users create an RBD pool beforehand and then reference the pool by name in the placement spec. 

-----

All that said, there is still a lot of discussion required here. @arttor please create a design doc PR so we can discuss in more detail. That is the process that we have in place for Rook so we can have discussions on a per-line basis.

**Comment by travisn** [comment] 2024-07-11 19:09
> I wasn't trying to suggest that this shouldn't be done on the zone CRD. I was trying to just say that we can't use multiple zone CRDs.

> The Ceph configurations are done on a per-zone basis, so as a starting point, I think it makes sense to consider putting these on the zone CRD. I think that will also help users conceptualize the feature and how ceph features map to rook features.

> I think that will also make it more likely that the feature will work with multisite, because someone will inevitably ask about it soon like they always do. And if we decide we need to move it, that will require deprecation of the config on the CephObjectStore.

I'm thinking we would want the `additionalPlacements` slice defined on the CephObjectStore for the common scenario. The CephObjectZone CRD really exists for the multisite scenario, so if we need to support this feature for multisite, this should just mean we would also add the `additionalPlacements` slice to the CephObjectStoreZone CRD in addition. In any case, agreed we should have a design doc PR opened to be clear on all these points as this discussion is getting long. 

> I also think that we need to spend more time talking about the user/Rook API as well. I have reservations about defining pools that are likely to be reused between placements. I think it may be more straightforward to require users create an RBD pool beforehand and then reference the pool by name in the placement spec.

Agreed, this is what I was also trying to say in my [previous comment](https://github.com/rook/rook/issues/14441#issuecomment-2221433377) where I suggested we just take the pool names for the placements as strings, rather than trying to configure the pools directly in the object-related CRs. The pools could be created with the CephBlockPool CR.

> All that said, there is still a lot of discussion required here. @arttor please create a design doc PR so we can discuss in more detail. That is the process that we have in place for Rook so we can have discussions on a per-line basis.

@arttor Likely you could add a new section to the [store.md](https://github.com/rook/rook/blob/master/design/ceph/object/store.md) and/or [zone.md](https://github.com/rook/rook/blob/master/design/ceph/object/zone.md).

**Comment by travisn** [comment] 2024-07-11 19:16
> @travisn your suggestion maps better to our use-case since we are not using multisite. And it will be easier to implement when all placements managed under ObjectStore CRD. Just a couple of questions:
> 
> 1. are `dataPool`, `indexPool`, and `dataExtraPool` are string names of pre-exising `CephBlockPool` or it could be [PoolSpec](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L743)?

I was thinking the `CephBlockPool` would be defined for each of the pools needed to configure the placements, and the placements specified for the object store would only be the string names of the pools.

> 2. do we have plans to support Ceph StorageClasses in the scope of this feature?

Storage classes likely make sense in the scope of this feature, though I'm not clear exactly how it fits together. This would be helpful to flush out in the design doc.

> 3. how to handle multisite? In our workaround we use `CephObjectStore` name for `--rgw-zonegroup=` and `--rgw-zone=`. Because it is equal to default zone and zonegroup created for rgw. What should we do if `CephObjectStore.spec.zone.name` is set?

If `CephObjectStore.spec.zone.name` is set, this is the multisite configuration. In that case, the placements should not be specified in the CephObjectStore, but instead should be set in the CephObjectStoreZone. So I think we need the placement settings in both places if we want to support multisite. But that still seems like it could come later if needed, and not worry about multisite for the placements for now, unless we think there could be a design issue with that.

**Comment by travisn** [comment] 2024-07-11 19:18
> what do you think about following workflow?

How about in the design document you describe the flow in textual form (likely with a bulleted list of steps)? Then it's easier to comment on individual steps of the flow. Thanks!

**Comment by arttor** [comment] 2024-07-12 10:57
Thank you. I will summarize all discussions and propose target-placement solution for a single-site, considering future extensions for StorageClasses and multi-site in the design document.

**Comment by anthonyeleven** [comment] 2024-07-12 15:49
I've never used multisite.  I would think that the two are not related, but it's certainly possible that someone would want to use both.  Does that complicate implementation?

**Comment by BlaineEXE** [comment] 2024-07-12 15:56
> I've never used multisite. I would think that the two are not related, but it's certainly possible that someone would want to use both. Does that complicate implementation?

Multisite often ends up being an unexpected complicating factor for RGW features. I'm trying to figure out what the likelihood is of someone wanting to use both of these features, and effectively the likelihood of us having to convert what we've done with single site to work with multisite.

**Closed** 2024-09-09 17:16 UTC
Labels: feature
