### ISSUE TITLE
No agents running

### ISSUE THREAD

**Issue by kyschouv** [rook/rook#4139] opened 2019-10-21 20:33 UTC
I'm having a lot of trouble getting Rook running (on AKS, `1.14.6`). I seem to be getting close, but I'm having an issue with getting agents running. None ever seem to start up, no matter what I do, and I'm not seeing anything in logs that would help me. This is what I see after deploying `rook-release/rook-ceph` (`image.tag`: `v1.1.2`, `agent.flexVolumeDirPath`: `/etc/kubernetes/volumeplugins`) and a `CephCluster` (`spec.cephVersion.image`: `ceph/ceph:v14.2.4-20190917`, have varied almost all other settings with no success):

```
NAME                                                READY   STATUS      RESTARTS   AGE
pod/csi-cephfsplugin-5fqlm                          3/3     Running     0          14m
pod/csi-cephfsplugin-provisioner-78d9994b5d-47mbj   4/4     Running     0          14m
pod/csi-cephfsplugin-provisioner-78d9994b5d-9fbz8   4/4     Running     0          14m
pod/csi-cephfsplugin-qlg2j                          3/3     Running     0          14m
pod/csi-cephfsplugin-w6qvf                          3/3     Running     0          14m
pod/csi-rbdplugin-2jkpd                             3/3     Running     0          14m
pod/csi-rbdplugin-nm22c                             3/3     Running     0          14m
pod/csi-rbdplugin-provisioner-74d6966958-6sn4m      5/5     Running     0          14m
pod/csi-rbdplugin-provisioner-74d6966958-wln4w      5/5     Running     0          14m
pod/csi-rbdplugin-s756w                             3/3     Running     0          14m
pod/rook-ceph-mgr-a-7f6fcb48d9-8cn4f                1/1     Running     0          7m55s
pod/rook-ceph-mon-a-557756d7d-5j9f7                 1/1     Running     0          10m
pod/rook-ceph-mon-b-57f9d66597-gmjb4                1/1     Running     0          9m36s
pod/rook-ceph-mon-c-78d78b7f64-kj96g                1/1     Running     0          8m54s
pod/rook-ceph-operator-64c78d68b5-tmpss             1/1     Running     0          12m
pod/rook-ceph-osd-0-559cf4c5c5-fh4cg                1/1     Running     0          5m17s
pod/rook-ceph-osd-1-7978b4896-vx7gl                 1/1     Running     0          4m5s
pod/rook-ceph-osd-2-684bc9499c-v997d                1/1     Running     0          4m4s
pod/rook-ceph-osd-prepare-set1-0-data-dmncb-644x8   0/1     Completed   0          7m25s
pod/rook-ceph-osd-prepare-set1-1-data-bd9sv-m8b8w   0/1     Completed   0          7m25s
pod/rook-ceph-osd-prepare-set1-2-data-bs9c4-22vnt   0/1     Completed   0          7m24s
pod/rook-discover-2q7zq                             1/1     Running     0          17m
pod/rook-discover-hpqg4                             1/1     Running     0          17m
pod/rook-discover-n46g9                             1/1     Running     0          17m
```

No real errors in the operator logs. Nothing mentioning agents. Any ideas?

**Comment by galexrt** [comment] 2019-10-21 21:01
Rook Ceph uses Ceph CSI since v1.1 as default. The rook-ceph-agents are for Flexvolume which is not used anymore unless the users manually activates it.

So everything looks fine from the output you posted. Be sure to use the new CSI StorageClass manifests and not the old Flexvolume StorageClassses.

If you want to use Flexvolume (recommendation is to use Ceph CSI thus the default for v1.1), you need to set more than just the `agent.flexVolumeDirPath` value).

Closing as not a bug.

**Closed by galexrt** 2019-10-21 21:01 UTC
Labels: bug

**Comment by yacinelazaar** [comment] 2019-10-22 05:23
> Rook Ceph uses Ceph CSI since v1.1 as default. The rook-ceph-agents are for Flexvolume which is not used anymore unless the users manually activates it.
> 
If it is not used anymore then why its a prerequisite on the v1.1 docs?
For the activation, do we just need to configure the flexvolume path with the kubelet and the operator or is there something else?

> So everything looks fine from the output you posted. Be sure to use the new CSI StorageClass manifests and not the old Flexvolume StorageClassses.
> 
Is there any template file for the new storageclass manifests we can follow?

**Comment by galexrt** [comment] 2019-10-22 12:01
It can still be used, the documentation as of now today just doesn't express it too good that flexvolume prerequisites are only needed to be fullfilled when flexvolume is used.
For which activation? If you need to use Flexvolume instead of Ceph CSI (e.g., Kubernetes version lower 1.13), you would set the flexvolume dir path and disable the flexvolume parts (depending on which install method, manifests or Helm that varies a bit).

**Comment by yacinelazaar** [comment] 2019-10-22 12:20
Running on K8s 1.15 using manifests. Followed the flexconfig config on the docs but the agent was never deployed.
PVCs and PVs are created and bound but they never mount on pods.
I resorted to using Ceph CSI and the drivers work and PVs are mounted.

**Comment by galexrt** [comment] 2019-10-23 08:55
Flexvolume can still be used, the documentation as of now today just doesn't express it too good that flexvolume prerequisites are only needed to be fullfilled when flexvolume is used. We are working on that.

What do you want to activate exactly?
If you need to use Flexvolume instead of Ceph CSI (e.g., Kubernetes version lower 1.13), you need to set the flexvolume dir path and disable the Ceph CSI parts (depending on which install method, manifests or Helm that varies a bit).
E.g., https://github.com/rook/rook/blob/release-1.1/cluster/examples/kubernetes/ceph/operator.yaml#L152-L155 and see lines 162 to 170 for lines to deactivate to disable Ceph CSI then and have Flexvolume active.

**Comment by yq513** [comment] 2019-12-07 14:22
> Flexvolume can still be used, the documentation as of now today just doesn't express it too good that flexvolume prerequisites are only needed to be fullfilled when flexvolume is used. We are working on that.
> 
> What do you want to activate exactly?
> If you need to use Flexvolume instead of Ceph CSI (e.g., Kubernetes version lower 1.13), you need to set the flexvolume dir path and disable the Ceph CSI parts (depending on which install method, manifests or Helm that varies a bit).
> E.g., https://github.com/rook/rook/blob/release-1.1/cluster/examples/kubernetes/ceph/operator.yaml#L152-L155 and see lines 162 to 170 for lines to deactivate to disable Ceph CSI then and have Flexvolume active.

I have also encountered errors for this reason, such as:
Unable to attach or mount volumes: unmounted volumes = [wordpress-persistent-storage], unattached volumes = [default-token-gq92d wordpress-persistent-storage]: failed to get Plugin from volumeSpec for volume "pvc-56ba158b-d26d-486e -89e9-fac52bf28eca "err = no volume plugin matched

I hope the description of operator.yaml is more clear. For example, what should happen when I choose CSI, and how should I choose to annotate CSI for FLEX. It took me two weeks to understand, and pod finally used ceph. Thank you for your efforts
My email is nitaimei@gmail.com,
China mailbox laizikaishi@163.com

**Comment by galexrt** [comment] 2020-01-25 10:28
@yq513 Should you still experience issues mounting storage, please open a new issue with the template filled out, errors logs + events and other such information.
