### ISSUE TITLE
Restrict a ceph pool to a subset of OSDs

### ISSUE THREAD

**Issue by mumrau** [rook/rook#2959] opened 2019-04-10 13:50 UTC
Hello.

I'm using rook for ceph right now, and I have different policies depending on the storage I desire, with each level corresponding to a `CephBlockPool` and it's associated `StorageClass`.
On the other hand, we have some business using `ceph` as a storage backend, a subset of these (let's say a cassandra cluster) already has replication included directly _into_ the business.

For this business I would really appreaciate the factor of replication to be 1, in order to not duplicate storage both in cassandra _and_ in ceph.
Nonetheless, if I have a node failure, I'm losing 1/n (with n number of OSDs) of my storage, chances are that at some point the data I want to query into cassandra will be stored in different chunks, but these chunks would be co-located on the failed node.
My whole cassandra cluster will, in a certain amount of time, completely fail due to "corrupted" filesystem.

Would it be feasible to restict a `CephBlockPool` to a dedicated OSD? If so, I could associate one OSD to each of my 4 cassandra, and be more fault-tolerant.

Thank you in advance.

**Comment by travisn** [comment] 2019-04-10 21:26
@mumrau If there is only a single OSD with the data and its node is lost, would cassandra instances be able to recover after the backing store is lost? I am imagining what you want is that each instance of cassandra points to its own block PVC, then each instance of cassandra would be independent and function in master/slave mode?

**Comment by mumrau** [comment] 2019-04-11 07:34
Cassandra instance would be able to recover and tolerate a node failure because cassandra system itself has a factor of replication (let's assume it's 2), when the node will come back online after the storage node has been completely destroyed, the other cassandra nodes would re-assigne and stream data to the replacement cassandra, which would come with a fresh PV. I hope it makes sense to you @travisn .

In the end, I need a `StorageClass` that ensures me that the entire data is on a single OSD (or a subset of my OSDs, configurable), so that I can ask for a PVC. I would then have multiple of these similar `CephBlockPools` underlying behind their own storage classes that ensure me that a single node lost would kill a single cassandra workload.

**Comment by travisn** [comment] 2019-04-11 17:11
Perhaps what you want is the `crushRoot` property on the pool. See https://rook.io/docs/rook/v0.9/ceph-pool-crd.html

**Comment by mumrau** [comment] 2019-04-12 15:56
Thing is, with the crushRoot way, I would be forced to have a completely dedicated osd for every simulated "availability zone" (sort of).
It would great to be able to "share" the same osd but I feel like it would kinda screw the underlying ceph model. 
I will probably give it a shot and see if it's that complicated, maybe I'll have multiple OSDs on the same node, like one for the classic replicated pool, and a second one for a single "availability zone" of my Cassandra cluster (according to the example I've been talking about in this issue).

**Comment by albertdb** [comment] 2019-05-20 12:12
+1 for this feature. In fact, it could be more general. Think about ephemeral volumes (the concept, you could still use PVC). You don't want to replicate them (so a volume failure is equivalent to a pod failure), but you don't want that potentially all of them fail in case of OSD failure.

So it would be great to be able to limit the parallelism of data stripping across a configurable amount of OSD. That could be extended to limit a pool to use a specific subset or to not overlap with another already defined pool, so they are different availability zones, dynamically managed.

**Comment by albertdb** [comment] 2019-08-18 15:14
Bad bot. Don't close.

**Comment by albertdb** [comment] 2019-11-17 07:44
Still relevant.

**Comment by mykaul** [comment] 2019-11-17 16:36
I think regardless of the replica count, we wish to limit a pool to specific set of OSDs, that in turn will be running on specific (labeled?) nodes.

**Comment by BlaineEXE** [comment] 2019-11-19 18:56
I think this might be something one would need to do from the Ceph CLI in the toolbox pod. I would be wary to put this functionality into Rook as a first class citizen, because I don't see that it is within the 80% of normal users basis, and it would be complex to implement. 

It's also not clear to me why Cassandra must be using Ceph underneath. Why not use a non-sharded database like Postgres or MySQL on top of Ceph or use Cassandra on local disks.

**Comment by mykaul** [comment] 2019-11-20 10:32
I don't think it matters what the workload is really (Cassandra or other) - the requests are both legitimate:
1. Support replica 1 - you lose the data, you re-run the job (for example in CI) and you don't want to pay the replication tax (in performance and cost).
2. Have a pool per set of nodes - again, for various reasons, inc. separation of noisy neighbors (so infra storage and workload storage), edge use cases (the nodes are in a distant location, and then performance and cost of network bandwidth is an issue), security reasons sepration, SLA (different level of performance from a different set of nodes) and other reasons.

**Comment by BlaineEXE** [comment] 2019-11-20 19:22
I believe Rook already supports a replication factor of 1. via `spec:replicated:size` in the CRDs. Unless I am misunderstanding what you intend here.

As far as having a pool per set of nodes, this is possible to do today using Ceph's CLI directly from the toolbox. If implementing this in Rook directly, it would take some time and effort to propose a way to format requests for pools like this into a declarative statement in a manifest and how to handle this for the lifetime of the Ceph cluster as nodes and disks fail and are replaced over time. Having limited resources on the project, we have to justify large efforts like this by considering how many users are benefited and how much benefit they get compared to using the toolbox in the CLI.

I have started looking for other devs' feedback here to try to get more information coming into this issue/request.

**Comment by travisn** [comment] 2019-11-21 07:31
In a related conversation today, there is a very real need for access to storage that is:
- Local to the node for highest performance possible
- No replication. The application manages its own redundancy if needed

Postgres was the example application for these requirements. With Ceph we are bound by the CRUSH rules for distributing the data. If we can't pick up sufficient topology information from then node labels to construct the CRUSH map, agreed with @BlaineEXE that this would be a challenge to implement in Rook. Data affinity is not something that Ceph design allows for. The data by design is spread across the failure domains.

An alternative for postgres and similar scenarios is that we really should have a storage operator that discovers and provisions local volumes. There is no need for Ceph in this scenario.

**Comment by mumrau** [comment] 2019-11-21 07:41
I am not pushing for this feature to be implemented right now, I totally understand the 80% of users rule @BlaineEXE.
There are multiple use cases involved, the one you quote @travisn , when you want to have the data as close as possible from the workload, but also having let's say 2 different pools, all using a whole disk on the machine, but one being on HDDs and the other one on SSDs.
If I try to mess up with Ceph CLI to try and create the desired environment, I'll post the details here.

On the other hand, I'll keep fighting the stale bot :dagger:

**Comment by mykaul** [comment] 2019-11-21 08:20
> In a related conversation today, there is a very real need for access to storage that is:
> 
>     * Local to the node for highest performance possible
> 
>     * No replication. The application manages its own redundancy if needed
> 
> 
> Postgres was the example application for these requirements. With Ceph we are bound by the CRUSH rules for distributing the data. If we can't pick up sufficient topology information from then node labels to construct the CRUSH map, agreed with @BlaineEXE that this would be a challenge to implement in Rook. Data affinity is not something that Ceph design allows for. The data by design is spread across the failure domains.
> 
> An alternative for postgres and similar scenarios is that we really should have a storage operator that discovers and provisions local volumes. There is no need for Ceph in this scenario.

This has several disadvantages:
1. It's not consistent, from the developer perspective - they need to use 2 different storages.
2. It is not expandable - you cannot easily begin with replica 1 and later on move to higher replica count.
3. It may or may not support all the additional goodies we have or may add (compression, encryption, etc.) - and again, per #1 - not in a consistent, abstract from the implementation way.

**Comment by mykaul** [comment] 2019-11-21 08:23
> I believe Rook already supports a replication factor of 1. via `spec:replicated:size` in the CRDs. Unless I am misunderstanding what you intend here.

Just replica 1 is good, but may not be enough - if you can ensure it is only running on specific OSDs, you can have more control (hopefully) on its uptime. You KNOW that if you bring down OSD x or y, then that pool will be down. Vs. if it is spread over all your OSDs, a single failure anywhere might bring it down - which you may not have expected.

I agree to everything said on complexity of the overall solution within Rook - we'll need to look at it vs. other priorities.

**Comment by albertdb** [comment] 2019-11-21 08:45
> > I believe Rook already supports a replication factor of 1. via `spec:replicated:size` in the CRDs. Unless I am misunderstanding what you intend here.
> 
> Just replica 1 is good, but may not be enough - if you can ensure it is only running on specific OSDs, you can have more control (hopefully) on its uptime. You KNOW that if you bring down OSD x or y, then that pool will be down. Vs. if it is spread over all your OSDs, a single failure anywhere might bring it down - which you may not have expected.
> 
> I agree to everything said on complexity of the overall solution within Rook - we'll need to look at it vs. other priorities.

That's the key. Once you have tens of OSD, the probability of experiencing a failure on one of the OSD and bringing down all PV with replica 1 rises considerably, up to the point of being an unreliable storage system.

**Comment by BlaineEXE** [comment] 2019-11-21 18:41
I have gotten the suggestion to create a CRUSH hierarchy based on kubernetes node labels--I believe this feature is planned for Rook but not implmented yet, @travisn? With that, one could create a pool (manually, currently) and assign it to a particular hierarchy tier. I think this would be the most idiomatic way of achieving what is requested here in Ceph's terminology.

I think it would be a reasonable conversation to talk about allowing pool configuration in Rook manifests to specify a hierarchy tier.

**Comment by travisn** [comment] 2019-11-22 21:06
> This has several disadvantages:
>
> It's not consistent, from the developer perspective - they need to use 2 different storages.
It is not expandable - you cannot easily begin with replica 1 and later on move to higher replica count.
> It may or may not support all the additional goodies we have or may add (compression, encryption, etc.) - and again, per #1 - not in a consistent, abstract from the implementation way.

Agreed on the disadvantages. But the scenario has come up multiple times this week, particularly around postgres that needs to be optimized for a high performance database. @liewegas also sees this scenario as something better addressed with local storage than attempting to make Ceph fit the scenario.

> I have gotten the suggestion to create a CRUSH hierarchy based on kubernetes node labels--I believe this feature is planned for Rook but not implmented yet, @travisn? With that, one could create a pool (manually, currently) and assign it to a particular hierarchy tier. I think this would be the most idiomatic way of achieving what is requested here in Ceph's terminology.

> I think it would be a reasonable conversation to talk about allowing pool configuration in Rook manifests to specify a hierarchy tier to achieve this functionality in a way that leverage's Ceph's features and doesn't overcomplicate Rook's manifests.

@BlaineEXE The implementation to pick up node labels to create the CRUSH hierarchy was actually just added recently and is included in the latest release. See the [topology topic](https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html#custom-location-information-for-osds). After the hierarchy is created, you can then use the `crushRoot` property in the pool CR to specify where in the hierarchy the pool should consume resources. So I believe we're already exposing all this machinery in Rook.

**Comment by BlaineEXE** [comment] 2019-12-02 20:21
> @BlaineEXE The implementation to pick up node labels to create the CRUSH hierarchy was actually just added recently and is included in the latest release. See the [topology topic](https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html#custom-location-information-for-osds). After the hierarchy is created, you can then use the `crushRoot` property in the pool CR to specify where in the hierarchy the pool should consume resources. So I believe we're already exposing all this machinery in Rook.

Does this mean we can close this issue as resolved?

**Comment by travisn** [comment] 2020-02-06 21:54
Closing since the CRUSH hierarchy and specify the crushRoot property in the pool is already supported. If a locality is needed for a volume on a specific node, a local storage PV should be used instead of Rook.

**Closed by travisn** 2020-02-06 21:54 UTC
Labels: feature

**Comment by aarononeal** [comment] 2020-05-18 01:59
@travisn I followed the topology topic to create multiple availability zones under the default root. How does one specify these zones using `crushRoot`? 

I tried:
- location formats: `root=default zone=zone1`
- hierarchy paths: `default/zone1` and `/default/zone1`

Results in error: `ceph-block-pool-controller: failed to reconcile invalid pool CR "pool1" spec: unrecognized crush root root=default zone=zone1`

**Comment by aarononeal** [comment] 2020-05-18 02:26
It appears this maps to this [rule syntax](https://docs.ceph.com/docs/nautilus/rados/operations/crush-map/#creating-a-rule-for-a-replicated-pool):
`ceph osd crush rule create-replicated {name} {root} {failure-domain-type} [{class}]`

Which just accepts a single name. I guess that's fine if `{root}` is unique across the crush map. But if there are multiple datacenters each with a `rack1` and you want to target a specific one, you can't unless you include the whole parent hierarchy in the name like `us-east-datacenter1-rack1`.

In any case, not a rook limitation and I can rename my buckets.

**Comment by travisn** [comment] 2020-05-18 17:00
@aarononeal Ceph requires a unique name for every identifier in the CRUSH hierarchy, so you're correct that if you had `rack1` in multiple zones, you would need to rename them to be unique.

**Comment by blackliner** [comment] 2024-03-16 00:52
@aarononeal what did you end up using for `crushRoot`? Is it even possible to mention a region/zone/rack here, or does it have to be a location of type `root`, `default` being the one available usually.

**Comment by aarononeal** [comment] 2024-03-17 22:37
I used `default` and then had to ensure unique names for other nodes. I believe in my tests that parameter did have to be of type `root`, though `failure-domain-type` is more flexible of course.

**Comment by blackliner** [comment] 2024-03-20 19:16
@aarononeal so did you end up with specifying something like this? Where `us-west-2-zone-a` is of type `zone`, and not `root`?
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: block-zone-a
  namespace: rook-ceph
spec:
  crushRoot: us-west-2-zone-a
  failureDomain: host
  replicated:
    size: 3
```

**Comment by blackliner** [comment] 2024-03-20 19:18
@mumrau 
> Thing is, with the crushRoot way, I would be forced to have a completely dedicated osd for every simulated "availability zone" (sort of).

This is what I am struggling with too: If I must use a "real" crush root of type `root`, this means one OSD can not be used by multiple pools (because these pools might want to be spread over all zones for example)

**Comment by aarononeal** [comment] 2024-03-20 19:31
In the end I didn't have fast enough network architecture to support multi-zone replication so I went back to just a single default root. I also don't recall being able to specify zones but am not 100% sure due to the time since my test.

A couple things to consider:

1. If there is a limitation, it's not from Rook. The schema there is just a convenience for the `ceph osd crush rule create-replicated` command.
2. You can test fairly easily what is accepted by adding some test zones to your CRUSH map and running that command.

**Comment by aarononeal** [comment] 2024-03-20 19:36
The [docs](https://docs.ceph.com/en/nautilus/rados/operations/crush-map/#creating-a-rule-for-a-replicated-pool) for that command do say this:

> Normally, the entire cluster hierarchy is nested beneath a root node named default. If you have customized your hierarchy, you may want to create a rule nested at some other node in the hierarchy. It doesn’t matter what type is associated with that node (it doesn’t have to be a root node).

So there's a pretty good chance it might accept a zone after all.

**Comment by blackliner** [comment] 2024-03-20 20:57
Oh, so I will need a new crush rule for these specific zoned pools. And then specify this custom rule as in the `CephBlockPool` instead of `crushRoot` 🤔 

But I do not see a `existingCrushRuleName` field in [the Resource](https://github.com/rook/rook/blob/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md) 😢

**Comment by parth-gr** [comment] 2024-03-21 09:07
Yes you need a custom crush rule for that, and I believe you can set the value by  subfailuredomain for the crush rule, but for its value I think the field is missing. https://github.com/rook/rook/blob/b3b6775cf9b3ffdd88cd5a3f342ac4883a6a42ac/pkg/apis/ceph.rook.io/v1/types.go#L1008
