### ISSUE TITLE
my rook-ceph-agent is CrashLoopBackOff

### ISSUE THREAD

**Issue by planeo1105** [rook/rook#2377] opened 2018-12-13 01:42 UTC
One of the rook-ceph-agent is CrashLoopBackOff. Then look logs
[root@k8s-prelease ~]# kubectl logs -f rook-ceph-agent-g8lqx -n rook-ceph-system
2018-12-13 01:15:47.590627 I | rookcmd: starting Rook v0.9.0-4.g8a49531 with arguments '/usr/local/bin/rook ceph agent'
2018-12-13 01:15:47.590736 I | rookcmd: flag values: --help=false, --log-level=INFO
2018-12-13 01:15:47.592235 I | cephcmd: starting rook ceph agent
2018-12-13 01:15:47.593046 I | exec: Running command: cat /lib/modules/3.10.0-693.2.2.el7.x86_64/modules.builtin
2018-12-13 01:15:47.600197 I | exec: Running command: modinfo -F parm rbd
2018-12-13 01:15:47.606178 I | exec: Running command: modprobe rbd single_major=Y
failed to run rook ceph agent. no mount security mode env var found on the agent, have you upgraded your Rook operator correctly?

I don't know this question,help me.

**Comment by galexrt** [comment] 2018-12-14 06:46
Which rook image tag are you using?
You seem to be running a move-able image tag, e.g., `master`, which is not recommended as it is moving and in your case you now have servers with an image of state that is X days old and on a new/other machine an image of state "now".

**Comment by planeo1105** [comment] 2018-12-18 08:18
@galexrt Thank you, Now I use rook image is master, I delete rook-ceph-operator.yml,and replace rook-ceph-operator.yaml. It's done

**Comment by galexrt** [comment] 2019-03-04 23:13
Closing as issue is resolved for @planeo1105 and the issue is already pretty old.

***

@still-L If you should still have the issue and have ensured that you are using a tagged release and not, e.g., `master`, please open a new issue with logs and/or events of the crashing Pods.

**Closed by galexrt** 2019-03-04 23:13 UTC
