### ISSUE TITLE
Rook not deploying OSD pods

### ISSUE THREAD

**Issue by jbmcfarlin31** [rook/rook#3201] opened 2019-05-20 18:09 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Trying to deploy the newest v1.0.1 Rook operator and associated Ceph cluster - but noticed according to the documentation that my OSD pods are not coming up. Instead, I see the following:
```
NAME                                        READY   STATUS      RESTARTS   AGE
rook-ceph-agent-6sx8v                       1/1     Running     0          22m
rook-ceph-agent-7gf4k                       1/1     Running     0          22m
rook-ceph-mgr-a-66c6c8bb49-ts2g2            1/1     Running     0          14m
rook-ceph-mon-a-6d77868b4d-2t65p            1/1     Running     0          15m
rook-ceph-mon-b-7fbf7db874-42m24            1/1     Running     0          15m
rook-ceph-mon-c-8544cdf89d-t5m6j            1/1     Running     0          14m
rook-ceph-operator-78b7564c74-8kj6c         1/1     Running     0          23m
rook-ceph-osd-prepare-10.253.44.205-s9d5l   0/2     Completed   0          13m
rook-ceph-osd-prepare-10.253.44.207-ppspj   0/2     Completed   0          13m
rook-discover-hkmr4                         1/1     Running     0          22m
rook-discover-wtj8f                         1/1     Running     0          22m
```
In the same output above, I tend to see a `rook-ceph-mon-d` pod coming up and deleting itself on and off - even though I specified the number of mons as the default `3`.

**Expected behavior:**
The output from the [rook documentation](https://rook.github.io/docs/rook/v1.0/ceph-quickstart.html) should look something like this:
```
NAME                                   READY   STATUS      RESTARTS   AGE
rook-ceph-agent-4zkg8                  1/1     Running     0          140s
rook-ceph-mgr-a-d9dcf5748-5s9ft        1/1     Running     0          77s
rook-ceph-mon-a-7d8f675889-nw5pl       1/1     Running     0          105s
rook-ceph-mon-b-856fdd5cb9-5h2qk       1/1     Running     0          94s
rook-ceph-mon-c-57545897fc-j576h       1/1     Running     0          85s
rook-ceph-operator-6c49994c4f-9csfz    1/1     Running     0          141s
rook-ceph-osd-0-7cbbbf749f-j8fsd       1/1     Running     0          25s
rook-ceph-osd-1-7f67f9646d-44p7v       1/1     Running     0          25s
rook-ceph-osd-2-6cd4b776ff-v4d68       1/1     Running     0          25s
rook-ceph-osd-prepare-minikube-vx2rz   0/2     Completed   0          60s
rook-discover-dhkb8                    1/1     Running     0          140s
```

**How to reproduce it (minimal and precise):**

1) Deploy the [example/common.yml](https://github.com/rook/rook/blob/v1.0.1/cluster/examples/kubernetes/ceph/common.yaml)
2) Deploy the [example/operator.yml](https://github.com/rook/rook/blob/v1.0.1/cluster/examples/kubernetes/ceph/operator.yaml) and then pause and wait for the discover, agent, and other pods to come up
3) Deploy the [example/cluster.yml](https://github.com/rook/rook/blob/v1.0.1/cluster/examples/kubernetes/ceph/cluster.yaml)
4) `kubectl -n rook-ceph get pods`

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 16.04`
* Kernel (e.g. `uname -a`): `Linux 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `Azure Stack`
* Rook version (use `rook version` inside of a Rook Pod): `1.0.1`
* Kubernetes version (use `kubectl version`): `1.13.4`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `RKE`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Ceph ===> 
```
  cluster:
    id:     442c960e-107f-4f91-91b0-e4d3019c4094
    health: HEALTH_WARN
            Reduced data availability: 100 pgs inactive

  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 25m)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   1 pools, 100 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             100 unknown
```

**Comment by jbmcfarlin31** [comment] 2019-05-20 20:17
Adding more information to this, as I got my toolbox to finally come up...

The command `ceph osd status` returns:
```
+----+------+------+-------+--------+---------+--------+---------+-------+
| id | host | used | avail | wr ops | wr data | rd ops | rd data | state |
+----+------+------+-------+--------+---------+--------+---------+-------+
+----+------+------+-------+--------+---------+--------+---------+-------+
```

**Comment by travisn** [comment] 2019-05-20 21:49
@jbmcfarlin31 You will need storage devices attached to your nodes in order to configure OSDs with cluster.yaml. If you don't have devices on your nodes, instead try creating cluster-test.yaml, which is for a testing environment (not production) and doesn't require devices.

**Comment by jbmcfarlin31** [comment] 2019-05-21 14:46
@travisn thank you for the reply. Could you elaborate on what exactly you would need for a "storage device"? Or if there is already documentation somewhere, can you point me to that? When I was running rook v0.9.3, the OSD's came up and I think they were just using the k8s worker disks as they devices.

**Comment by marcstreeter** [comment] 2019-05-22 23:58
if this is a new install of 1.0.1 I wouldn't be surprised that the problem is Ceph Nautilus per https://github.com/rook/rook/issues/3180

**Comment by jbmcfarlin31** [comment] 2019-06-06 14:51
@marcstreeter this was an upgrade from v0.9.3. I was going to go to 1.0 first but saw 1.0.1 was out with bug fixes, so figured i'd try that one. Interestingly enough though, that issue you referenced talks about the OSD pods having crashloops. In my particular case, I don't even see the OSD's coming up.

Perhaps it could be a wrong configuration on my head as like what travisn said above - but no matter what I try for storage devices, things just don't seem to want to deploy the OSD's.

**Comment by marcstreeter** [comment] 2019-06-13 10:00
you may be right, at this point however unless you selected mimic even moving to 1.0.x would result in the OSD's that do come up to fail again (and enter the aforementioned crash loop). Probably is best to stay in the version of rook prior to Nautilus until it points to the version of Ceph that fixes this issue.  There probably just needs to be some automated testing implemented here so that releases like Rook 1.0 don't happen again.  I'm still learning CI/CD at the moment so I can't fault too much really.

**Comment by jbmcfarlin31** [comment] 2019-06-13 15:58
@marcstreeter I did upgrade and deploy rook v1.0.2 that was released - and now I can get OSD pods to deploy and come up. I can leverage storage as well though now the ceph dashboard seems to constantly throw 500 errors. I'm thinking of just downgrading back to v0.9.3 until some of this stuff is ironed out... 

I need to be able to have ceph storage and minio object storage which both seem to be broke in this version...

**Comment by leseb** [comment] 2019-06-13 17:52
@jbmcfarlin31 as per your last comment, it seems your initial issue has been resolved. Closing this, feel free to re-open if you have any more concerns. Thanks.

**Closed by leseb** 2019-06-13 17:52 UTC
Labels: bug
