### ISSUE TITLE
Ability to create an Object Store zone configured to use `cloud-sync` module

### ISSUE THREAD

**Issue by WoodyWoodsta** [rook/rook#13777] opened 2024-02-15 09:52 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add the ability to create an Objectstore Multisite zone (probably by CRD) which is configured to use the [`cloud-sync` module](https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/).

**What is use case behind this feature:**
This would allow users to set up off-site, off-ceph replication for the purpose of backups.

**Environment**:
N/A

See also: https://github.com/rook/rook/discussions/13717

**Comment by Ornias1993** [comment] 2024-03-08 09:48
This would be an insanely great feature, allowing us to make local s3 backups for our postgresql databases on-the-fly, while also having the fallback to fetch a backup from the cloud in case of emergency.

**Comment by WoodyWoodsta** [comment] 2024-05-18 20:09
Not stale. Still greatly needed.

**Comment by travisn** [comment] 2024-05-20 16:57
@WoodyWoodsta @Ornias1993 Since this module can be configured with ceph commands according to the [doc](https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/#how-to-configure), we should be able to have a prototype by configuring it with such commands in the Rook toolbox. Do you already have a working prototype  by using the toolbox, or could you try it and share the full configuration that worked for you? It will greatly help for implementing of this feature.

**Comment by WoodyWoodsta** [comment] 2024-05-20 17:05
@travisn I haven't attempted a setup via commands as I wasn't sure how rook would respond to config outside of the current CRDs. If you think this is the right way to go, I can try this and I can report back.

**Comment by travisn** [comment] 2024-05-20 17:32
If it's an object zone not defined by the rook CRs, then Rook wouldn't notice if you're attempting to configure a new zone with these settings. And I was assuming to try in a test cluster in case there is some unintended side effect.

**Comment by WoodyWoodsta** [comment] 2024-05-20 17:41
We can't afford the ability to try this in a non-production cluster, but hopefully we can do it in such a way that it targets non-production buckets.

Remembering now that my original concern was the need for another RGW, so this is more than a configuration.

**Comment by ntm97** [comment] 2024-06-14 13:29
Hey!

I would also really appreciate this feature, so I decided to put in some work and see if I can configure it manually.
It took a while, but I managed to get it working (see steps below)!

Is @thotz already actively working on this? Can we hope for this to be implemented in v1.15?

Also, can I safely keep this manual setup running alongside rook, or should I expect it to break over time (because the keys in the keyring are rotated or something like that)?

If you need any further information, please let me know. For now, I still have this setup running, so I can do some further testing if needed.


### Steps To Configure Cloud Sync

Assuming you already have a `CephObjectStore` called `my-store` (realm, zonegroup and zone `my-store`), follow these steps:
- Run `ceph auth add client.rgw.sync.a mon 'allow rw' osd 'allow rwx'` in the toolbox-container to add a key for the sync RGW;
- Create a `Secret` called `rook-ceph-rgw-sync-a-keyring` similar to the existing `secret/rook-ceph-rgw-my-store-a-keyring`, but replace the key with the one of `client.rgw.sync.a` you just added to the keyring and replace `[client.rgw.my.store.a]` with `[client.rgw.sync.a]`;
- Create a `Service` called `rook-ceph-rgw-sync` similar to the existing `service/rook-ceph-rgw-my-store`, but replace every occurrence of `my-store` with `sync`;
- Create a `Deployment` called `rook-ceph-rgw-sync-a` similar to the existing `deployment.apps/rook-ceph-rgw-my-store-a`, but basically replacing every occurrence of `my-store` and `my.store` with `sync` **except** for the following places:
  - Keep the args `--rgw-realm=my-store` and `--rgw-zonegroup=my-store` as the `sync` zone will be part of the same realm and zonegroup;
  - Keep the name of the `ConfigMap` `rook-ceph-rgw-my-store-mime-types` which is mounted as a volume. We don't need to change any of its contents, so we may as well reuse it for the `sync` RGW deployment.
- Now that we have a second RGW running, we can create and configure the zone from the toolbox-container;
- Create the `sync` zone by running `radosgw-admin zone create --rgw-zonegroup=my-store --rgw-zone=sync --endpoints='http://<IP of service/rook-ceph-rgw-sync>:80' --tier-type=cloud`;
- Create a synchronization user by running `radosgw-admin user create --uid=synchronization-user --display-name='Synchronization User' --system` and take note of the access and secret keys;
- Run `radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=my-store --access-key=<access key> --secret=<secret key>`
- Run `radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=sync --access-key=<access key> --secret=<secret key>`
- Configure the `sync` zone to talk to your S3 target with `radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=sync --tier-config=connection.endpoint=<S3 endpoint>,connection.access_key=<S3 access key>,connection.secret=<S3 secret key>,target_path='<your bucket>/${zone}-${sid}/${bucket}'`. For additional configuration options, see https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/;
- Run `radosgw-admin period update --commit`

Now you should be able to check the sync status with `radosgw-admin sync status --rgw-zone=sync` and get back something like this:

```
realm 7f889959-89b4-4914-92cc-6ca90801fa02 (my-store)
      zonegroup 531d73c9-0a54-46eb-b23f-1283b7a5afb8 (my-store)
           zone 6eab694d-b4e8-4200-a56f-046eb01cd312 (sync)
   current time 2024-06-14T13:13:20Z
zonegroup features enabled: resharding
                   disabled: compress-encrypted
  metadata sync syncing
                full sync: 0/64 shards
                incremental sync: 64/64 shards
                metadata is caught up with master
      data sync source: 94b408d1-e661-4c68-8be1-2362c6bfd191 (my-store)
                        syncing
                        full sync: 0/128 shards
                        incremental sync: 128/128 shards
                        data is caught up with source
```

If you create an object in zone `my-store` it should appear in your target S3 bucket within a few minutes.

**Comment by thotz** [comment] 2024-06-14 13:56
@ntm97 Thanks for manually testing this feature, One small suggestion though you can just create another `cephobjectstore`  named `rgw-sync-a` and `cephobjectstoreuser` name  `synchronization-user` for that objectstore instead of performing steps 1 to 5 and no 7.

Now for the implementation part we either include it as part of cephobjectstore CRD, we have the `zone` [field](https://rook.io/docs/rook/latest-release/CRDs/Object-Storage/ceph-object-store-crd/#zone-settings) or include the options in [cephobjectzone](https://rook.io/docs/rook/latest-release/CRDs/Object-Storage/ceph-object-zone-crd/) CRD. 

I prefer the first one, assuming this one is easier to implement and can be used with a normal ceph object-store without much overhead

The second approach can be easily integrated with multisite clusters, but this feature is not related to multisite and also the normal object store needs to be converted to multisite first as steps mentioned [here](https://rook.io/docs/rook/latest-release/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite/#configure-an-existing-object-store-for-multisite)

**Comment by ntm97** [comment] 2024-06-17 09:04
> For the cloud endpoint IMHO it just needs a rgw server and credentials for s3 user

Not sure what you mean by that. For the sync to work, you need a zone with tier-tye `cloud`, a RGW, and a user that is configured for both your "normal" and your `cloud` zone.

> Yaa even I favour `CephObjectStore.Zone` approach. We can have file like cloud-sync into that and add all options in it. 

Isn't the `CephObjectStore.spec.zone` field intended to specify a zone that is **not** managed by the `CephObjectStore`? So I think specifying `CephObjectStore.spec.zone.name` and any kind of sync settings in the `CephObjectStore` should probably be mutually exclusive. Otherwise the controller would have to do some configuration on the externally managed zone.

So maybe we should add `CephObjectStore.spec.sync` instead? Something like:

```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
spec:
  sync:
    type: "cloud"
    configuration:
      connection:
        endpoint: <string>
        hostStyle: <"path" | "virtual">
        accessKey: <SecretReference>
        secret: <SecretReference>
      targetPath: <string>
```

**Comment by thotz** [comment] 2024-06-18 06:43
> > For the cloud endpoint IMHO it just needs a rgw server and credentials for s3 user
> 
> Not sure what you mean by that. For the sync to work, you need a zone with tier-tye `cloud`, a RGW, and a user that is configured for both your "normal" and your `cloud` zone.
> 
> > Yaa even I favour `CephObjectStore.Zone` approach. We can have file like cloud-sync into that and add all options in it.
> 
> Isn't the `CephObjectStore.spec.zone` field intended to specify a zone that is **not** managed by the `CephObjectStore`? So I think specifying `CephObjectStore.spec.zone.name` and any kind of sync settings in the `CephObjectStore` should probably be mutually exclusive. Otherwise the controller would have to do some configuration on the externally managed zone.
> 
> So maybe we should add `CephObjectStore.spec.sync` instead? Something like:
> 
> ```
> apiVersion: ceph.rook.io/v1
> kind: CephObjectStore
> spec:
>   sync:
>     type: "cloud"
>     configuration:
>       connection:
>         endpoint: <string>
>         hostStyle: <"path" | "virtual">
>         accessKey: <SecretReference>
>         secret: <SecretReference>
>       targetPath: <string>
> ```
 Sorry @ntm97  I misread the feature from `cloud-sync` to `cloud-transition` hence got all the confusion. The structure `tier-config` is the same for both for feature. I checked with RGW devs, from their advice it is better to integrate with multisite. So we need to user `cephobjectzone` CRD instead of pool settings we may need to add tier-config settings there.

**Comment by BlaineEXE** [comment] 2024-06-18 16:54
Hi @ntm97. We are open to you doing design and implementation work if you want to. You've already done good first analysis here (https://github.com/rook/rook/issues/13777#issuecomment-2168055558) which is very helpful for us as reviewers.

From the Ceph docs, it looks like this feature can get quite complicated: https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/#non-trivial-configuration

One of the things I would like to make sure we are able to do is add this support to Rook without having to add support for each field of the possible configs. When we get to advanced features like this, having typed fields for everything usually just ends up making Rook more complicated and limiting what users are able to do.

One of the things we should understand is whether the non-trivial JSON object configuration is required for any version of this feature. Based on the doc section [here](https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/#how-to-configure), it seems to me that it should be possible to do all configuration using the commandline, and that we might be able to simplify the scope of Rook's work by supporting only the trivial configs. That might require users to duplicate information between CephObjectZone objects, but it would also mean that Rook doesn't need to manage shared configuration on the backend, which can get immensely complicated.

I think this feature makes the most sense if Rook only has to handle typed CRD fields for a small set of required arguments like `--endpoints`, `--tier-type`, and the access key/secret. Then Rook allows a map[string]string for adding any more advanced changes.

However, we also need to talk about security. Obviously, for a cloud store, we need to add cloud-side credentials to Rook. That is easy enough to do with Kubernetes Secrets, but we also need to make sure those secrets are kept safe by Rook itself. That means that Rook really should not be setting the secrets on the commandline in plaintext where they might be logged to container logs. We should chat with RGW devs to understand whether those can be set from files instead. If not, we will probably have to add special non-logging commands for `radosgw-admin`, or we will need to modify existing command infrastructure to sanitize those from logs.

It also occurs to me that some users might consider `acls` and `acl_profiles` to be sensitive information that users don't want recorded in plaintext on the CephObjectZone object. 

It also seems from the documentation that RGW has intention to support non-S3 cloud providers in the future. That seems to suggest that even Rook's handling of access key+secret might become outmoded over time.

I think it would be worth planning a mechanism that allows users to define whatever config values they want in a secret, with appropriately matching config names, and then pass the name of the secret to Rook.

For example:
```yaml
kind: Secret
...
data:
  connection.access_key: QWE
  connection.secret: RTY
  connection.host_style: path
  connection.endpoint: UIOP
  target_path: ASDF
  acls: |
    [
      # insert 'acls' json blob here?
    ]
  # etc.
```

In this system, even endpoint is handled in the secret config. Rook's config handling would be relegated to `--tier-type` and the name of the secret to read config values from.

**Comment by ntm97** [comment] 2024-06-19 09:15
Hey @thotz, @BlaineEXE, just to make sure we are on the same page, are we thinking something like this for a minimal cloud sync setup?

```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-a
spec:
  realm: realm-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: data-zone
spec:
  zoneGroup: zonegroup-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: data-store
spec:
  zone:
    name: data-zone
---
apiVersion: v1
kind: Secret
metadata:
  name: tier-config
data:
  connection.endpoint: foo
  ...
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: sync-zone
spec:
  zoneGroup: zonegroup-a
  sync:
    tierType: cloud
    tierConfigSecret: 
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: sync-store
spec:
  zone:
    name: sync-zone
```

The one thing that isn't really obvious to me with this design is how we would handle the creation of the user that the `sync-store` uses to authenticate with the `data-store`. As far as I can tell, we have to create the user, get its AK/SK and add them to both zones (`data-zone` and `sync-zone`). So that would require some sort of explicit link between both zones, I guess.

> That means that Rook really should not be setting the secrets on the commandline in plaintext where they might be logged to container logs. We should chat with RGW devs to understand whether those can be set from files instead. If not, we will probably have to add special non-logging commands for radosgw-admin, or we will need to modify existing command infrastructure to sanitize those from logs.

The only option I am aware of to modify the tier-config is `radosgw-admin zone modify` with one of these flags:
```
   --tier-config=<k>=<v>[,...]
                             set zone tier config keys, values
   --tier-config-rm=<k>[,...]
                             unset zone tier config keys
```
This isn't really ideal for security reasons, as you pointed out, but it's also a pretty impractical API for the controller to reconcile the tier-config. Probably the only way we could deal with deleted config keys is to just get the tier-config, remove every single key, and then add back the ones from the secret - every time the secret is changed. That feels kind of clunky.


If we can figure out a sensible solution, I'd be willing to try implementing this. But just so you know I don't have any experience with the rook codebase, so we'll see if anything becomes of it :smile:

**Comment by ntm97** [comment] 2024-06-20 18:30
> The cloud sync module, from what I can glean from Ceph docs, is intended to allow RGW to sync data to AWS or some other non-RGW S3 backend.
> 
> In that case, it is not reasonable security-wise or implementation-wise for Rook to create the remote user. The remote user must be created by mechanisms associated with the remote system, and then that user's credentials must be given to Rook so Rook can do the sync operations.

I wasn't referring to the "remote user" as you call it. There are actually two sets of credentials at play here, as the cloud sync module is essentially a two-step process: data store -> sync store -> remote system. Obviously the user has to provide credentials to be used by the sync store in the latter step to communicate with the remote system, but first the sync store needs to talk to the data store (or maybe the other way around).

> > Edit: Why is the [CephObjectStoreUser CRD](https://rook.io/docs/rook/latest-release/CRDs/Object-Storage/ceph-object-store-user-crd/) tied to a store? From the radosgw-admin CLI, I don't really get the impression that there is any kind of connection between users and RGWs.
> 
> An S3 user is unusable and irrelevant unless a store exists. Also, Rook does not use `radosgw-admin` to create users any more. Rook uses the recommended RGW Admin Ops (HTTP) API.

But can't one user theoretically be used with multiple stores/zones? If you look at https://github.com/rook/rook/issues/13777#issuecomment-2168055558:

> * Create a synchronization user by running radosgw-admin user create --uid=synchronization-user --display-name='Synchronization User' --system and take note of the access and secret keys;
> * Run radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=my-store --access-key=<access key> --secret=<secret key>
> * Run radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=sync --access-key=<access key> --secret=<secret key>

I created one user, which is then configured for both zones the same way. I am not entirely sure that that's 100% correct/required like that, but it's the only way so far I managed to get it working. Maybe the communication between the two stores is bidirectional?

Anyways, that would be a user, where I feel like it doesn't really belong to **one** store specifically. And I don't see a way to really reflect that in the current rook CRDs.

**Comment by BlaineEXE** [comment] 2024-06-20 18:50
> I wasn't referring to the "remote user" as you call it. There are actually two sets of credentials at play here, as the cloud sync module is essentially a two-step process: data store -> sync store -> remote system. Obviously the user has to provide credentials to be used by the sync store in the latter step to communicate with the remote system, but first the sync store needs to talk to the data store (or maybe the other way around).

I see. Though, I think this might be an assumption. From the Ceph docs, I see it clearly stated that "The cloud sync module requires a creation of a new zone." However, I don't see a requirement that an RGW needs to be associated with the new zone. It seems to me that the `sync-store` from your example [here](https://github.com/rook/rook/issues/13777#issuecomment-2178177543) might not be required. The `sync-zone` certainly is required based on Ceph docs. Based on my understanding of how multisite works with just Ceph RGWs, I believe it is the job of the `data-store` to do the syncing.

I can also clarify that one of the prior RGW devs explained to me that a Zone is more or less equivalent to an object store. It seems to me like it follows that if the Zone is a Ceph RGW zone, then the zone has a CephObjectStore/RGWs, but if the zone is AWS, the Zone won't have a CephObjectStore.

I could be wrong about this, but that is the way that this makes sense to me currently.

@cbodley might have some clarifications.

I can also add that Rook does support multiple CephObjectStores per zone, but that is to support a zone having dedicated client RGWs separate from dedicated multisite replication RGWs. Like this

```
Realm A              Ext Realm
  |                    |
ZGroup A             Ext ZGroup
  |                    |
Zone A               Ext Zone
 /  \                  |
|  SyncObjStore <--> Ext RGWs
ClientObjStore
```

**Comment by ntm97** [comment] 2024-06-20 19:03
> I could be wrong about this, but that is the way that this makes sense to me currently.

I definitely share your intuition right there. That's how I understood it at first too, but what threw me off, was [this part of the docs](https://docs.ceph.com/en/quincy/radosgw/cloud-sync-module/#how-to-configure):

> The cloud sync module requires a creation of a new zone. The zone tier type needs to be defined as cloud:
> `radosgw-admin zone create --rgw-zonegroup={zone-group-name} --rgw-zone={zone-name} --endpoints={http://fqdn}[,{http://fqdn}] --tier-type=cloud`

If I don't have a second RGW, what am I supposed to specify as endpoints here? Using the endpoints of the pre-existing data store definitely didn't work for me. And not specifying any endpoints at all didn't either. In both cases just nothing ever seemed to happen.

That's when I found [this third-party guide on how to setup the cloud sync module](https://croit.io/blog/how-to-back-up-object-storage-using-the-cloud-sync-module) which clearly states:

> There must be a radosgw assigned to each of the zones

**Comment by cbodley** [comment] 2024-06-20 19:05
this cloud sync module hasn't seen any development or testing since it was first written in 2018, so i've assumed that nobody's been trying to use it. are folks out there really using it successfully?

more recently, we introduced lifecycle transitions to cloud: https://docs.ceph.com/en/latest/radosgw/cloud-transition/. that feature is actually tested and maintained, so i'd strongly recommend that over this cloud sync module

> However, I don't see a requirement that an RGW needs to be associated with the new zone.

@BlaineEXE a radosgw does need to be running in this zone to perform the actual replication

**Comment by ntm97** [comment] 2024-06-20 19:46
> this cloud sync module hasn't seen any development or testing since it was first written in 2018, so i've assumed that nobody's been trying to use it. are folks out there really using it successfully?

Oh, ok...

Maybe some background would be helpful here: I stumbled on the cloud sync module in the search of a feasible backup solution for our rook-based S3 stores. Ideally, I would like to have something that allows me to take regular backups of all the S3 objects and store them outside ceph to facilitate disaster recovery in case the ceph cluster is broken beyond repair. From my understanding @WoodyWoodsta seems to be in a similar situation.

I haven't really found any other reasonable solutions for this problem (maybe except manually running something like rclone/s3cmd sync/etc.). @cbodley do you have any insight on what a typical backup strategy for RGW may look like?
 
> more recently, we introduced lifecycle transitions to cloud: https://docs.ceph.com/en/latest/radosgw/cloud-transition/. that feature is actually tested and maintained, so i'd strongly recommend that over this cloud sync module

As far as I understand, this doesn't really fit the use-case of backups, right? From [the docs](https://docs.ceph.com/en/latest/radosgw/cloud-transition/#object-modification-limitations):

> By default, post transition, the source object gets deleted. But it is possible to retain its metadata but with updated values (like storage-class and object-size) by setting config option ‘retain_head_object’ to true. However GET on those objects shall still fail with ‘InvalidObjectState’ error.

In my use-case, I don't want the objects gone from my original RGW store. I just want to replicate them to someplace outside of ceph, leaving the original data untouched.

**Comment by WoodyWoodsta** [comment] 2024-06-20 20:31
Hey folks - thank you @ntm97 for taking the initiative. I'll admit, I'm not ceph-minded enough, nor Rook aware to be actively contributing, so really appreciate the effort here.

> more recently, we introduced lifecycle transitions to cloud...so i'd strongly recommend that over this cloud sync module

@cbodley just to confirm with @ntm97, tiering transitions is an entirely different use-case (well, it's storage tiers as in the name, not replication!). I share @ntm97's requirements in that we need off-site _replication_. Objects need to continue to be available in the same storage tier with the same availability behaviour.

It just so happens that our very specific use case has developed into taking original media assets, converting them into formats for public use, and we then manually ship the original media to archival s3 storage off site as part of our ingestion API. We've accepted that if we need to recover the assets in the case of a rook cluster failure, we'd retrieve original assets from off-site archive and reprocess. But of course this still isn't proper replication and doesn't come with all the benefits of such.

If the solution isn't the cloud-sync module, then there isn't anything else within ceph which supports replication from what I can tell, which is what led me to assume cloud-sync was replication the ceph way (and with it being a multi-site architecture, seemed like exactly how it should work). Other solutions would include externally and periodically syncing buckets using something like [rclone](https://github.com/rclone/rclone), but then there is the classic performance cost vs consistency tradeoff problem.

**Comment by BlaineEXE** [comment] 2024-06-20 21:38
@WoodyWoodsta thanks for chiming in. It's great to have multiple users able to chime in with use-case desires. And thanks @ntm97 for expressing your use case more clearly.

> Other solutions would include externally and periodically syncing buckets using something like [rclone](https://github.com/rclone/rclone), but then there is the classic performance cost vs consistency tradeoff problem.

You are correct. Today, something like rclone is the way to replicate objects between Ceph/RGW and non-Ceph object stores. I also want to note, since I'm not sure what your consistency expectations are of multi-site sync, that my understanding of object store replication is that it does not have the same consistency guarantees that RADOS has. Multisite object replication (and I assume cloud sync as well) is eventually-consistent to my understanding.

-----

I'm also really glad I asked for Casey's advice. For one, to clear up the RGW requirement that I was wrong about, but also to understand that the `cloud-sync` module might actually not be a stable feature that we should spend a lot of time exposing to Rook users. I take Casey's expert advice seriously.

From cloud transition doc (https://docs.ceph.com/en/latest/radosgw/cloud-transition/), it seems like the cloud transition feature might hinge upon object storage class support (distinct from K8s StorageClasses). The feature request for that in Rook is #12824.

-----

As for how to enable Ceph-to-non-Ceph object store syncing, I personally feel that a dedicated utility seems reasonable. I am of the philosophy that cloud architectures (and software architectures overall) work best when specialized components can be hooked together, rather than relying on components to be monoliths. I'm sure there are benefits to doing site-to-site replication with RGW natively, and I am curious to hear Casey's response here also.

Given that the RGW expert-recommended strategy is to use cloud transition, and given that it requires a non-trivial object-storage-class feature, I think it is reasonable for Rook to recommend a dedicated syncing utility like rclone for users who have requirements in the present moment. And let's keep a pulse on this issue for the longer term.

**Comment by WoodyWoodsta** [comment] 2024-06-20 22:08
> Multisite object replication (and I assume cloud sync as well) is eventually-consistent to my understanding.

Viewing consistency as a scale, eventually consistent cloud-sync is sure better for sensitive replication than `rclone` running once every hour, as an example. Over and above that, `rclone` operates blind to changes. I'd need to dig into how `rclone` does the diffs but I have a feeling it's exhaustive and therefore costly if you have many objects. You could probably optimise by including a last-modified query.

The attractive part of cloud-sync, and multi-site in general, was that it sits in the flow of changes. Maybe I'm wrong!

Otherwise, I have no interest in writing something to keep a record of changes in an attempt to make replicating more optimal and intelligent :D

**Comment by blackliner** [comment] 2024-06-26 22:44
Chiming in as another customer use case: large scale data collection in the automotive / AD sector. Our goal is to ingest the recorded data from vehicles to our on-prem ceph cluster, and have the `cloud-sync` module replicate all of it to an AWS S3 bucket. The data that is stored on-prem will be consumed by machine learning clusters that also reside in the same on-prem cluster, whereas the data in the S3 bucket will be consumed by a Spark cluster.

That being said, from reading the docs on cloud transition, I have the impression that this is merely a way to allow glacier-like tiering, rather than one-way replication:
> By default, post transition, the source object gets deleted. But it is possible to retain its metadata but with updated values (like storage-class and object-size) by setting config option ‘retain_head_object’ to true. However GET on those objects shall still fail with ‘InvalidObjectState’ error.

Maybe @cbodley knows more, and there are other features to be added that will make this a real replication feature.

And thanks @ntm97 for your [post](https://github.com/rook/rook/issues/13777#issuecomment-2168055558), it's good to see that the feature can be made to work, even if manually for now.

**Comment by ssbagwe** [comment] 2024-07-30 21:02
> * Configure the `sync` zone to talk to your S3 target with `radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=sync --tier-config=connection.endpoint=<S3 endpoint>,connection.access_key=<S3 access key>,connection.secret=<S3 secret key>,target_path='<your bucket>/${zone}-${sid}/${bucket}'`. For additional configuration options, see https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/;

Thanks, this works with AWS S3. But it only syncs in us-east-1. How do I sync in us-west-2 region? 

I tried below combination but doesn't work:

```
--tier-config=connection.endpoint=s3.us-west-2.amazonaws.com
--tier-config=connection.region='us-west-2'
--tier-config=region='us-west-2'
```

**Comment by BlaineEXE** [comment] 2024-07-31 14:21
From the Ceph docs, I don't see any option for region, only endpoint. https://docs.ceph.com/en/quincy/radosgw/cloud-sync-module/#trivial-configuration

**Comment by ssbagwe** [comment] 2024-07-31 22:19
It doesn't work with. Only works with default us-east-1

`--tier-config=connection.endpoint=http://s3.us-west-2.amazonaws.com`

**Comment by BlaineEXE** [comment] 2024-08-01 14:17
You might be better served asking about that behavior in the Ceph slack or mailing list: https://ceph.io/en/community/connect/

Many more Ceph RGW users and devs might have some experience with this there.

**Comment by thotz** [comment] 2024-08-21 10:36
The cloud transition handles it correctly https://docs.ceph.com/en/reef/radosgw/cloud-transition/. After checking  the rgw codebase it is not handle properly in https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_sync_module_aws.cc. Most like it is due to lack of interest for the feature in upstream ceph

**Comment by BlaineEXE** [comment] 2024-08-21 14:11
I changed the title to reflect that the solution should use the cloud transition feature, due to cloud-sync being broken.

**Comment by WoodyWoodsta** [comment] 2024-08-21 16:48
Where should the concept of replication sit then? These are still two different features, with different outcomes and use cases.

**Comment by BlaineEXE** [comment] 2024-08-21 17:23
That does seem like a good question. My big hesitation with cloud-sync is that it sounds like it is partially broken and that it doesn't have maintenance effort committed to it. I don't see a lot of value for users in adding an RGW feature that is half-baked and has no bakers.

For replicating from RGW to AWS (for example) it seems to me that could transition still applies, but instead of "after 30 days" the transition would be "immediately." But if there needs to be 2-way sync, I don't know.

Maybe @cbodley can shed some more light on how cloud transition can (or can't) meet RGW-->AWS "replication" needs.

While we aren't talking about lifecycle settings at the moment, we are working on storage pool placement and S3 storage classes in this PR: https://github.com/rook/rook/pull/14588. I think this will be a required foundation for Rook to support cloud transition in the future.

**Comment by cbodley** [comment] 2024-08-21 17:25
> Maybe @cbodley can shed some more light on how cloud transition can (or can't) meet RGW-->AWS "replication" needs.

i would agree with @WoodyWoodsta that the cloud transition feature targets a very different use case

**Comment by BlaineEXE** [comment] 2024-08-21 17:30
Okay. I will readjust the title to be what it was originally then, since RGW->cloud replication is still a desire.

**Comment by sdragon83** [comment] 2024-08-28 07:22
> > * Configure the `sync` zone to talk to your S3 target with `radosgw-admin zone modify --rgw-zonegroup=my-store --rgw-zone=sync --tier-config=connection.endpoint=<S3 endpoint>,connection.access_key=<S3 access key>,connection.secret=<S3 secret key>,target_path='<your bucket>/${zone}-${sid}/${bucket}'`. For additional configuration options, see https://docs.ceph.com/en/latest/radosgw/cloud-sync-module/;
> 
> Thanks, this works with AWS S3. But it only syncs in us-east-1. How do I sync in us-west-2 region?
> 
> I tried below combination but doesn't work:
> 
> ```
> --tier-config=connection.endpoint=s3.us-west-2.amazonaws.com
> --tier-config=connection.region='us-west-2'
> --tier-config=region='us-west-2'
> ```

The region parameter is supported in the source code at https://github.com/ceph/ceph/blob/main/src/rgw/rgw_zone.cc, but it seems to be used when accessing buckets.
The rgw operation is designed to create a bucket first and then perform a sync operation.
AWS requires the LocationConstraint parameter when creating a bucket, but it appears there is currently no way to pass this value.
HTTP/1.1 400 Bad Request
x-amz-request-id: E8JDZY591QY62RMZ
x-amz-id-2: kxAjOGnhVEsL2ojlOSbVa4BPUvqp6B5uBplbET2fxSI51kmBm9fRasg5h+dsCzuNvHuNMqxEU9M=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Wed, 28 Aug 2024 05:18:25 GMT
Server: AmazonS3
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>E8JDZY591QY62RMZ</RequestId><HostId>kxAjOGnhVEs12ojlOSbVa4BPUvkp6C5uBplbEC2fxS551kmBm9fKasg5h+dsCzuAvHuNOqxEN9M=</HostId></Error>

This should be release on Ceph, not Rook.

**Comment by thotz** [comment] 2024-08-28 12:46
@sdragon83 : Please note rgw supports region parameter lot of use cases, but it is not properly added for cloud sync module and code is based on this file doc: https://docs.google.com/document/d/18o51Uwn2S9tIjarx9Bli6yw81kl4bDwQpTrMTchk898/edit

**Comment by BlaineEXE** [comment] 2024-08-28 14:37
@thotz that gdoc is not publicly visible.

**Comment by thotz** [comment] 2024-08-29 14:23
> @thotz that gdoc is not publicly visible.

Oops my mistake, I was intended provide the github link only

**Closed** 2024-11-05 20:02 UTC
Labels: feature, wontfix

**Comment by boxstep** [comment] 2025-05-05 13:19
anyone managed to run this with different region?

if you actually put "region" in connection parameters and view the logs it actually has that information

`20250505/eu-west-1/s3/aws4_request`

but somehow it error's out without any clear message.

**Comment by BlaineEXE** [comment] 2025-05-05 19:50
@boxstep you may have better luck asking Ceph devs about this in the Ceph Slack channel or mailing list. RGW devs there will have more technical info. https://ceph.io/en/community/connect/

**Comment by ath88** [comment] 2025-08-21 09:22
Reading through this issue, is the current recommended approach to replication to off-site S3 to use a scheduled `rclone` job or similar?

Cloud Sync seems like the perfect approach to off-site backup of our S3 storage.
