### ISSUE TITLE
Failure on  ceph pg dump pgs_brief -> PGDumpBrief unmarshal issue

### ISSUE THREAD

**Issue by erulabs** [rook/rook#3178] opened 2019-05-15 02:33 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
It appears a failed node (which has been removed and cannot be re-added) can send rook-operator into a loop wherein it seems to never remove the OSD / node (even after being removed from the cluster list)

From the operator logs:
```
2019-05-15 02:02:41.646661 I | exec: Running command: ceph pg dump pgs_brief --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/230761221
2019-05-15 02:02:42.169023 I | exec: dumped pgs_brief
2019-05-15 02:02:42.169942 I | util: retrying after 15s, last error: failed to unmarshal pg dump response: json: cannot unmarshal object into Go value of type []client.PGDumpBrief
```

**Expected behavior:**
I expect either the pgs_brief can be successfully unmarshaled or eventually the system would abandon the effort and forcibly remove the OSD (since I have replicas: 3, and can tolerate the loss of the OSD's data if for some reason it is truly corrupted?)

**How to reproduce it (minimal and precise):**
1. have cluster with `useAllNodes: false`
2. remove node from map
3. see `ceph status` at HEALTHY (and OSD as "out")
4. delete node's host machine and all data
5. rook goes into `cannot unmarshal object into Go value of type []client.PGDumpBrief` loop
6. perhaps this message is unrelated? Need to read more about PGDumpBrief to know exactly whats broken here

**Environment**:
* OS (e.g. from /etc/os-release): coreos 2079.3.0
* Kernel (e.g. `uname -a`): Linux kubesail-k8s-master 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration: DigitalOcean "16gb"
* Rook version (use `rook version` inside of a Rook Pod):  rook: v1.0.1
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by erulabs** [comment] 2019-05-15 02:49
Ah, calling PURGE on the OSD successfully removed it and operator was able to move on. Feel free to close if this is expected behavior

**Comment by erulabs** [comment] 2019-05-15 02:58
One probably worthwhile note: I have recently upgraded from v0.9 to v1.0.1

**Comment by travisn** [comment] 2019-05-16 21:40
@erulabs Did you also update to Nautilus or just the rook upgrade? (ceph v14) @rohan47 is looking into this issue and it looks like a format change in Nautilus.

**Comment by iainlbc** [comment] 2019-05-22 04:02
Running into this as well! 
- Terminated a storage node that was part of a kops provisioned auto scaling group
- New node came up with a new volume (new ip/kube node)
- Operator ran discovery, provisioned a mon on it, joined that to the quorum
- Discovery pods for some reason thought a FS was present on the new node -- im thinking this kept the OSD from being provisioned?:
``````2019-05-21 19:41:38.280505 I | cephosd: skipping device nvme1n1 that is in use (not by rook). fs: LVM2_member, ownPartitions: true```
- Operator logs kept looping this, though the node was removed from the k8s cluster:
```2019-05-22 00:28:51.516633 W | op-osd: waiting for the osd.1 to exceed the grace period
2019-05-22 00:29:51.919034 I | op-osd: osd.1 is marked 'DOWN'
2019-05-22 00:29:51.919062 W | op-osd: osd.1 has been down for longer than the grace period (down since 2019-05-22 00:19:47.860733131 +0000 UTC m=+20460.126060951)
2019-05-22 00:30:52.324875 I | op-osd: osd.1 is marked 'DOWN'```
- I deleted the operator pod so it would be created (is this the best way to restart the operator?)
- This started new provision-discovery pods
- This time they found the volume was available, and an OSD was started
- Operator logs started to spam:
```
2019-05-22 04:02:10.629308 I | exec: dumped pgs_brief
2019-05-22 04:02:10.629604 I | util: retrying after 15s, last error: failed to unmarshal pg dump response: json: cannot unmarshal object into Go value of type []client.PGDumpBrief
2019-05-22 04:02:25.629821 I | exec: Running command: ceph pg dump pgs_brief --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/454455758
```

**Comment by travisn** [comment] 2019-06-06 20:34
Reopening for backport to 1.0

**Comment by sfxworks** [comment] 2019-06-23 08:07
Hi
```
019-06-23 08:06:02.037835 I | util: retrying after 15s, last error: failed to unmarshal pg dump response: json: cannot unmarshal object into Go value of type []client.PGDumpBrief
```
Similar experience after the steps above here https://github.com/rook/rook/issues/3178#issuecomment-494643596

- upgraded from 0.9 to 1.0
- wanted to remove a node/osd
- deleted the osd via ceph tooklkit
- drained a node
- deleted the node via kubectl
- terminate the host
- scaled deployment down/up
- now getting these within the operator

**Comment by leseb** [comment] 2019-06-28 12:07
@sfxworks are you using `v1.0.2`?

**Comment by rohan47** [comment] 2019-06-28 16:48
I am not able to reproduce this @sfxworks 
It will be nice to get more details on how to reproduce this

**Comment by sfxworks** [comment] 2019-07-02 10:31
Sorry for the delay and lack of detail. I am also running a baremetal cluster, so I am not eliminating that as a factor. 

```
kubectl describe pod -n rook-ceph-system | grep Image
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:7c97d0839bf1ca2e85e72813a135996481aa3641fe3de229de107668f958a62e
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:7c97d0839bf1ca2e85e72813a135996481aa3641fe3de229de107668f958a62e
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
    Image:         rook/ceph:v1.0.0
    Image ID:      docker.io/rook/ceph@sha256:b30006ca8e03341c40d47d52d661f85cf36a3a563aa7e951bc4e44d321409322
```

```
NAME         STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
a1           Ready    <none>   87d   v1.14.0   66.70.180.162    <none>        Ubuntu 18.04.2 LTS   4.15.0-47-generic   cri-o://1.13.1-dev
a2           Ready    <none>   87d   v1.14.0   158.69.22.8      <none>        Ubuntu 18.04.2 LTS   4.15.0-47-generic   cri-o://1.13.1-dev
a3           Ready    <none>   29d   v1.14.2   145.239.205.54   <none>        Ubuntu 18.04.2 LTS   4.15.0-50-generic   containerd://1.2.6
server-1-1   Ready    <none>   73d   v1.14.1   54.39.178.54     <none>        Ubuntu 18.04.2 LTS   4.15.0-52-generic   cri-o://1.13.1-dev
vps207526    Ready    master   87d   v1.14.0   158.69.113.202   <none>        Ubuntu 18.04.2 LTS   4.15.0-47-generic   cri-o://1.13.1-dev
```

I followed the guide provided with some minor issues.

```
sh-4.2# ceph status
2019-07-02 10:28:37.177 7f2e572c0700 -1 --2-  >> v2:10.107.217.249:6790/0 conn(0x7f2e581544b0 0x7f2e58152670 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer v2:10.107.217.249:6790/0 is using msgr V1 protocol
2019-07-02 10:28:37.329 7f2e57ac1700 -1 --2-  >> v2:10.108.236.12:6790/0 conn(0x7f2e5815a0e0 0x7f2e5815c4e0 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer v2:10.108.236.12:6790/0 is using msgr V1 protocol
2019-07-02 10:28:37.381 7f2e572c0700 -1 --2- 10.244.8.0:0/985620317 >> v2:10.107.217.249:6790/0 conn(0x7f2e581544b0 0x7f2e58152670 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer v2:10.107.217.249:6790/0 is using msgr V1 protocol
2019-07-02 10:28:37.581 7f2e572c0700 -1 --2-  >> v2:10.107.217.249:6790/0 conn(0x7f2e580ad3e0 0x7f2e580ad860 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=1 rx=0 tx=0)._handle_peer_banner peer v2:10.107.217.249:6790/0 is using msgr V1 protocol
2019-07-02 10:28:37.737 7f2e57ac1700 -1 --2- 10.244.8.0:0/3458052720 >> v2:10.108.236.12:6790/0 conn(0x7f2e580b2ef0 0x7f2e580b53e0 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=1 rx=0 tx=0)._handle_peer_banner peer v2:10.108.236.12:6790/0 is using msgr V1 protocol
2019-07-02 10:28:37.785 7f2e572c0700 -1 --2- 10.244.8.0:0/3458052720 >> v2:10.107.217.249:6790/0 conn(0x7f2e580ad3e0 0x7f2e580ad860 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=1 rx=0 tx=0)._handle_peer_banner peer v2:10.107.217.249:6790/0 is using msgr V1 protocol
  cluster:
    id:     e5a100b0-6abd-4968-8895-300501aa9200
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum h,f,g (age 9d)
    mgr: a(active, since 7h)
    osd: 6 osds: 4 up (since 7d), 4 in (since 7d)

  data:
    pools:   1 pools, 100 pgs
    objects: 10.35k objects, 31 GiB
    usage:   288 GiB used, 1.8 TiB / 2.1 TiB avail
    pgs:     100 active+clean

  io:
    client:   235 KiB/s wr, 0 op/s rd, 29 op/s wr
```
https://github.com/rook/rook/blob/master/Documentation/ceph-upgrade.md
Scaling down and up the mons still left me with them using the v1 protocol for example.

**Comment by sfxworks** [comment] 2019-07-02 10:32
@leseb I am using v1.0.0. Apologies, was this resolved in a later variant?

**Comment by noahdesu** [comment] 2019-07-02 22:07
@sfxworks looks like the fix is in v1.0.2 

https://github.com/rook/rook/commit/fb22976750536208cef985ab3174d0f1441c93a7

**Comment by sfxworks** [comment] 2019-07-03 08:24
Thanks! I checked out release-1.0 before I started the upgrade. Experience among repositories has taught me to not use master, but I'll make an exception this time. Thanks for clarifying!

**Comment by noahdesu** [comment] 2019-07-03 15:20
@sfxworks it appears the fix is in v1.0.2. Why would you use master?

**Comment by rohan47** [comment] 2019-07-03 15:25
The fix was backported into release 1.0
https://github.com/rook/rook/pull/3272

**Comment by sfxworks** [comment] 2019-07-03 18:33
```
-bash-4.2# cat .bash_history | grep deploy/rook-ceph-operator
kubectl -n $ROOK_SYSTEM_NAMESPACE set image deploy/rook-ceph-operator rook-ceph-operator=rook/ceph:v1.0.0
```
Interesting! So to confirm, I'd just
```
kubectl -n $ROOK_SYSTEM_NAMESPACE set image deploy/rook-ceph-operator rook-ceph-operator=rook/ceph:v1.0.2
```

**Comment by noahdesu** [comment] 2019-07-03 18:40
Looks like that is the recommended method:

https://github.com/rook/rook/blob/master/Documentation/ceph-upgrade.md#patch-release-upgrades

**Comment by rohan47** [comment] 2019-07-04 07:37
@sfxworks Is it solved for you? If it is then I will close the issue.

**Closed** 2019-07-04 09:05 UTC
Labels: bug

**Comment by sfxworks** [comment] 2019-07-04 11:55
This solved my issue, thanks!
