### ISSUE TITLE
After upgrade from v17.2.6 to v17.2.7 OSDs crashloopbackoff

### ISSUE THREAD

**Issue by Dennisovan92** [rook/rook#13137] opened 2023-11-01 18:06 UTC
* Bug Report

When changing version of ceph in rook-ceph helm chart from v17.2.6 to v17.2.7-20231027 as described in issue #12099 OSD pods are not starting back and they are stuck on Init:CrashLoopBackOff.

I'm deploying rook-ceph with helm chart from ArtificalHub using Terraform.

OS: CentOS Stream release 8
Kernel: 4.18.0-519.el8.x86_64

kubeadm version: &version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.2", GitCommit:"89a4ea3e1e4ddd7f7572286090359983e0387b2f", GitTreeState:"clean", BuildDate:"2023-09-13T09:34:32Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

```
| k8s-control-plane-10           Ready           control-plane           v1.28.2                       9           142           1885              7             12            2000           15591 8h             │
│ k8s-storage-node151            Ready           storage                 v1.28.2                      14           179           2301              2              7            8000           31719 8h             │
│ k8s-storage-node152            Ready           storage                 v1.28.2                      13           172           2524              2              7            8000           31719 8h             │
│ k8s-storage-node153            Ready           storage                 v1.28.2                      15           666           3100              8              9            8000           31719 8h             │
│ k8s-worker101                  Ready           worker                  v1.28.2                       9           257           1522              6              6            4000           23655 8h             │
│ k8s-worker102                  Ready           worker                  v1.28.2                       9           121           1257              3              5            4000           23655 8h             │
│ k8s-worker103                  Ready           worker                  v1.28.2                       9            50           1245              1              5            4000           23655 8h             │
│ k8s-worker104                  Ready           worker                  v1.28.2                       7            54           1131              1              7            4000           15591 8h             │
│ k8s-worker105                  Ready           worker                  v1.28.2                       9            86           1371              2              8            4000           15591 8h             │
```

* CephCluster  Info:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  creationTimestamp: "2023-11-01T10:09:31Z"
  finalizers:
  - cephcluster.ceph.rook.io
  generation: 9
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rook-ceph
  namespace: rook-ceph
  resourceVersion: "91418"
  uid: f0653b79-8625-4457-a6ea-fe51841d94ea
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.7-20231027
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  dashboard:
    enabled: true
    port: 8443
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    count: 2
    modules:
    - enabled: true
      name: rook
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring: {}
  network:
    connections:
      compression: {}
      encryption: {}
    multiClusterService: {}
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage
              operator: In
              values:
              - storage
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-taint.kubernetes.io/storage
        operator: Exists
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  resources:
    cleanup:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        cpu: 500m
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    exporter:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 50Mi
    logcollector:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    osd:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
    prepareosd:
      requests:
        cpu: 500m
        memory: 50Mi
  security:
    keyRotation:
      enabled: false
    kms: {}
  storage:
    flappingRestartIntervalHours: 0
    nodes:
    - devices:
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook1
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook2
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook3
      name: k8s-storage-node151
    - devices:
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook1
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook2
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook3
      name: k8s-storage-node152
    - devices:
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook1
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook2
      - name: /dev/disk/by-id/dm-name-vg_rook-lv_rook3
      name: k8s-storage-node153
    store: {}
    useAllDevices: false
  waitTimeoutForHealthyOSDInMinutes: 10
status:
  ceph:
    capacity:
      bytesAvailable: 2471865466880
      bytesTotal: 2473888579584
      bytesUsed: 2023112704
      lastUpdated: "2023-11-01T17:34:31Z"
    details:
      OSD_DOWN:
        message: 3 osds down
        severity: HEALTH_WARN
      OSD_FLAGS:
        message: 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT}
          flags set
        severity: HEALTH_WARN
      OSD_HOST_DOWN:
        message: 1 host (3 osds) down
        severity: HEALTH_WARN
      PG_DEGRADED:
        message: 'Degraded data redundancy: 648/1944 objects degraded (33.333%), 88
          pgs degraded, 265 pgs undersized'
        severity: HEALTH_WARN
      POOL_APP_NOT_ENABLED:
        message: 1 pool(s) do not have an application enabled
        severity: HEALTH_WARN
    fsid: dda6c867-4047-4fb9-a744-1575da352c5d
    health: HEALTH_WARN
    lastChanged: "2023-11-01T17:22:13Z"
    lastChecked: "2023-11-01T17:34:31Z"
    previousHealth: HEALTH_OK
    versions:
      mds:
        ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable): 2
      mgr:
        ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable): 2
      mon:
        ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable): 3
      osd:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 6
      overall:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 6
        ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable): 8
      rgw:
        ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable): 1
  conditions:
  - lastHeartbeatTime: "2023-11-01T17:33:46Z"
    lastTransitionTime: "2023-11-01T17:33:46Z"
    message: Processing OSD 6 on node "k8s-storage-node151"
    reason: ClusterProgressing
    status: "True"
    type: Progressing
  - lastHeartbeatTime: "2023-11-01T17:34:35Z"
    lastTransitionTime: "2023-11-01T10:11:51Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  message: Cluster created successfully
  observedGeneration: 8
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
    osd:
      storeType:
        bluestore: 9
  version:
    image: quay.io/ceph/ceph:v17.2.7-20231027
    version: 17.2.7-0
```

* Pods:

```
╭─    ~ ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  at kubernetes-admin@kubernetes ⎈  at 18:35:39  ─╮
╰─ kubectl -n rook-ceph get pods                                                                                                                                                                                 ─╯
NAME                                                            READY   STATUS                  RESTARTS      AGE
csi-cephfsplugin-4p9ng                                          2/2     Running                 0             7h27m
csi-cephfsplugin-6rhrn                                          2/2     Running                 0             7h27m
csi-cephfsplugin-778nq                                          2/2     Running                 0             7h27m
csi-cephfsplugin-8bgbd                                          2/2     Running                 0             7h27m
csi-cephfsplugin-f89th                                          2/2     Running                 0             7h27m
csi-cephfsplugin-jv45x                                          2/2     Running                 0             7h27m
csi-cephfsplugin-kw68l                                          2/2     Running                 0             7h27m
csi-cephfsplugin-provisioner-74d7b764fd-h84ww                   5/5     Running                 0             7h27m
csi-cephfsplugin-provisioner-74d7b764fd-k4fhm                   5/5     Running                 0             7h27m
csi-cephfsplugin-rj5wt                                          2/2     Running                 0             7h27m
csi-rbdplugin-7xbwh                                             2/2     Running                 0             7h27m
csi-rbdplugin-jkdwv                                             2/2     Running                 0             7h27m
csi-rbdplugin-lsr4v                                             2/2     Running                 0             7h27m
csi-rbdplugin-lxf7d                                             2/2     Running                 0             7h27m
csi-rbdplugin-n2njh                                             2/2     Running                 0             7h27m
csi-rbdplugin-provisioner-bd9496c4c-cr92g                       5/5     Running                 0             7h27m
csi-rbdplugin-provisioner-bd9496c4c-kgzcd                       5/5     Running                 0             7h27m
csi-rbdplugin-tzjrv                                             2/2     Running                 0             7h27m
csi-rbdplugin-w4bm4                                             2/2     Running                 0             7h27m
csi-rbdplugin-xxsv5                                             2/2     Running                 0             7h27m
rook-ceph-crashcollector-k8s-storage-node151-7874f465b5-7pbdq   1/1     Running                 0             3m51s
rook-ceph-crashcollector-k8s-storage-node152-6cdb798bb4-2kj42   0/1     Pending                 0             5m25s
rook-ceph-crashcollector-k8s-storage-node153-796c7cf66f-nknzn   1/1     Running                 0             5m23s
rook-ceph-mds-ceph-filesystem-a-5889dccf7-tsqh2                 2/2     Running                 0             8m38s
rook-ceph-mds-ceph-filesystem-b-5645fc8dc5-g8lkd                2/2     Running                 0             5m28s
rook-ceph-mgr-a-845b8f54b4-mqqxf                                3/3     Running                 0             13m
rook-ceph-mgr-b-5dbb64d6d5-qwv4v                                3/3     Running                 0             12m
rook-ceph-mon-a-76459f94c8-sm7jh                                2/2     Running                 0             15m
rook-ceph-mon-b-8467684b98-qx5kj                                2/2     Running                 0             17m
rook-ceph-mon-c-685747fc48-vctq2                                2/2     Running                 0             16m
rook-ceph-operator-7dcbcc966b-dcll9                             1/1     Running                 0             8m35s
rook-ceph-osd-0-d7bdb7874-xml4g                                 0/2     Init:CrashLoopBackOff   5 (59s ago)   3m56s
rook-ceph-osd-1-747bcc9f6d-56tjh                                2/2     Running                 0             7h25m
rook-ceph-osd-2-65d74b486c-x2gc2                                2/2     Running                 0             7h25m
rook-ceph-osd-3-9b5fc6477-xt6b7                                 0/2     Init:CrashLoopBackOff   5 (46s ago)   3m53s
rook-ceph-osd-4-f9cddfb8c-qg4gt                                 2/2     Running                 0             7h25m
rook-ceph-osd-5-dc9c87c87-snj2k                                 2/2     Running                 0             7h25m
rook-ceph-osd-6-6f7554f964-6xk4t                                0/2     Init:CrashLoopBackOff   5 (60s ago)   3m51s
rook-ceph-osd-7-5b6c45585c-74tfp                                2/2     Running                 0             7h25m
rook-ceph-osd-8-5bd7c96659-8r6m5                                2/2     Running                 0             7h25m
rook-ceph-osd-prepare-k8s-storage-node151-z4knb                 0/1     Completed               0             5m29s
rook-ceph-osd-prepare-k8s-storage-node152-kq8dw                 0/1     Completed               0             5m29s
rook-ceph-osd-prepare-k8s-storage-node153-djh6r                 0/1     Completed               0             5m28s
rook-ceph-rgw-ceph-objectstore-a-844bfbb5d7-hv9nf               2/2     Running                 0             10m
rook-ceph-tools-5cf9976f76-n6c5l                                1/1     Running                 0             17m
rook-discover-75t4x                                             1/1     Running                 0             18m
rook-discover-f8x5m                                             1/1     Running                 0             18m
rook-discover-mgl9x                                             1/1     Running                 0             18m
```

* Failing OSD Logs
```
╭─    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 1 ✘  at kubernetes-admin@kubernetes ⎈  at 18:37:18  ─╮
╰─ kubectl -n rook-ceph logs rook-ceph-osd-0-d7bdb7874-xml4g --all-containers                                                                                                                                    ─╯

+ OSD_ID=0
+ CEPH_FSID=dda6c867-4047-4fb9-a744-1575da352c5d
+ OSD_UUID=447c4553-d301-457a-b48d-69c1a6afe74a
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
+ CV_MODE=raw
+ DEVICE=/dev/mapper/vg_rook-lv_rook3
+ cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
+ python3 -c '
import configparser

config = configparser.ConfigParser()
config.read('\''/etc/ceph/ceph.conf'\'')

if not config.has_section('\''global'\''):
    config['\''global'\''] = {}

if not config.has_option('\''global'\'','\''fsid'\''):
    config['\''global'\'']['\''fsid'\''] = '\''dda6c867-4047-4fb9-a744-1575da352c5d'\''

with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
    config.write(configfile)
'
+ ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.0]
	key = AQBCJEJlDLPvGxAAfuSxVKFq6S/sR/EzuGvbcg==
+ [[ raw == \l\v\m ]]
++ mktemp
+ OSD_LIST=/tmp/tmp.nFvPJSRqNw
+ ceph-volume raw list /dev/mapper/vg_rook-lv_rook3
+ cat /tmp/tmp.nFvPJSRqNw
{}
+ find_device
+ python3 -c '
import sys, json
for _, info in json.load(sys.stdin).items():
	if info['\''osd_id'\''] == 0:
		print(info['\''device'\''], end='\'''\'')
		print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
		sys.exit(0)  # don'\''t keep processing once the disk is found
sys.exit('\''no disk found with OSD ID 0'\'')
'
no disk found with OSD ID 0
+ ceph-volume raw list
+ cat /tmp/tmp.nFvPJSRqNw
{}
++ find_device
++ python3 -c '
import sys, json
for _, info in json.load(sys.stdin).items():
	if info['\''osd_id'\''] == 0:
		print(info['\''device'\''], end='\'''\'')
		print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
		sys.exit(0)  # don'\''t keep processing once the disk is found
sys.exit('\''no disk found with OSD ID 0'\'')
'
no disk found with OSD ID 0
+ DEVICE=
Error from server (BadRequest): container "expand-bluefs" in pod "rook-ceph-osd-0-d7bdb7874-xml4g" is waiting to start: PodInitializing
```

* Operator logs:
In attachment

**Comment by Dennisovan92** [comment] 2023-11-01 18:08
[operator.log](https://github.com/rook/rook/files/13230392/operator.log)

**Comment by sp98** [comment] 2023-11-06 04:39
@Dennisovan92 closing it as a duplicate of #13136

**Comment by mdbooth** [comment] 2023-11-07 22:05
This is different to #13136, and may be a separate bug. #13136 is a crash in ceph-volume. This isn't touching ceph-volume. This is python embedded in the initContainer by rook.

/reopen

**Comment by mdbooth** [comment] 2023-11-08 13:13
@sp98 See above. This is a different issue. You probably want to reopen this.

**Comment by mdbooth** [comment] 2023-11-08 16:08
My bad! #13136 describes 2 different crashes, and this is the second one. I was only looking at the first. I think the fix for this is in progress in https://github.com/ceph/ceph/pull/54392.

**Comment by sp98** [comment] 2023-11-09 04:09
@mdbooth Lets use #13136 to track this c-v issue. I'll close this one.

**Closed by sp98** 2023-11-09 04:09 UTC
Labels: bug
