### ISSUE TITLE
Rook partitions disappearing

### ISSUE THREAD

**Issue by benceszikora** [rook/rook#1797] opened 2018-06-18 13:57 UTC
**Bug Report**

What happened: The WAL and the DB partitions have disappeared from the disks used by rook:
```
(parted) p                                                                
Model: ATA ST8000NM0055-1RM (scsi)
Disk /dev/sde: 8002GB
Sector size (logical/physical): 512B/4096B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name              Flags
 1      1049kB  8002GB  8002GB               ROOK-OSD22-BLOCK
```
This has happened to *all* disks on one of my OSD nodes (let's called it node A), and I can see the same thing on some of the disks on another one (if the number of these increases I'll report back).

When the OSD pods are restarted, all the OSDs show up as `up` for a while, and then they get marked as down.

On node B, when I have a bunch of OSDs marked as down it's a lot more than just the ones missing these partitions. These seem to be marked down because of errors like this:
```
2018-06-18 13:47:55.462024 I | osd41: 2018-06-18 13:47:55.461895 7fffef198700 -1 osd.41 55903 heartbeat_check: no reply from 7.129.19.2:6963 osd.52 ever on either front or back, first ping sent 2018-06-18 13:47:32.056846 (cutoff 2018-06-18 13:47:35.461750)                                      
```
I am not sure if these two issues are related.

What you expected to happen: The partitions persists and the OSDs work correctly.

How to reproduce it (minimal and precise):
This test cluster is running `v0.7.1-4.g4233e03` on 2 nodes with 41 x 7.3TB disks in each. Not sure what exactly triggers this behavior.

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.3
* Kernel (e.g. `uname -a`): 3.10.0-514.6.1.el7.x86_64
* Cloud provider or hardware configuration: Dell DSS7500
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`): v0.7.1-4.g4233e03
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare-metal based on open-source
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
HEALTH_WARN 36 osds down; 1/15108714 objects misplaced (0.000%); Reduced data availability: 4568 pgs inactive, 2671 pgs down, 1896 pgs peering, 1691 pgs stale; Degraded data redundancy: 56 pgs undersized; 12 slow requests are blocked > 32 sec
```

**Comment by benceszikora** [comment] 2018-06-21 15:35
This has just happened again on a completely clean setup (same version). All of the OSDs only have the BLOCK partition left. Weirdly they still show as up, but we are starting to see inconsistent PG errors with `read_errors`.
I see a bunch of these messages earlier, but not much else:
```
bluefs _allocate failed to allocate 0x400000 on bdev 0, free 0xff000; fallback to bdev 1
```

**Comment by bsqrd** [comment] 2018-06-21 19:06
We discovered that the WAL and DB partitions for the OSDs were apparently migrated from the original OSD SCSI block devices over to a NVMe device that we specified for metadata in our cluster definition:

`
    "storage": {
      "deviceFilter": "^((sd[e-z])|(sda[a-s]))",
      "metadataDevice": "nvme0n1",
      "storeConfig": {
        "storeType": "bluestore"
      },
` 

Here is the partitions that were "missing" that now exist on the NVMe device:
`
Model: NVMe Device (nvme)
Disk /dev/nvme0n1: 2000GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End     Size    File system  Name            Flags
 1      1049kB  605MB   604MB                ROOK-OSD0-WAL
 2      605MB   22.1GB  21.5GB               ROOK-OSD0-DB
 3      22.1GB  22.7GB  604MB                ROOK-OSD1-WAL
 4      22.7GB  44.2GB  21.5GB               ROOK-OSD1-DB
 5      44.2GB  44.8GB  604MB                ROOK-OSD2-WAL
 6      44.8GB  66.2GB  21.5GB               ROOK-OSD2-DB
 7      66.2GB  66.8GB  604MB                ROOK-OSD3-WAL
[snip]
81      883GB   884GB   604MB                ROOK-OSD40-WAL
82      884GB   905GB   21.5GB               ROOK-OSD40-DB

`

We do not understand what would change the OSDs to use partitions on the NVMe after the OSD was already created.

But we started configuring the pools and RGW quickly after the initial deployment was made.  Perhaps we needed to wait for the operator to fully complete the deployment, which is what I expect would perform the changes to the OSD metadata configuration??

We also expect that the data was not migrated between the devices when the OSD metadata was moved to the NVMe.  Ceph as we understand it does not have a any tools for moving data between devices directly (I think some on the ceph-users list have done scary things like `dd` the data from one device to another!!). It relies upon removing a OSD and having Ceph recreate the data on existing OSDs.  Once removed the OSD can be recreated with the new metadata partitions on the separate device (NVMe in our case) on a different device and add it back into the cluster.

Thanks for all help here!
-Bryan

**Comment by galexrt** [comment] 2018-06-28 10:12
@travisn @jbw976 I have added this to 0.8 project/milestone, so we make sure this does not happen with `master`/0.8.

**Comment by travisn** [comment] 2018-07-11 16:45
@bsqrd are you saying your WAL and DB partitions moved from the original OSD to the nvme? Did your CRD change or was it always specified like this? 
```
 "metadataDevice": "nvme0n1",
```
It is expected that the operator would create the partitions as you see here, though it is not expected that they would change after initial creation. Rook certainly wouldn't do anything to migrate the data with a change of configuration like that either. I suspect the OSDs were originally created this way since they start at ID 0. If the OSDs would have changed, Rook likely would have created a new ID.

**Comment by bsqrd** [comment] 2018-07-11 22:59
Yes, the order of operations is unclear for us.  But I believe @benceszikora does believe the initial configuration was correct with the following directive:
```
 "metadataDevice": "nvme0n1",
```
And then subsequently the partitions were moved/lost.

**Comment by benceszikora** [comment] 2018-07-16 14:54
@travisn @bsqrd In the initial configuration we definitely had the nvme set already.

I am not 100% sure that on this specific occasion all of these were created as partitions first, they might have correctly been created on the nvme first. However I have seen the cluster with the same errors before, where I do remember that most of the partitions were on the block devices, but a few had them missing and they appeared on the nvme. We definitely did not change the `metadataDevice` after setting up the cluster on either occasion.

Unfortunately I have not been able to repoduce this since then though.

**Comment by travisn** [comment] 2018-07-17 18:17
@benceszikora i have not been able to repro this issue when specifying a `metadataDevice` in the candidate v0.8 build (latest master). After restarting the operator I also confirmed that the metadata devices was detected as in-use and the same osd pods and partitions remained running. How about if I close this issue for now? Please re-open if you can get a repro.

**Closed by travisn** 2018-07-17 18:17 UTC
Labels: ceph
