### ISSUE TITLE
[Multus] improve csi holder design

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#13055] opened 2023-10-18 06:41 UTC
**Is this a bug report or feature request?**
* Feature Request

Currently, the holder pod is having two problems

* Need to be updated manually when the cephcsi image is updated in Rook

This is because we are using the cephcsi as the container image for the holder daemonset. In most of the large clusters, this is a big problem as they need to follow certain steps like (cordon, drain, and node reboot) which takes so much of time. 

The above pain can be reduced by switching to the kubernetes pause container image which is bare minimal and requires an update when there is an update/upgrade in the kubernetes cluster. In most of cases the kubernetes upgrade will have a process of cordon and drain internally as they need to update the node components, We need to find a mechanism to find the right pause container image used by the kubernetes and use that in the holder pod daemonset.

* Avoid accidental deletion of the Holder pod.

Avoid deletion of the Holder pod is not something we are currently doing today, If the holder pod is deleted we will lose all the application mounts and all the mounts need to be remounted by following the same set of procedures like e(cordon, drain, and the node reboot) Again this is also not an easy and best solution. We should avoid accidental deletion of the holder pod. I was thinking about adding a finalizer to the pod thinking it can avoid it. Sadly it can avoid the pod deletion but the container in the pods gets terminated. Thinking more about leads to the idea of using the Webhooks to avoid the deletion of holder pods
. If we add a webhook we can avoid this case as well.

Thanks to @BlaineEXE for all the discussions/suggestions we had in this area. @travisn let me know what you think about it.

**Comment by Madhu-1** [comment] 2023-10-18 07:36
Adding the link provided by @BlaineEXE  https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#optional-parameters which might help for webhook

**Comment by BlaineEXE** [comment] 2023-10-18 15:21
I think the initial idea was that the holder pod should be happy to keep running at whatever version of it is currently running without need for change regardless of Rook, Ceph, CSI, or Kubernetes version upgrades. That was/is actually a beneficial feature, and that feature is critical for providing user apps with storage I/O through upgrades and without requiring advanced upgrade needs like rebooting nodes.

I think the biggest impact of using the cephcsi image for the holder is that if centos, ceph, or cephcsi images have CVEs, users will likely want to update those to be safe. However, if we use an extremely stable image that uses `FROM scratch` (like the pause container), the pods are unlikely to require updating.

I think the biggest side effect of the design (which we are more or less forced to implement because of how the ceph kernel clients operate) is that the behavior is unexpected. Users generally expect to see all the images updated when apps are updated. The behavior we use for the holders breaks that default assumption. However, I think that using a different image entirely for these pods will make it less likely that users will notice and suspect a problem.

**Comment by BlaineEXE** [comment] 2023-10-18 15:58
Another thing we might consider to try to combat the issues with users being confused by the version not changing: remove the `rook-version` label from the holder daemonset

**Comment by travisn** [comment] 2023-10-18 18:26
> Need to be updated manually when the cephcsi image is updated in Rook

Since the daemonset spec is updated with a new image, but the policy isn't to update the pods until the node is restarted, I thought we were ok with the current behavior, and I understand this is also what Blaine described.

> Avoid accidental deletion of the Holder pod.

Do we have cases where the holder pod was disabled accidentally? What was the cause? We need to really understand why this happens. If it's just because an admin went rogue, we don't need to support that or other similar corner cases. 

Webhooks are very challenging and will introduce a lot of complexity. We struggled with this for a long time in the admission controller and finally decided it wasn't worth the headache and disabled it.

**Comment by Madhu-1** [comment] 2023-10-19 09:07
> > Need to be updated manually when the cephcsi image is updated in Rook
> 
> Since the daemonset spec is updated with a new image, but the policy isn't to update the pods until the node is restarted, I thought we were ok with the current behavior, and I understand this is also what Blaine described.
> 
> > Avoid accidental deletion of the Holder pod.
> 
> Do we have cases where the holder pod was disabled accidentally? What was the cause? We need to really understand why this happens. If it's just because an admin went rogue, we don't need to support that or other similar corner cases.
> 

There could be many reasons, kubernetes deleting the pod or users  deleting the holder pod etc. because we don't have control to block anyone from deleting holder pods.

> Webhooks are very challenging and will introduce a lot of complexity. We struggled with this for a long time in the admission controller and finally decided it wasn't worth the headache and disabled it.

i think we just need to create the `ValidatingAdmissionPolicy` and `ValidatingAdmissionPolicyBinding` with required details and this will take care of the problem (i could be wrong haven't tested it though)

**Comment by travisn** [comment] 2023-10-19 16:47
> > Webhooks are very challenging and will introduce a lot of complexity. We struggled with this for a long time in the admission controller and finally decided it wasn't worth the headache and disabled it.
> 
> i think we just need to create the `ValidatingAdmissionPolicy` and `ValidatingAdmissionPolicyBinding` with required details and this will take care of the problem (i could be wrong haven't tested it though)

Certificates were a big challege as well. @subhamkrai thoughts?

**Comment by subhamkrai** [comment] 2023-10-20 07:38
> > > Webhooks are very challenging and will introduce a lot of complexity. We struggled with this for a long time in the admission controller and finally decided it wasn't worth the headache and disabled it.
> > 
> > 
> > i think we just need to create the `ValidatingAdmissionPolicy` and `ValidatingAdmissionPolicyBinding` with required details and this will take care of the problem (i could be wrong haven't tested it though)
> 
> Certificates were a big challege as well. @subhamkrai thoughts?

IIRC, when there was a need to update the certificates we were hit by RBAC issue and we failed to find the root issue

**Comment by subhamkrai** [comment] 2023-10-20 07:40
Here is the [pr](https://github.com/rook/rook/pull/11143) with the an issue mentioned where I was trying to fix the issue but moved it to another priority.

**Comment by subhamkrai** [comment] 2023-10-25 13:26
> > Validating admission policies offer a declarative, in-process alternative to validating admission webhooks.
> > Validating admission policies use the Common Expression Language (CEL) to declare the validation rules of a policy. Validation admission policies are highly configurable, enabling policy authors to define policies that can be parameterized and scoped to resources as needed by cluster administrators.
> 
> @travisn @subhamkrai [ValidatingAdmissionPolicy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#optional-parameters) is an alternative to admission webhook and uses CEL to customize the rules, AFAIK we don't need to worry about certificates here

Yes and I remember you have opened the issue in rook also

**Comment by simu** [comment] 2023-11-10 09:10
Hi,

I discovered this issue while trying to determine how the holder pods are supposed to be updated/recreated after a ceph-csi upgrade.

> > Need to be updated manually when the cephcsi image is updated in Rook
> 
> Since the daemonset spec is updated with a new image, but the policy isn't to update the pods until the node is restarted, I thought we were ok with the current behavior, and I understand this is also what Blaine described.

Currently, while testing the upgrade to Rook v1.12 and ceph-csi v3.9.0 we're seeing the following behavior of the holder pods: After a ceph-csi upgrade, the holder pods are running with the old ceph-csi image indefinitely (across node drains and node reboots), since the `OnDelete` update strategy for daemonsets only creates pods which match the new daemonset spec after an existing pod is explicitly deleted, cf. https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy. In particular, these pods aren't deleted and recreated when restarting nodes with drain&reboot, cf. https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#use-kubectl-drain-to-remove-a-node-from-service.

> But from a user, standpoint, I think the biggest side effect of the holder design (which we are more or less forced to implement because of how the ceph kernel clients operate) is that the behavior doesn't follow what most applications do when they upgrade. Users generally expect to see all the images updated when apps are updated. The behavior we use for the holders breaks that default assumption, and this is something that I have seen many many users report as confusing. I think that using a different image entirely for these pods will make it less likely that users will notice and suspect a problem.

Currently, the biggest impact for us is that the holder daemonsets are stuck with 0/x up-to-date pods after a ceph-csi upgrade, which causes the [`KubeDaemonSetRolloutStuck` alert](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/bcf8426b9c5ee85fdf8a6d9c62708f94e0367b21/alerts/apps_alerts.libsonnet#L174-L199) to fire for the holder daemonsets until someone manually deletes the holder pods to allow new pods matching the new daemonset spec to be created. Note that we can work around this, by excluding the holder daemonsets from that alert.

**Comment by BlaineEXE** [comment] 2023-11-10 16:18
Thanks for the detailed info, @simu ! This will really help us figure out how to best improve/document the experience.

**Comment by BlaineEXE** [comment] 2024-01-09 17:11
There would be a lot to convey here in detail, and I still want to have a deep discussion with Madhu who is on an extended PTO.

All other CSI drivers I’ve investigated use host networking and requirement that hosts be route-able to storage system -- versus Rook has opted to try out this holder pattern to eliminate the need to have hosts need to be route-able to the Ceph cluster.

Holder design has some maintenance drawbacks for devs.

Holder design has conceptual drawbacks for users. Repeatedly users have a hard time conceptualizing what the purpose is.

Holder design also has maintenance (upgrade) drawbacks for admins, and simu's post above was extremely helpful to help me see the extent of that in clarity.

I am considering that we should potentially abandon holder design in favor of pivoting to host-networking-and-host-is-routable methods/assumptions. This will still be quite challenging, but I think it will be valuable in the long-term to help with the pain points for devs and users in the long-term. 

As for how we will safely migrate existing Multus users away from the holder design, Madhu, Travis, Subham, and I will have to take some extended efforts to plan those very complicated details.

If you, as users, have inputs as to the long-term good or bad of such a decision, please let us know here.

**Comment by BlaineEXE** [comment] 2024-01-26 16:41
@Madhu-1, @travisn, @subhamkrai, and I have spent some time researching this and developing a plan to move forward. 

We believe we can target a user-facing workflow that looks something like this:
1. Admin initiates Rook upgrade
2. Admin configures host to route to multus public network
   - Rook will provide docs and examples for how to do this
3. Admin runs multus validation tool to verify ODF hosts can route to multus nets
   - only run host connectivity check so as not to disrupt cluster in production
4. During this upgrade, Rook automatically:
   a. Updates CSI drivers to use host network namespace
   b. Stops managing the holder DaemonSet, but leaves it running so existing PVCs don’t hang
5. Admin drains and un-drains each K8s node one-by-one to migrate PVCs to host ns
   - These steps will be added to upgrade docs
6. After all nodes are migrated, user deletes the holder DaemonSet
   - we will attempt to find a simple metric for admins to determine if it’s safe to delete the holder DS

Madhu was able to do an early test of how this will work here: https://hackmd.io/IyHqitcBQbmGxgZ3QmSfCg

This WIP change fixes the bug noted in that HackMD link: https://github.com/rook/rook/pull/13613

Tasks to be completed:
- [ ] **[Planned: @subhamkrai & @Madhu-1]** Rook should switch CSI to hostNetwork deployment only after user intervention. For example, the user may set an operator config env var like `ROOK_CSI_DISABLE_HOLDER=true` to instruct Rook to stop deploying holder pods.
- [ ] **[Researching: @BlaineEXE]** Document base requirements for making hosts routable to multus public network. Hosts must be able to route to the multus public network may not be a clear enough requirement statement for users. We should be able to provide a clearer breakdown of what that means.
- [ ] **[Researching: @BlaineEXE]** Provide example for users to make hosts routable using a new DHCP server. (Not all admins may have the ability to spin up a new DHCP server on the multus public net.)
- [ ] If possible, also provide an example to make hosts routable using a new DHCP server. (A DHCP server may make the Kubernetes/Rook/Multus processes much simpler, and it is a step that will be familiar to many admins.)
- [ ] Make changes to the multus validation tool to check host-multus connectivity, and include its usage in docs and examples.

**Comment by travisn** [comment] 2024-03-27 21:18
@BlaineEXE Since #13890 was merged, shall we close this? Or anything else blocking for v1.14 related to this?

**Comment by BlaineEXE** [comment] 2024-03-28 22:21
There are still checklist items here to do, but I think we have completed things that would block the next release. https://github.com/rook/rook/issues/13055#issuecomment-1912358866

**Comment by BlaineEXE** [comment] 2024-05-28 20:45
Let's close this high-level issue and start tracking the 1 follow-on item that is most important: adding host<-->public-net compatibility checking to the multus validation test.

The PR is in the works here: https://github.com/rook/rook/pull/14230

**Closed by BlaineEXE** 2024-05-28 20:45 UTC
Labels: feature, wontfix, csi, multus
