### ISSUE TITLE
CephFS: Automatic resizing of PersistentVolumes with CSI 2.0 driver does not automatically adjust quota limit

### ISSUE THREAD

**Issue by sebschlue** [rook/rook#5092] opened 2020-03-26 12:01 UTC
**Is this a bug report or feature request?**
* Bug Report

Tags: ceph, csi

**Deviation from expected behavior:**

CephFS: Automatic resizing of PersistentVolumes with CSI 2.0 driver does not automatically adjust quota limit.

**Expected behavior:**
With CSI 2.0 driver, automatic resizing of PersistentVolumes should "just work".

**How to reproduce it (minimal and precise):**
Install a fresh Ceph cluster release 1.2. Here is the shortened script, I can provide the full script if necessary.

````
git clone --single-branch --branch release-1.2 https://github.com/rook/rook.git
cd rook/cluster/examples/kubernetes/ceph
kubectl apply -f common.yaml
kubectl apply -f operator.yaml
kubectl apply -f cluster.yaml
kubectl apply -f toolbox.yaml
kubectl apply -f filesystem.yaml
ceph osd pool set myfs-data0 pg_num 32
ceph osd pool set myfs-metadata pg_num 32
kubectl apply -f csi/cephfs/storageclass.yaml
````
Then create a PVC and example application (in my case this was Apache HTTPD as DaemonSet where the Pods share the htdocs dir. Here is the PVC, I can provide DaemonSet definition if necessary.

````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-httpd-htdocs-pvc
  namespace: httpd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs
````

This PVC and its PV now could not be enlarged, so I need to upgrade to CSI 2.0 driver:

Grab cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml from master branch and kubectl-apply it.

Update rook ceph operator image version: `kubectl -n rook-ceph set image deploy/rook-ceph-operator rook-ceph-operator=rook/ceph:v1.2.6`

Add the following deployment env variables to rook ceph operator deployment object:

```
env:
    - name: ROOK_CSI_CEPH_IMAGE
        value: "quay.io/cephcsi/cephcsi:v2.0.0"
    - name: ROOK_CSI_REGISTRAR_IMAGE
        value: "quay.io/k8scsi/csi-node-driver-registrar:v1.2.0"
    - name: ROOK_CSI_PROVISIONER_IMAGE
        value: "quay.io/k8scsi/csi-provisioner:v1.4.0"
    - name: ROOK_CSI_SNAPSHOTTER_IMAGE
        value: "quay.io/k8scsi/csi-snapshotter:v1.2.2"
    - name: ROOK_CSI_ATTACHER_IMAGE
        value: "quay.io/k8scsi/csi-attacher:v2.1.0"
    - name: ROOK_CSI_RESIZER_IMAGE
        value: "quay.io/k8scsi/csi-resizer:v0.4.0"
```

I have done this by running `kubectl -n rook-ceph edit deployment rook-ceph-operator` and then editing the yaml.

Then, after all Pods have been restarted, I try to enlarge volume:

First of all, I verify that there is an actual limit by writing a 10GB file (which works) and then writing an additional 1GB file, which does not work, I get "Disk quota exceeded" message. For far, so good.

Before enlargement:

`````
persistentvolume/pvc-1402087d-ef7f-4cbb-855a-4aa08546df31        10Gi       RWX            Delete           Bound    httpd/cephfs-httpd-htdocs-pvc                      csi-cephfs                                       3d22h

persistentvolumeclaim/cephfs-httpd-htdocs-pvc   Bound    pvc-1402087d-ef7f-4cbb-855a-4aa08546df31   10Gi       RWX            csi-cephfs     3d22h
`````

df from inside of Pod:

````
10.43.182.84:6789,10.43.220.98:6789,10.43.46.213:6789:/volumes/csi/csi-vol-a490c790-6acd-11ea-bcfc-b24e4d64b58c/b0d0b73d-0d97-4322-9954-3db10dd40e2d ceph      10G     0   10G   0% /usr/local/apache2/htdocs
````

New enlarge by editing PVC: `kubectl -n httpd edit pvc cephfs-httpd-htdocs-pvc`

At first glance, it seems to work:

````
persistentvolume/pvc-1402087d-ef7f-4cbb-855a-4aa08546df31        20Gi       RWX            Delete           Bound    httpd/cephfs-httpd-htdocs-pvc                      csi-cephfs                                       3d23h

persistentvolumeclaim/cephfs-httpd-htdocs-pvc   Bound    pvc-1402087d-ef7f-4cbb-855a-4aa08546df31   20Gi       RWX            csi-cephfs     3d23h
`````
But quota limit is still in place: I still get "Disk quota exceeded" message and df still shows size of 10GB instead of 20GB.

Restarting the Pods does not help.

````
$ kubectl -n httpd describe pvc cephfs-httpd-htdocs-pvc
Name:          cephfs-httpd-htdocs-pvc
Namespace:     httpd
StorageClass:  csi-cephfs
Status:        Bound
Volume:        pvc-1402087d-ef7f-4cbb-855a-4aa08546df31
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"cephfs-httpd-htdocs-pvc","namespace":"httpd"},"spec...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      20Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    httpd-9f9vm
               httpd-fjjhg
               httpd-nqkjr
               httpd-q2nw7
               httpd-tbhfd
               httpd-xltv4
Events:
  Type     Reason                  Age    From                                            Message
  ----     ------                  ----   ----                                            -------
  Normal   Resizing                6m31s  external-resizer rook-ceph.cephfs.csi.ceph.com  External resizer is resizing volume pvc-1402087d-ef7f-4cbb-855a-4aa08546df31
  Warning  ExternalExpanding       6m31s  volume_expand                                   Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   VolumeResizeSuccessful  6m29s  external-resizer rook-ceph.cephfs.csi.ceph.com  Resize volume succeeded
````

I have already figured out that I need to run the following command:

````
ceph fs subvolume resize myfs csi-vol-a490c790-6acd-11ea-bcfc-b24e4d64b58c 21474836480 csi
````

But this should be done automatically.

**File(s) to submit**:

No files to submit, all infomation included inline in "How to reproduce" paragraph.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7

* Kernel (e.g. `uname -a`): Linux node1.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.2.6
go: go1.11

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)

* Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

k3s

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

HEALTH_OK

**Comment by RandyLevensalor** [comment] 2020-05-04 22:00
I'm seeing this with Rook 1.3 and Kubernetes 1.19 as well.  

rook version
rook: v1.3.2
go: go1.13.8

The only line that I see in the rook-ceph-mgr-a log file is:
```
debug 2020-05-04 21:52:03.403 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.516347 -' entity='client.csi-cephfs-provisioner' cmd=[{"prefix": "fs subvolume create", "vol_name": "myfs-ec", "sub_name": "csi-vol-18bd4200-8e4e-11ea-9533-becb7b57ab08", "size": 215822106624, "group_name": "csi", "mode": "777", "target": ["mon-mgr", ""]}]: dispatch
```

It looks like it is trying to re-create the existing subvolume and isn't issuing the resize command.

I updated this by changing the size PVC and running `kubectl apply -f my-pvc.yaml`

Thanks @sebschlue for posting the workaround.  It resolved the issue.

**Comment by Madhu-1** [comment] 2020-05-05 02:10
The user should not resize the subvolume manually, can you please provide below output
* Kubectl get pvc -o yaml
* Logs from the csi-cephfsplugin container of provisioner pod
* Log from the csi-cephfsplugin container from the csi-cephfs daemonset pod from the node where app pod is scheduled

**Comment by Madhu-1** [comment] 2020-05-05 09:16
@joscollin PTAL

**Comment by joscollin** [comment] 2020-05-05 11:01
@Madhu-1 
We need to figure out which mounting method is used by csi. If it is kernel client, you need a version >= 4.17 and a mimic+ cluster to avail CephFS quota. `fs subvolume resize` command is only available from nautilus 14.2.8 or higher. However, the quota resize is possible by reissuing `fs subvolume create` command in versions older than nautilus 14.2.8.

We need to check:
1. Kernel client version
2. Ceph version

**Comment by Madhu-1** [comment] 2020-05-05 11:03
@joscollin details are provided in https://github.com/rook/rook/issues/5092#issue-588367977

**Comment by Madhu-1** [comment] 2020-05-05 11:04
rook uses cephfs kernel client by default irrespective of kernel version to avoid transport endpoint not connected issue due fuse client.

**Comment by joscollin** [comment] 2020-05-05 11:14
@Madhu-1 Then it is obvious. "3.10.0-1062.el7.x86_64" - that's the reason why it fails to automatically adjust quota limit. Use 4.17 or higher.

> I have already figured out that I need to run the following command:
> ceph fs subvolume resize myfs csi-vol-a490c790-6acd-11ea-bcfc-b24e4d64b58c 21474836480 csi
> But this should be done automatically.

I think the cluster is upgraded to nautilus 14.2.8 or higher. But somehow the kernel is older than 4.17.

**Comment by Madhu-1** [comment] 2020-05-05 11:18
@joscollin if you look at the issue carefully user is claiming that he is able to resize the subvolume with `ceph fs subvolume resize` command and he is seeing expected size in app pod. in cephcsi we are using `ceph fs subvolume create` command to resize the PVC why it's not working as expected here? any idea

**Comment by joscollin** [comment] 2020-05-05 12:28
@Madhu-1 As I mentioned earlier, Use kernel 4.17 or higher for quota to work properly in all situations. Additionally, use nautilus 14.2.8 or higher for the `fs subvolume resize` command availability.

Below are the basic requirements for quota to work properly:

`Quotas are implemented in the kernel client 4.17 and higher. Quotas are supported by the userspace client (libcephfs, ceph-fuse). Linux kernel clients >= 4.17 support CephFS quotas but only on mimic+ clusters. Kernel clients (even recent versions) will fail to handle quotas on older clusters, even if they may be able to set the quotas extended attributes.`

All the functionalities of CephFS quota won't work if one of these requirements are met. In some cases (older clusters), the user might be able to set the quota, but it doesn't mean that the quota feature is fully functional in that cluster.

**Comment by RandyLevensalor** [comment] 2020-05-05 16:25
I'm running the 5.3 HWE kernel on Ubuntu 18.04.

I can reproduce this later today and capture the log files.

```
uname -a
Linux node1 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by RandyLevensalor** [comment] 2020-05-05 17:32
@Madhu-1 The cephfs-csi plugin log files don't output anything when I increase the pvc size.

It looks like the manager is trying to create the existing subvolume and the resize operation is not being initiated.  This really looks like a rook-ceph orchestration issue and not a lower level ceph or kernel issue.

Here is the log from mgr-a.

```bash
kubectl -n rook-ceph logs rook-ceph-mgr-a-d9cd47f56-9mt9z  | grep csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08
debug 2020-05-05 16:55:39.887 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.533531 -' entity='client.csi-cephfs-provisioner' cmd=[{"prefix": "fs subvolume create", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "size": 1073741824, "group_name": "csi", "mode": "777", "pool_layout": "myfs-ec-data0", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-05-05 16:55:56.807 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.534690 -' entity='client.csi-cephfs-node' cmd=[{"prefix": "fs subvolume getpath", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "group_name": "csi", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-05-05 16:57:37.563 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.534789 -' entity='client.csi-cephfs-node' cmd=[{"prefix": "fs subvolume getpath", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "group_name": "csi", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-05-05 16:59:50.812 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.534906 -' entity='client.csi-cephfs-node' cmd=[{"prefix": "fs subvolume getpath", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "group_name": "csi", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-05-05 17:08:34.442 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.533834 -' entity='client.csi-cephfs-provisioner' cmd=[{"prefix": "fs subvolume getpath", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "group_name": "csi", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-05-05 17:08:35.174 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.533849 -' entity='client.csi-cephfs-provisioner' cmd=[{"prefix": "fs subvolume create", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "size": 2147483648, "group_name": "csi", "mode": "777", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-05-05 17:09:58.631 7f1411f21700  0 log_channel(audit) log [DBG] : from='client.535224 -' entity='client.csi-cephfs-node' cmd=[{"prefix": "fs subvolume getpath", "vol_name": "myfs-ec", "sub_name": "csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08", "group_name": "csi", "target": ["mon-mgr", ""]}]: dispatch
```

Please let me know if there are any other log files that you would like to see.

The logs from the cephfs on the node and the cephfs provisioner logs.

```bash
rlevensalor@gateway:~/notes/home/media/nzbget$ kubectl -n rook-ceph logs csi-cephfsplugin-provisioner-95ccff866-98zmq csi-cephfsplugin
W0504 03:15:50.006460       1 driver.go:164] EnableGRPCMetrics is deprecated
rlevensalor@gateway:~/notes/home/media/nzbget$ kubectl -n rook-ceph logs csi-cephfsplugin-provisioner-95ccff866-2phfl csi-cephfsplugin
W0430 00:24:13.136593       1 driver.go:164] EnableGRPCMetrics is deprecated
rlevensalor@gateway:~/notes/home/media/nzbget$ kubectl -n rook-ceph logs csi-cephfsplugin-s6vrk csi-cephfsplugin
W0504 03:15:53.785371       1 cephcsi.go:180] mountcachedir option is deprecated
W0504 03:15:53.859923       1 driver.go:164] EnableGRPCMetrics is deprecated
```

After increasing the size of the pvc and restarting the pod, the volume still shows 1GB and not the new size of 2GB.

```bash
Filesystem                Size      Used Available Use% Mounted on
<snip>
192.168.0.193:6789,192.168.0.191:6789,192.168.0.192:6789:/volumes/csi/csi-vol-3f6379d9-8ef1-11ea-9533-becb7b57ab08/27855850-5894-4aa9-be73-1a658df38346
                          1.0G         0      1.0G   0% /test-pvc
<snip>
```

I've attached the pod file and yaml that I used to create and grow the volumes.  The origional-pvc.yaml is the pvc output after it is created.  larger-pvc.yaml is the output after the pvc has been increased in size.


[Archive.zip](https://github.com/rook/rook/files/4582549/Archive.zip)

**Comment by joscollin** [comment] 2020-05-06 01:32
> I'm running the 5.3 HWE kernel on Ubuntu 18.04.
> 

Please explain how this magically happened now. You started this issue by claiming a different OS/Kernel [here](https://github.com/rook/rook/issues/5092#issue-588367977).

Show us the output of:
$ ceph versions

**Comment by RandyLevensalor** [comment] 2020-05-06 01:45
@joscollin 
Apologies for the confusion around kernel versions.  I didn't open this issue.  I was seeing the exact same behavior and thought that it was probably the same issue.  The workaround that was posted in the initial issue worked like a charm.

The manager issuing a create call instead of a resize call seems like an issue with the manager or higher-level call in the stack within rook-ceph and doesn't appear to be an issue with ceph or the kernel.

I'm not very familiar with the code and could be totally off base.

``
[root@rook-ceph-tools-59c5486bc5-6jcq9 /]# ceph versions
{
    "mon": {
        "ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)": 3
    },
    "mgr": {
        "ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)": 1
    },
    "osd": {
        "ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)": 8
    },
    "mds": {},
    "overall": {
        "ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)": 12
    }
}
```

**Comment by joscollin** [comment] 2020-05-06 02:57
@RandyLevensalor 
You have all the prerequisites met from the back-end Ceph:
1. Kernel Version >= 4.17 (You have 5.3)
2. Ceph Version is mimic+ (You have Nautilus 14.2.9)
3. `fs subvolume resize` command is available since [Nautilus 14.2.8](https://docs.ceph.com/docs/master/releases/nautilus/#v14-2-8-nautilus). (You have Nautilus 14.2.9).

This clarifies why the `resize` command worked on your cluster. As you said in your previous comment, this should be an orchestration issue.

**Comment by Madhu-1** [comment] 2020-05-06 13:58
this is will fixed in https://github.com/ceph/ceph-csi/pull/1018 and will be available in next cephcsi release

**Comment by RandyLevensalor** [comment] 2020-05-06 17:01
@Madhu-1 @joscollin Thanks for your help debugging and fixing this issue!

**Comment by Madhu-1** [comment] 2020-06-23 15:09
This is fixed now,closing

**Closed by Madhu-1** 2020-06-23 15:09 UTC
Labels: bug, csi
