### ISSUE TITLE
serviceaccount "rook-ceph-cluster" not found

### ISSUE THREAD

**Issue by liuruibin** [rook/rook#2329] opened 2018-12-04 10:13 UTC
`kubectl create -f cluster.yaml`
 
cloud not create `osd` pods

` kubectl describe jobs.batch -n rook-ceph rook-ceph-osd-prepare-xxx`
```
Name:           rook-ceph-osd-prepare-vm-16-6-ubuntu
Namespace:      rook-ceph
Selector:       controller-uid=5c3eca4d-f7ac-11e8-98a6-525400842c0a
Labels:         app=rook-ceph-osd-prepare
                rook_cluster=rook-ceph
Annotations:    <none>
Parallelism:    1
Completions:    1
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=rook-ceph-osd-prepare
                    controller-uid=5c3eca4d-f7ac-11e8-98a6-525400842c0a
                    job-name=rook-ceph-osd-prepare-vm-16-6-ubuntu
                    rook_cluster=rook-ceph
  Service Account:  rook-ceph-cluster
  Containers:
   copy-bins:
    Image:      rook/ceph:master
    Port:       <none>
    Host Port:  <none>
    Args:
      ceph
      osd
      copybins
    Environment:
      ROOK_PATH:  /rook
    Mounts:
      /rook from rook-binaries (rw)
   provision:
    Image:      ceph/ceph:v13
    Port:       <none>
    Host Port:  <none>
    Command:
      /rook/tini
    Args:
      --
      /rook/rook
      ceph
      osd
      provision
    Environment:
      ROOK_NODE_NAME:             vm-16-6-ubuntu
      ROOK_CLUSTER_ID:            3f729e07-f7ac-11e8-98a6-525400842c0a
      ROOK_PRIVATE_IP:             (v1:status.podIP)
      ROOK_PUBLIC_IP:              (v1:status.podIP)
      ROOK_CLUSTER_NAME:          rook-ceph
      ROOK_MON_ENDPOINTS:         <set to the key 'data' of config map 'rook-ceph-mon-endpoints'>  Optional: false
      ROOK_MON_SECRET:            <set to the key 'mon-secret' in secret 'rook-ceph-mon'>          Optional: false
      ROOK_ADMIN_SECRET:          <set to the key 'admin-secret' in secret 'rook-ceph-mon'>        Optional: false
      ROOK_CONFIG_DIR:            /var/lib/rook
      ROOK_CEPH_CONFIG_OVERRIDE:  /etc/rook/config/override.conf
      ROOK_OSD_DATABASE_SIZE:     1024
      ROOK_OSD_JOURNAL_SIZE:      1024
      ROOK_DATA_DIRECTORIES:      /rook/storage-dir
    Mounts:
      /etc/ceph from ceph-default-config-dir (rw)
      /rook from rook-binaries (rw)
      /rook/storage-dir from rook-storage-dir (rw)
      /var/lib/rook from rook-data (rw)
  Volumes:
   rook-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook
    HostPathType:
   ceph-default-config-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
   rook-config-override:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rook-config-override
    Optional:  false
   rook-binaries:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
   rook-storage-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /rook/storage-dir
    HostPathType:
Events:
  Type     Reason        Age   From            Message
  ----     ------        ----  ----            -------
  Warning  FailedCreate  9s    job-controller  Error creating: pods "rook-ceph-osd-prepare-vm-16-6-ubuntu-" is forbidden: error looking up service account rook-ceph/rook-ceph-cluster: serviceaccount "rook-ceph-cluster" not found
```

**Comment by travisn** [comment] 2018-12-04 15:21
@liuruibin in master the `rook-ceph-cluster` serviceaccount no longer exists. It has been renamed to `rook-ceph-osd`. Can you check if you are using an operator.yaml and cluster.yaml that are from the same version of master?

**Comment by liuruibin** [comment] 2018-12-04 15:32
@travisn that was my script
```
kubectl apply -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/operator.yaml
kubectl apply -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml

```

**Comment by travisn** [comment] 2018-12-04 15:37
Something seems to have gone wrong during the deployment with inconsistent versions of the yamls. It is a new deployment? Or has this been running for some time? Can you try [cleaning up your cluster](https://rook.io/docs/rook/master/ceph-teardown.html) and deploy again?

**Comment by NickUfer** [comment] 2018-12-04 20:51
Same problem for me. Thought maybe the old cahed rook/ceph:master image uses somehow the old serviceaccount but then I realized, the latest version on docker hub is from 6 days ago, so before these group changes...maybe because of that

**Comment by travisn** [comment] 2018-12-04 20:58
Ah, the problem is that the master build has hit random failures for the last several days. We need to get a successful build out since the changes were merged on Saturday. I'll start the build again.

**Comment by travisn** [comment] 2018-12-04 22:57
@NickUfer @liuruibin we have a master build published now, please confirm that it is working for you now.

**Comment by NickUfer** [comment] 2018-12-05 07:12
Is working as expected now :+1:

**Comment by galexrt** [comment] 2019-03-04 23:18
Closing as the issue seems to be resolved.
Please comment if the issue still appears for you in the latest tagged release (`v0.9.3`).

**Closed by galexrt** 2019-03-04 23:18 UTC
