### ISSUE TITLE
mon crashing after reboot

### ISSUE THREAD

**Issue by abh** [rook/rook#1382] opened 2018-01-06 06:25 UTC
**Bug Report**

After rebooting two of our three rook-ceph-mon's are crashing, log attached.

[rook-ceph-mon.log](https://github.com/rook/rook/files/1608517/rook-ceph-mon.log)

Running rook/rook:v0.6.1 on Kubernetes v1.7.9+coreos.0 (tectonic).

**Comment by abh** [comment] 2018-01-06 07:44
My issue seems similar to #1354. Is it that the operator started new mons (with fresh databases) and if it did this to more than one at a time the data gets lost?  The servers have a bunch of  "rook-ceph-monX" directories (several updated around/after it stopped working)

**Comment by camflan** [comment] 2018-01-08 20:46
I had our rook/ceph cluster come down today after a node reboot. What I noticed, while in full panic mode, was that ceph-monN were all on the same node. I wonder if this caused an issue because the backing hostDir was being read from 3 ceph-mons. Not only were they all reading the same data, but there was N-1 other nodes data that wans't being read.

I remember seeing something in the logs about attempting to replay data followed by a core dump of the ceph-mon application binary.

**Comment by abh** [comment] 2018-01-15 03:22
I think part of what happened to me was that as tectonic was rebooting nodes two mons ended up on one host (and then later that node rebooted and boom). #1386

**Comment by galexrt** [comment] 2018-01-15 14:00
@abh The fix to not place more than one mon on one node, is being tracked by #1386 and #1387, the PR is available at #1406 but is still work in progress.

**Comment by evgeniwk** [comment] 2018-01-30 12:20
I have kube 1.9.3 with calico on 3 nodes. Rook cluster has `useAllNodes: true` and `monCount: 3`. Each mon placed on each node initially, but after node3 rebooted I got the same issue too:
```
rook            rook-ceph-mon0-xfnxr                           0/1       Error              17         1d
rook            rook-ceph-mon1-tdw2d                           1/1       Running            0          1d
rook            rook-ceph-mon2-vttjz                           0/1       CrashLoopBackOff   16         1d
rook            rook-ceph-mon3-7q4v6                           1/1       Running            0          57m
```
after restart I see that mon3 is started on node1 and look like it is not connected to any other mon, also it has:
```
2018-01-30 10:52:37.410056 I | rook-ceph-mon1: 2018-01-30 10:52:37.327150 mon.rook-ceph-mon0 mon.1 192.168.7.219:6790/0 7837 : cluster [INF] Standby daemon mds.mmppjh is not responding, dropping it
2018-01-30 10:52:37.410171 I | rook-ceph-mon1: 2018-01-30 10:52:37.327241 mon.rook-ceph-mon0 mon.1 192.168.7.219:6790/0 7838 : cluster [INF] Standby daemon mds.mcbqrw is not responding, dropping it
2018-01-30 10:52:37.410194 I | rook-ceph-mon1: 2018-01-30 10:52:37.327275 mon.rook-ceph-mon0 mon.1 192.168.7.219:6790/0 7839 : cluster [INF] Standby daemon mds.mzkwpt is not responding, dropping it
2018-01-30 10:52:37.410206 I | rook-ceph-mon1: 2018-01-30 10:52:37.327715 mon.rook-ceph-mon0 mon.1 192.168.7.219:6790/0 7840 : cluster [WRN] Health check failed: insufficient standby MDS daemons available (MDS_INSUFFICIEN
T_STANDBY)
```
my multiple fs includes:
```
  metadataPool:
    replicated:
      size: 2
```
both of failed pods have:
```
...
2018-01-30 11:58:00.527864 I | rook-ceph-mon2: 2018-01-30 11:58:00.527797 7f815a50ef40  4 rocksdb: [/build/ceph/src/rocksdb/db/version_set.cc:2859] Recovered from manifest file:/var/lib/rook/rook-ceph-mon2/data/store.db/MANIFEST-002388 succeeded,manifest_file_number is 2388, next_file_number is 2394, last_sequence is 886958, log_number is 0,prev_log_number is 0,max_column_family is 0
2018-01-30 11:58:00.527874 I | rook-ceph-mon2: 
2018-01-30 11:58:00.527877 I | rook-ceph-mon2: 2018-01-30 11:58:00.527812 7f815a50ef40  4 rocksdb: [/build/ceph/src/rocksdb/db/version_set.cc:2867] Column family [default] (ID 0), log number is 2387
2018-01-30 11:58:00.527880 I | rook-ceph-mon2: 
2018-01-30 11:58:00.527929 I | rook-ceph-mon2: 2018-01-30 11:58:00.527870 7f815a50ef40  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1517313480527866, "job": 1, "event": "recovery_started", "log_files": [2389]}
2018-01-30 11:58:00.527939 I | rook-ceph-mon2: 2018-01-30 11:58:00.527906 7f815a50ef40  4 rocksdb: [/build/ceph/src/rocksdb/db/db_impl_open.cc:482] Recovering log #2389 mode 2
2018-01-30 11:58:00.531423 I | rook-ceph-mon2: 2018-01-30 11:58:00.531342 7f815a50ef40  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1517313480531331, "cf_name": "default", "job": 1, "event": "table_file_creation", "file_number": 2394, "file_size": 1036, "table_properties": {"data_size": 86, "index_size": 27, "filter_size": 18, "raw_key_size": 51, "raw_average_key_size": 25, "raw_value_size": 16, "raw_average_value_size": 8, "num_data_blocks": 1, "num_entries": 2, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
2018-01-30 11:58:00.531439 I | rook-ceph-mon2: 2018-01-30 11:58:00.531375 7f815a50ef40  4 rocksdb: [/build/ceph/src/rocksdb/db/version_set.cc:2395] Creating manifest 2395
2018-01-30 11:58:00.531442 I | rook-ceph-mon2: 
2018-01-30 11:58:00.536735 I | rook-ceph-mon2: 2018-01-30 11:58:00.536661 7f815a50ef40  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1517313480536655, "job": 1, "event": "recovery_finished"}
2018-01-30 11:58:00.542227 I | rook-ceph-mon2: 2018-01-30 11:58:00.542159 7f815a50ef40  4 rocksdb: [/build/ceph/src/rocksdb/db/db_impl_open.cc:1063] DB pointer 0x55ab12e04000
2018-01-30 11:58:00.543275 I | rook-ceph-mon2: 2018-01-30 11:58:00.543176 7f815a50ef40  0 starting mon.rook-ceph-mon2 rank 0 at public addr 192.168.5.48:6790/0 at bind addr 192.168.90.126:6790/0 mon_data /var/lib/rook/rook-ceph-mon2/data fsid d62fd065-9692-45c4-8ca3-4ae8c9a6360f
2018-01-30 11:58:00.543576 I | rook-ceph-mon2: 2018-01-30 11:58:00.543357 7f815a50ef40  0 starting mon.rook-ceph-mon2 rank 0 at 192.168.5.48:6790/0 mon_data /var/lib/rook/rook-ceph-mon2/data fsid d62fd065-9692-45c4-8ca3-4ae8c9a6360f
2018-01-30 11:58:00.544145 I | rook-ceph-mon2: 2018-01-30 11:58:00.544064 7f815a50ef40  1 mon.rook-ceph-mon2@-1(probing).paxosservice(pgmap 1..2) refresh upgraded, format 0 -> 1
2018-01-30 11:58:00.556063 I | rook-ceph-mon2: 2018-01-30 11:58:00.555742 7f814ead3700  0 log_channel(cluster) log [INF] : mon.rook-ceph-mon2 calling new monitor election
2018-01-30 11:58:00.570430 I | rook-ceph-mon2: 2018-01-30 11:58:00.570348 7f814ead3700  0 log_channel(cluster) log [INF] : mon.rook-ceph-mon2 calling new monitor election
2018-01-30 11:58:05.580464 I | rook-ceph-mon2: 2018-01-30 11:58:05.580282 7f81512d8700  0 log_channel(cluster) log [INF] : mon.rook-ceph-mon2@0 won leader election with quorum 0,2
2018-01-30 11:58:05.584685 I | rook-ceph-mon2: 2018-01-30 11:58:05.584472 7f81512d8700  0 log_channel(cluster) log [WRN] : overall HEALTH_WARN 2 osds down; 1 host (2 osds) down; Reduced data availability: 136 pgs inactive; Degraded data redundancy: 932/77484 objects degraded (1.203%!)(MISSING), 527 pgs unclean, 391 pgs degraded, 391 pgs undersized; 1/3 mons down, quorum rook-ceph-mon0,rook-ceph-mon1
2018-01-30 11:58:05.604930 I | rook-ceph-mon2: 2018-01-30 11:58:05.604764 7f814ead3700  0 log_channel(cluster) log [INF] : monmap e3: 3 mons at {rook-ceph-mon0=192.168.7.219:6790/0,rook-ceph-mon1=192.168.11.116:6790/0,rook-ceph-mon2=192.168.5.48:6790/0}
2018-01-30 11:58:05.614258 I | rook-ceph-mon2: 2018-01-30 11:58:05.614097 7f814ead3700 -1 /build/ceph/src/mds/FSMap.cc: In function 'void FSMap::assign_standby_replay(mds_gid_t, fs_cluster_id_t, mds_rank_t)' thread 7f814ead3700 time 2018-01-30 11:58:05.605075
2018-01-30 11:58:05.614340 I | rook-ceph-mon2: /build/ceph/src/mds/FSMap.cc: 870: FAILED assert(mds_roles.at(standby_gid) == FS_CLUSTER_ID_NONE)
...
failed to run mon. failed to start mon: Failed to complete rook-ceph-mon2: signal: aborted (core dumped)
```

**Comment by galexrt** [comment] 2018-03-07 17:02
From the error message, this seems to be a duplicate of #1027.

**Comment by jbw976** [comment] 2018-03-07 19:44
Closing this to track on #1027 which this issue does appear to be a duplicate of.

**Closed by jbw976** 2018-03-07 19:44 UTC
