### ISSUE TITLE
no active mgr

### ISSUE THREAD

**Issue by microyahoo** [rook/rook#12483] opened 2023-07-07 04:59 UTC
**Is this a bug report or feature request?**
* Bug Report

After the cluster runs for a period of time, all mgr daemons are not active like below
![20230707-125503](https://github.com/rook/rook/assets/10202906/0ce5a8b9-020c-4906-b6cd-cab84091e7e0)

Then I use strace to track ceph-mgr process, which shows connections timed out
![20230707-125738](https://github.com/rook/rook/assets/10202906/2d69f9f1-311c-4071-a87f-0fbbcb2fcdd1)

Most connections are in the `CLOSE_WAIT` state. It comes to normal after I delete one ceph-mgr pod.
```
[root@node08 ~]# netstat -anpl | grep 775 -w | grep CLOSE_WAIT | wc -l
524
[root@node08 ~]# netstat -anpl | grep 775 -w | wc -l
539
```
I collect one ceph-mgr log, found it hangs at a certain point in time
[mgr-a.log](https://github.com/rook/rook/files/11974770/mgr-a.log)

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`): `Linux node01 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): release-1.10
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.10
* Kubernetes version (use `kubectl version`): v1.22.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment] 2023-07-07 12:23
@microyahoo can you please share the operator logs

**Comment by travisn** [comment] 2023-07-07 15:30
@microyahoo Do you have [two mgr pods](https://github.com/rook/rook/blob/release-1.11/deploy/examples/cluster.yaml#L57) or just one? Two would be recommended in case one has an issue.
The issue of a mgr hanging is known, though I don't have the ceph tracker at the moment to know the status.

**Comment by microyahoo** [comment] 2023-07-07 15:52
yes, we have two mgr pods, but two mgr pods are all hanging. I only restarted one of the pods, and the other one did not restart in order to preserve the environment. @travisn

**Comment by microyahoo** [comment] 2023-07-07 16:10
I didn’t see any useful information in the operator log, maybe as @travisn  mentioned, this is a ceph issue @parth-gr 
[operator.log](https://github.com/rook/rook/files/11983962/operator.1.log)

**Comment by travisn** [comment] 2023-07-07 17:18
Here is the tracker: https://tracker.ceph.com/issues/58379
Looks like the fix has been [backported to quincy](https://github.com/ceph/ceph/pull/52134), so it would be in the next release.

**Closed** 2023-09-13 20:02 UTC
Labels: bug, wontfix

**Comment by chauncyAAA** [comment] 2024-01-10 05:17
It seems like the problem is still unresolved.
I just deploy rook-1.13.1 version on rhel9.2,but the promblem sill exists.
<img width="1000" alt="image" src="https://github.com/rook/rook/assets/49383817/c3d75ee1-f76e-4253-88f8-2c3ed7c2ed1e">

**Comment by travisn** [comment] 2024-01-10 17:33
@chauncyAAA
1. What version of Ceph is running? 
2. Are there mgr pods running?
3. Does restarting the mgr pod bring it up again?

**Comment by Ramblurr** [comment] 2024-02-14 08:26
I am experiencing this problem too on a fresh cluster install.

> 1. What version of Ceph is running?
```
$ ceph version
ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable)
```

rook-ceph-cluster helm chart v1.13.4

> 2. Are there mgr pods running?

No.

```
k -n rook-ceph get pods
NAME                                            READY   STATUS    RESTARTS       AGE
csi-cephfsplugin-94czn                          3/3     Running   1 (13h ago)    13h
csi-cephfsplugin-kt8mt                          3/3     Running   0              13h
csi-cephfsplugin-mpcp4                          3/3     Running   1 (13h ago)    13h
csi-cephfsplugin-provisioner-677ff4ddc6-7b6q4   6/6     Running   0              13h
csi-cephfsplugin-provisioner-677ff4ddc6-ccvgc   6/6     Running   4 (13h ago)    13h
csi-cephfsplugin-s6wzv                          3/3     Running   1 (13h ago)    13h
csi-rbdplugin-7s7v6                             3/3     Running   0              13h
csi-rbdplugin-fkfj7                             3/3     Running   1 (13h ago)    13h
csi-rbdplugin-nm48d                             3/3     Running   1 (13h ago)    13h
csi-rbdplugin-provisioner-77f9c667d4-jrxkt      6/6     Running   1 (13h ago)    13h
csi-rbdplugin-provisioner-77f9c667d4-nppcm      6/6     Running   4 (13h ago)    13h
csi-rbdplugin-sqhdd                             3/3     Running   1 (13h ago)    13h
rook-ceph-mon-a-6d786f8b87-r5lz7                2/2     Running   0              13h
rook-ceph-mon-b-b49c9d6cd-87gpq                 2/2     Running   2 (3h1m ago)   13h
rook-ceph-mon-c-77479778cc-dc728                2/2     Running   2 (160m ago)   13h
rook-ceph-operator-659cbbd5d8-hmz6k             1/1     Running   0              13h
rook-ceph-tools-6c5cfc85bd-5nfrj                1/1     Running   0              13h
```

> 3. Does restarting the mgr pod bring it up again?

n/a

**Comment by parth-gr** [comment] 2024-02-14 09:19
@Ramblurr please add the rook operator logs

**Comment by Ramblurr** [comment] 2024-02-14 10:30
@parth-gr thanks for the reply, turns out I wasn't patient enough. They ended up being created after a restart of the operator.

**Comment by parth-gr** [comment] 2024-02-14 10:31
great
