### ISSUE TITLE
External cluster - Objectstore can t detect the CEPH Image version

### ISSUE THREAD

**Issue by ghabarid** [rook/rook#9513] opened 2022-01-03 12:10 UTC
We have an external Ceph cluster, which is created with ROOK operator. We have created a "client" rook/ceph cluster that connects to that external cluster.
Things worked fine under:
ROOK version: 1.7.9
Ceph version: 16.2.5
We could create pv/pvc volumes and buckets and objestusers.

After upgrading to 
ROOK version: 1.8.1
Ceph image: quay.io/ceph/ceph:v16.2.7-20211208
the RBD work fine, we still can work with pv etc.
The problem is the objectstore. It is stocked in  Phase:  Progressing, and the event log shows:
ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/xxx-objectstore". failed to detect running and desired ceph version: failed to detect ceph image version: failed to set up ceph version job: Rook image [rook/ceph:v1.8.1] and run image [] must be specified

Any ideas? Are we using the wrong image version?

**Comment by ghabarid** [comment] 2022-01-03 13:34
It seems that in the cephcluster we have to specify the ceph image version, just like the following:
cephVersion:
      image: quay.io/ceph/ceph:v16.2.7-20211208
This was not "necessary" in older versions.
I would suggest that this field should be mandatory.
Thx.

**Comment by leseb** [comment] 2022-01-03 13:43
> It seems that in the cephcluster we have to specify the ceph image version, just like the following: cephVersion: image: quay.io/ceph/ceph:v16.2.7-20211208 This was not "necessary" in older versions. I would suggest that this field should be mandatory. Thx.

Thanks, the field cannot be mandatory since not everyone deploys rgw/mds in the Kubernetes cluster. Most of the users are connecting to the external cluster and just consuming what's available. In this scenario, the image field is not mandatory.
I'm closing this since the issue is now fixed. Thanks.

**Closed by leseb** 2022-01-03 13:43 UTC
Labels: bug

**Comment by ghabarid** [comment] 2022-01-03 14:39
OK.
I would suggest working on a better message/event on the cephobject that gives more guides of the problem. Not just as warning.

**Comment by leseb** [comment] 2022-01-04 13:47
> OK. I would suggest working on a better message/event on the cephobject that gives more guides of the problem. Not just as warning.

Please elaborate on what you would like to see clarified.
