### ISSUE TITLE
Ceph storage class Unable to mount volumes for pod timeout expired waiting for volumes to attach or mount for pod list of unmounted volumes

### ISSUE THREAD

**Issue by vincent927** [rook/rook#2887] opened 2019-03-25 08:19 UTC
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**

When i deploy rook on Rancher2.1.6 by [doc1](https://rook.github.io/docs/rook/master/ceph-quickstart.html#deploy-the-rook-operator),[doc2](https://rook.github.io/docs/rook/master/ceph-block.html),and deploy a wordpress sample , pod start error:
```
Warning | FailedScheduling | pod has unbound PersistentVolumeClaims (repeated 2 times) | 23 minutes ago
Normal | Scheduled | Successfully assigned default/wordpress-mysql-6d9d576684-254c9 to node2 | 23 minutes ago
Warning | FailedMount | Unable to mount volumes for pod "wordpress-mysql-6d9d576684-254c9_default(59d6a78d-4ed3-11e9-a352-00163e0e2e83)": timeout expired waiting for volumes to attach or mount for pod "default"/"wordpress-mysql-6d9d576684-254c9". list of unmounted volumes=[mysql-persistent-storage]. list of unattached volumes=[mysql-persistent-storage default-token-plcdj] | a few seconds ago


```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`):
```
Linux test1.eyingchina.com 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration:
4CPU 8GRAM
* Rook version (use `rook version` inside of a Rook Pod):
v0.93
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher2.1.6
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
```
HEALTH_OK
```

**Comment by sp98** [comment] 2019-03-25 09:11
Hi @vincent927 

Please see the  pre-requisites under the  "Flex Configuration" section in case of Rancher at  https://rook.io/docs/rook/v0.6/k8s-pre-reqs.html

**Comment by vincent927** [comment] 2019-03-25 09:37
I found this document https://rook.io/docs/rook/v0.9/flexvolume.html , but I still can't find how to modify cluster.yml with Rancher. @sp98

**Comment by Inamatus** [comment] 2019-03-25 16:10
I have this problem too.  Use kubespray and deploy on Ubuntu 18.04 LTS. This problem appear when i updated to v. 0.93

**Comment by satoru-takeuchi** [comment] 2019-03-26 00:50
> I have this problem too. Use kubespray and deploy on Ubuntu 18.04 LTS. This problem appear when i updated to v. 0.93

Which version you updated from? Is it v0.9.2?

**Comment by Inamatus** [comment] 2019-03-26 01:44
> I encountered this problem too. I configured as the following link.
> 
> https://rook.io/docs/rook/v0.9/flexvolume.html
> 
> > I have this problem too. Use kubespray and deploy on Ubuntu 18.04 LTS. This problem appear when i updated to v. 0.93
> 
> Which version you updated from? Is it v0.9.2?

I updated its from 0.90. This link i tried to configure with this step. It wasn't work for me. 
There're many bug for Rook and Kubespray. Kubespray had a problem with hostfile its changed from host.ini to host.yaml but no had any notice for this changed very very bad.

**Comment by satoru-takeuchi** [comment] 2019-03-27 00:32
> It's work for me. The document must be update as soon as possible for this issue. There many wrong information on its.

Unfortunately it doesn't work for me.

In my case, I don't use kubespray. I use my own k8s management engine on CoreOS container linux.

I dug into this problem. Please let me know if you have any idea.

# summary

volume mount fails due to ".../rook-ceph-system mount ..." failure with exit code 2.
I guess /dev/rbd0 failed to be formatted due to it, but, unfortunately, I didn't know the detail yet.

# environment

- OS: CoreOS container linux 2023.5.0
- k8s manager: CKE # https://github.com/cybozu-go/cke
- Rook: 0.9.3
- k8s version:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", ...
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", ...
```

# What changes I made to yaml files.

- Add this line to operator.yaml

```
name: FLEXVOLUME_DIR_PATH
value: "/var/lib/kubelet/volumeplugins"
```

- Add "--volume-plugin-dir=/var/lib/kubelet/volumeplugins" option to kubelet:

This is set correctly as follows.

```
$ ps ax | grep kubelet
 2569 ?        Ssl    2:19 apiserver <snip> --allow-privileged=true --volume-plugin-dir=/var/lib/kubelet/volumeplugins
```

- Change some parameters of cluster.yaml as follows
 - "mon -> count" from 3 to 1
 - "storage -> useAllNodes" from true to false
 - "storage -> directories -> path" from nothing to "/var/lib/kubelet/rook"
 - "storage -> nodes -> name" from nothing to 10.69.0.4 # it's one of my k8s worker node

- Change mysql.yaml as follow
 - mysql-pv-claim's "spec -> resources -> requests -> storage" from 20Gi to 128Mi

# step to reproduce

```
$ kubectl create -f operator.yaml
$ kubectl create -f cluster.yaml
$ kubectl create -f storageclass.yaml
$ kubectl create -f mysql.yaml
```

# expected result

/dev/rbd0 is mounted as /var/lib/mysql at mysql pod

# actual result

- /dev/rbd0 exists at a node which mysql pod exists on, but failed to mount it as follow.

```
$ kubectl get pod
NAME                               READY   STATUS              RESTARTS   AGE
wordpress-mysql-6887bf844f-nzdl6   0/1     ContainerCreating   0          29s
$ kubectl describe pod wordpress-mysql-6887bf844f-nzdl6
Events:
  Type     Reason            Age                    From                Message
  ----     ------            ----                   ----                -------
  Warning  FailedScheduling  2m52s (x3 over 2m53s)  default-scheduler   pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
  Normal   Scheduled         2m52s                  default-scheduler   Successfully assigned default/wordpress-mysql-6887bf844f-nzdl6 to 10.69.0.5
  Warning  FailedMount       112s                   kubelet, 10.69.0.5  MountVolume.SetUp failed for volume "pvc-8e791905-5024-11e9-992f-525400168799" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume replicapool/pvc-8e791905-5024-11e9-992f-525400168799: failed to map image replicapool/pvc-8e791905-5024-11e9-992f-525400168799 cluster rook-ceph. failed to map image replicapool/pvc-8e791905-5024-11e9-992f-525400168799: Failed to complete 'rbd': signal: interrupt. . output:
  Warning  FailedMount       49s                    kubelet, 10.69.0.5  Unable to mount volumes for pod "wordpress-mysql-6887bf844f-nzdl6_default(8ec8aab4-5024-11e9-a673-525400ba49d9)": timeout expired waiting for volumes to attach or mount for pod "default"/"wordpress-mysql-6887bf844f-nzdl6". list of unmounted volumes=[mysql-persistent-storage]. list of unattached volumes=[mysql-persistent-storage default-token-c9rhx]
  Warning  FailedMount       47s (x7 over 111s)     kubelet, 10.69.0.5  MountVolume.SetUp failed for volume "pvc-8e791905-5024-11e9-992f-525400168799" : unexpected end of JSON input
```

# Analyze

pv and pvc exists.

```
$ kubectl -n rook-ceph get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS      REASON   AGE
pvc-8e791905-5024-11e9-992f-525400168799   128Mi      RWO            Delete           Bound    default/mysql-pv-claim   rook-ceph-block            5m5s
$ kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-pv-claim   Bound    pvc-8e791905-5024-11e9-992f-525400168799   128Mi      RWO            rook-ceph-block   5m22s
```

/dev/rbd exists.

```
$ sudo su
bash-4.3# ls /dev/rbd0
/dev/rbd0
```

But it's not be formatted as ext4.

```
# mount /dev/rbd0 /mnt/
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/rbd0, missing codepage or helper program, or other error.
```

After mkfs /dev/rbd0 manually, mysql seems to work fine.

```
$ kubectl describe pod wordpress-mysql-6887bf844f-nzdl6
...
...
  Warning  FailedMount       5m2s (x6 over 16m)   kubelet, 10.69.0.5  Unable to mount volumes for pod "wordpress-mysql-6887bf844f-nzdl6_default(8ec8aab4-5024-11e9-a673-525400ba49d9)": timeout expired waiting for volumes to attach or mount for pod "default"/"wordpress-mysql-6887bf844f-nzdl6". list of unmounted volumes=[mysql-persistent-storage]. list of unattached volumes=[mysql-persistent-storage default-token-c9rhx]
  Normal   Pulling           3m5s                 kubelet, 10.69.0.5  pulling image "mysql:5.6"
  Normal   Pulled            2m47s                kubelet, 10.69.0.5  Successfully pulled image "mysql:5.6"
  Normal   Created           2m47s                kubelet, 10.69.0.5  Created container
  Normal   Started           2m47s                kubelet, 10.69.0.5  Started container
```

There are some error logs on journal log of a node which mysql pod exist.

```
Mar 27 00:16:30 rack0-worker5 abf4f58504ed[1383]: E0327 00:16:30.595472    2719 driver-call.go:267] Failed to unmarshal output for command: mount, output: "", error: unexpected end of JSON input
Mar 27 00:16:30 rack0-worker5 abf4f58504ed[1383]: W0327 00:16:30.596486    2719 driver-call.go:150] FlexVolume: driver call failed: executable: /var/lib/kubelet/volumeplugins/ceph.rook.io~rook-ceph-system/rook-ceph-system, args: [mount /var/lib/kubelet/pods/8ec8aab4-5024-11e9-a673-525400ba49d9/volumes/ceph.rook.io~r
ook-ceph-system/pvc-8e791905-5024-11e9-992f-525400168799 {"clusterNamespace":"rook-ceph","dataBlockPool":"","image":"pvc-8e791905-5024-11e9-992f-525400168799","kubernetes.io/fsType":"ext4","kubernetes.io/pod.name":"wordpress-mysql-6887bf844f-nzdl6","kubernetes.io/pod.namespace":"default","kubernetes.io/pod.uid":"8ec
8aab4-5024-11e9-a673-525400ba49d9","kubernetes.io/pvOrVolumeName":"pvc-8e791905-5024-11e9-992f-525400168799","kubernetes.io/readwrite":"rw","kubernetes.io/serviceAccount.name":"default","pool":"replicapool","storageClass":"rook-ceph-block"}], error: exit status 2, output: ""
Mar 27 00:16:30 rack0-worker5 abf4f58504ed[1383]: E0327 00:16:30.597820    2719 nestedpendingoperations.go:267] Operation for "\"flexvolume-ceph.rook.io/rook-ceph-system/8ec8aab4-5024-11e9-a673-525400ba49d9-pvc-8e791905-5024-11e9-992f-525400168799\" (\"8ec8aab4-5024-11e9-a673-525400ba49d9\")" failed. No retries perm
itted until 2019-03-27 00:18:32.597759794 +0000 UTC m=+5038.618144971 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"pvc-8e791905-5024-11e9-992f-525400168799\" (UniqueName: \"flexvolume-ceph.rook.io/rook-ceph-system/8ec8aab4-5024-11e9-a673-525400ba49d9-pvc-8e791905-5024-11e9-992f-525400168
799\") pod \"wordpress-mysql-6887bf844f-nzdl6\" (UID: \"8ec8aab4-5024-11e9-a673-525400ba49d9\") : unexpected end of JSON input"
```

It means ".../rook-ceph-system mount ..." failed with exit code 2. I guess /dev/rbd0 failed to be
formatted due to it, but, unfortunately, I didn't know the detail yet.

# Note

The above mentioned steps doesn't work with Rook v0.9.0 too.

**Comment by satoru-takeuchi** [comment] 2019-03-30 09:12
In my case, the root cause is that /tmp is mounted as read-only. So rook-ceph-system mount tries to
output its error log, due to mkfs failure output, to read-only /tmp.

This problem can be fixed by appending bind mount from host's /tmp to kubelet container's /tmp

**Comment by vincent927** [comment] 2019-04-01 01:41
Maybe can try this method，update operator.yaml change the "FLEXVOLUME_DIR_PATH"

```
        # Set the path where the Rook agent can find the flex volumes
        - name: FLEXVOLUME_DIR_PATH
          value: "/var/lib/kubelet/volumeplugins"
```

**Comment by marcstreeter** [comment] 2019-04-29 14:53
@vincent927 I tried that, but it still has the same issue. I tried it also with `/var/lib/kubelet/volume-plugins` and same issue too (ofcourse I'm also using kubespray so I may need to open a separate ticket).

**Closed** 2019-04-30 01:20 UTC
Labels: bug
