### ISSUE TITLE
A single Ceph cluster can stall the reconcile loop for all Ceph clusters

### ISSUE THREAD

**Issue by haslersn** [rook/rook#11330] opened 2022-11-18 10:25 UTC
I have two Ceph clusters (one internal and one external). Sometimes the external Ceph cluster doesn't reconcile after operator startup. This is a problem, because the `/var/lib/rook/rook-ceph-external/` directory with config and keyring doesn't get created within the operator Pod, which is required for other operations (such as bucket provisioning) to succeed.

I suspect this is due to the fact that Rook reconciles Ceph clusters sequentially and the reconcile of the internal Ceph cluster doesn't terminate (the debug message `done reconciling ceph cluster in namespace` doesn't occur in the log), so the reconcile of the external Ceph cluster never starts.

The reason why the reconcile of the internal Ceph cluster doesn't terminate is probably this other issue which I currently have: #11304 -- one OSD doesn't get prepared successfully.

However, I think if one Ceph cluster has a problem, then that shouldn't spread to other Ceph clusters, so the operator should probably reconcile them concurrently.

**Is this a bug report or feature request?**
* Bug Report

**Logs to submit**:

(Note that the rook version is dirty because I added some additional info output beginning with `DEBUG:`.)

```
2022-11-18 09:25:59.991238 I | rookcmd: starting Rook v1.10.5-1.gd73c8c3c5.dirty with arguments '/usr/local/bin/rook ceph operator'
2022-11-18 09:25:59.991383 I | rookcmd: flag values: --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO, --operator-image=, --service-account=
2022-11-18 09:25:59.991390 I | cephcmd: starting Rook-Ceph operator
2022-11-18 09:26:00.248960 I | cephcmd: base ceph version inside the rook operator image is "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)"
2022-11-18 09:26:00.264950 I | op-k8sutil: ROOK_CURRENT_NAMESPACE_ONLY="false" (env var)
2022-11-18 09:26:00.264987 I | operator: watching all namespaces for Ceph CRs
2022-11-18 09:26:00.265142 I | operator: setting up schemes
2022-11-18 09:26:00.270075 I | operator: setting up the controller-runtime manager
I1118 09:26:01.321545       1 request.go:682] Waited for 1.042898567s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/node.k8s.io/v1beta1?timeout=32s
2022-11-18 09:26:01.478437 I | operator: Fetching webhook cert-manager-webhook to see if cert-manager is installed.
2022-11-18 09:26:01.485470 I | operator: Fetching Issuer rook-ceph/selfsigned-issuer.
2022-11-18 09:26:01.492885 I | operator: Fetching certificate rook-ceph/rook-admission-controller-cert.
2022-11-18 09:26:01.500024 I | operator: looking for admission webhook secret "rook-ceph-admission-controller"
2022-11-18 09:26:01.505220 I | operator: admission webhook secret "rook-ceph-admission-controller" found
2022-11-18 09:26:01.505268 I | operator: Creating webhook rook-ceph/rook-ceph-webhook.
2022-11-18 09:26:01.511918 I | operator: admission webhook already exists. updating it
2022-11-18 09:26:01.575510 I | operator: setting up admission webhooks
2022-11-18 09:26:01.576924 I | ceph-cluster-controller: successfully started
2022-11-18 09:26:01.577065 I | ceph-cluster-controller: enabling hotplug orchestration
2022-11-18 09:26:01.577120 I | ceph-crashcollector-controller: successfully started
2022-11-18 09:26:01.577167 I | ceph-block-pool-controller: successfully started
2022-11-18 09:26:01.577213 I | ceph-object-store-user-controller: successfully started
2022-11-18 09:26:01.577243 I | ceph-object-realm-controller: successfully started
2022-11-18 09:26:01.577276 I | ceph-object-zonegroup-controller: successfully started
2022-11-18 09:26:01.577299 I | ceph-object-zone-controller: successfully started
2022-11-18 09:26:01.577515 I | ceph-object-controller: successfully started
2022-11-18 09:26:01.577563 I | ceph-file-controller: successfully started
2022-11-18 09:26:01.577622 I | ceph-nfs-controller: successfully started
2022-11-18 09:26:01.577661 I | ceph-rbd-mirror-controller: successfully started
2022-11-18 09:26:01.577698 I | ceph-client-controller: successfully started
2022-11-18 09:26:01.577740 I | ceph-filesystem-mirror-controller: successfully started
2022-11-18 09:26:01.577779 I | operator: rook-ceph-operator-config-controller successfully started
2022-11-18 09:26:01.577802 I | ceph-csi: rook-ceph-operator-csi-controller successfully started
2022-11-18 09:26:01.577824 I | op-bucket-prov: rook-ceph-operator-bucket-controller successfully started
2022-11-18 09:26:01.577847 I | ceph-bucket-topic: successfully started
2022-11-18 09:26:01.577878 I | ceph-bucket-notification: successfully started
2022-11-18 09:26:01.577900 I | ceph-bucket-notification: successfully started
2022-11-18 09:26:01.577926 I | ceph-fs-subvolumegroup-controller: successfully started
2022-11-18 09:26:01.577952 I | blockpool-rados-namespace-controller: successfully started
2022-11-18 09:26:01.579528 I | operator: starting the controller-runtime manager
2022-11-18 09:26:01.783781 I | op-k8sutil: ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS="15" (configmap)
2022-11-18 09:26:01.783842 I | op-k8sutil: ROOK_LOG_LEVEL="DEBUG" (configmap)
2022-11-18 09:26:01.783858 I | op-k8sutil: ROOK_ENABLE_DISCOVERY_DAEMON="false" (configmap)
2022-11-18 09:26:01.784369 D | ceph-spec: "ceph-object-zone-controller": CephCluster resource "rook-ceph-external" found in namespace "rook-ceph-external"
2022-11-18 09:26:01.784416 D | ceph-spec: "ceph-object-zone-controller": ceph status is "HEALTH_OK", operator is ready to run ceph command, reconciling
2022-11-18 09:26:01.786886 D | ceph-crashcollector-controller: reconciling node: "kone04"
2022-11-18 09:26:01.788196 I | ceph-cluster-controller: DEBUG: Reconciling request: rook-ceph/rook-ceph
2022-11-18 09:26:01.788370 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2022-11-18 09:26:01.788848 D | ceph-spec: "ceph-object-zonegroup-controller": CephCluster resource "rook-ceph-external" found in namespace "rook-ceph-external"
2022-11-18 09:26:01.788884 D | ceph-spec: "ceph-object-zonegroup-controller": ceph status is "HEALTH_OK", operator is ready to run ceph command, reconciling
2022-11-18 09:26:01.789494 D | ceph-spec: "ceph-object-controller": CephCluster resource "rook-ceph-external" found in namespace "rook-ceph-external"
2022-11-18 09:26:01.789538 D | ceph-spec: "ceph-object-controller": ceph status is "HEALTH_OK", operator is ready to run ceph command, reconciling
2022-11-18 09:26:01.789927 D | ceph-spec: found existing monitor secrets for cluster rook-ceph-external
2022-11-18 09:26:01.790074 D | ceph-spec: "ceph-file-controller": CephCluster resource "rook-ceph" found in namespace "rook-ceph"
2022-11-18 09:26:01.790102 D | ceph-spec: "ceph-file-controller": ceph status is "HEALTH_WARN", operator is ready to run ceph command, reconciling
2022-11-18 09:26:01.790254 D | clusterdisruption-controller: reconciling "rook-ceph-external/"
2022-11-18 09:26:01.790415 D | clusterdisruption-controller: reconciling "rook-ceph-external/rook-ceph-external"
2022-11-18 09:26:01.790498 D | clusterdisruption-controller: reconciling "rook-ceph/rook-ceph"
2022-11-18 09:26:01.790578 D | ceph-spec: ceph version found "17.2.5-0"
2022-11-18 09:26:01.790639 D | clusterdisruption-controller: reconciling "rook-ceph/"
2022-11-18 09:26:01.790744 I | operator: rook-ceph-operator-config-controller done reconciling
2022-11-18 09:26:01.791943 D | ceph-spec: found existing monitor secrets for cluster rook-ceph-external
2022-11-18 09:26:01.792639 I | op-k8sutil: CSI_ENABLE_HOST_NETWORK="true" (default)
2022-11-18 09:26:01.792830 D | ceph-csi: not a multus cluster "rook-ceph/rook-ceph-operator-config" or CSI_ENABLE_HOST_NETWORK is true, not deploying the ceph-csi plugin holder
2022-11-18 09:26:01.792956 D | ceph-csi: not a multus cluster "rook-ceph/rook-ceph-operator-config" or CSI_ENABLE_HOST_NETWORK is true, not deploying the ceph-csi plugin holder
2022-11-18 09:26:01.794720 D | ceph-spec: found existing monitor secrets for cluster rook-ceph
[...]
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v1.10.5

**Comment by parth-gr** [comment] 2022-11-18 11:51
`2022-11-18 09:26:01.790415 D | clusterdisruption-controller: reconciling "rook-ceph-external/rook-ceph-external"` I see it's started reconciling for the external cluster too

**Comment by haslersn** [comment] 2022-11-18 11:52
@parth-gr No, that's the clusterdisruption-controller, not the ceph-cluster-controller. This issue is all about the ceph-cluster-controller.

**Comment by haslersn** [comment] 2022-11-18 12:20
> how about your health of the external and the normal cluster?

Both are healthy, but how is this question related to the issue? `/var/lib/rook/rook-ceph-external/` is an ephemeral directory within the operator Pod. It is not a host path and as such it is not related to the health of the cluster. But it is required for the operator to perform certain operations on the cluster.

**Comment by parth-gr** [comment] 2022-11-18 12:27
>But it is required for the operator to perform certain operations on the cluster.

But if the operator reconciles for the first time then only it will go and create the following cluster-connected and create other mons and other pods and also perform all other operations that the operator does for external cluster connection,

Can you restart your operator and provide full logs so we can see what let the operator skip this reconciliation/create a directory?

**Comment by haslersn** [comment] 2022-11-18 14:12
> provide full logs

Full logs: https://gist.github.com/haslersn/a4d051780083fd0a1e3df77e54a7a850

In my version of the operator I added the following debug output on top of v1.10.5:

```diff
--- a/pkg/operator/ceph/cluster/controller.go
+++ b/pkg/operator/ceph/cluster/controller.go
@@ -221,6 +221,7 @@ func (r *ReconcileCephCluster) Reconcile(context context.Context, request reconc
 }
 
 func (r *ReconcileCephCluster) reconcile(request reconcile.Request) (reconcile.Result, cephv1.CephCluster, error) {
+       logger.Infof("DEBUG: Reconciling request: %v", request)
        // Pass the client context to the ClusterController
        r.clusterController.client = r.client
```

As you can see in the full log, it doesn't contain the string `DEBUG: Reconciling request: rook-ceph-external/rook-ceph-external` . Therefore, the function `func (r *ReconcileCephCluster) reconcile(request reconcile.Request)` never gets called with `rook-ceph-external`.

> so we can see what let the operator skip this reconciliation

My original post already contains the likely explanation: The operator doesn't finish reconciling `rook-ceph` (otherwise the log would contain the string `done reconciling ceph cluster in namespace`), so it never gets to reconciling `rook-ceph-external`.

https://github.com/rook/rook/blob/343a3c9709e567e5415caf0bda6d5444441fa2a5/pkg/operator/ceph/cluster/cluster.go#L164

**Comment by travisn** [comment] 2022-11-19 00:04
Looks like the OSDs are stuck processing here:
```
2022-11-18 10:11:12.146020 I | op-osd: waiting... 0 of 1 OSD prepare jobs have finished processing and 19 of 19 OSDs have been updated
```

@BlaineEXE Do we need to add another check that the number of expected OSDs for configuration is done so it doesn't get stuck here? 

@haslersn Did you perhaps remove an OSD? I wonder if there is some dangling resource that is confusing the operator. If there are any configmaps named `rook-ceph-osd-<node>-status`, delete them and restart the operator.

Regarding whether to process the clusters in parallel, yes this would be preferred so issues with one cluster reconcile wouldn't affect the other. I'd say it hasn't yet been implemented for two reasons:
- Concern that the operator log will be more difficult to read If the cluster reconciles are intertwined
- There will certainly be difficult-to-find bugs since the operator was implemented serially and there may be resources that need to be locked between the cluster reconciles goroutines.

**Comment by haslersn** [comment] 2022-11-19 04:15
> If there are any configmaps named `rook-ceph-osd-<node>-status`, delete them and restart the operator.

No, there are no such ConfigMaps. Not even for the still existing OSDs.

However, note that this issue is not about my internal Ceph cluster. The point is, no matter how badly that Ceph cluster is in shape, it shouldn't affect the reconciling of unrelated Ceph clusters.

> Regarding whether to process the clusters in parallel

Another option would be to reconcile them sequentially, but don't perform any blocking tasks and don't repeat any failed tasks in a (possibly endless) loop. Instead, if the operator needs to wait or retry something, reschedule the Ceph cluster for reconciling. This way, different Ceph clusters get reconciled in alternation.

**Comment by haslersn** [comment] 2022-11-19 04:19
> Do we need to add another check that the number of expected OSDs for configuration is done so it doesn't get stuck here?

Just mentioning for completeness: the expected number of OSDs is 20 here. The "19 of 19" which the operator reports is related to 19 existing OSDs. But that's still one less than expected. So it's correct that the operator tries to prepare another OSD. This fails, but this issue is about the fact no failure whatsoever should have effects on totally unrelated Ceph clusters.

**Comment by parth-gr** [comment] 2023-02-28 13:23
Why not to simple start a different rook cluster? @haslersn

**Comment by haslersn** [comment] 2023-02-28 14:01
@parth-gr because that's more complexity and requires several manual changes to how rook is deployed. With a single rook operator, we can simply use the manifests (common.yaml, operator.yaml, toolbox.yaml) downloaded from the repo.

**Comment by briend** [comment] 2024-01-24 19:29
We saw this issue as well while testing multiple ceph clusters with one Rook Operator managing them.  Consider this scenario:

- cluster A has an OSD replaced, health is WARN while degraded objects recover
- cluster B also has an OSD replaced

In this scenario, cluster A may block the replacement of the OSD for cluster B.   Rook will not finish reconciling cluster A until it is not WARN, which may take several days while degraded objects count is >0.  Cluster B will have to wait a long time in a degraded or broken state before its new OSD is initialized.

One workaround is to temporarily add `continueUpgradeAfterChecksEvenIfNotHealthy: true` to the CephCluster CR for cluster A, and restart the rook operator.  Ideally the operator would skip the whole cluster if it wasn't healthy and continue with the next cluster (doesn't have to be concurrent, does it?)

Another idea could be to skip reconciliation entirely if you added a label `do_not_reconcile: true` to the CephCluster CR, similar to the debug methods for daemons added here: https://github.com/rook/rook/issues/12785

**Comment by briend** [comment] 2024-01-24 19:52
not stale

**Comment by briend** [comment] 2024-01-25 23:38
> Another idea could be to skip reconciliation entirely if you added a label `do_not_reconcile: true` to the CephCluster CR, similar to the debug methods for daemons added here: #12785

I tried setting `do_not_reconcile: true` label on all the CRs in the cluster, and even the other label `ceph.rook.io/do-not-reconcile: true` on all the OSD deployments and pods.   Nothing can seem to stop the osd wait loop.  I do see the labels are recognized in rook debug output:

```
ceph-cluster-controller: object "do_not_reconcile" matched on update but "ceph-mycluster-rook-ceph-cluster" label is set, doing nothing
```

This seems to be why I can set `continueUpgradeAfterChecksEvenIfNotHealthy: true` to have it continue:

https://github.com/rook/rook/blob/034756df0e690fc67a3f1bb1af56fa701af91a17/pkg/operator/ceph/cluster/osd/update.go#L94-L96

I didn't see anything obvious to break out of the `updateAndCreateOSDsLoop` (or avoid going into the loop in the first place) based on labels: https://github.com/rook/rook/blob/034756df0e690fc67a3f1bb1af56fa701af91a17/pkg/operator/ceph/cluster/osd/status.go#L173

The only other work-around I can see is to just keep restarting Rook and hope the order it processes the ceph clusters is what you need.

**Comment by BlaineEXE** [comment] 2024-01-25 23:53
@travisn @sp98 I think we should stop doing the OSD wait loop. Instead, if the reconciler needs to wait for an OSD to become ready or the cluster to be healthy, the reconcile loop should return a reconcile result without error and where there is some `retryAfter` 10 minutes or so.

**Comment by travisn** [comment] 2024-01-26 23:32
It would certainly be ideal if we had a separate operator managing each CephCluster. But even if they are configured to only watch their own cluster and only one of them owns the csi driver, I worry that there will be lurking bugs for years to come particularly in areas such as OBC/COSI that watch for resources in all namespaces.

Failing the reconcile after some timeout seems reasonable since it would unblock other cluster reconciles. At the same time, it may lead to starving of updating OSDs in large clusters if they keep restarting the reconcile. Perhaps we could have a flag that causes the reconcile to fail after a timeout instead of waiting indefinitely. 

Setting `continueUpgradeAfterChecksEvenIfNotHealthy: true` seems like a reasonable workaround for now.

**Comment by parth-gr** [comment] 2024-03-28 09:17
Closing in perspective of https://github.com/rook/rook/issues/13848

**Closed by parth-gr** 2024-03-28 09:17 UTC
Labels: bug

**Comment by travisn** [comment] 2024-03-28 14:42
To be clear, we expect #13848 to fix this, but until then the issue is not resolved.
