### ISSUE TITLE
Automatically configure `mgr/rook/storage_class`

### ISSUE THREAD

**Issue by Omar007** [rook/rook#12858] opened 2023-09-06 12:01 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
1. Automatically configure the `mgr/rook/storage_class` value based on the CephCluster configuration.
2. Have the `mgr/rook/storage_class` setting support multiple items (turn it into a space separated list?).

The first item is currently a manual step. Not too complicated but the cluster configuration object contains the required information. E.g. the following dumps all the storage classes used:
```
kubectl -n rook-ceph get cephcluster rook-ceph -o jsonpath='{.spec.storage.storageClassDeviceSets[*].volumeClaimTemplates[*].spec.storageClassName}'
```
It seems like this could be used to automatically populate the configuration to improve the out-of-the-box experience.

Both doing it manually as well as automatic has another limitation in the current version, which means the second item needs to be done as well to complete the feature; the cluster config can easily have more than a single storage class configured for provisioning. This can not currently be set as the value for `mgr/rook/storage_class` as it seems to be limited to a single value (exact string match?).

**What is use case behind this feature:**
- Improve the oob experience (prevent errors from popping up in the dashboard)
- Eliminate manual work (both initial and later reconfigurations)
- Extend the supported clusters beyond single storage class deployments

**Environment**:
N/A

**Comment by travisn** [comment] 2023-09-06 18:09
@Omar007 Please explain more about the need for the `mgr/rook/storage_class` to be set. How does the dashboard use this? Is it trying to create OSDs? What failure is the dashboard showing if it is not set? Instead of setting this value, I'd expect the mgr module to query inspect the CephCluster CR settings if it needs to find the storage class being used by Rook for the OSDs.

**Comment by Omar007** [comment] 2023-09-06 20:28
It seems to, by default, get set to `local`. That does not match the actual storage class(es) used in the deployment.  

The dashboard uses this information to populate pages such as the disk information (`/inventory`), which does not work at all out of the box as a result and just throws 500 errors at the user. It also shows a whole set of `N/A` in areas such as the hosts page (`/hosts`).  
In both cases, the manager throws the following exception:

```
debug 2023-09-06T20:26:21.468+0000 7fa447dca700  0 [rook ERROR orchestrator._interface] No storage class exists matching name provided in ceph config at mgr/rook/storage_class
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
    return OrchResult(f(*args, **kwargs))
  File "/usr/share/ceph/mgr/rook/module.py", line 229, in get_inventory
    discovered_devs = self.rook_cluster.get_discovered_devices(host_list)
  File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 758, in get_discovered_devices
    storage_class = self.get_storage_class()
  File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 749, in get_storage_class
    raise Exception('No storage class exists matching name provided in ceph config at mgr/rook/storage_class')
Exception: No storage class exists matching name provided in ceph config at mgr/rook/storage_class
debug 2023-09-06T20:26:21.474+0000 7fa447dca700  0 [dashboard ERROR exception] Internal Server Error
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 258, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/orchestrator.py", line 33, in _inner
    return method(self, *args, **kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 527, in inventory
    return get_inventories(None, refresh)
  File "/usr/share/ceph/mgr/dashboard/controllers/host.py", line 272, in get_inventories
    for host in orch.inventory.list(hosts=hosts, refresh=do_refresh)]
  File "/usr/share/ceph/mgr/dashboard/services/orchestrator.py", line 39, in inner
    raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
Exception: No storage class exists matching name provided in ceph config at mgr/rook/storage_class
```

**Comment by travisn** [comment] 2023-09-06 21:07
We really need some effort put into dashboard integration for Rook from inside the Ceph dashboard. Rook won't be able to fix these dashboard issues with Rook fixes alone. It would be great to discuss with @rkachach.

**Comment by rkachach** [comment] 2023-09-25 09:42
@Omar007 that seems to be a known issue, @jmolmo has already provided a fix for the original issue and in your case the workarround seems to be creating a storage-class (as of the comment https://github.com/rook/rook/issues/10703#issuecomment-1256279736):


```
cat <<EOF | kubectl apply -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
EOF
```

**Comment by Omar007** [comment] 2023-09-25 09:46
The problem experienced is basically the same, true. But that was not why I made this post; as I mentioned, it can be manually configured (at least for 1 class, multiple is still not an option).  

I made this issue as a feature request, not a bug report, as this is really about improving the situation and out-of-the-box experience of things.
That said, strictly speaking, this could be divided up into 2 issues, 1 feature and 1 bug, neither of which are not covered by the mentioned ticket;
The feature part would be the out-of-the-box experience improvements.  
The bug part is that it currently only support 1 class value instead of multiple.

**Comment by rkachach** [comment] 2023-09-29 08:58
@Omar007 sorry, not sure why I though that this was a BUG not a feature request. We had some discussions about this issue and we think it makes sense to add support to automatically detect the storage class instead of populating the variable manually.

**Comment by rkachach** [comment] 2023-10-02 10:30
This support requires changes on the rook orchestrator (ceph-project) that will be addressed as part of https://tracker.ceph.com/issues/63038

**Comment by rkachach** [comment] 2023-11-03 21:30
@Omar007 the feature has been merged to the ceph main branch. I have already tested the code on my local setups but it would be great if you can test the new feature and see if it solves the issues you were experimenting. Thanks.

**Comment by Omar007** [comment] 2023-11-13 13:08
@rkachach has this by chance been automatically build into a container image/tag for either an upcoming 17.x or 18.x release I could use?

**Comment by Omar007** [comment] 2023-11-26 14:16
Sorry for the delay. I've upgraded the cluster to `quay.io/ceph/daemon-base@sha256:cb226bc79ccb47df9993ecd9da840db5b20eb27f8e4c383f029b5621ba316156`.  

First glance experience loading up the interface seems good, no error is being thrown at me. However, there are some problems. I'm not sure which ones are related to this change and which are unrelated so I'll list the things I noticed, starting with the ones related to the physical disks:

1. the disks dataset is incomplete; not all disks are being shown/accounted for. There are only 24/30 disks present in total on both the "Hosts" tab as well as the "Physical Disks" tab. These account for the disks of 1 out of the 3 defined device sets. It's the one I have defined *last* in the cluster spec. The total disk/OSD count is 30 but (next point)
2. the "Services" tab shows 60/30 in the OSDs "Running" column. That is double the total amount of disks/OSDs somehow? Expanding it shows only 30 total entries. These entries match with what is shown in the "OSDs" and "CRUSH map" tab.

Then what I'm fairly sure is unrelated but I also noticed:

3. the MDS daemons on the "Services" tab are shown to be offline (0 running), while the "Summary" tab shows 3 with a green checkmark and 3 with a blue exclamation mark. The MDS log has a few occurences of `missed beacon ack from the monitors` but the filesystems seems to work fine.
4. the "Upgrade" tab throws an error that it's not supported by the orchestrator and no daemon versions are shown for any of the daemons.
5. the "Overview" and "Multi-Site" tabs in the "Object Gateway" section are unable to retrieve lists such as zones, realms, etc. The overview does list correct numbers in the "Inventory" card but everything else on either of the tabs is empty.

**Comment by rkachach** [comment] 2023-11-27 09:57
@Omar007 thank you very much for testing the changes and for the feedback. Unfortunately any issue we detect at this stage will not be fixed on the next reef release (`v18.2.1`) as this release doesn't admit more PRs.

I'll try to address the points inline:

> Sorry for the delay. I've upgraded the cluster to `quay.io/ceph/daemon-base@sha256:cb226bc79ccb47df9993ecd9da840db5b20eb27f8e4c383f029b5621ba316156`.
> 
> First glance experience loading up the interface seems good, no error is being thrown at me. However, there are some problems. I'm not sure which ones are related to this change and which are unrelated so I'll list the things I noticed, starting with the ones related to the physical disks:
> 
> 1. the disks dataset is incomplete; not all disks are being shown/accounted for. There are only 24/30 disks present in total on both the "Hosts" tab as well as the "Physical Disks" tab. These account for the disks of 1 out of the 3 defined device sets. It's the one I have defined _last_ in the cluster spec. The total disk/OSD count is 30 but (next point)

[rkachach] please, can you attach your cluster spec?. It's really hard to understand why some of the disks are not listed. As of the current logic  we only list the configured disks from the section `storageClassDeviceSets` section, not all the available ones. 

> 2. the "Services" tab shows 60/30 in the OSDs "Running" column. That is double the total amount of disks/OSDs somehow? Expanding it shows only 30 total entries. These entries match with what is shown in the "OSDs" and "CRUSH map" tab.
> 

[rkachach] I'm not able to reproduce this on my cluster. Let's see if with your cluster.yaml file I can figure out why the OSDs listing is not consistent. 

> Then what I'm fairly sure is unrelated but I also noticed:
> 
> 3. the MDS daemons on the "Services" tab are shown to be offline (0 running), while the "Summary" tab shows 3 with a green checkmark and 3 with a blue exclamation mark. The MDS log has a few occurences of `missed beacon ack from the monitors` but the filesystems seems to work fine.

[rkachach] Please, can you open an issue for this?

> 4. the "Upgrade" tab throws an error that it's not supported by the orchestrator and no daemon versions are shown for any of the daemons.

[rkachach] Ceph upgrades in Rook works on different way than upgrades on a `cephadm` deployment. This error is should be treated gracefully but shouldn't affect the normal functioning of the dashboard. 

> 5. the "Overview" and "Multi-Site" tabs in the "Object Gateway" section throw a 500 error at the user saying they are unable to retrieve lists such as zones, realms, etc. The overview does list correct numbers in the "Inventory" card but everything else on either of the tabs is empty.

[rkachach] being addressed by https://github.com/rook/rook/pull/13256

**Comment by Omar007** [comment] 2023-11-27 11:58
> Unfortunately any issue we detect at this stage will not be fixed on the next reef (v18.2.1) as release code is frozen and it doesn't admit more PRs.  

No problem, it's already an improved situation compared to before. Nothing wrong with incrementally improving it further in a later release  :)

> please, can you attach your cluster spec?

I have stripped out resource allocations and placement information as that information does not add value here:
```
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/daemon-base@sha256:cb226bc79ccb47df9993ecd9da840db5b20eb27f8e4c383f029b5621ba316156
  dashboard:
    ssl: false
  network:
    connections:
      requireMsgr2: true
  storage:
    useAllNodes: false
    useAllDevices: false
    storageClassDeviceSets:
      - name: nvme-ssd
        count: 2
        portable: false
        encrypted: true
        volumeClaimTemplates:
          - spec:
              storageClassName: nvme-ssd
              resources:
                requests:
                  storage: 93Gi
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
      - name: sata-ssd
        count: 4
        portable: false
        encrypted: true
        volumeClaimTemplates:
          - spec:
              storageClassName: sata-ssd
              resources:
                requests:
                  storage: 931Gi
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
      - name: scsi-hdd
        count: 24
        portable: false
        encrypted: true
        volumeClaimTemplates:
          - spec:
              storageClassName: scsi-hdd
              resources:
                requests:
                  storage: 3726Gi
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
```

> As of the current logic we only list the configured disks from the section storageClassDeviceSets section, not all the available ones.  

That is what I expected to see as well but that did not seem to happen. As you can see in the cluster spec above, there's 30 total disks, split in sets of 2 (NVMe backed), 4 (SATA backed) and 24 (SAS backed) respectively. Only the last set of disks is shown.  

Ofc. the nodes themselves have more disks but I would not expect these to show up at all. They are not part of the cluster spec.

> Please, can you open an issue for this?

https://github.com/rook/rook/issues/13271

**Comment by rkachach** [comment] 2023-11-27 12:27
@Omar007 thank you very much

can you plz attach your mgr pod logs?

**Comment by rkachach** [comment] 2023-11-27 13:58
@Omar007 I think I found the problem. I created the image `docker.io/rkachach/ceph:reef-v1` which contains the latest from reef plus the fix candidate. Can you give it a try plz and let me know if that fixes the issue?

**Comment by rkachach** [comment] 2023-11-27 17:16
> It does! The disks of each device set are now shown. Looks like all 30 are present and accounted for in the correct places on the "Hosts" and "Physical Disks" tabs.
> 

Awesome, thank you @Omar007 :) .. let's keep this issue open as the feature is not fully implemented.

> ![screenshot_2023-11-27T16:14:00](https://private-user-images.githubusercontent.com/5380079/285936702-a5f78e45-6fd1-435b-8566-9f729d5cee90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDUxNzksIm5iZiI6MTcwMTEwNDg3OSwicGF0aCI6Ii81MzgwMDc5LzI4NTkzNjcwMi1hNWY3OGU0NS02ZmQxLTQzNWItODU2Ni05ZjcyOWQ1Y2VlOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMTcwNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzUxYzk2MjBhMjg4OWJlNmM5ZjAzZDkyNWRhNDJlNjkyNDI4MTllMDUwNGM1MWY2OGMyYzFmNDI2ZTgzMzgyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M4Cd4VAWaAZivdMRqnuasmiMzRXomEfstzMKXVfi2GQ)
> 
> Ofc. the other points still stand but those turned out to be separate things and those all have their own issues/tickets at this point I believe 🤔

I'll double check but I think we should be good. 

> 
> EDIT: all except the OSD running daemons count inconsistency I suppose. Should I make a separate item for that or mention/group it under #13271 as a more generic "Services tab (MDS/OSD) daemon state inconsistencies"?? 🤔

I think it's a different issue so I'd recommend creating a new ticket for it. In case after investigation we find that the issue is the same then we can just mark it as duplicate. For instance is seems a different issue.

> 
> EDIT2: just in case the empty columns are throwing you off, I'm assuming this is due to my set-up specifically so I hadn't mentioned it before; the information is actually available when using the "Devices" and "SMART" sections on the "Hosts" tab when I need it, e.g.: ![screenshot_2023-11-27T16:33:11](https://private-user-images.githubusercontent.com/5380079/285942432-4f340581-1207-4596-8f29-6b692fc36129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDUxNzksIm5iZiI6MTcwMTEwNDg3OSwicGF0aCI6Ii81MzgwMDc5LzI4NTk0MjQzMi00ZjM0MDU4MS0xMjA3LTQ1OTYtOGYyOS02YjY5MmZjMzYxMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMTcwNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVjMDg2YzkzOTdiMzVjYzM0NjFiZGM1MTE5MjEwODZjM2JmODc4NjRkM2RhMmZhMDRlMjlmYzU0MGUxNDQxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Oy8MVuv8AgraoyKUj45Ik915-eesVobtvRHa6IQWbUA) ![screenshot_2023-11-27T16:32:58](https://private-user-images.githubusercontent.com/5380079/285942453-eb19105f-9ff4-4a43-bfcc-d22636c2e620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDUxNzksIm5iZiI6MTcwMTEwNDg3OSwicGF0aCI6Ii81MzgwMDc5LzI4NTk0MjQ1My1lYjE5MTA1Zi05ZmY0LTRhNDMtYmZjYy1kMjI2MzZjMmU2MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMTcwNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ0ZjVlMzE5ZDY5Yjg5OGM1NDI1MTVmZjQyMGYwODNhNjkwMzg5YWFkYjU5OGU0ZDFmMjg5ZjAxOTI5ZmIzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NRM7FB0YQpWVC3NInyouX6npTfTf9c5-2IW7r8nBiRM)

Great, thanks for the update.

**Comment by Omar007** [comment] 2023-11-27 18:18
> I think it's a different issue so I'd recommend creating a new ticket for it.

https://github.com/rook/rook/issues/13278

**Comment by rkachach** [comment] 2023-11-29 13:42
@Omar007 I create an image that contain a fix candidate for the OSD and MDS issues you reported. The image is `docker.io/rkachach/ceph:reef-v3` 

Note: it doesn't contain the fix for the physical devices. It only contain the fix for the dashboard inconsistencies.

**Comment by Omar007** [comment] 2023-11-29 20:04
> It would be great if you can give it a try.

I did, looks good. See respective issues:

https://github.com/rook/rook/issues/13271#issuecomment-1832619803  
https://github.com/rook/rook/issues/13278#issuecomment-1832621289  

> Note1: I fixed another issue: basically the daemons the belongs to services were not being listed under the corresponding tab for mds, nfs and rgw. This listing only worked for mon, mgr and other services such as crash.

Seems good, I can see those 3 in their respective tables when expanding their service rows  :+1: 

> Note2: it doesn't contain the fix for the physical devices. It only contain the fix for the dashboard inconsistencies.

:ok_hand:

**Comment by rkachach** [comment] 2024-02-02 08:26
Fix is ready and should be available on the next ceph release.

**Comment by travisn** [comment] 2024-04-09 20:06
> Fix is ready and should be available on the next ceph release.

@rkachach In which releases can we expect it?

**Comment by rkachach** [comment] 2024-04-11 07:54
> > Fix is ready and should be available on the next ceph release.
> 
> @rkachach In which releases can we expect it?

It's already included but there's a BUG which was fixed by https://github.com/ceph/ceph/pull/54676. So in summary it should be available either with squid or the next reef release (because v18.2.2 didn't include the fix).

**Comment by Omar007** [comment] 2024-06-11 14:26
Bump to prevent closure pending release.

**Comment by rkachach** [comment] 2024-08-20 12:56
@Omar007 is sthis still an issue even after the last rook release (which recommends using `Ceph 18.2.4`) ?

**Comment by Omar007** [comment] 2024-08-20 13:48
Updated the cluster to rook 1.14.9 and ceph 18.2.4 and looks good. As mentioned before in https://github.com/rook/rook/issues/12858#issuecomment-1828154514 the columns are otherwise empty (I still assume due to it being a PVC based cluster) but the right amount is showing up now.  

As (some of) the information does seem to be available elsewhere (e.g. in the "Devices" and "Physical Disks" tab in the "Hosts" section within the dashboard), it would probably be a nice improvement if these columns could be (partly) populated but I'd say that is something for a new feature request  ;) 

Closing this one :+1:

**Closed** 2024-08-20 13:48 UTC
Labels: feature, ceph-dashboard

**Comment by rkachach** [comment] 2024-09-04 11:28
@Omar007 thank you very much for testing the changes and for the detailed feedback. Indeed, what you propose seems like a new-feature request. I'd highly recommend opening a ticket for that in Ceph Dashboard project :+1:
