### ISSUE TITLE
ceph (nautilus): OSDs crashloop due to pod memory environment variable settings when setting cluster resources

### ISSUE THREAD

**Issue by d-luu** [rook/rook#3180] opened 2019-05-15 15:31 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSDs crashlooping

**Expected behavior:**
OSDs running

**How to reproduce it (minimal and precise):**
* Setup filestore and set resource requests and limits for Rook components in cluster.yaml
* Set rook cross cluster related stuff namespace to rook-ceph-system and cluster components to rook-ceph (not sure if its needed)
* Build Rook 1.0 using update from: https://github.com/rook/rook/pull/3165 to fix the panic issue 
* Deploy Rook with Ceph v14.2.1-20190430

**Environment**:
* OS (e.g. from /etc/os-release): SUSE Linux Enterprise Server 12 SP3
* Kernel (e.g. `uname -a`): 4.4.162-94.72
* Cloud provider or hardware configuration: vSphere
* Rook version (use `rook version` inside of a Rook Pod): 1.0
* Kubernetes version (use `kubectl version`): 1.12.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Findings**:
* Mimic works fine as is
* Nautilus: OSDs crashloop...no logs are given in pod when this happens and describe deployment only mentions it not having enough available

**Workaround/notes**:
* OSD memory request/limits can be set but the POD_MEMORY_REQUEST and POD_MEMORY_LIMIT environment variable seem to only work when less than actual pod memory settings (or when node allocatable)
* OSD POD_MEMORY_REQUEST looks like it needs to be less than POD_MEMORY_LIMIT
* (may or may not affect things) pass empty resources to OSD provisioner in the code (this was because i was seeing different behavior in the operator logs)

Once the workarounds are done, the OSDs come up, but only seem to be stable for about 15 minutes or so before it starts crashlooping again.

**Comment by leseb** [comment] 2019-05-15 15:51
Dup of https://github.com/rook/rook/issues/3162?

**Comment by galexrt** [comment] 2019-05-15 15:55
@d-luu Please post the logs of the crashing OSDs and / or verify if you also get the segmentation fault error mentioned in #3162. Please close if it is the same error. Thanks!

**Comment by d-luu** [comment] 2019-05-15 16:04
The pods do not output any logs (even when using the previous -p flag) when crashlooping.

**Comment by leseb** [comment] 2019-05-15 16:11
@d-luu what about `docker logs` directly? same?

**Comment by d-luu** [comment] 2019-05-15 16:12
@leseb also empty

**Comment by d-luu** [comment] 2019-05-15 16:34
at the moment, for the nautilus filestore case at least, it seems as though removing both POD_MEMORY_REQUEST and POD_MEMORY_LIMIT environment variables brings up the OSD

I will be checking if it crashes or not but it seems to be lasting longer than the previous workaround I mentioned

**Comment by aquavitae** [comment] 2019-05-17 06:25
I'm seeing this issue too - and it does seem to be resolved by removing the POD_MEMORY_* envvars from the osd deployments. It doesn't seem like a great fix though since it looks like it needs to be a manual step after the osds have started up.

**Comment by d-luu** [comment] 2019-05-17 17:11
I will be making a PR to the code base soon to address it

**Comment by leseb** [comment] 2019-05-19 14:11
I can reproduce, it's a bug in Ceph, please wait.

**Comment by leseb** [comment] 2019-05-19 15:12
Fix proposed here: https://github.com/ceph/ceph/pull/28159, so we have to wait for 14.2.2.

**Comment by leseb** [comment] 2019-06-04 12:50
I'm closing this because dup of https://github.com/rook/rook/issues/3162

**Closed by leseb** 2019-06-04 12:50 UTC
Labels: bug
