### ISSUE TITLE
Upgrade operator sdk for csv generation and remove placeholder RGW role and role binding

### ISSUE THREAD

**Issue by travisn** [rook/rook#10141] opened 2022-04-22 16:14 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
A placeholder role and binding were added in #10108 for the new rook-ceph-rgw service account solely for the purposes of csv generation. If we update to the latest operator sdk v1.8 we can use a new flag for `--extra-service-accounts`, then we can remove the placeholder role and binding.  

**Expected behavior:**
Use the latest operator sdk for improved csv generation.

**Comment by Rakshith-R** [comment] 2022-04-28 14:10
Similar clusterrole and binding placeholder has been added for csi-nfs-nodeplugin here https://github.com/rook/rook/pull/10183

**Comment by BlaineEXE** [comment] 2022-08-30 16:39
I understand from @subhamkrai that there are a lot of pretty big changes caused by updating to a new version. This potentially stands to cause some issues for anything that relies on the upstream v1.10 release, and we've seen a lot of seemingly minor changes cause headaches for dependent entities. I would suggest that we work on this for just the master branch and let it go out with v1.11 to give us more time to fix issues that are likely to arise from any changes. 

We may as well also update to the very latest operator-sdk tooling version(s) as well. I poked at this briefly a long time ago, and the changes were substantial enough that I gave up and left it for a future exercise. 

I advised Subham that my strategy for updating would be to locally create an entirely new tooling path from scratch to modernize our old and very hacky CSV generation with the latest operator-sdk abilities. It might be easiest to swap out the CSV portions of our `make build` tooling with the new stuff, and get rid of the old rather than figuring out how to integrate new methods into the old scripts.

@travisn do you have other thoughts?

**Comment by travisn** [comment] 2022-08-30 16:47
The csv generation has mainly only been used for downstream, so perhaps we can learn what other projects are doing downstream as well since that's where we risk breaking something. 

Agreed that this work will target 1.11.

**Comment by JvGinkel** [comment] 2023-11-18 15:22
As this issue now is closed I'm not sure if we still need this? https://github.com/rook/rook/blob/master/deploy/examples/common.yaml#L14

```yaml
# TODO: remove this, once https://github.com/rook/rook/issues/10141
# is resolved.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-nodeplugin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
```

**Comment by travisn** [comment] 2023-11-20 18:49
> As this issue now is closed I'm not sure if we still need this https://github.com/rook/rook/blob/master/deploy/examples/common.yaml#L14

@Madhu-1 ?

**Comment by Rakshith-R** [comment] 2023-11-21 03:16
> > As this issue now is closed I'm not sure if we still need this https://github.com/rook/rook/blob/master/deploy/examples/common.yaml#L14
> 
> @Madhu-1 ?

We'll need it now with cephfs read affinity

**Comment by Rakshith-R** [comment] 2023-11-21 03:17
Reopened by mistake, closing

**Closed by Rakshith-R** 2023-11-21 03:17 UTC
Labels: bug
