### ISSUE TITLE
Daily CI smoke test suite against Ceph Master is failing when csi rbd provisioner tries to to delete an rbd image

### ISSUE THREAD

**Issue by travisn** [rook/rook#9679] opened 2022-01-28 18:41 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The [daily CI smoke test suite](https://github.com/travisn/rook/runs/4974651984?check_suite_focus=true) running against Ceph Master is failing. The [daily CI history](https://github.com/rook/rook/actions/workflows/daily-nightly-jobs.yml) shows it has been failing for the past 10 days.

The error is:
```
2022-01-28 00:58:02.762987 I | integrationTest: Waiting for PV "pvc-b778ef51-c420-4efc-b501-74f5ec21f02f" to have status "" with exists false
    ceph_base_block_test.go:363: 
        	Error Trace:	ceph_base_block_test.go:363
        	            				ceph_base_block_test.go:338
        	            				ceph_smoke_test.go:111
        	Error:      	Should be true
        	Test:       	TestCephSmokeSuite/TestBlockStorage_SmokeTest
```

The csi rbd provisioner log shows that the image is failing to be deleted because the image is not found. The error indicates the problem is that the `rbd` pool doesn't exist, but it's the `replicapool` where the image was created. The rook CI doesn't create the default `rbd` pool. 
```
I0128 00:55:37.836315       1 omap.go:87] ID: 37 Req-ID: 0001-0008-smoke-ns-0000000000000002-b57bd609-7fd4-11ec-8678-0242ac110009 got omap values: (pool="replicapool", namespace="", name="csi.volume.b57bd609-7fd4-11ec-8678-0242ac110009"): map[csi.imageid:5efd93a7a631 csi.imagename:csi-vol-b57bd609-7fd4-11ec-8678-0242ac110009 csi.volname:pvc-b778ef51-c420-4efc-b501-74f5ec21f02f csi.volume.owner:default]
I0128 00:55:37.848224       1 rbd_util.go:679] ID: 37 Req-ID: 0001-0008-smoke-ns-0000000000000002-b57bd609-7fd4-11ec-8678-0242ac110009 
rbd: adding task to remove image "replicapool/csi-vol-b57bd609-7fd4-11ec-8678-0242ac110009" with id "5efd93a7a631" from trash
E0128 00:55:37.856117       1 rbd_util.go:690] ID: 37 Req-ID: 0001-0008-smoke-ns-0000000000000002-b57bd609-7fd4-11ec-8678-0242ac110009 
failed to add task to delete rbd image: replicapool/csi-vol-b57bd609-7fd4-11ec-8678-0242ac110009, 
rados: ret=-2, No such file or directory: "[errno 2] RADOS object not found (error opening pool 'rbd')"
E0128 00:55:37.856189       1 utils.go:200] ID: 37 Req-ID: 0001-0008-smoke-ns-0000000000000002-b57bd609-7fd4-11ec-8678-0242ac110009 
GRPC error: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "[errno 2] RADOS object not found (error opening pool 'rbd')"
```

@idryomov Could there be a recent change in ceph master that caused the image removal to ignore the pool name?

**Expected behavior:**
Rook tests are expected to pass against Ceph master.

**Comment by idryomov** [comment] 2022-01-28 19:46
No, nothing that could cause something like that comes to mind.

Is `ceph --version` or `rbd --version` logged anywhere?  I couldn't find anything but the container digest and the history at https://quay.io/repository/ceph/daemon-base?tab=history doesn't go that far.

**Comment by travisn** [comment] 2022-01-28 20:28
The CSI driver version since 7 days ago is v3.5, which is based on Ceph v16.2.7. Prior that that update, we had the CSI version 3.4 and I believe its base Ceph image was v16.2.5. So this appears to be unrelated to the CSI version update since it started a few days before that. 
@Madhu-1 other thoughts?

**Comment by idryomov** [comment] 2022-01-28 20:45
I think I see the bug, but it's not a recent (as in a few days old) change.  It's getting late here, I'll confirm and report back tomorrow.

**Comment by idryomov** [comment] 2022-01-29 14:22
Addressed in https://github.com/ceph/ceph/pull/44834.

**Comment by Madhu-1** [comment] 2022-01-31 07:17
> The CSI driver version since 7 days ago is v3.5, which is based on Ceph v16.2.7. Prior that that update, we had the CSI version 3.4 and I believe its base Ceph image was v16.2.5. So this appears to be unrelated to the CSI version update since it started a few days before that. @Madhu-1 other thoughts?

@idryomov We haven't seen this in cephcsi CI as we test with released ceph versions. this is only with the ceph master?

**Comment by idryomov** [comment] 2022-01-31 07:26
Yes, only on master.  What isn't clear is that according to @travisn the CI job broke only 10 days ago -- the root cause is 11 months old.

**Comment by travisn** [comment] 2022-01-31 18:40
> Yes, only on master. What isn't clear is that according to @travisn the CI job broke only 10 days ago -- the root cause is 11 months old.

@idryomov Thanks for the quick fix! We will look forward to picking that up after it's merged to verify. I can't think what would have changed in the Rook tests recently either that would have caused the failure.

**Comment by idryomov** [comment] 2022-02-01 11:12
I have just merged it.

**Closed** 2022-04-09 20:02 UTC
Labels: bug, wontfix
