### ISSUE TITLE
mgr fails to start dashboard, prometheus on IPv6-disabled nodes

### ISSUE THREAD

**Issue by iMartyn** [rook/rook#3334] opened 2019-06-21 14:45 UTC
**Is this a bug report or feature request?**
* Bug Report

#2171 Provided a workaround for this issue but this codepath has been refactored away and now there is no way to set the listen IP in rook.

**Deviation from expected behavior:**

Ceph dashboard and prometheus modules fail to listen on pods that are scheduled on machines with IPv6 forcibly disabled.

**Expected behavior:**

Ceph dashboard and prometheus modules listen correctly

**How to reproduce it (minimal and precise):**
On a machine with IPv6 *disabled* install rook with ceph 14.1 or above.  The mgr pod will be created without an initcontainer and observe the error :
```
ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created
```
This is because listening on `::` is not acceptable on a machine with IPv6 disabled.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
* Kernel (e.g. `uname -a`): Linux aks-nodepool1-27848402-1 4.15.0-1045-azure #49-Ubuntu SMP Mon May 13 16:30:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Azure
* Rook version (use `rook version` inside of a Rook Pod): ` rook: v1.0.2`
* Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):`HEALTH_ERR 2 mgr modules have failed`

**Comment by iMartyn** [comment] 2019-06-21 15:42
Pinging @noahdesu Just so you're aware :-)

**Comment by iMartyn** [comment] 2019-06-24 09:04
IMO there is no need to in k8s ever listen on '::'.  Even on IPv6 enabled clusters, the idea is to be able to access external services via IPv6 and for Ingresses (sometimes) to listen on IPv6.  Internal to the cluster there should never be a need to listen on IPv6.  Therefore we should just use the initcontainer for all versions.

**Comment by iMartyn** [comment] 2019-06-24 09:05
Logs from an mgr restart here :
```
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  e: 'ceph-mgr'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  0: 'ceph-mgr'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  1: '--fsid=70a272ff-8de2-402c-b6b7-4c6d769a9e2a'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  2: '--keyring=/etc/ceph/keyring-store/keyring'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  3: '--log-to-stderr=true'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  4: '--err-to-stderr=true'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  5: '--mon-cluster-log-to-stderr=true'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  6: '--log-stderr-prefix=debug '
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  7: '--default-log-to-file=false'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  8: '--default-mon-cluster-log-to-file=false'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  9: '--mon-host=[v2:10.0.87.72:3300,v1:10.0.87.72:6789],[v2:10.0.226.118:3300,v1:10.0.226.118:6789],[v2:10.0.229.46:3300,v1:10.0.229.46:6789]'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  10: '--mon-initial-members=c,a,b'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  11: '--id=a'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  12: '--foreground'
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn respawning with exe /usr/bin/ceph-mgr
debug 2019-06-24 07:43:24.950 7f89da72d700  1 mgr respawn  exe_path /proc/self/exe
debug 2019-06-24 07:43:24.994 7ff27ba47b80  0 ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable), process ceph-mgr, pid 1
debug 2019-06-24 07:43:24.994 7ff27ba47b80  0 pidfile_write: ignore empty --pid-file
debug 2019-06-24 07:43:25.022 7ff27ba47b80  1 mgr[py] Loading python module 'ansible'
debug 2019-06-24 07:43:25.094 7ff27ba47b80  1 mgr[py] Loading python module 'balancer'
debug 2019-06-24 07:43:25.110 7ff27ba47b80  1 mgr[py] Loading python module 'crash'
debug 2019-06-24 07:43:25.122 7ff27ba47b80  1 mgr[py] Loading python module 'dashboard'
debug 2019-06-24 07:43:25.262 7ff27ba47b80  1 mgr[py] Loading python module 'deepsea'
debug 2019-06-24 07:43:25.350 7ff27ba47b80  1 mgr[py] Loading python module 'devicehealth'
debug 2019-06-24 07:43:25.362 7ff27ba47b80  1 mgr[py] Loading python module 'diskprediction_local'
debug 2019-06-24 07:43:25.378 7ff27ba47b80  1 mgr[py] Loading python module 'influx'
debug 2019-06-24 07:43:25.390 7ff27ba47b80  1 mgr[py] Loading python module 'insights'
debug 2019-06-24 07:43:25.402 7ff27ba47b80  1 mgr[py] Loading python module 'iostat'
debug 2019-06-24 07:43:25.414 7ff27ba47b80  1 mgr[py] Loading python module 'localpool'
debug 2019-06-24 07:43:25.430 7ff27ba47b80  1 mgr[py] Loading python module 'orchestrator_cli'
debug 2019-06-24 07:43:25.442 7ff27ba47b80  1 mgr[py] Loading python module 'pg_autoscaler'
debug 2019-06-24 07:43:25.478 7ff27ba47b80  1 mgr[py] Loading python module 'progress'
debug 2019-06-24 07:43:25.502 7ff27ba47b80  1 mgr[py] Loading python module 'prometheus'
debug 2019-06-24 07:43:25.586 7ff27ba47b80  1 mgr[py] Loading python module 'rbd_support'
debug 2019-06-24 07:43:25.598 7ff27ba47b80  1 mgr[py] Loading python module 'restful'
debug 2019-06-24 07:43:25.722 7ff27ba47b80  1 mgr[py] Loading python module 'rook'
debug 2019-06-24 07:43:26.030 7ff27ba47b80  1 mgr[py] Loading python module 'selftest'
debug 2019-06-24 07:43:26.046 7ff27ba47b80  1 mgr[py] Loading python module 'status'
debug 2019-06-24 07:43:26.066 7ff27ba47b80  1 mgr[py] Loading python module 'telegraf'
debug 2019-06-24 07:43:26.086 7ff27ba47b80  1 mgr[py] Loading python module 'telemetry'
debug 2019-06-24 07:43:26.226 7ff27ba47b80  1 mgr[py] Loading python module 'test_orchestrator'
debug 2019-06-24 07:43:26.258 7ff27ba47b80  1 mgr[py] Loading python module 'volumes'
debug 2019-06-24 07:43:26.294 7ff27ba47b80  1 mgr[py] Loading python module 'zabbix'
debug 2019-06-24 07:43:26.310 7ff2672a6700  0 ms_deliver_dispatch: unhandled message 0x557e89008a00 mon_map magic: 0 v1 from mon.1 v2:10.0.229.46:3300/0
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  e: 'ceph-mgr'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  0: 'ceph-mgr'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  1: '--fsid=70a272ff-8de2-402c-b6b7-4c6d769a9e2a'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  2: '--keyring=/etc/ceph/keyring-store/keyring'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  3: '--log-to-stderr=true'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  4: '--err-to-stderr=true'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  5: '--mon-cluster-log-to-stderr=true'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  6: '--log-stderr-prefix=debug '
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  7: '--default-log-to-file=false'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  8: '--default-mon-cluster-log-to-file=false'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  9: '--mon-host=[v2:10.0.87.72:3300,v1:10.0.87.72:6789],[v2:10.0.226.118:3300,v1:10.0.226.118:6789],[v2:10.0.229.46:3300,v1:10.0.229.46:6789]'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  10: '--mon-initial-members=c,a,b'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  11: '--id=a'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  12: '--foreground'
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn respawning with exe /usr/bin/ceph-mgr
debug 2019-06-24 07:43:26.310 7ff2672a6700  1 mgr respawn  exe_path /proc/self/exe
debug 2019-06-24 07:43:26.354 7f5ebf056b80  0 ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable), process ceph-mgr, pid 1
debug 2019-06-24 07:43:26.354 7f5ebf056b80  0 pidfile_write: ignore empty --pid-file
debug 2019-06-24 07:43:26.382 7f5ebf056b80  1 mgr[py] Loading python module 'ansible'
debug 2019-06-24 07:43:26.454 7f5ebf056b80  1 mgr[py] Loading python module 'balancer'
debug 2019-06-24 07:43:26.470 7f5ebf056b80  1 mgr[py] Loading python module 'crash'
debug 2019-06-24 07:43:26.482 7f5ebf056b80  1 mgr[py] Loading python module 'dashboard'
debug 2019-06-24 07:43:26.614 7f5ebf056b80  1 mgr[py] Loading python module 'deepsea'
debug 2019-06-24 07:43:26.694 7f5ebf056b80  1 mgr[py] Loading python module 'devicehealth'
debug 2019-06-24 07:43:26.706 7f5ebf056b80  1 mgr[py] Loading python module 'diskprediction_local'
debug 2019-06-24 07:43:26.718 7f5ebf056b80  1 mgr[py] Loading python module 'influx'
debug 2019-06-24 07:43:26.730 7f5ebf056b80  1 mgr[py] Loading python module 'insights'
debug 2019-06-24 07:43:26.742 7f5ebf056b80  1 mgr[py] Loading python module 'iostat'
debug 2019-06-24 07:43:26.754 7f5ebf056b80  1 mgr[py] Loading python module 'localpool'
debug 2019-06-24 07:43:26.766 7f5ebf056b80  1 mgr[py] Loading python module 'orchestrator_cli'
debug 2019-06-24 07:43:26.778 7f5ebf056b80  1 mgr[py] Loading python module 'pg_autoscaler'
debug 2019-06-24 07:43:26.814 7f5ebf056b80  1 mgr[py] Loading python module 'progress'
debug 2019-06-24 07:43:26.838 7f5ebf056b80  1 mgr[py] Loading python module 'prometheus'
debug 2019-06-24 07:43:26.922 7f5ebf056b80  1 mgr[py] Loading python module 'rbd_support'
debug 2019-06-24 07:43:26.934 7f5ebf056b80  1 mgr[py] Loading python module 'restful'
debug 2019-06-24 07:43:27.058 7f5ebf056b80  1 mgr[py] Loading python module 'rook'
debug 2019-06-24 07:43:27.358 7f5ebf056b80  1 mgr[py] Loading python module 'selftest'
debug 2019-06-24 07:43:27.374 7f5ebf056b80  1 mgr[py] Loading python module 'status'
debug 2019-06-24 07:43:27.394 7f5ebf056b80  1 mgr[py] Loading python module 'telegraf'
debug 2019-06-24 07:43:27.414 7f5ebf056b80  1 mgr[py] Loading python module 'telemetry'
debug 2019-06-24 07:43:27.554 7f5ebf056b80  1 mgr[py] Loading python module 'test_orchestrator'
debug 2019-06-24 07:43:27.586 7f5ebf056b80  1 mgr[py] Loading python module 'volumes'
debug 2019-06-24 07:43:27.622 7f5ebf056b80  1 mgr[py] Loading python module 'zabbix'
debug 2019-06-24 07:43:27.638 7f5eaa8b5700  0 ms_deliver_dispatch: unhandled message 0x561d6a1faa00 mon_map magic: 0 v1 from mon.1 v2:10.0.229.46:3300/0
debug 2019-06-24 07:43:28.370 7f5eaa8b5700  1 mgr handle_mgr_map Activating!
debug 2019-06-24 07:43:28.370 7f5eaa8b5700  1 mgr handle_mgr_map I am now activating
debug 2019-06-24 07:43:28.378 7f5e9992e700  1 mgr load Constructed class from module: balancer
debug 2019-06-24 07:43:28.378 7f5e9992e700  1 mgr load Constructed class from module: crash
debug 2019-06-24 07:43:28.378 7f5e9992e700  1 mgr load Constructed class from module: dashboard
debug 2019-06-24 07:43:28.378 7f5e9992e700  1 mgr load Constructed class from module: devicehealth
debug 2019-06-24 07:43:28.378 7f5e9992e700  1 mgr load Constructed class from module: iostat
debug 2019-06-24 07:43:28.378 7f5e9992e700  1 mgr load Constructed class from module: orchestrator_cli
debug 2019-06-24 07:43:28.382 7f5e9992e700  1 mgr load Constructed class from module: progress
debug 2019-06-24 07:43:28.382 7f5e9992e700  1 mgr load Constructed class from module: prometheus
debug 2019-06-24 07:43:28.382 7f5e9992e700  1 mgr load Constructed class from module: restful
debug 2019-06-24 07:43:28.382 7f5e9992e700  1 mgr load Constructed class from module: rook
debug 2019-06-24 07:43:28.382 7f5e9992e700  1 mgr load Constructed class from module: status
debug 2019-06-24 07:43:28.386 7f5e9992e700  1 mgr load Constructed class from module: volumes
debug 2019-06-24 07:43:28.386 7f5e938e2700  1 mgr[restful] server not running: no certificate configured
[24/Jun/2019:07:43:28] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[24/Jun/2019:07:43:28] ENGINE Started monitor thread '_TimeoutMonitor'.
[24/Jun/2019:07:43:28] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created

debug 2019-06-24 07:43:28.398 7f5e8de84700  0 mgr[prometheus] [24/Jun/2019:07:43:28] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created

[24/Jun/2019:07:43:28] ENGINE Bus STOPPING
[24/Jun/2019:07:43:28] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::', 9283)) already shut down
[24/Jun/2019:07:43:28] ENGINE Stopped thread '_TimeoutMonitor'.
[24/Jun/2019:07:43:28] ENGINE Bus STOPPED
[24/Jun/2019:07:43:28] ENGINE Bus EXITING
[24/Jun/2019:07:43:28] ENGINE Bus EXITED
Exception in thread HTTPServer Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created

[24/Jun/2019:07:43:28] ENGINE Bus STARTING
[24/Jun/2019:07:43:28] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f5e9d76a990>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 174, in start
    self.wait()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 208, in wait
    raise self.interrupt
error: No socket could be created

debug 2019-06-24 07:43:28.498 7f5e940e3700  0 mgr[prometheus] [24/Jun/2019:07:43:28] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f5e9d76a990>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 174, in start
    self.wait()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 208, in wait
    raise self.interrupt
error: No socket could be created

[24/Jun/2019:07:43:28] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: error('No socket could be created',)

debug 2019-06-24 07:43:28.498 7f5e940e3700  0 mgr[prometheus] [24/Jun/2019:07:43:28] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: error('No socket could be created',)

[24/Jun/2019:07:43:28] ENGINE Bus STOPPING
[24/Jun/2019:07:43:28] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::', 9283)) already shut down
[24/Jun/2019:07:43:28] ENGINE No thread running for None.
[24/Jun/2019:07:43:28] ENGINE Bus STOPPED
[24/Jun/2019:07:43:28] ENGINE Bus EXITING
[24/Jun/2019:07:43:28] ENGINE Bus EXITED
debug 2019-06-24 07:43:28.498 7f5e940e3700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'prometheus' while running on mgr.a: error('No socket could be created',)
debug 2019-06-24 07:43:28.498 7f5e940e3700 -1 prometheus.serve:
debug 2019-06-24 07:43:28.498 7f5e940e3700 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/prometheus/module.py", line 1022, in serve
    cherrypy.engine.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 250, in start
    raise e_info
ChannelFailures: error('No socket could be created',)

[24/Jun/2019:07:43:28] ENGINE Started monitor thread '_TimeoutMonitor'.
[24/Jun/2019:07:43:28] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created

debug 2019-06-24 07:43:28.522 7f5e8a7f7700  0 mgr[dashboard] [24/Jun/2019:07:43:28] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created

[24/Jun/2019:07:43:28] ENGINE Bus STOPPING
[24/Jun/2019:07:43:28] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::', 8443)) already shut down
[24/Jun/2019:07:43:28] ENGINE Stopped thread '_TimeoutMonitor'.
[24/Jun/2019:07:43:28] ENGINE Bus STOPPED
[24/Jun/2019:07:43:28] ENGINE Bus EXITING
[24/Jun/2019:07:43:28] ENGINE Bus EXITED
Exception in thread HTTPServer Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 187, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1824, in start
    raise socket.error(msg)
error: No socket could be created

[24/Jun/2019:07:43:28] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f5ea043e1d0>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 174, in start
    self.wait()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 208, in wait
    raise self.interrupt
error: No socket could be created

debug 2019-06-24 07:43:28.618 7f5e96928700  0 mgr[dashboard] [24/Jun/2019:07:43:28] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f5ea043e1d0>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 174, in start
    self.wait()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 208, in wait
    raise self.interrupt
error: No socket could be created

[24/Jun/2019:07:43:28] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: error('No socket could be created',)

[24/Jun/2019:07:43:28] ENGINE Bus STOPPING
debug 2019-06-24 07:43:28.618 7f5e96928700  0 mgr[dashboard] [24/Jun/2019:07:43:28] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: error('No socket could be created',)

[24/Jun/2019:07:43:28] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('::', 8443)) already shut down
[24/Jun/2019:07:43:28] ENGINE No thread running for None.
[24/Jun/2019:07:43:28] ENGINE Bus STOPPED
[24/Jun/2019:07:43:28] ENGINE Bus EXITING
[24/Jun/2019:07:43:28] ENGINE Bus EXITED
debug 2019-06-24 07:43:28.618 7f5e96928700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'dashboard' while running on mgr.a: error('No socket could be created',)
debug 2019-06-24 07:43:28.618 7f5e96928700 -1 dashboard.serve:
debug 2019-06-24 07:43:28.618 7f5e96928700 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/module.py", line 340, in serve
    cherrypy.engine.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 250, in start
    raise e_info
ChannelFailures: error('No socket could be created',)

debug 2019-06-24 07:43:29.390 7f5e9912d700  0 log_channel(cluster) log [DBG] : pgmap v2: 300 pgs: 300 active+clean; 2.2 KiB data, 67 GiB used, 436 GiB / 503 GiB avail
debug 2019-06-24 07:43:30.370 7f5e9812b700  0 log_channel(cluster) log [DBG] : pgmap v3: 300 pgs: 300 active+clean; 2.2 KiB data, 67 GiB used, 436 GiB / 503 GiB avail
debug 2019-06-24 07:43:32.370 7f5e9812b700  0 log_channel(cluster) log [DBG] : pgmap v4: 300 pgs: 300 active+clean; 2.2 KiB data, 67 GiB used, 436 GiB / 503 GiB avail
debug 2019-06-24 07:43:34.374 7f5e9812b700  0 log_channel(cluster) log [DBG] : pgmap v5: 300 pgs: 300 active+clean; 2.2 KiB data, 67 GiB used, 436 GiB / 503 GiB avail
```

**Comment by iMartyn** [comment] 2019-06-25 11:57
As a further point to help prioritize the fix for this - On Azure AKS this makes it impossible to use prometheus to create alerting for rook as their clusters are ipv6 disabled (at least in 50% of the nodes - one AZ).

**Comment by noahdesu** [comment] 2019-06-26 21:54
@iMartyn do you have the exact ceph version that you are running? I think this is a duplicate issue that we fixed in upstream Ceph https://github.com/ceph/ceph/pull/26635. In order to have that fix you'd need to be using a version of Ceph with the fix. We should have also accounted for that delayed release of Ceph in Rook by checking versions, but there could a bug there, or perhaps this is an entirely new issue!

**Comment by iMartyn** [comment] 2019-06-27 13:15
@noahdesu We're running ceph ceph/ceph:v14.2.1-20190430
I saw the fix to ceph, it's not a fix, it fixes the validation error, but still tries to listen on `::` which is invalid, so the module crashes.

**Comment by iMartyn** [comment] 2019-06-27 15:15
@noahdesu https://github.com/ceph/ceph/pull/28246/commits/38e7083301f4d5e419f4c7c1fb596d529d3ab83c actually fixes the problem but is currently only in `master`.

**Comment by noahdesu** [comment] 2019-06-27 15:52
Oh, great. This must be an issue of non-standarization. Removing the validation (and leaving "::") had fixed the error for multiple users that had ipv6 disabled. I'll look to see what we can do as a workaround for this since it will be a while before that fix that works for your environment makes its way down into the backports and containers.

**Comment by noahdesu** [comment] 2019-08-12 20:06
@iMartyn backported into Nautilus https://github.com/ceph/ceph/commit/3fdf6d0b810fb90ba612055553b357ca62108fc4 should be in 14.2.3

**Comment by noahdesu** [comment] 2019-08-12 20:06
CC @jmolmo

**Comment by jmolmo** [comment] 2019-09-05 15:02
It was not possible for me to reproduce the bug with my environment (see env below) , but i have checked and prepared a workaround that will alleviate the problem until the [fix](https://github.com/ceph/ceph/commit/38e7083301f4d5e419f4c7c1fb596d529d3ab83c) (only in master) will reach existent installations.

@iMartyn: the workaround we proposed you (#2171) must work, the problem you saw is because the _prometheus_ module also uses Cherry.py as http server and also uses the problematic default address ":::". Using the following procedure the problem will be solved

### Workaround for other environments where dashboard/prometheus  modules do not start when ipv6 disabled:

**1. [Connect](https://rook.github.io/docs/rook/master/ceph-toolbox.htm) to the cluster toolbox :**

`# kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') bash`


**2. Set the dashboard server address to "0.0.0.0"**
`# ceph config set mgr mgr/dashboard/server_addr 0.0.0.0`

**3. Set the prometheus mgr module server address to "0.0.0.0"**
`# ceph config set mgr mgr/prometheus/server_addr  0.0.0.0`

**4. Verify the settings values:**

```
# ceph config dump | grep dashboard
mgr          advanced mgr/dashboard/server_addr         0.0.0.0         *  
  mgr.a      advanced mgr/dashboard/server_port         8445            *  
  mgr.a      advanced mgr/dashboard/ssl                 true            *  
  mgr.a      advanced mgr/dashboard/ssl_server_port     8445            *  
  mgr.a      advanced mgr/dashboard/url_prefix          /ceph-dashboard * 

# ceph config dump | grep prom
mgr          advanced mgr/prometheus/server_addr        0.0.0.0         * 
```

**5. Restart the modules**

```
# ceph mgr module disable dashboard
# ceph mgr module disable prometheus
# ceph mgr module enable dashboard
# ceph mgr module enable prometheus
```

**6. Check the manager logs (in the manager pod)**

```
...
[05/Sep/2019:14:33:51] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.
[05/Sep/2019:14:33:51] ENGINE Bus STARTING
[05/Sep/2019:14:33:51] ENGINE Started monitor thread '_TimeoutMonitor'.
[05/Sep/2019:14:33:52] ENGINE Started monitor thread '_TimeoutMonitor'.
[05/Sep/2019:14:33:52] ENGINE Serving on 0.0.0.0:9283
[05/Sep/2019:14:33:52] ENGINE Bus STARTED
[05/Sep/2019:14:33:52] ENGINE Serving on 0.0.0.0:8445
[05/Sep/2019:14:33:52] ENGINE Bus STARTED

```


env:
**Environment where i cannot reproduce the issue:**
k8 Nodes:
CentOS Linux release 7.6.1810 (Core)

With ipv6 disabled:

```
[vagrant@node3 ~]$ cat /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

[vagrant@node3 ~]$ ip addr show | grep net6
```
Ceph version:
ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)

**Comment by suvl** [comment] 2019-12-10 16:40
@jmolmo 's workaround worked for me just now.

**Closed** 2020-03-17 00:50 UTC
Labels: bug, wontfix
