### ISSUE TITLE
Provide multi-arch Container image for CephCSI

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#4753] opened 2020-01-27 18:30 UTC
We now have a amd64 Docker image `quay.io/cephcsi/cephcsi:v2.0.0-arm64` but Quay current doesn't support multi-arch images, so once they do it would be nice to build the image as multi-arch (amd64,arm64, and others if possible)

**Comment by Madhu-1** [comment] 2020-04-27 05:09
This is fixed in cephcsi , closing

**Comment by jaredallard** [comment] 2020-05-01 05:08
> This is fixed in cephcsi , closing

Is there a certain version this is fixed in?

**Comment by Madhu-1** [comment] 2020-05-01 05:09
> > This is fixed in cephcsi , closing
> 
> Is there a certain version this is fixed in?

its available from cephcsi v2.0.0 onwards images are available at https://quay.io/repository/cephcsi/cephcsi

**Comment by jaredallard** [comment] 2020-05-01 06:17
> https://quay.io/repository/cephcsi/cephcsi

Thanks a bunch for the quick reply... for someone who hasn't worked with this project much yet.... would there be specific things I'd need to do to get rook-ceph v1.3.2 to have these fixes to get arm64 working? Right now it's not working for me, so just trying to figure it out.

**Comment by Madhu-1** [comment] 2020-05-01 06:20
https://github.com/rook/rook/issues/4051 might help you to run rook on arm64

**Comment by billimek** [comment] 2020-05-01 10:56
I suggest that this issue raised by @onedr0p isn't solved by cephcsi v2.0.0 onward.  cephcsi 2.0.0 onward currently provides _separate_ arm64-based images.  @onedr0p can you clarify the ask?  I wonder if we prematurely closed this issue?

I believe that the issue is for a "multi-arch" image containing the ability to run in different architectures (e.g. arm64 & amd64).  This is different than an image tagged for arm64 and a different image tagged for amd64.  See this [issue](https://github.com/ceph/ceph-csi/pull/707#issuecomment-572025092) for some background.

@jaredallard to give you a straight answer (as far as I can tell), as things stand right now there is no solution for running rook & ceph CSI in a mixed amd64 & arm64 environment:

* The cephcsi 2.0.0+ images are not muilti-arch (there are separate arm64-tagged images)
* The other required images to properly consume ceph CSI workloads are not currently available in arm64 variants, let alone multi-arch variants.  These images are:
  * quay.io/k8scsi/csi-provisioner
  * quay.io/k8scsi/csi-snapshotter
  * quay.io/k8scsi/csi-attacher
  * possibly more?

**Comment by onedr0p** [comment] 2020-05-01 13:04
I would like multi-arch images, which I think is possible with quay, it just takes a little more effort compared to dockerhub. 

@Madhu-1 can you please re-open this issue?

**Comment by travisn** [comment] 2020-05-01 14:26
While there isn't a fix needed for this in Rook, reopening to track the issue in the CSI driver.

**Comment by Madhu-1** [comment] 2020-05-01 14:37
Quay doesn't support multi arch as of now. We need to wait till support is available in quay.io

**Comment by jaredallard** [comment] 2020-05-01 16:27
@Madhu-1 Am I mistaken, or do they not support it already? https://thenewstack.io/red-hats-quay-3-container-supports-multiple-architectures/

(I admittedly haven't looked into Quay in a long time so I could be off base)

**Comment by onedr0p** [comment] 2020-05-01 17:13
@Madhu-1 they sure do support multi-arch images now, take a look at cert-manager repo here: https://quay.io/repository/jetstack/cert-manager-controller?tab=tags

**Comment by Madhu-1** [comment] 2020-05-04 05:09
> @Madhu-1 they sure do support multi-arch images now, take a look at the cert-manager repo here: https://quay.io/repository/jetstack/cert-manager-controller?tab=tags

is this a free account?at least when I tried last time, quay free account doesn't support multi-architecture images

**Comment by Madhu-1** [comment] 2020-05-04 05:10
closing this as a duplicate of https://github.com/rook/rook/issues/4051, lets track it in one issue

**Closed by Madhu-1** 2020-05-04 05:10 UTC
Labels: feature
