### ISSUE TITLE
CI Integration tests should gather logs and archive them on test failues. 

### ISSUE THREAD

**Issue by dangula** [rook/rook#931] opened 2017-08-21 19:19 UTC
We need to gather logs and archive them on integration test failures to help with troubleshooting and investigating.

**Comment by jbw976** [comment] 2017-08-21 20:19
This looks like a dupe of #897

**Comment by jbw976** [comment] 2017-08-23 17:25
This should help with how to collect the logs: https://github.com/rook/rook/blob/master/Documentation/advanced-configuration.md#log-collection

**Closed** 2017-08-24 21:02 UTC
Labels: test
