### ISSUE TITLE
Unable to mount volume

### ISSUE THREAD

**Issue by r-moiseev** [rook/rook#1790] opened 2018-06-14 09:11 UTC
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
I have deployed rook-operator with helm chart and very basic cluster and block-storage pool from doc.
When i created PVC, PV was created, but can not be mounted to a pod. I have this:
```
Unable to mount volumes for pod ***": timeout expired waiting for volumes to attach/mount for pod "***". list of unattached/unmounted volumes=[data]
```
I can see that volume was successfully created in operator logs

What you expected to happen:
Volume mounted to a pod

How to reproduce it (minimal and precise):
Deploy rook-alpha/rook with helm
Create Cluster as described in quickstart
Create Blockstorage Pool as described in quickstart
Create SC for this Pool
Create PVC 

**Environment**:
* OS ubuntu 15.04
* Kernel (e.g. `uname -a`): Linux dev1-master-0 4.13.0-1018-azure #21-Ubuntu SMP Thu May 17 13:58:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: AzureRM
* Rook version (use `rook version` inside of a Rook Pod): v0.7.1
* Kubernetes version (use `kubectl version`): 0.9.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray on Azure
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by zhwenh** [comment] 2018-06-14 11:37
Support rbd-nbd for mounting operations on Ceph rbd volumes

**What this PR does / why we need it**: 
This PR improves Ceph RBD support by allowing the pkg/volume/rbd to use the rbd-nbd client. This client is based on the common and broadly adopted (librados) librbd library, and it is being actively developed and maintained&nbsp;as part of the ceph upstream code base, unlike krbd.

**Which issue(s) this PR Fixes**: 
Fixes #32266

**Special notes for your reviewer**:
rbd-nbd will be used for Ceph rbd volumes if rbd fails.

Some inspiration was pulled from these PRs #38936 & #55866.

**Test Description**: Tested against a k8s cluster with centos/7 as the host os. rbd-nbd installed from package rbd-nbd-10.2.3.rpm.

Tested:
1. Fall-through to current rbd map/unmap when no rbd-nbd tools are found.
2. Map/Unmap through rbd-nbd.
3. Detecting image already mapped to a nbd device and skipping additional mapping.
4. Detecting image already mapped to a rbd device and skipping additional mapping through nbd.
5. Unmap in hosts having mixed rbd and nbd devices (caused by fall-throughs for some images).
6. Map failure in rbd-nbd due to missing image.
7. Map failure in rbd-nbd due to unreachable mon.
8. Fall-through to current rbd map when rbd-nbd map fails for any reason.


**Release note**:

```release-note
K8s supports rbd-nbd for Ceph rbd volume mounts.
```

**Comment by zhwenh** [comment] 2018-06-14 11:39
Add support for accessing Ceph RBD with the rbd-nbd client 

Add support for the recently emerged rbd-nbd feature-rich client to improve support for Ceph RBD in Kubernetes.

Background

Kubernetes already offers support for Ceph RBD based on the krbd kernel client. Unfortunately, due to obvious reasons, krbd can't use the librbd user-space space library that gets most of the development focus. This caused a feature gap when compared to VM-based environments.

At the moment krbd lacks exclusive locking infrastructure, image management facilities and multi-DC support (remote backups!). The detailed list can be obtained by comparing the definitions of RBD_FEATURES_ALL macro in librbd and kernel. While there are efforts on partially closing the gap (patches waiting for merge), librbd continuously gets new items like consistency groups or fencing improvements.

Beside the feature gap krbd exhibits additional drawback. Being entirely kernel space impacts fault-tolerance as any kernel panic affects a whole node -- not only a single Pod using RBD storage. According to the rbd-nbd pull request the reliability, especially on non-x86 platforms, was one of the driving factors behind the new client.

Those issues can be addressed by employing rbd-nbd -- a thin adapter (858 lines of code in Jewel) between NBD subsystem of Linux kernel and librbd.

The primary concern about rbd-nbd was performance. The authors claimed it's comparable to krbd. Together with Intel we verified those claims. Tests on typical HW where Ceph is deployed (SSDs for journals, HDDs as main storage) showed rbd-nbd delivers 70-80% of krbd performance. Though, we don't consider the raw performance as a deciding factor. Even fastest RBD client wouldn't be a solution-of-choice for performance critical use cases like RDBMS hosting.

Proposal

We would like to propose incorporating support for rbd-nbd. The integration can be accomplished in multiple ways.

Extending the current in-tree plugin for RBD to use krbd or rbd-nbd depending on a configuration parameter. This would assure the excellent commonality. On the other hand we see differences where this might become an issue.
The krbd-based plugin employs the advisory locking mechanism to provide fencing at the cost of HA -- in case of node crash a manual intervention is required. However, serving images marked to use exclusive locking feature would result in employing the same underlying infrastructure twice. At the moment this isn’t an issue because krbd simply doesn’t support exclusive lock. However, when it finally gets it, RBD images created with Ceph’s default capabilities set will be inaccessible in read-write mode. This was the reason why a similar solution has been refused in QEMU.
Another problem we see are additional dependencies. After fencing capability is integrated directly in krbd, the dependency on user-space /usr/bin/rbd CLI utility can be removed. The helper is not required for mapping RBD images as the kernel interface may be used directly by the plugin.
Dedicated in-tree plugin. Offers greatest flexibility in adopting new features (like dynamic provisioning of Persistent Volumes).
Dedicated FlexVolume plugin. Simple but limited. Bringing support for e.g. dynamic provisioning would require extensive changes in FlexVolume’s interfaces.
At the moment the option # 2 looks most promising. Though we stay entirely open for the discussion.

Future work

Performance

rbd-nbd efficiency suffers from extra context switches and extensive memory copying between kernel and user-space boundaries. Although we can do nothing with the first factor, the second can be improved for large blocks transfers. Linux kernel has facilities for zero-copy page-aligned memory transfers between kernel and application via the combination of splice and vmsplice system calls.

Fencing

Actually Mirantis is working on bringing fencing to librbd on the top of exclusive lock infrastructure. This would allow to move from the flawed advisory lock mechanism that is currently used by rbd storage plugin.

Dynamic provisioning

Currently RBD images must be created ahead by a cluster administrator. We see possibility to implement the dynamic provisioning for RBD in the future.

**Comment by galexrt** [comment] 2018-06-14 11:39
@r-moiseev Can you check your kubelet logs for volume mount errors such as `no volume plugin matched`?
Is your kubelet configured to use the same flexvolume directory as the Rook operator? See https://rook.io/docs/rook/v0.7/flexvolume.html.

**Comment by galexrt** [comment] 2018-06-14 11:42
@zhwenh Seems to be a Kubernetes issue/PR description you have posted. Could you elaborate on your comments? I don't see how this is directly related to this issue.

**Comment by r-moiseev** [comment] 2018-06-14 12:17
I have this error in kubelet:
```
Error processing volume "data" for pod "drone-drone-server-865fbf7fbd-njjt9_ci(8a659735-6f13-11e8-9190-000d3a22a084)": error processing PVC "ci"/"drone-drone": failed to fetch PVC ci/drone-drone from API server. err=persistentvolumeclaims "drone-drone" not found
```

**Comment by galexrt** [comment] 2018-06-14 12:28
@r-moiseev The `no volume plugin matched` means that the kubelet can't find the Rook volume plugin in the flexvolume directory.
Can you check that your flexvolume plugin dir path contains a directory named `rook.io~rook`. Check that the Rook operator has the `FLEXVOLUME_DIR_PATH`  environment variable set to the same path as the kubelet flexvolume plugin dir path. In both cases try deleting the rook-agent DaemonSet and restarting the Rook operator Pod and see if after the rook-agent DaemonSet has been created a gain the error has gone away.

**Comment by r-moiseev** [comment] 2018-06-14 12:41
@galexrt rook-operator has no `FLEXVOLUME_DIR_PATH` at all

**Comment by galexrt** [comment] 2018-06-14 12:44
@r-moiseev But your kubelet nodes have the flexvolume dir flag set? If so, delete the `rook-agent` DaemonSet and add the `FLEXVOLUME_DIR_PATH` env var to the operator.
See https://rook.io/docs/rook/v0.7/flexvolume.html.

**Comment by r-moiseev** [comment] 2018-06-14 13:06
Manually added this variable to helm chart, redeployed operator, recreated agent, and its working now.

Thank you.

**Comment by galexrt** [comment] 2018-06-14 13:23
@r-moiseev To document here the helm chart also has an option for it https://rook.io/docs/rook/v0.7/helm-operator.html#configuration `agent.flexVolumeDirPath`.

**Comment by aziemski** [comment] 2018-07-05 00:11
is there workaround for k8s v1.11.0?

**Comment by allen13** [comment] 2018-07-23 02:36
I'm running on openshift-enterprise 3.9.33 with rook v0.8 and I'm having this issue even when the FLEXVOLUME_DIR_PATH is set.

`journalctl -f -u atomic-openshift-node`

`Jul 22 19:28:18 ocp-06 atomic-openshift-node[2438]: E0722 19:28:18.930350    2462 desired_state_of_world_populator.go:289] Failed to add volume "alertmanager-main-db" (specName: "pvc-f282459a-8e1f-11e8-b0ef-0800270fad8c") for pod "f2844a0f-8e1f-11e8-b0ef-0800270fad8c" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "pvc-f282459a-8e1f-11e8-b0ef-0800270fad8c" err=no volume plugin matched`

```
$ ls /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
ceph.rook.io~rook  ceph.rook.io~rook-ceph-system  rook.io~rook  rook.io~rook-ceph-system
```

I've deleted everything and started from scratch just to make everthing got restarted including the agent deamonsets.

Also, I've made sure to follow every single step exactly from here https://github.com/rook/rook/blob/master/Documentation/openshift.md

**Comment by allen13** [comment] 2018-07-27 17:22
I was able to resolve this by changing the FLEXVOLUME_DIR_PATH var to /etc/origin/kubelet-plugins/volume/exec . 

Apparently, the type of openshift install you use affects where the plugin path resides: https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_flex_volume.html

**Comment by jbw976** [comment] 2018-07-27 19:14
This speaks to the big disappointment of no longer being able to "discover" the right path the Kubelet will be looking in for flexvolumes, as discussed in https://github.com/rook/rook/issues/1330#issuecomment-369346395.  We cannot do it programmatically from the agent, but I'm wondering if we can improve our documentation to help users figure out where the Kubelet will be looking, so that they know what exactly to set `FLEXVOLUME_DIR_PATH` to in operator.yaml.

**Comment by galexrt** [comment] 2018-07-28 10:47
@jbw976 I'm working on an overhaul of the flexvolume docs which will also add OpenShift doc links and readd Atomic.

**Comment by galexrt** [comment] 2018-08-07 15:40
The docs have been overhauled, please give it a look here: https://rook.io/docs/rook/v0.8/flexvolume.html.
I'm closing this for now as I believe the docs have been updated to better the user experience.
Please create a new issue if you think the flexvolume docs can be further improved. Thank you!

**Closed by galexrt** 2018-08-07 15:40 UTC
Labels: ceph, docs, flexvolume

**Comment by ToroNZ** [comment] 2018-08-09 20:03
Future travelers:

I had all these symptoms but in my case it was resolved by restarting the kubelet.
K8s 1.11
Fedora 28

I followed an old guide for k8s 1.7 https://github.com/rook/rook/blob/master/Documentation/common-issues.md#kubelet-restart

**Comment by wallnerryan** [comment] 2018-10-19 19:09
thanks @ToroNZ  on kubernetes 1.12 and rook/ceph 0.8 and had to restart kubelet as well on 1/3 workers. All plugin directories were there otherwise, and restart fixed a stuck `ContainerCreating`

**Comment by Harold2017** [comment] 2019-05-20 04:22
same issue, but with `wrong fs type`. i have to change fstype from `xfs` to `ext4`  to sucecssfully mount.
