### ISSUE TITLE
bluefs _allocate unable to allocate 0x90000 on bdev 1

### ISSUE THREAD

**Issue by osaffer** [rook/rook#9885] opened 2022-03-10 13:44 UTC
ceph-version: 16.2.6-0
rook-version: v1.7.4

Hi,

One nice morning that all of my osd pod were crashed, except one by node.
When I check OSD log I can see : 
ebug     -7> 2022-03-10T09:59:05.158+0000 7ff21a9db080  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1646906345165107, "job": 1, "event": "recovery_started", "log_files": [17870]}
debug     -6> 2022-03-10T09:59:05.158+0000 7ff21a9db080  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #17870 mode 2
debug     -5> 2022-03-10T09:59:05.430+0000 7ff21a9db080  3 rocksdb: [le/block_based/filter_policy.cc:584] Using legacy Bloom filter with high (20) bits/key. Dramatic filter space and/or accuracy improvement is available with format_version>=5.
debug     -4> 2022-03-10T09:59:05.434+0000 7ff21a9db080  1 bluefs _allocate unable to allocate 0x90000 on bdev 1, allocator name block, allocator type hybrid, capacity 0x4ffc00000, block size 0x10000, free 0x0, fragmentation 0, allocated 0x0
debug     -3> 2022-03-10T09:59:05.434+0000 7ff21a9db080 -1 bluefs _allocate allocation failed, needed 0x80cbb
debug     -2> 2022-03-10T09:59:05.434+0000 7ff21a9db080 -1 bluefs _flush_range allocated: 0x0 offset: 0x0 length: 0x80cbb
debug     -1> 2022-03-10T09:59:05.442+0000 7ff21a9db080 -1 /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.6/rpm/el8/BUILD/ceph-16.2.6/src/os/bluestore/BlueFS.cc: In function 'int BlueFS::_flush_range(BlueFS::FileWriter*, uint64_t, uint64_t)' thread 7ff21a9db080 time 2022-03-10T09:59:05.440116+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.6/rpm/el8/BUILD/ceph-16.2.6/src/os/bluestore/BlueFS.cc: 2768: ceph_abort_msg("bluefs enospc")

After some researches, I noticed that some people got more or less the same issue:  
They talked about a workaround : 
[osd]
 bluestore_allocator = bitmap

Can you tell me where I can set this parameter?

I have also added some new disk on each nodes

Thank you very much

**Comment by travisn** [comment] 2022-03-10 17:23
Yes, that command in the toolbox should work. Another way to set it is in the [ceph.conf overrides](https://rook.github.io/docs/rook/v1.8/ceph-advanced-configuration.html#custom-cephconf-settings).

**Comment by osaffer** [comment] 2022-03-10 17:30
I have added disk, I thought rebalanced could help, but no 

Many of the OSD are down.

Do you have any idea ?

ceph health detail
HEALTH_ERR 1 filesystem is degraded; 1 MDSs report slow metadata IOs; mons aa,z are low on available space; 2/314120 objects unfound (0.001%); noup,nodown flag(s) set; 8 osds down; 5 nearfull osd(s); 1 scrub errors; Reduced data availability: 460 pgs inactive, 51 pgs down; Low space hindering backfill (add storage if this doesn't resolve itself): 29 pgs backfill_toofull; Possible data damage: 2 pgs recovery_unfound, 1 pg inconsistent; Degraded data redundancy: 257006/940204 objects degraded (27.335%), 254 pgs degraded, 306 pgs undersized; 7 pool(s) nearfull; 1 pool(s) have no replicas configured; 107 daemons have recently crashed; 81 slow ops, oldest one blocked for 11536 sec, daemons [osd.14,osd.20,osd.21,osd.22,osd.23,osd.24] have slow ops.
[WRN] FS_DEGRADED: 1 filesystem is degraded
    fs postgresfs is degraded
[WRN] MDS_SLOW_METADATA_IO: 1 MDSs report slow metadata IOs
    mds.postgresfs-b(mds.0): 1 slow metadata IOs are blocked > 30 secs, oldest blocked for 11544 secs
[WRN] MON_DISK_LOW: mons aa,z are low on available space
    mon.z has 18% avail
    mon.aa has 23% avail
[WRN] OBJECT_UNFOUND: 2/314120 objects unfound (0.001%)
    pg 4.18 has 1 unfound objects
    pg 4.1a has 1 unfound objects
[WRN] OSDMAP_FLAGS: noup,nodown flag(s) set
[WRN] OSD_DOWN: 8 osds down
    osd.0 (root=default,host=adakub2-do-gov-lu) is down
    osd.2 (root=default,host=adakub1-do-gov-lu) is down
    osd.6 (root=default,host=adakub1-do-gov-lu) is down
    osd.7 (root=default,host=adakub2-do-gov-lu) is down
    osd.8 (root=default,host=adakub3-do-gov-lu) is down
    osd.11 (root=default,host=adakub5-do-gov-lu) is down
    osd.16 (root=default,host=adakub4-do-gov-lu) is down
    osd.17 (root=default,host=adakub4-do-gov-lu) is down
[WRN] OSD_NEARFULL: 5 nearfull osd(s)
    osd.12 is near full
    osd.13 is near full
    osd.14 is near full
    osd.18 is near full
    osd.19 is near full
[ERR] OSD_SCRUB_ERRORS: 1 scrub errors
[WRN] PG_AVAILABILITY: Reduced data availability: 460 pgs inactive, 51 pgs down
    pg 2.30 is stuck inactive for 6m, current state unknown, last acting []
    pg 2.33 is stuck inactive for 6m, current state unknown, last acting []
    pg 2.36 is stuck inactive for 36h, current state undersized+degraded+peered, last acting [12]
    pg 2.37 is stuck inactive for 34h, current state undersized+degraded+peered, last acting [12]
    pg 2.38 is stuck inactive for 6m, current state unknown, last acting []
    pg 2.3b is stuck inactive for 6m, current state unknown, last acting []
    pg 2.3d is stuck inactive for 36h, current state undersized+degraded+peered, last acting [13]
    pg 3.31 is down, acting [24]
    pg 3.32 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.34 is down, acting [19,20]
    pg 3.35 is stuck inactive for 34h, current state undersized+degraded+peered, last acting [12]
    pg 3.36 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.39 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.80 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.81 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.84 is stuck inactive for 36h, current state undersized+degraded+peered, last acting [13]
    pg 3.86 is stuck inactive for 40h, current state undersized+degraded+peered, last acting [12]
    pg 3.87 is down, acting [21,19]
    pg 3.88 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.8c is stuck inactive for 36h, current state undersized+degraded+peered, last acting [19]
    pg 3.8d is stuck inactive for 6m, current state unknown, last acting []
    pg 3.8f is stuck inactive for 36h, current state undersized+degraded+peered, last acting [14]
    pg 3.93 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.96 is down, acting [20,13]
    pg 3.97 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.9e is down, acting [19]
    pg 3.9f is stuck inactive for 36h, current state undersized+degraded+peered, last acting [14]
    pg 3.a0 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.a3 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.a5 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.a8 is down, acting [21]
    pg 3.ac is stuck inactive for 39h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [13]
    pg 3.ad is stuck inactive for 36h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [14]
    pg 3.ae is stuck inactive for 6m, current state unknown, last acting []
    pg 3.b0 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.b1 is stuck inactive for 36h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [18]
    pg 3.b2 is stuck inactive for 6m, current state unknown, last acting []
    pg 3.b4 is stuck inactive for 42h, current state undersized+degraded+peered, last acting [19]
    pg 3.b6 is down, acting [19]
    pg 3.b7 is stuck inactive for 42h, current state undersized+degraded+peered, last acting [19]
    pg 3.bd is stuck inactive for 6m, current state unknown, last acting []
    pg 8.25 is stuck inactive for 6m, current state unknown, last acting []
    pg 8.30 is stuck inactive for 6m, current state unknown, last acting []
    pg 8.33 is stuck inactive for 6m, current state unknown, last acting []
    pg 8.37 is stuck inactive for 6m, current state unknown, last acting []
    pg 8.38 is stuck inactive for 6m, current state unknown, last acting []
    pg 8.3b is stuck inactive for 6m, current state unknown, last acting []
    pg 8.3c is stuck inactive for 6m, current state unknown, last acting []
    pg 8.3d is stuck inactive for 6m, current state unknown, last acting []
    pg 8.3e is stuck inactive for 6m, current state unknown, last acting []
    pg 8.3f is stuck inactive for 6m, current state unknown, last acting []
[WRN] PG_BACKFILL_FULL: Low space hindering backfill (add storage if this doesn't resolve itself): 29 pgs backfill_toofull
    pg 3.1a is undersized+degraded+remapped+backfill_wait+backfill_toofull+peered, acting [12]
    pg 3.1c is undersized+degraded+remapped+backfill_toofull+peered, acting [13]
    pg 3.2e is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.48 is undersized+degraded+remapped+backfill_toofull+peered, acting [18]
    pg 3.4c is active+undersized+degraded+remapped+backfill_toofull, acting [19,18]
    pg 3.53 is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.77 is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.ac is undersized+degraded+remapped+backfill_toofull+peered, acting [13]
    pg 3.ad is undersized+degraded+remapped+backfill_toofull+peered, acting [14]
    pg 3.b1 is undersized+degraded+remapped+backfill_toofull+peered, acting [18]
    pg 3.c6 is undersized+degraded+remapped+backfill_wait+backfill_toofull+peered, acting [12]
    pg 3.cf is active+undersized+degraded+remapped+backfill_toofull, acting [18,13]
    pg 3.d6 is active+undersized+degraded+remapped+backfill_toofull, acting [13,18]
    pg 3.e6 is undersized+degraded+remapped+backfill_toofull+peered, acting [14]
    pg 3.103 is undersized+degraded+remapped+backfill_toofull+peered, acting [18]
    pg 3.107 is undersized+degraded+remapped+backfill_toofull+peered, acting [14]
    pg 3.10f is active+undersized+degraded+remapped+backfill_toofull, acting [13,18]
    pg 3.11a is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.121 is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.126 is active+undersized+degraded+remapped+backfill_toofull, acting [18,13]
    pg 3.148 is undersized+degraded+remapped+backfill_toofull+peered, acting [18]
    pg 3.152 is undersized+degraded+remapped+backfill_toofull+peered, acting [14]
    pg 3.158 is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.182 is undersized+degraded+remapped+backfill_toofull+peered, acting [13]
    pg 3.183 is undersized+degraded+remapped+backfill_toofull+peered, acting [19]
    pg 3.184 is undersized+degraded+remapped+backfill_toofull+peered, acting [14]
    pg 3.1c4 is active+undersized+degraded+remapped+backfill_toofull, acting [13,14]
    pg 3.1df is active+undersized+degraded+remapped+backfill_toofull, acting [19,13]
    pg 3.1fe is active+undersized+degraded+remapped+backfill_toofull, acting [18,12]
[ERR] PG_DAMAGED: Possible data damage: 2 pgs recovery_unfound, 1 pg inconsistent
    pg 4.18 is active+recovery_unfound+undersized+degraded+remapped, acting [13,23], 1 unfound
    pg 4.1a is active+recovery_unfound+degraded+remapped, acting [23,24,18], 1 unfound
    pg 8.48 is active+clean+inconsistent, acting [14]
[WRN] PG_DEGRADED: Degraded data redundancy: 257006/940204 objects degraded (27.335%), 254 pgs degraded, 306 pgs undersized
    pg 2.26 is active+undersized+degraded, acting [22,12]
    pg 2.27 is stuck undersized for 3h, current state active+undersized+remapped, last acting [24,12]
    pg 2.28 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [14]
    pg 2.2c is stuck undersized for 3h, current state active+undersized+remapped, last acting [24,19]
    pg 2.2d is stuck undersized for 3h, current state undersized+degraded+peered, last acting [14]
    pg 2.2f is stuck undersized for 3h, current state active+undersized+degraded, last acting [12,22]
    pg 2.34 is stuck undersized for 3h, current state active+undersized+degraded, last acting [24,12]
    pg 2.36 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [12]
    pg 2.37 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [12]
    pg 2.3a is stuck undersized for 3h, current state active+undersized+degraded, last acting [12,19]
    pg 2.3d is stuck undersized for 3h, current state undersized+degraded+peered, last acting [13]
    pg 3.2c is stuck undersized for 3h, current state active+undersized+degraded, last acting [19,13]
    pg 3.2d is stuck undersized for 3h, current state active+undersized+degraded, last acting [13,19]
    pg 3.2e is stuck undersized for 3h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [19]
    pg 3.2f is stuck undersized for 3h, current state undersized+degraded+peered, last acting [18]
    pg 3.30 is stuck undersized for 81m, current state active+undersized+degraded, last acting [14,21]
    pg 3.33 is stuck undersized for 77m, current state active+undersized+degraded, last acting [13,20]
    pg 3.35 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [12]
    pg 3.3c is stuck undersized for 2h, current state active+undersized+degraded, last acting [12,23]
    pg 3.82 is stuck undersized for 3h, current state active+undersized+degraded, last acting [20,18]
    pg 3.84 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [13]
    pg 3.85 is stuck undersized for 83m, current state active+undersized+degraded, last acting [14,20]
    pg 3.86 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [12]
    pg 3.8a is stuck undersized for 3h, current state active+undersized+degraded, last acting [19,13]
    pg 3.8b is stuck undersized for 3h, current state active+undersized+degraded, last acting [14,19]
    pg 3.8c is stuck undersized for 3h, current state undersized+degraded+peered, last acting [19]
    pg 3.8e is stuck undersized for 89m, current state active+undersized+remapped, last acting [22,14]
    pg 3.8f is stuck undersized for 3h, current state undersized+degraded+peered, last acting [14]
    pg 3.91 is stuck undersized for 87m, current state active+undersized+degraded, last acting [19,20]
    pg 3.92 is stuck undersized for 108m, current state active+undersized+degraded, last acting [19,20]
    pg 3.94 is stuck undersized for 3h, current state active+undersized+degraded, last acting [13,12]
    pg 3.98 is stuck undersized for 2h, current state active+undersized+degraded, last acting [12,22]
    pg 3.9c is stuck undersized for 3h, current state active+undersized+degraded, last acting [12,14]
    pg 3.9f is stuck undersized for 3h, current state undersized+degraded+peered, last acting [14]
    pg 3.a4 is stuck undersized for 31m, current state active+undersized+degraded, last acting [14,23]
    pg 3.a6 is stuck undersized for 3h, current state active+undersized+degraded, last acting [13,19]
    pg 3.a7 is stuck undersized for 2h, current state active+undersized+degraded, last acting [12,22]
    pg 3.a9 is stuck undersized for 3h, current state active+undersized+degraded, last acting [18,19]
    pg 3.ab is stuck undersized for 3h, current state active+undersized+degraded, last acting [14,19]
    pg 3.ac is stuck undersized for 3h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [13]
    pg 3.ad is stuck undersized for 3h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [14]
    pg 3.af is stuck undersized for 29m, current state active+undersized+degraded, last acting [14,24]
    pg 3.b1 is stuck undersized for 3h, current state undersized+degraded+remapped+backfill_toofull+peered, last acting [18]
    pg 3.b3 is stuck undersized for 3h, current state active+undersized+degraded, last acting [19,12]
    pg 3.b4 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [19]
    pg 3.b5 is stuck undersized for 96m, current state active+undersized+degraded, last acting [19,20]
    pg 3.b7 is stuck undersized for 3h, current state undersized+degraded+peered, last acting [19]
    pg 3.b8 is stuck undersized for 3h, current state active+undersized+degraded, last acting [18,12]
    pg 3.ba is stuck undersized for 3h, current state active+undersized+degraded, last acting [13,18]
    pg 3.bc is stuck undersized for 41m, current state active+undersized+degraded, last acting [13,24]
    pg 3.bf is stuck undersized for 29m, current state active+undersized+degraded, last acting [23,13]
[WRN] POOL_NEARFULL: 7 pool(s) nearfull
    pool 'device_health_metrics' is nearfull
    pool 'postgresfs-metadata' is nearfull
    pool 'postgresfs-data0' is nearfull
    pool 'kasten' is nearfull
    pool 'replicated-metadata-pool' is nearfull
    pool 'ec-data-pool' is nearfull
    pool 'replicapool' is nearfull
[WRN] POOL_NO_REDUNDANCY: 1 pool(s) have no replicas configured
    pool 'replicapool' has no replicas configured
[WRN] RECENT_CRASH: 107 daemons have recently crashed
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:08:55.455991Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:08:59.481943Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:09:21.913985Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:09:51.875101Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:10:48.987078Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:13:00.912860Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:15:52.124031Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:21:02.146165Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:26:20.210456Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:31:29.732832Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:36:34.183155Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:42:04.885070Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:47:31.909163Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:52:43.127810Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-08T23:57:54.151466Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-08T23:58:36.317819Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-08T23:58:55.731023Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-08T23:59:26.763089Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-09T00:00:14.173814Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-09T00:02:58.135836Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-09T00:04:38.642419Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-09T00:08:07.904989Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-09T00:13:17.136007Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-09T00:15:05.736004Z
    osd.10 crashed on host rook-ceph-osd-10-54c89559f7-mrdln at 2022-03-09T00:18:24.899076Z
    osd.4 crashed on host rook-ceph-osd-4-5b857df594-n867l at 2022-03-09T00:20:10.403294Z
    osd.5 crashed on host rook-ceph-osd-5-6db86dc99f-2p28r at 2022-03-09T00:20:57.627027Z
    osd.5 crashed on host rook-ceph-osd-5-6db86dc99f-2p28r at 2022-03-09T00:21:01.820004Z
    osd.5 crashed on host rook-ceph-osd-5-6db86dc99f-2p28r at 2022-03-09T00:21:18.909466Z
    osd.5 crashed on host rook-ceph-osd-5-6db86dc99f-2p28r at 2022-03-09T00:21:51.695160Z
    and 77 more
[WRN] SLOW_OPS: 81 slow ops, oldest one blocked for 11536 sec, daemons [osd.14,osd.20,osd.21,osd.22,osd.23,osd.24] have slow ops.

**Comment by osaffer** [comment] 2022-03-10 17:32
debug     -9> 2022-03-10T09:59:05.158+0000 7ff21a9db080  4 rocksdb: [version_set.cc:4568] Recovered from manifest file:db/MANIFEST-013853 succeeded,manifest_file_number is 13853, next_file_number is 17873, last_sequence is 1730541083, log_number is 17870,prev_log_number is 0,max_column_family is 0,min_log_number_to_keep is 0

debug     -8> 2022-03-10T09:59:05.158+0000 7ff21a9db080  4 rocksdb: [version_set.cc:4577] Column family [default] (ID 0), log number is 17870

debug     -7> 2022-03-10T09:59:05.158+0000 7ff21a9db080  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1646906345165107, "job": 1, "event": "recovery_started", "log_files": [17870]}
debug     -6> 2022-03-10T09:59:05.158+0000 7ff21a9db080  4 rocksdb: [db_impl/db_impl_open.cc:760] Recovering log #17870 mode 2
debug     -5> 2022-03-10T09:59:05.430+0000 7ff21a9db080  3 rocksdb: [le/block_based/filter_policy.cc:584] Using legacy Bloom filter with high (20) bits/key. Dramatic filter space and/or accuracy improvement is available with format_version>=5.
debug     -4> 2022-03-10T09:59:05.434+0000 7ff21a9db080  1 bluefs _allocate unable to allocate 0x90000 on bdev 1, allocator name block, allocator type hybrid, capacity 0x4ffc00000, block size 0x10000, free 0x0, fragmentation 0, allocated 0x0
debug     -3> 2022-03-10T09:59:05.434+0000 7ff21a9db080 -1 bluefs _allocate allocation failed, needed 0x80cbb
debug     -2> 2022-03-10T09:59:05.434+0000 7ff21a9db080 -1 bluefs _flush_range allocated: 0x0 offset: 0x0 length: 0x80cbb
debug     -1> 2022-03-10T09:59:05.442+0000 7ff21a9db080 -1 /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.6/rpm/el8/BUILD/ceph-16.2.6/src/os/bluestore/BlueFS.cc: In function 'int BlueFS::_flush_range(BlueFS::FileWriter*, uint64_t, uint64_t)' thread 7ff21a9db080 time 2022-03-10T09:59:05.440116+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.6/rpm/el8/BUILD/ceph-16.2.6/src/os/bluestore/BlueFS.cc: 2768: ceph_abort_msg("bluefs enospc")

 ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
 1: (ceph::__ceph_abort(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe5) [0x5582d93c0c8c]
 2: (BlueFS::_flush_range(BlueFS::FileWriter*, unsigned long, unsigned long)+0x1131) [0x5582d9ab7901]
 3: (BlueFS::_flush(BlueFS::FileWriter*, bool, bool*)+0x90) [0x5582d9ab7be0]
 4: (BlueFS::_flush(BlueFS::FileWriter*, bool, std::unique_lock<std::mutex>&)+0x32) [0x5582d9ac8cf2]
 5: (BlueRocksWritableFile::Append(rocksdb::Slice const&)+0x11b) [0x5582d9ae132b]
 6: (rocksdb::LegacyWritableFileWrapper::Append(rocksdb::Slice const&, rocksdb::IOOptions const&, rocksdb::IODebugContext*)+0x1f) [0x5582d9f73acf]
 7: (rocksdb::WritableFileWriter::WriteBuffered(char const*, unsigned long)+0x58a) [0x5582da08581a]
 8: (rocksdb::WritableFileWriter::Append(rocksdb::Slice const&)+0x2d0) [0x5582da086c70]
 9: (rocksdb::BlockBasedTableBuilder::WriteRawBlock(rocksdb::Slice const&, rocksdb::CompressionType, rocksdb::BlockHandle*, bool)+0xb6) [0x5582da1a2416]
 10: (rocksdb::BlockBasedTableBuilder::WriteBlock(rocksdb::Slice const&, rocksdb::BlockHandle*, bool)+0x26c) [0x5582da1a2d5c]
 11: (rocksdb::BlockBasedTableBuilder::WriteBlock(rocksdb::BlockBuilder*, rocksdb::BlockHandle*, bool)+0x3c) [0x5582da1a347c]
 12: (rocksdb::BlockBasedTableBuilder::Flush()+0x6d) [0x5582da1a350d]
 13: (rocksdb::BlockBasedTableBuilder::Add(rocksdb::Slice const&, rocksdb::Slice const&)+0x2b8) [0x5582da1a6978]
 14: (rocksdb::BuildTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::Env*, rocksdb::FileSystem*, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::FileOptions const&, rocksdb::TableCache*, rocksdb::InternalIteratorBase<rocksdb::Slice>*, std::vector<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> >, std::allocator<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> > > >, rocksdb::FileMetaData*, rocksdb::InternalKeyComparator const&, std::vector<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::allocator<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> >, unsigned long, rocksdb::SnapshotChecker*, rocksdb::CompressionType, unsigned long, rocksdb::CompressionOptions const&, bool, rocksdb::InternalStats*, rocksdb::TableFileCreationReason, rocksdb::EventLogger*, int, rocksdb::Env::IOPriority, rocksdb::TableProperties*, int, unsigned long, unsigned long, rocksdb::Env::WriteLifeTimeHint, unsigned long)+0xa45) [0x5582da1513d5]
 15: (rocksdb::DBImpl::WriteLevel0TableForRecovery(int, rocksdb::ColumnFamilyData*, rocksdb::MemTable*, rocksdb::VersionEdit*)+0xcf5) [0x5582d9fb6415]
 16: (rocksdb::DBImpl::RecoverLogFiles(std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long*, bool, bool*)+0x1c2e) [0x5582d9fb8b4e]
 17: (rocksdb::DBImpl::Recover(std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, bool, bool, bool, unsigned long*)+0xae8) [0x5582d9fb9ea8]
 18: (rocksdb::DBImpl::Open(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**, bool, bool)+0x59d) [0x5582d9fb3bcd]
 19: (rocksdb::DB::Open(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**)+0x15) [0x5582d9fb4f65]
 20: (RocksDBStore::do_open(std::ostream&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x10c1) [0x5582d9f2cec1]
 21: (BlueStore::_open_db(bool, bool, bool)+0x948) [0x5582d99b24d8]
 22: (BlueStore::_open_db_and_around(bool, bool)+0x2f7) [0x5582d9a1c657]
 23: (BlueStore::_mount()+0x204) [0x5582d9a1f514]
 24: (OSD::init()+0x380) [0x5582d94f4a10]
 25: main()
                                                                                                                                                                                                                            1545,88       57%

**Comment by osaffer** [comment] 2022-03-11 14:08
Hi,

It has been fixed.
1. Extend disk
2. resize pvresize /dev/sdX
3. pvdisplay -m to find the disk associated
4. lvextend -L +10G /dev/mapper/ceph--eda319c5--cce0--4a33--90d1--9ecf950676f5-osd--data--08884bac--6bac--4ae5--8a28--cdc43de1b85e

When done, put a sleep inside the pod 
Edit osd deployment, change command ceph-osd to 
command:
- sh
- -c
- sleep 10000
Open session inside osd pod
ceph-bluestore-tool bluefs-bdev-expand --path /var/lib/ceph/osd/ceph-X
parted
edit osd deployment put back ceph-osd

Then OSD should be green again

**Comment by BlaineEXE** [comment] 2022-03-16 19:23
Closing this since it seems resolved.

**Closed by BlaineEXE** 2022-03-16 19:23 UTC
Labels: bug

**Comment by harrykas** [comment] 2022-09-21 08:10
@osaffer I've encountered the same issue and your plan works, thank you very much.
Just want to ask - what the exact reason of this and how to prevent it to happen again?

**Comment by osaffer** [comment] 2022-09-21 20:23
Some OSD were full If I remember well ... I would say, monitor your OSD :D 
I have enabled prometheus and I monitor with Grafana

**Comment by harrykas** [comment] 2022-09-22 06:29
@osaffer hehe, you're right, that ceph instance was full. It is for development and another team supports it so I have no monitoring for it. Yet :)
Thank you!

**Comment by osaffer** [comment] 2022-09-22 08:01
> @osaffer hehe, you're right, that ceph instance was full. It is for development and another team supports it so I have no monitoring for it. Yet :) Thank you!

You are welcome ... my environment is also a development one so , I had not configured any monitoring.
But thanks to the problems, we acquire good knowledge :D

**Comment by thenamehasbeentake** [comment] 2023-10-13 07:59
`https://tracker.ceph.com/issues/53466`
We encountered the same problem. Add bluefs_shared_alloc_size=4096 to our ceph.conf for the OSDs, and the osd can be restored temporarily.

**Comment by microyahoo** [comment] 2023-11-03 10:07
The issue is fixed in https://github.com/ceph/ceph/pull/48854, 
and related issues:
https://tracker.ceph.com/issues/53899
https://tracker.ceph.com/issues/53466
