### ISSUE TITLE
Can Rook operator monitor all namespaces pvc creation.

### ISSUE THREAD

**Issue by citywander** [rook/rook#782] opened 2017-07-03 10:24 UTC
I run rook operator in "default" namespace and create MariaDB in resource namespace. I found bind pvc error.
Whether I have to install operator in each namespace? Or some configuration to make operator monitor all namespaces?

**Comment by travisn** [comment] 2017-07-04 12:45
@citywander i believe you're hitting #475. Can check if copying the secret to your namespace fixes the issue?

**Comment by citywander** [comment] 2017-07-23 00:32
Yes, thanks.

2017-07-04 5:45 GMT-07:00 Travis Nielsen <notifications@github.com>:

**Comment by bassam** [comment] 2017-08-04 15:47
duplicate of #475. tracking there.

**Closed by bassam** 2017-08-04 15:47 UTC
