### ISSUE TITLE
Dashboard - cannot create bucket - InvalidLocationConstraint

### ISSUE THREAD

**Issue by peter-poki** [rook/rook#6210] opened 2020-09-02 14:15 UTC
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When creating bucket with s3cmd or mc client, **bucket is created.**
But when creating bucket **in dashboard, it fails** with code 400 and message "InvalidLocationConstraint"

`
{"detail": "RGW REST API failed request with status code 400\n(b'{\"Code\":\"InvalidLocationConstraint\",\"Message\":\"The specified location-constr'\n b'aint is not valid\",\"BucketName\":\"tst01\",\"RequestId\":\"tx00000000000000010cda3'\n b'-005f4fa675-30219-s3\",\"HostId\":\"30219-s3-s3\"}')", "component": "rgw"}
`

![image](https://user-images.githubusercontent.com/22402252/91994019-62cf6f80-ed36-11ea-971b-55577d89992e.png)

**Expected behavior:**
Bucket is created via dasboard.

**How to reproduce it (minimal and precise):**
Standard deployment of cluster and object storage.

**File(s) to submit**:
RGW Logs
`

debug 2020-09-02T14:17:18.096+0000 7f5bac0a0700  1 ====== starting new request req=0x7f5b0013c8a0 =====
debug 2020-09-02T14:17:18.097+0000 7f5bac0a0700  1 ====== req done req=0x7f5b0013c8a0 op status=0 http_status=200 latency=0.001000111s ======
debug 2020-09-02T14:17:18.360+0000 7f5bb20ac700  1 ====== starting new request req=0x7f5afffb98a0 =====
debug 2020-09-02T14:17:18.388+0000 7f5bb20ac700  1 ====== req done req=0x7f5afffb98a0 op status=0 http_status=200 latency=0.028003110s ======
debug 2020-09-02T14:17:20.293+0000 7f5b3f7c7700  1 ====== starting new request req=0x7f5affcb38a0 =====
debug 2020-09-02T14:17:20.295+0000 7f5b3f7c7700  0 req 1102320 0.002000222s s3:create_bucket location constraint (default) can't be found.
debug 2020-09-02T14:17:20.295+0000 7f5b3f7c7700  1 ====== req done req=0x7f5affcb38a0 op status=-2208 http_status=400 latency=0.002000222s ======
debug 2020-09-02T14:17:18.893+0000 7f7baa5e8700  1 ====== starting new request req=0x7f7ab6df58a0 =====
debug 2020-09-02T14:17:18.893+0000 7f7baa5e8700  1 ====== req done req=0x7f7ab6df58a0 op status=0 http_status=200 latency=0s ======
debug 2020-09-02T14:17:22.870+0000 7f5c311aa700  0 WARNING: RGWRados::log_usage(): user name empty (bucket=), skipping
debug 2020-09-02T14:17:22.870+0000 7f5c311aa700  0 WARNING: RGWRados::log_usage(): user name empty (bucket=tst01), skipping
debug 2020-09-02T14:17:23.563+0000 7f5b60809700  1 ====== starting new request req=0x7f5b0003a8a0 =====
debug 2020-09-02T14:17:23.593+0000 7f5b60809700  1 ====== req done req=0x7f5b0003a8a0 op status=0 http_status=200 latency=0.029003221s ======
debug 2020-09-02T14:17:20.552+0000 7f7b38d05700  1 ====== starting new request req=0x7f7ab65e58a0 =====
debug 2020-09-02T14:17:20.567+0000 7f7b38d05700  1 ====== req done req=0x7f7ab65e58a0 op status=0 http_status=200 latency=0.015001249s ======
debug 2020-09-02T14:17:20.648+0000 7f7be7e63700  0 WARNING: RGWRados::log_usage(): user name empty (bucket=), skipping
debug 2020-09-02T14:17:28.096+0000 7f5b67817700  1 ====== starting new request req=0x7f5b0013c8a0 =====
debug 2020-09-02T14:17:28.097+0000 7f5b67817700  1 ====== req done req=0x7f5b0013c8a0 op status=0 http_status=200 latency=0.001000111s ======
debug 2020-09-02T14:17:28.360+0000 7f5b7b03e700  1 ====== starting new request req=0x7f5afffb98a0 =====
debug 2020-09-02T14:17:28.394+0000 7f5b7b03e700  1 ====== req done req=0x7f5afffb98a0 op status=0 http_status=200 latency=0.034003776s ======
debug 2020-09-02T14:17:28.892+0000 7f7ba35da700  1 ====== starting new request req=0x7f7ab6df58a0 =====
debug 2020-09-02T14:17:28.892+0000 7f7ba35da700  1 ====== req done req=0x7f7ab6df58a0 op status=0 http_status=200 latency=0s ======
debug 2020-09-02T14:17:33.565+0000 7f5bdc100700  1 ====== starting new request req=0x7f5b0003a8a0 =====
debug 2020-09-02T14:17:33.600+0000 7f5bdc100700  1 ====== req done req=0x7f5b0003a8a0 op status=0 http_status=200 latency=0.035003887s ======
debug 2020-09-02T14:17:30.551+0000 7f7b7f592700  1 ====== starting new request req=0x7f7ab65e58a0 =====
debug 2020-09-02T14:17:30.570+0000 7f7b9cdcd700  1 ====== req done req=0x7f7ab65e58a0 op status=0 http_status=200 latency=0.019001582s ======
`

**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): Linux k8s-ra01v 4.18.0-193.6.3.el8_2.x86_64
* Cloud provider or hardware configuration: local vSphere Cluster created with Rancher
* Rook version (use `rook version` inside of a Rook Pod): v.1.4.1
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
* Kubernetes version (use `kubectl version`): 1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by thotz** [comment] 2020-09-15 16:46
@peter-poki I have updated about ur issue in https://tracker.ceph.com/issues/44926, it was fairly producible in my set up and the work around mentioned in ceph tracker was not working for me

**Comment by alfonsomthd** [comment] 2020-09-16 08:57
> @peter-poki I have updated about ur issue in https://tracker.ceph.com/issues/44926, it was fairly producible in my set up and the work around mentioned in ceph tracker was not working for me

This error usually indicates that the object gateway daemon is not able to retrieve the zonegroup map.
It's recommended to update the period after any multisite change.
See:
https://docs.ceph.com/docs/master/radosgw/multisite/#update-the-period
https://tracker.ceph.com/issues/44926#note-15

@travisn Can you help to confirm that after any multisite change period is updated?
In rook environment, should daemons be restarted after updating period?

**Comment by travisn** [comment] 2020-09-16 18:37
@alfonsomthd Yes, after any update to the object store, rook will update the period. I don't expect the rgw daemons need to be restarted after the period is updated. @alimaredia ?

**Comment by thotz** [comment] 2020-09-17 05:22
@travisn @alfonsomthd , If I understand correctly in the current workflow zone and zonegroups are created before setting the dashboard options for rgw and period was not updated post setting those options. AFAIK rgw daemon is not restarted the after updating the period

**Comment by alimaredia** [comment] 2020-09-18 04:36
@travisn That is correct the rgw daemons do not need to be restarted after the period is updated.

I don't think that the period is committed after any update to the object store. Could you show me where this is happening in the code if you believe that's the case. It's my understanding that the period is commited in the object store only upon initial configuration of multisite. In fact the rgw daemon is not even started until after the period is committed during this initial configuration.

**Comment by zhanghe9702** [comment] 2020-09-23 09:15
i have the same problem, and update-the-period is not working for me.
![2020-09-23 17-05-34 的屏幕截图](https://user-images.githubusercontent.com/16931323/93992572-4b792480-fdc0-11ea-9519-406f74cb6fda.png)

**Comment by zhanghe9702** [comment] 2020-09-23 09:29
by the way, this cmd ` s3cmd mb --no-ssl --host=${AWS_HOST} --region=":default-placement" --host-bucket=  s3://rookbucket
Bucket 's3://rookbucket/' created`
works for me

**Comment by thotz** [comment] 2020-09-25 09:52
@alfonsomthd anyidea why update period is not working this scenario?

**Comment by alfonsomthd** [comment] 2020-09-25 11:18
> @alfonsomthd anyidea why update period is not working this scenario?

I'll try to reproduce the issue ASAP and let you know.

**Comment by alfonsomthd** [comment] 2020-09-29 07:21
@thotz  @peter-poki This fix is to be backported to Octopus release:
https://github.com/ceph/ceph/pull/37449

@alimaredia Do you have any insight on why the issue described below is happening?
https://tracker.ceph.com/issues/47676

**Comment by Mutantt** [comment] 2020-12-15 08:40
i have the same issue.i cant create a bucket with dashboard but i can create bucket with this command over tools pod:
s3cmd -d mb --no-ssl --host=${AWS_HOST} --region=":default-placement" --host-bucket= s3://bucket 
also i able to create and remove user from object gateway section on dashboard.
i used this command but nothing changed : radosgw-admin period update --commit

**Closed** 2021-03-22 20:07 UTC
Labels: bug, wontfix

**Comment by Zajda208** [comment] 2021-03-23 17:21
I have had the same issue too in version 15.2.10. Problem is when you follow the Ceph manual for creating multizone setup there is a point to rename zonegroup named: "default" to something else e.g. us-east. In this case, is renamed the zonegroup name but not the api_name. Solution is following:
1. radosgw-admin zonegroup get --rgw-zonegroup=us-east
2. check the JSON output if "name" and "api_name" matched
3. If not then copy the json to file e.g. zonegroup_us-east.json and edit the field "api_name"
4. import the json: radosgw-admin zonegroup set --infile ./zonegroup_eu-dev.json
5. check it again: radosgw-admin zonegroup get --rgw-zonegroup=us-east
6. update period: radosgw-admin period update --commit (you can use --rgw-realm=<your_realm> if you have it more)
7. restart radosgw containers: ceph orch restart rgw.<realm>.us-east
And it works.

**Comment by alfonsomthd** [comment] 2021-10-19 07:22
> I have had the same issue too in version 15.2.10. Problem is when you follow the Ceph manual for creating multizone setup there is a point to rename zonegroup named: "default" to something else e.g. us-east. In this case, is renamed the zonegroup name but not the api_name. Solution is following:
> 
> 1. radosgw-admin zonegroup get --rgw-zonegroup=us
> 2. check the JSON output if "name" and "api_name" matched
> 3. If not then copy the json to file e.g. zonegroup_us.json and edit the field "api_name"
> 4. import the json: radosgw-admin zonegroup set --infile ./zonegroup_us.json
> 5. check it again: radosgw-admin zonegroup get --rgw-zonegroup=us
> 6. update period: radosgw-admin period update --commit (you can use --rgw-realm=<your_realm> if you have it more)
> 7. restart radosgw containers: ceph orch restart rgw.<realm>.<zone>
>    And it works.

When configuring multi-site, default zonegroup and zone should not be reused/renamed but deleted:
https://docs.ceph.com/en/latest/radosgw/multisite/#delete-default-zone-group-and-zone

**Comment by ksanislo** [comment] 2022-04-26 01:32
> I have had the same issue too in version 15.2.10. Problem is when you follow the Ceph manual for creating multizone setup there is a point to rename zonegroup named: "default" to something else e.g. us-east. In this case, is renamed the zonegroup name but not the api_name. Solution is following:
> 
> 1. radosgw-admin zonegroup get --rgw-zonegroup=us
> 2. check the JSON output if "name" and "api_name" matched
> 3. If not then copy the json to file e.g. zonegroup_us.json and edit the field "api_name"
> 4. import the json: radosgw-admin zonegroup set --infile ./zonegroup_us.json
> 5. check it again: radosgw-admin zonegroup get --rgw-zonegroup=us
> 6. update period: radosgw-admin period update --commit (you can use --rgw-realm=<your_realm> if you have it more)
> 7. restart radosgw containers: ceph orch restart rgw.<realm>.<zone>
>    And it works.

Thank you for this... it also resolved this problem on an older (started as jewel, currently 16.2.7) single-zone cluster as well.
